### ISSUE TITLE
Options to control non-customizable objects of the Create New World Screen

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#100]
probably could be considered a bug report.

It would be nice to be able to move these elements from the single player world creation screen.

![image](https://user-images.githubusercontent.com/3880072/97866280-436ea780-1cd1-11eb-902b-369a7cd1b4eb.png)

**Comment by Keksuccino** [comment]
It's just not worth it adding support for this screen.. It just doesn't work well >.< Sorry, will close this for now :(
