### ISSUE TITLE
Right click menu is cut

### ISSUE THREAD

**Issue by Madis0** [Keksuccino/FancyMenu#101]
**Describe the bug**
When right-clicking a button that's placed higher than the middle, some of the right click menu elements cannot be clicked.
**To Reproduce**
1. Click Customization
2. Click Create Layout
3. Right click the topmost button
4. See the issue

**Expected behavior**
Expected the right-click menu to top-align, so that all items are visible

**Crash Log**
N/A

**Screenshots**
Hope you don't mind the custom resource pack and non-English.
![screen](https://user-images.githubusercontent.com/8611110/98154272-37efcc00-1edd-11eb-884e-fbb95ef6c260.png)

**Basic Informations (please complete the following information):**
 - OS: Manjaro 20.1.2
 - FancyMenu Version 1.5.3.2
 - Fabric Version 0.16.6 b 214, API 0.25.1 b 416
 - Minecraft Version 1.16.4
 - Active Mods - too many but I doubt they affect this...

**Comment by Keksuccino** [comment]
Hi! What you’re describing is not really a bug, it’s just that your window is too small :D I can’t really fix this, sorry. Try to make the window bigger and if that’s not possible, lower your GUI scale, this should fix it.
