### ISSUE TITLE
Automatically exclude any menu that does not have a custom layout by Fancy Menu.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Keksuccino/FancyMenu#103]
**Describe your idea**
While working with "FancyMenu" I noticed in the logs when I open for example "JEI" it says "Fancy menu does not know how to handle layout so I set it to "full exclude current" and log stops. Why not save everyone a headache and set "full exclude unless custom layout?"

**Does it frustrate you to not already have this feature in the mod?**
I love your mod but because of the size of my pack I had to spend 4 hours excluding different menus "due to testing"

**Comment by Keksuccino** [comment]
That’s actually a pretty good idea.
Why have I never thought about that?

**Comment by Keksuccino** [comment]
And you mean JEI is outputting something to the log that says FancyMenu can’t handle this menu or do you mean something else?

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.5.4! Thank you for your suggestion!
