### ISSUE TITLE
Allow buttons and other objects to fade-in and out?

### ISSUE THREAD

**Issue by Kichura** [Keksuccino/FancyMenu#104]
**Describe your idea**
(Likely already answered somewhere else i assume): There should a feature in FancyMenu where you can customizable the buttons including other objects to fade in or out using a delay timer similar to making them entirely visible in instant.

**Does it frustrate you to not already have this feature in the mod?**
I can basically live with the instant-appearing buttons instead, However it would be decent if this feature even existed at all for title screen creators.

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.0.0! Thank you for your suggestion!
