### ISSUE TITLE
Need Help with button placing & sizing

### ISSUE THREAD

**Issue by Charismara** [Keksuccino/FancyMenu#106]
Hey,

I got 2 Screens (1920x1080 & 2560x1440) and if i'm moving the Window from one screen to another, all buttons are in the wrong size and place. I'm running into the same issue if i change the gui scaling. 

Is there a way to "fix" this?

**Comment by Keksuccino** [comment]
You're using wrong orientations for your button objects.

[This](https://github.com/Keksuccino/FancyMenu/wiki/Layout-Editor#understanding-object-orientations) should help you :)

**Comment by Charismara** [comment]
I've tried all orientations for the buttons but they are always a bit off the position they should be on the bigger screen. 
I get the best results with top left & mid left.

Screenshots with mid-left orientation

small:
![image](https://user-images.githubusercontent.com/14293974/99649311-58c72e00-2a54-11eb-9e1a-8ac17e3d658c.png)
big:
![image](https://user-images.githubusercontent.com/14293974/99649368-6a103a80-2a54-11eb-8ff1-0bfef362bfac.png)

**Comment by Keksuccino** [comment]
Only mid-left will work here, so you should be fine with that orientation.

Is the button background thing (black transparent image) part of the full background image or is it a separate image? It **needs** to be a **separate image** with one of the left orientations to work!

If you do all of these things, it should work perfectly fine! :)

**Comment by Charismara** [comment]
Thanks that fixed the positioning issue. Now i'm running into another one ^^"

If i add the button background as image it will be in front of all buttons and make them darker.
![image](https://user-images.githubusercontent.com/14293974/99690911-ea509300-2a88-11eb-80db-a25db70e2f98.png)

Is there any way to move the image to the layer behind the buttons (like the "behind the text" option in Word)?

**Comment by Keksuccino** [comment]
You can set the rendering order of your layout. By default, the rendering order is set to `foreground`. Put all your foreground stuff in one layout with the `foreground` rendering order and all your background stuff (like the button background) in another one with the `background` rendering order! :)

**Comment by Charismara** [comment]
Thanks! Now everything works like it should 👍
