### ISSUE TITLE
JPEG frames doesn’t work in animations

### ISSUE THREAD

**Issue by killercreeper42** [Keksuccino/FancyMenu#107]
**Describe the bug**
When I added a new animation I get stuck prerendering infinitely

**To Reproduce**
1: Have an animation with over 1000 frames or so.
2: Launch

**Expected behavior**
I expected it to load

**Crash Log**
No crash, just prerendering infinitely.

**Screenshots**
Not applicable.

**Basic Informations (please complete the following information):**
 - OS: [Windows 10]
 - FancyMenu Version [1.5.4]
 - Forge Version [14.23.5.2854]
 - Minecraft Version [1.12.2]
 - Active Mods [ Optifine, Galacticraft, Localized weather & storms, Modern Warfare 2.0, And around 30 other mods. ]

Update: I tried a 500 frame animation and it still wont load.

**Comment by Keksuccino** [comment]
Way too much frames. Animations should be as small as possible. Every frame needs to be loaded into the RAM and you don’t want 1000+ frames loaded into your RAM :D Especially if your frames have a high resolution like 4K.

**Comment by killercreeper42** [comment]
They are all 720p. Even 500 frames wont load though.

**Comment by Keksuccino** [comment]
~ See my edit above ~

Try to load the animation with only 5 frames or something. (Just for testing purposes)

**Comment by killercreeper42** [comment]
I'll try that in a bit.

**Comment by Keksuccino** [comment]
And if that doesn’t work, please send me your latest.log file (located at .minecraft/logs/latest.log).

**Comment by killercreeper42** [comment]
Ok.

**Comment by killercreeper42** [comment]
Ok so I got it to load the full 1000+ frame animation. For some reason it doesn't accept .jpeg files, but it does accept .jpg files.

**Comment by Keksuccino** [comment]
Was related to Konkrete (library mod) and was fixed in Konkrete v1.1.0! Thank you for your report!
