### ISSUE TITLE
Right-click menu position deviation

### ISSUE THREAD

**Issue by JiuMuln** [Keksuccino/FancyMenu#108]
When I entered 'edit layout', the menu popped up by the right button went beyond the screen, and I couldn't click on the menu item that went beyond the screen.
 - OS: Windows
 - FancyMenu Version: 1.5.4.1
 - Forge Version: 34.2.42
 - Minecraft Versio: 1.16.3
 - Active Mods: Optifine

**Comment by Keksuccino** [comment]
You mean the rightclick menu in the layout editor is out of screen? That’s not a bug, your MC window is just too small ^^ Try to maximize the window or lower your GUI scale! :)

**Comment by JiuMuln** [comment]
oh yes,thank you

Keksuccino <notifications@github.com> 于2020年11月30日周一 上午2:52写道：

**Comment by Keksuccino** [comment]
No problem ^-^
