### ISSUE TITLE
[1.0beta for 1.15.2] did i do something wrong? intro anim

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#11]
Trying to set up the intro animation

Here's the structure

![image](https://user-images.githubusercontent.com/3880072/80157250-5dde0080-858b-11ea-888a-7e4cae34f82f.png)

properties.txt
```
name=seilicans_landing
loop=false
fps=24
width=1920
height=1080
x=0
y=0
replayintro=false
```

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/80157359-9e3d7e80-858b-11ea-99b4-f1e90a59f6f5.png)
 
config.txt
```
##[customization]

B:showcustomizationbuttons = 'true';


##[mainmenu]

B:hiderealmsnotifications = 'true';
B:hidelogo = 'false';
B:hidebranding = 'true';
B:showmainmenufooter = 'true';


##[mainmenu_splash]

I:splashrotation = '-20';
B:hidesplashtext = 'false';
I:splashoffsetx = '0';
I:splashoffsety = '0';


##[loading]

S:gameintroanimation = 'intro';
```

# problem
it says it's loading and rendering the animation, but doesn't show the animation

# 165 files in the animation folder
![image](https://user-images.githubusercontent.com/3880072/80157477-e2c91a00-858b-11ea-8f5c-c948d1d06bf5.png)

**Comment by Keksuccino** [comment]
Hi! Your animation should work, but you’ve set the wrong name as "gameintroanimation" value. This has to be "seilicans_landing" instead of "intro" because you gave your animation this name in its properties :D

**Comment by kreezxil** [comment]
ok, thanks I didn't get that from the wiki, but it makes sense.

**Comment by AzureDoom** [comment]
The way around this that worked for me, was to split my first half into the intro and the second half into the animation. This does cause a weird bug though. 
![](https://i.imgur.com/uBhsiLV.gif)

**Comment by kreezxil** [comment]
@Keksuccino thank you so very much that worked perfectly for me. Can you double check your wiki make sure it is abundantly clear about that. feel from to use some of my images to enhance the wiki.

**Comment by Keksuccino** [comment]
I’ve updated the wiki page about the config file to make it more clear, but I wanted to write an extra page for game intros anyway, to have enough space to explain it! ^^ Thank you for telling me! :)
