### ISSUE TITLE
Panorama Customization (speed, blur)

### ISSUE THREAD

**Issue by Landsurfer2000** [Keksuccino/FancyMenu#110]
**Describe your idea**
more customization in terms of new panorama animation

**Does it frustrate you to not already have this feature in the mod?**
for sure, the current panorama settings are non-existent and the default panorama speed and lack of blur really nauseates me. I'm super super happy to see such an awesome feature able to be applied to any GUI i can think of!!! but with no options in the properties txt to change speed, apply blur, etc., its really hard for me to recommend using panoramas at the moment

My MC version is 1.12.2.

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.7.0! Thank you for your suggestion!
