### ISSUE TITLE
Splash Text Orientation

### ISSUE THREAD

**Issue by Landsurfer2000** [Keksuccino/FancyMenu#111]
**Describe your idea**
add orientation setting to splash text

**Does it frustrate you to not already have this feature in the mod?**
personally, this is a must have for me because everything else in my menu is properly aligned but the splash text is the only one that i cannot change orientation for so it jumps all over the place when testing on different aspect ratios. I checked the entirety of config.txt but no such option exists

im aware offset x and y exist but it still doesnt solve my problem, splash text seems to be default oriented to mid-centered

My mc version is 1.12.2

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.7.0! Thank you for your suggestion!
