### ISSUE TITLE
Custom Window Icon problems | Rewrite System

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#112]
**Describe the bug**
icons in title bar and taskbar are skewed on Linux 

![image](https://user-images.githubusercontent.com/3880072/101957250-b4558900-3bc6-11eb-96cf-1615dc9d1831.png)
![image](https://user-images.githubusercontent.com/3880072/101957264-bddef100-3bc6-11eb-9906-9b2738107f7d.png)
should be
![icon16x16](https://user-images.githubusercontent.com/3880072/101957307-d18a5780-3bc6-11eb-913a-c168252e1d00.png)
![icon32x32](https://user-images.githubusercontent.com/3880072/101957308-d222ee00-3bc6-11eb-82ca-1d5a106366ec.png)

**Basic Informations (please complete the following information):**
 - OS: Linux Manjaro 20
 - FancyMenu Version 1.6.0_MC_1.15-1.15.2
 - Forge Version  31.2.47
 - Minecraft Version 1.15.2
 - Active Mods https://gist.github.com/f1757fc598ced3a0b9b1d2714a5bc455

**Comment by Keksuccino** [comment]
This is a known bug. Try to remove one pixel from each corner (make it transparent) and it should work. I really don’t know why this happens. I think I will rewrite the method to set icons and use my own system for it. Now it uses Minecraft's system and yeah.. It is not working pretty well :D

**Comment by kreezxil** [comment]
yes, use your system. :)
