### ISSUE TITLE
Option to enable/disable visual grid overlay

### ISSUE THREAD

**Issue by Shorepion** [Keksuccino/FancyMenu#113]
**Describe your idea**
An option to enable/disable visual grid overlay, which can be used for better orientation, where to place your button to keep it symmetrical (as an example).
Also on top of that it would be cool to have magnetic gridlines which will auto force the button/image to be lined up.
So basically the grids most Image Editors have built-in.

**Does it frustrate you to not already have this feature in the mod?**
Definetly would be cool to have, because otherwise you have to calculate compare every position with every element to keep it symmetrical.

**Comment by Keksuccino** [comment]
The lines around focused objects are designed to not be annoying while moving objects. Means, the line is completely inside the object and will not be outside of it. It’s an optical illusion that the blue lines make the object bigger :D

**Comment by Shorepion** [comment]
I think there is a misunderstanding. I meant to have a grid overlay that is on top the Layout you are working on, just as a helper for orientation.

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.3.0! Thank you for your suggestion!
