### ISSUE TITLE
Session-specific text variable support for the layout editor

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#114]
**Describe your idea**
Have FM prepopulate some custom variables that we can use on our menus. For example:
$FORGE
$MCVERSION
$MCPVERSION
$NUM_MODS

and maybe go so far as to allow us to add our own custom variables

Having such a feature would allow us to control the block of text that normally appears under branding that we all tend to turn off. By placing its elements wherever we desire.

**Comment by Keksuccino** [comment]
Hooked this issue to remind myself of adding support for these variables to the layout editor.

The variables itself are already a thing, but you cannot use them in the editor.

**Variables:**
- %guiwidth% to get the current menu width
- %guiheight% to get the current menu height
- %playername% to get the client player name (broken in versions <1.7.0)
- %playeruuid% to get the client player uuid (broken in versions <1.7.0)
- %loadedmods% to get the number of **active** mods
- %totalmods% to get the total number of mods
- %version:<modid>% to get the version of a mod (also works for forge by using `forge` as modid)

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.0.0! Thank you for your suggestion!
