### ISSUE TITLE
Game Crashes when animation loops

### ISSUE THREAD

**Issue by GlacialKyuu** [Keksuccino/FancyMenu#115]
Ight, so i was setting the background animation as the [Minecraft Outro YouTube](https://www.reddit.com/r/FancyMenu/comments/jpt557/minecraft_cave_animation_youtube_outro_download/) video, but right when it starts looping, the game crashes with an (out of memory) error.

Repro Steps:

Create an new layout
Add an animation to its background (that loops)
Save it or use it (can work on the editor too)

Expected: loops normally

Actual: Runs out of mem and dies

OS: windows 10
FM Version: 1.6.0
Forge Version: 35.1.0
Minecraft Version: 1.16.4
Mods: JustEnoughItems, iChunUtil, Hwyla, CreativeCore, CMDCam, ScreenshotToClipboard, OptiFine, WorldEdit FORGE, MinecraftCapes, Konkrete (ofc), Collective, FullBrightnessToggle

LOG
[latest.log](https://github.com/Keksuccino/FancyMenu/files/5719025/latest.log)

**Comment by Keksuccino** [comment]
Hi!
Your log is getting spammed with texture errors.
This can be caused by mods that mess with texture loading.

Please try to load the game with **only** FancyMenu and Konkrete.

**Comment by GlacialKyuu** [comment]
Ight, i included the files for when the game crashes on the layout editor and on the menu (when i save it really quickly and see it)
debug and normal logs

(logs for layout editor were the first time i launched forge as i switched versions)
(log for the menu took some reloads to crash, can be bad for ppl editing config)

LOGS
[logs.zip](https://github.com/Keksuccino/FancyMenu/files/5720596/logs.zip)

**Comment by Keksuccino** [comment]
How much RAM do you have?

**Comment by GlacialKyuu** [comment]
I have 16gb of ram on my machine, minecraft has 10gb so......

**Comment by Keksuccino** [comment]
Can you check your task manager for how much is being used without MC and with MC running, please? MC with the (unoptimized) cave animation active/loaded should not use more than 2-3GB RAM.

**Comment by GlacialKyuu** [comment]
Here are the results,

With no minecraft running, Discord, and an YT video running
1.4 GB of ram

middle of animation: 8.6GB of ram (omg)

after stopped responding
11.0GB of ram

(the ram cap on the installation settings was 10g)

**Comment by Keksuccino** [comment]
Texture caching is not affected by the max RAM you set to MC ^^

I don't think this is a bug in FancyMenu, but maybe in your MC installation, Java, OpenGL or something else.
It isn't really clear were its origin is.

The last thing that comes to my mind is that maybe something's wrong with your animation(s).
I know, you've used the cave animation, but can you please send me a screenshot of your animation home directory (`.minecraft/config/fancymenu/animations`), the cave animation home directory and the animation frames directory inside the cave animation directory?

Problem is, the errors you get printed to your log are very generic and sound more like a general texture loading problem.
I think it would be the best to just reinstall MC and try if that helps.

I'm **pretty** sure that it's not a bug in FancyMenu.

**Comment by GlacialKyuu** [comment]
![image](https://user-images.githubusercontent.com/58439467/102732385-54bf5200-4319-11eb-9df2-eb10438f8a29.png)
![image](https://user-images.githubusercontent.com/58439467/102732392-57ba4280-4319-11eb-9253-9e5b7841d83f.png)
![image](https://user-images.githubusercontent.com/58439467/102732395-59840600-4319-11eb-9c51-6ac12a0bfd21.png)

there!

**Comment by Keksuccino** [comment]
Hmm, everything looks fine, as expected :/
That's really weird.. It seems to be an OpenGL texture problem not directly related to FancyMenu. Sadly, I don’t think I can fix that, because it’s something on your end :(
First time ever I see a bug like that..

Maybe it really helps if you reinstall MC and Java. That’s the only idea I have, sorry :(

**Comment by GlacialKyuu** [comment]
Alright, no problem man, hope this bug helps you in some way!
