### ISSUE TITLE
Randomized Background Stills

### ISSUE THREAD

**Issue by Landsurfer2000** [Keksuccino/FancyMenu#116]
**Describe your idea**
I would love it if there was a "randomize background" for image stills, just like there is for animations. I would love to have a different variation of menu stills in certain guis, but the only way i can do that is by registering a 1fps animation with one frame, which isn't really the most efficient and friendly method since it increases load times dramatically per animation

**Does it frustrate you to not already have this feature in the mod?**
it does just a tad, due to the only way i can achieve such a effect is with animations :c it would mean a lot to me if i could do this resourcefully!

my minecraft version is 1.12.2

**Comment by Landsurfer2000** [comment]
Also, if possible, randomized image elements in general, not just for backgrounds? like picking from a pool to be applied to the image element would be really cool

**Comment by Keksuccino** [comment]
Randomized layouts were added to FancyMenu v2.1.0!
This allows you to randomize everything, including background images :)
Thank you for your request!
