### ISSUE TITLE
Compatibility with `Slight` GUI enhancements

### ISSUE THREAD

**Issue by G43mc** [Keksuccino/FancyMenu#117]
I think it would be really cool if we could also use "Slight" GUI enhancements with this mod. The two don't appear to be vastly incompatible, but maybe I am wrong.

**Comment by G43mc** [comment]
The error message that pops up is also very confusing. So if some form of compatibility doesn't work, make sure whoever tries too gets a less confusing error message.

**Comment by Keksuccino** [comment]
I can’t really do something against the confusing content of error messages lmao. Java is generating these and they are very helpful if you know what to do with them :D
And if the error message is some of my custom warning/error outputs, these are more for me to better understand what’s happening when users report errors with logs.

This mod is on FancyMenu's [incompatibility list](https://github.com/Keksuccino/FancyMenu/wiki/Incompatibility-List) and adding support for it is not planned, I'm sorry..

But thank you very much for your report!
