### ISSUE TITLE
[Feature Request] Colored Shapes

### ISSUE THREAD

**Issue by ataylor-design** [Keksuccino/FancyMenu#118]
**Describe your idea**
A simple but useful feature to have would be basic colored shapes (squares, rectangles, and circles). Ideally, these shapes could be positioned and layered similarly to images and buttons. They could be set a custom hex color, with transparency options as well. The options for this could be:

* Darkening existing backgrounds without having to hop into an image editor.
* Quick prototyping of layout ideas.
* Testing layouts before starting to work with buttons, images, etc.
* Providing backgrounds and areas for groups of elements, such as menu buttons.
* Creating minimalistic menus.

**Does it frustrate you to not already have this feature in the mod?**
Yes. Currently, I do most of my layout wireframing and designing in image editors, by-hand sketch, etc. However, being able to do so in Fancymenu as well would allow for testing layouts before moving on to in-depth work. 

Granted, what I am suggesting can already be done to an extent by using solid-colored images. However, being able to change the opacity, color, and size of basic shapes in FancyMenu would make the process smoother. It would cut out having to jump between Minecraft, an image editor, and reloading constantly.

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.7.0! Thank you for your suggestion!
