### ISSUE TITLE
Game freezes on load [ fabric | macOS ]

### ISSUE THREAD

**Issue by superon** [Keksuccino/FancyMenu#119]
**Describe the bug**
game fails to load

**To Reproduce**
attempt to play using gdlauncher
**Expected behavior**
complete load

**Crash Log**
no crash, the game just hangs
https://pastebin.com/Tueraqpd
last line here is me killing the process

**Screenshots**
n/a

**Basic Informations (please complete the following information):**
 - OS: macOS high sierra 10.13.6
 - FancyMenu Version [fancymenu_fabric_1.6.0_MC_1.16.3-1.16.4]
 - Fabric api Version [fabric-api-0.28.4+1.16]
 - Minecraft Version [1.16.4]
 - Active Mods [fabric-api-0.28.4+1.16, fancymenu_fabric_1.6.0_MC_1.16.3-1.16.4, konkrete_fabric_1.1.0.1_MC_1.16.3-1.16.4]

**Comment by Keksuccino** [comment]
Hi! At what point exactly is is freezing/hanging?
Do you see the Minecraft window?

**Comment by superon** [comment]
no window appears

**Comment by NeviraOwner** [comment]
Happens with macOS 11 as well

**Comment by Keksuccino** [comment]
This should be finally fixed now in FancyMenu [Fabric] v1.7.1-1 !
Thank you very much for your report and sorry for the long waiting time, but debugging this issue was a pain because it was the most random thing I've ever seen and it didn't even threw an error to the log..
