### ISSUE TITLE
loading screen replacer

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#120]
**Describe your idea**
There's a mod called Loading Screens that changes the screen that appears after a player clicks on a world or server to play. The screen they see while the world loads/generates/logs in. It's not on all versions tho. It would be really nice if Fancy Menu could do this too.

see: https://www.curseforge.com/minecraft/mc-mods/loading-screens

**Does it frustrate you to not already have this feature in the mod?**

- [x] No

**Would it be really useful in reducing pack size?**

- [x] Yes

**Comment by Keksuccino** [comment]
But you should already be able to edit world loading screens, or am I wrong? o.O

**Comment by Keksuccino** [comment]
Closed because no response.
