### ISSUE TITLE
Buttonpresets for socials

### ISSUE THREAD

**Issue by Shorepion** [Keksuccino/FancyMenu#122]
**Describe your idea**
Buttonpresets for socials like Discord, Twitter, Patreon, GitHub, CurseForge Page... that are already built-in and configurable.
Basically a Button with the corresponding social page logo (normal and hover) and link(-generator) reffering to the modpackmaker socials.

**Does it frustrate you to not already have this feature in the mod?**
No. But its often used in many modpacks and manually added anyways. 
Having the presets would give a good standard look and will save time.

**Comment by Keksuccino** [comment]
Sorry, but I decided to not add this, because it would just create more elements that don't really do much. It's not too much work to create these buttons on your own, so I think it's okay. Thank you for your suggestion! :)

**Comment by Shorepion** [comment]
Ok, thats fair enough. Keeping priority to more important and more complex stuff is understandable👍🏻.
Regards
