### ISSUE TITLE
gif support for buttons (textures)

### ISSUE THREAD

**Issue by Shorepion** [Keksuccino/FancyMenu#123]
**Describe your idea**
Hey its me again 🌝
Adding .gif files for button textures. On top of that an optional hover feature, so that the gif will play as long as the mousepointer is over the button.

**Does it frustrate you to not already have this feature in the mod?**
I would really, really, really love to have this feature.
This extends the creativity beyond... something very big.
Im thinking of blood dripping buttons, matrix code gif on buttons, fading buttons...

Yours sincerely 
feature request dude Shorepion ✌🏻

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.3.0! Thank you for your suggestion!
