### ISSUE TITLE
Audio in the menu doesn't work

### ISSUE THREAD

**Issue by ENDRlOU** [Keksuccino/FancyMenu#124]
**Describe the bug**
With the "Enabled Audio" function, audio ('sound.wav': 00:09:22) is not played even after a rejoin or reload and without sound resource pack. The file path is correct, but the audio is not played.

**To Reproduce**
1. Go to 'Customization'.
2. Click on 'Edit Layouts'.
3. Hover over left arrow '>' and click.
4. Click 'Add', then there is click 'Audio'.
5. Click 'Choose file', and specify the location of the .wav file (config/fancymenu/animations/sound.wav).
6. Click 'Done'.
7. Click 'Audio', then there click the audio file name (sound.wav).
8. Click 'Enabled Audio'.
9. Close, save and exit the game, reload.
10. No changes, i.e. no audio.

**Expected behavior**
Audio shall plays endlessly in the main menu

**Crash Log**
No crashes

**Screenshots**
N/A

**Basic Informations:**
 - OS: ['Windows 7']
 - FancyMenu Version ['v1.7.0']
 - Forge Version [' [TLauncher] ForgeOptifine 1.16.4']
 - Minecraft Version ['1.16.4']
 - Active Mods [fancymenu v1.7.0 and konkrete v1.1.2, firstpersonmod 2.0.0, AmbientSounds v3.1.4, CreativeCore v2.0.10 and ItemPhysic v1.4.15 + Optifine 1.16.4 HD U G6 pre12 and tl_skin_capeforge ]

**Comment by Keksuccino** [comment]
Are you sure your audio file is a working WAV file with 48KHz and 16bit? Bit rate and sample rate are important.

Another problem could be a too low master volume in the MC volume settings.

**Comment by ENDRlOU** [comment]
> Are you sure your audio file is a working WAV file with 48KHz and 16bit? Bit rate and sample rate are important.
> 
> Another problem could be a too low master volume in the MC volume settings.

Oh, thank you! :)
Didn't think that KHz and Bit would affect. Now the audio is working, perfect! Problem solved. 9/10, because it would be even better a automatic muting/removing the standard background music (C418) in the main menu, which is superimposed on my audio file.

**Comment by Keksuccino** [comment]
You can mute the default menu audio in the mod config, ma dude.
`playmenumusic` https://github.com/Keksuccino/FancyMenu/wiki/Mod-Configuration#general
