### ISSUE TITLE
Can't close buttons "Customization" and "Reload"

### ISSUE THREAD

**Issue by ENDRlOU** [Keksuccino/FancyMenu#125]
**Describe the bug**
Keyboard shortcut "Ctrl" and "C" for close buttons "Customization", "Reload" not works (judjing by note). The other is that I don't know how to change this combination to close, but I didn't even change anything

**To Reproduce**
1. Click 'Ctrl' + 'C', even when hovering over buttons.
2. I think reload and enter MC again.
3. No changes, i.e buttons "Customization" and "Reload" are not missing.

**Expected behavior**
Close of buttons "Customization" and "Reload" 

**Crash Log**
No crashes

**Screenshots**
N/A

**Basic Informations:**
 - OS: ['Windows 7']
 - FancyMenu Version ['v1.7.0']
 - Forge Version [' [TLauncher] ForgeOptifine 1.16.4']
 - Minecraft Version ['1.16.4']
 - Active Mods [fancymenu v1.7.0 and konkrete v1.1.2, firstpersonmod 2.0.0, AmbientSounds v3.1.4, CreativeCore v2.0.10 and ItemPhysic v1.4.15 + Optifine 1.16.4 HD U G6 pre12 and tl_skin_capeforge ]

**Comment by Keksuccino** [comment]
Maybe another hotkey is in conflict with C? You can change the hotkey in the controls settings.

**Comment by ENDRlOU** [comment]
> Maybe another hotkey is in conflict with C? You can change the hotkey in the controls settings.

Hah, thank you! You're right, the "C" key was not installed, except for "r". The problem is solved, the buttons are hidden! There was no thought that in the settings of Minecraft there may be additional settings for mods.

**Comment by Keksuccino** [comment]
Great to hear it works now! :)
