### ISSUE TITLE
Transparency and blur for background

### ISSUE THREAD

**Issue by ENDRlOU** [Keksuccino/FancyMenu#126]
**Describe your idea**
Ability to include a transparent background for ongoing animation in other pages of buttons (like settings) of the main menu.
Ability to enable and adjust blur during pause menu, open inventory.

**Does it frustrate you to not already have this feature in the mod?**
No, but for such a mod for menu, I think it will be very good idea.

**Comment by Keksuccino** [comment]
> Ability to include a transparent background for ongoing animation in other pages of buttons (like settings) of the main menu.
What exactly do you mean?

**Comment by ENDRlOU** [comment]
> Ability to include a transparent background for ongoing animation in other pages of buttons (like settings) of the main menu.

Ah, I meant just animation video everywhere, in each page of buttons, where by transparent I just meant to remove these covers of dirt blocks

**Comment by Keksuccino** [comment]
You want to remove the dirt background of menus? You know, there isn’t anything behind this dirt texture when not in a world.

**Comment by ENDRlOU** [comment]
> You want to remove the dirt background of menus? You know, there isn’t anything behind this dirt texture when not in a world.

Uhm, i'm got other idea for first request, which is reformulated:
- Ability to clean cover of dirt blocks in any page of buttons, i.e, to include a transparent background for animation or image in other pages of buttons (like settings) of the main menu.
i.e, like in the upload menu will be not dirt, but animation or image. May be idea with transparency is bad, since probably the text will not be visible

**Comment by Keksuccino** [comment]
I still don’t really understand what you want me to add.

Still sounds like you want me to make dirt backgrounds "transparent" which is not possible when not in a world. Or do you mean to make backgrounds transparent **when** in a world?

What do you mean with the upload menu??
This part sounds like you want to be able to add a background image **behind** an animation. Is this correct?

**Comment by Keksuccino** [comment]
Closed because no response.

**Comment by HBI6428** [comment]
I think what this person is trying to say is when clicking single or multiplayer it has a dirt backround, right. So instead like when you play the game and then you click options it had a blurred backround instead showing your active game blurred behind the options menu.
![image](https://github.com/Keksuccino/FancyMenu/assets/153845475/aece782b-3f5c-4900-8c60-a054e6dec1a8)
![image](https://github.com/Keksuccino/FancyMenu/assets/153845475/74ca71b5-38db-4e5b-a0f7-4d06daaa1c2d)

Then to make these menus like the newest release version of Minecraft (1.20.6) 1 day before 1.21 lol

![image](https://github.com/Keksuccino/FancyMenu/assets/153845475/bb12fe8e-33b3-4d4b-80c1-2c9037ba44a0)
![image](https://github.com/Keksuccino/FancyMenu/assets/153845475/368430be-4ca0-4ac3-a0a1-d84f6f98f9ff)

like this but for the older versions of Minecraft for a cleaner look

**Comment by HBI6428** [comment]
therefore removing the dirt backround

**Comment by Keksuccino** [comment]
I have no plans on backporting the blur to older versions, sorry. But I added the ability to blur custom menu backgrounds in FancyMenu for MC 1.20.6+.
