### ISSUE TITLE
Continuing audio and sound for back action

### ISSUE THREAD

**Issue by ENDRlOU** [Keksuccino/FancyMenu#127]
**Describe your idea**
Ability to add a sound for the "Esc" key (as in GTA V during pause)
Continuing yours audio on other pages of buttons of the main menu or pause menu without stopping and repeating again.

**Does it frustrate you to not already have this feature in the mod?**
For such an action to put audio in the menu, I think, yes, a little, because the audio only works on 1 page, and going back it even plays again, but not sound.

**Comment by Keksuccino** [comment]
Just add your menu audio to all menus you want it to play.
When you switch from one menu with an audio to another one with the same audio, it will continue playing.
