### ISSUE TITLE
Audio in the pause menu doesn't work

### ISSUE THREAD

**Issue by ENDRlOU** [Keksuccino/FancyMenu#129]
**Describe the bug**
With the "Enabled Audio" function in the Pause Menu, audio is played only in the customization, but not without customization, even after a rejoin or reload and without sound resource pack. The file path is correct, 48KHz and 16 bit, all volume 100%, but the audio is not played. In the main menu is playing. 

**To Reproduce**
1. Go to 'Customization'.
2. Click on 'Edit Layouts'.
3. Hover over left arrow '>' and click.
4. Click 'Add', then there is click 'Audio'.
5. Click 'Choose file', and specify the location of the .wav file (config/fancymenu/animations/menupause.wav).
6. Click 'Done'.
7. Click 'Audio', then there click the audio file name (menupause.wav).
8. Click 'Enabled Audio'.
9. Close, save and exit the game, then reload, join to game and pause.
10. No changes, i.e. no audio.

**Expected behavior**
Audio shall plays endlessly in the pause menu

**Crash Log**
No crashes

**Screenshots**
N/A

**Basic Informations:**
 - OS: ['Windows 7']
 - FancyMenu Version ['v1.7.0']
 - Forge Version [' [TLauncher] ForgeOptifine 1.16.4']
 - Minecraft Version ['1.16.4']
 - Active Mods [fancymenu v1.7.0 and konkrete v1.1.2, firstpersonmod 2.0.0, AmbientSounds v3.1.4, CreativeCore v2.0.10 and ItemPhysic v1.4.15 + Optifine 1.16.4 HD U G6 pre12 and tl_skin_capeforge ]

**Comment by Keksuccino** [comment]
Not a bug, that's on purpose. By default, menu sounds don't play while in a world.
You can set `playbackgroundsoundsinworld` to `true` in the mod config to play sounds while in a world.
https://github.com/Keksuccino/FancyMenu/wiki/Mod-Configuration#general

I highly recommend you to join my [discord](http://discord.keksuccino.de/) for that type of questions, so you don't need to open an issue everytime :D
And you will probably get a quicker answer! ^^
