### ISSUE TITLE
Compatibility for More Refined Storage

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#13]
# Synopsis
I have a huge 1.12.2 mod pack that takes a long time to load. So I created a small mod pack with just Fancy Menu in it. I configured everything to my liking then copied it to the new mod with huge load times. 

**However**, the custom main menu doesn't load.

## What happens
The intro animation that I made in the fm only pack loads just fine in the bigger pack, however the main menu is vanilla.

## What I think is happening
On the tiny fm only pack the customization file is named **GuiMainMenu.txt**, so I thought to myself maybe you're storing what the name of the main menu is or if there is even in a strange place. Don't know for sure. So I create a new custom layout and save it.

**__Weirder Things__**, the new layout menu is now called **GuiCustomMainMenu.txt**!!! "Custom" came from somewhere, the tiny fm pack didn't generate the filename not one time. It's like you took the effort to make sure that your mod can't load previously generated configs. I'm sure you didn't do that deliberately. 

**I'm fairly certain**, that is not the case because the tiny fm only pack can load the custom screen no issues, over and over again from fresh start.

## What now?
For me, i'll just bite the bullet and rebuild the screen entirely in the larger pack which I did not want to do because of the long loading times when debugging the menu.

## Why did I post this?
1. it really is a bug/useability report
2. no one else reported
3. this is a great mod and I want others to know this bug is acknowledged at least by someone

**Comment by Keksuccino** [comment]
Take a look at the menu identifier (by clicking on the menu info button) of the main menu when you loaded your big mod pack. I bet the identifier now ends with "GuiCustomMainMenu", so obviously, your previously generated customization file, which is searching for menus with another identifier, isn’t working. The identifier changed to something like "CustomMainMenu", because one of your active mods is completely overriding the vanilla main menu screen. I don’t think that all customization features will work in this custom screen, but you can try it. Just change the identifier in your customization file to the correct one and it should load.

**Comment by kreezxil** [comment]
ok, i was coming here to say that I found this

![image](https://user-images.githubusercontent.com/3880072/80418110-7c4e3f80-889c-11ea-887b-197b6efb12f9.png)

this needs to be documented in your wiki.

**Comment by Keksuccino** [comment]
This IS documented in my wiki.

**Comment by kreezxil** [comment]
yep, removed that mod and no longer have my problem. If you don't have an incompatible list, might need to start one.

**Comment by Keksuccino** [comment]
> is there no way you can override the gui bs caused by other mods and force your menu to take precedence? thus avoiding this altogether?

That’s not possible. Most mods are waiting for the specific menu to load and loading its custom version instead. There’s literally no way to prevent this. The way I’m customizing menus now is the most universal way possible. My method maximizes the compatibility with other mods, but to customize special types of menus like the main menu, I have to add many stuff to make things like custom backgrounds possible. If some mod completely overrides a menu (which is a very lazy and REALLY bad practice), I can’t do anything.

> BTW, you're 90% incompatible with More Refined Storage mod. What it prevents is the background.

Do you mean the main menu customization is incompatible with this mod or customization on general?
Again: Sorry, but I can’t do anything to prevent such things. I can make individual mods compatible with FancyMenu, but preventing menu overriding in general is impossible. (If only the main menu customization is incompatible with the other mod, I will make it compatible with it.)

> If you don't have an incompatible list, might need to start one.

People should know that not every mod is compatible with all other mods ^^ Especially a mod that seems to override a complete menu screen. Is the incompatible mod visually customizing the main menu? Do you see any difference to the vanilla one? o.O Or is the dev just casually overriding menu screens?

**Comment by kreezxil** [comment]
That's why I suggested making a public incompatible list. Having such a list show you care more than you do and helps pack authors find quickly where things have gone awry without having to dig thru everything.

I'm only trying to help you out.

**Comment by Keksuccino** [comment]
I will make a wiki page for incompatible mods :)

**Comment by Keksuccino** [comment]
Added compatibility for More Refined Storage with FancyMenu v1.0.1.

**Comment by kreezxil** [comment]
nice
