### ISSUE TITLE
Confusing Project Structure 

### ISSUE THREAD

**Issue by macbrayne** [Keksuccino/FancyMenu#130]
The project structure is kind of confusing. You are probably using Gradle for builds but you've stripped every sub project of its build.gradle and settings.gradle. Do you have sensitive information like your api keys embedded in your build files or is there another reason for removing them? You could provide the api keys via environment variables or store it in gradle.properties.
Potential contributors might have problems setting up the project locally if you don't provide the necessary files.
You also might want to consider separating the fabric and forge versions into different branches or projects.

**Comment by Keksuccino** [comment]
The source is for researching.
I will not change it’s structure or separate it into different repos, sorry.
