### ISSUE TITLE
Delay appearance for image

### ISSUE THREAD

**Issue by ENDRlOU** [Keksuccino/FancyMenu#131]
**Describe your idea**
That when you right-click on the set image, you can set the appearance delay like from the buttons.

**Does it frustrate you to not already have this feature in the mod?**
I added a word to the title from the animation video (like "CAVES&CLIFS") or what added a image of a gear for the square settings button. While the title is being built, while the button appears in 2 seconds, the images have already come running! It doesn't look very good.

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.0.0! Thank you for your suggestion!
