### ISSUE TITLE
.ogg support for menu music

### ISSUE THREAD

**Issue by BBoldt** [Keksuccino/FancyMenu#134]
**Describe your idea**
Support for using .ogg files as background music for menus. I don't think it would be too hard to support as all the other music and sounds in minecraft are in .ogg format. .wav files are cool and everything but they are MASSIVE. For instance, a song of mine that I want to put in my main menu is 27MB as a .wav, but only 3MB as an .ogg.

**Does it frustrate you to not already have this feature in the mod?**
I can live without it, but it just seems weird that only .wav is supported.

**Comment by BBoldt** [comment]
For instance, a song of mine that I want to put in my main menu is 27MB as a .wav, but only 3MB as an .ogg.

**Comment by Keksuccino** [comment]
The new audio extension for FancyMenu v2.6.4-1+ supports OGG files now! :)

Fabric: https://www.curseforge.com/minecraft/mc-mods/audio-extension-for-fancymenu-fabric
Forge: https://www.curseforge.com/minecraft/mc-mods/audio-extension-for-fancymenu-forge
