### ISSUE TITLE
Unable to open GUI

### ISSUE THREAD

**Issue by CaptJack2883** [Keksuccino/FancyMenu#135]
**Describe the bug**
I get an error screen that says the GUI I want doesn't exist or is not supported. I cannot exit this screen once I get into it. 

**To Reproduce**
1. Go to Inventory Screen (JEI is Enabled).
2. Click on Tips button near the bottom.
3. Click on 2 or 3 of the 6 tips that appear. 
4. Try to click Back button.
5. Error screen appears, cannot exit by Back button onscreen, or with Escape key or other keybinds. 

**Expected behavior**
I should be able to exit the menu and continue playing. 

**Crash Log**
If the bug includes a crash, please paste or link it here.
There was no crash, but I had to hit Alt+F4 to exit the game.

**Screenshots**
![FancyMenu](https://user-images.githubusercontent.com/59985652/106580172-34cda180-6507-11eb-846c-97330c32c4ed.jpg)
![Tips Button](https://user-images.githubusercontent.com/59985652/106580182-37c89200-6507-11eb-9bc5-d61b91a0cfcb.jpg)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 1.7.0_MC_1.16.2-1.16.5
 - Forge Version 36.0.9
 - Minecraft Version 1.16.5
 - Active Mods: Modpack Skypopolis 4 - Beta 5

I have also reported this to the Modpack author in case this is their issue and not yours.

**Comment by Keksuccino** [comment]
Hi! Why did you had to exit the game with ALT+F4?

**Comment by CaptJack2883** [comment]
The accept button took me back to the same tips screen, which had a back button, but that only gave me the same error. Attempting to use the escape key also lead me through the same loop.

**Comment by Keksuccino** [comment]
Strange o.O Will try to reproduce this, thank you for telling me! :)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.7.1! Thank you for your report!
