### ISSUE TITLE
Can't move Mod Menu button

### ISSUE THREAD

**Issue by rbits0** [Keksuccino/FancyMenu#137]
**Describe the bug**
The mods button from Mod Menu doesn't show in the editor, so I can't remove it. This is a problem, because a button in my layout is overlapping with it.

**To Reproduce**
1. Install Fancy Menu and Mod Menu
2. Go to edit layout
3. Mods button doesn't show in editor

**Expected behavior**
Mods button should show in the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/56014573/107132993-1963fb80-6938-11eb-9406-368797b2b39a.png)
![image](https://user-images.githubusercontent.com/56014573/107132997-241e9080-6938-11eb-98ee-3d316c1d1e60.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.7.1
 - Fabric Version 0.11.1
 - Minecraft Version 1.16.5
 - Active Mods: Mod Menu, I also have MinimalMenu installed to hide the realms button. I also have Continue Button which adds the continue button to the menu

**Comment by Keksuccino** [comment]
Hi! Please try to uninstall MinimalMenu.
You can hide the Realms button with FancyMenu.

**Comment by Keksuccino** [comment]
Closed because no response. Please open a new issue if you still have problems with the mod.
