### ISSUE TITLE
Right Click on more things

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#138]
**Describe your idea**
It would be nice to be able to right click on the minecraft logo, copyright, and splash text and be able to do the things to them that the config.txt allows that you can not currently do now in the GUI.

**Comment by Keksuccino** [comment]
Adding these things to the editor screen would be a pain, FM's editor is just not built to hold more than vanilla buttons as default elements :/ Maybe I'll add it when I rewrite the editor some day, but will close this for now because it's very unlikely that it gets added, sorry :(

**Comment by kreezxil** [comment]
naw, you can shelve this permanently. I feel you've aptly covered everything I wanted in the FM menu.
