### ISSUE TITLE
[1.12.2] line feed/carriage return

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#14]
When entering images into the path box,

if you hit enter, it comes back with a screen that says the image is not found at the location

**HOWEVER**, if you instead hit the done button and not the enter key, with the same exact path typed, it will load the image at that location.

**Comment by Keksuccino** [comment]
I will look into it, thank you for reporting this!

**Comment by Keksuccino** [comment]
Fixed with FancyMenu v1.0.1.
