### ISSUE TITLE
Add the option for a delay appearance for splash text

### ISSUE THREAD

**Issue by Owehttamy** [Keksuccino/FancyMenu#140]
Pretty straightforward suggestion. Just like the buttons have the option to input a delay appearance by seconds, it would be nice to have that same option for splash text, and maybe even the same for the logo itself, too.

Very similar to #138 but I'd particularly be content with simple delay functionality.

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.0.0! Thank you for your suggestion!
