### ISSUE TITLE
Dark overlay in Main Menu 1.12.2

### ISSUE THREAD

**Issue by LabsZero** [Keksuccino/FancyMenu#141]
**Describe the bug**
When I exit a multiplayer sever and then go back to the main menu the whole Main Menu goes into a dark overlay.

**To Reproduce**
1. Go to 'Multiplayer'
2. Click on 'a server'
3. Scroll down to 'Exit that server'

**Expected behavior**
It should not be showing as i have no overlay in place that could be causing it

**Crash Log**
N/A

**Screenshots**
https://i.imgur.com/35wxo42.png

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.7.1
 - Forge Version 14.23.5.2855
 - Minecraft Version 1.12.2
 - Active Mods OptiFine, and a lot of mods in my modpack i can provide a curseforge zip if required.

**Comment by Duatao7055** [comment]
Could you provide your modlist? I've been having the same issue and I could narrow down the problem mods based on the mods we have in common.

**Comment by Duatao7055** [comment]
I did some testing and I figured out that this bug occurs using Fancy Menu 1.7.1, Konkrete 1.1.3, and Forge 14.23.5.2854, and it appears to be an issue with the player entity being rendered on a custom gui. When the game first loads up and I get to the gui with a player entity, there is no dark overlay, but when I enter and exit a world, the gui will have an overlay. The overlay color seems to depend on the brightness in game, as I've tested entering and exiting a world at different times of day, with and without night vision, and with brightness: bright and moody and the results of the overlay change. Here are some screenshots, each labelled with the situation the world was in that I left before they were taken.
Night vision and brightness: bright at night time
![Bug1](https://user-images.githubusercontent.com/68502073/109073595-73402180-76ab-11eb-926b-82d806832035.png)
No night vision, still using brightness: bright at night time
![Bug2](https://user-images.githubusercontent.com/68502073/109073634-80f5a700-76ab-11eb-8552-5ada8e058fa3.png)
No night vision, brightness: moody at night time
![Bug3](https://user-images.githubusercontent.com/68502073/109073704-9ff43900-76ab-11eb-844f-4132dd828bf4.png)
No night vision, brightness: moody during the day
![Bug4](https://user-images.githubusercontent.com/68502073/109073813-c4e8ac00-76ab-11eb-93be-54aa36d1db69.png)
The overlay only starts existing when I open the custom gui with the player entity on it, but persists when I enter any gui with or without the player entity. The overlay stops when I enter any world. Here are the config files I used:
[overworld.txt](https://github.com/Keksuccino/FancyMenu/files/6039226/overworld.txt)
[overworld.txt](https://github.com/Keksuccino/FancyMenu/files/6039231/overworld.txt)
The first is the customguis file, the second is the customization file.

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.0.0! Thank you for your report!
