### ISSUE TITLE
[1.16.5] Custom title/icon crash on MacOS

### ISSUE THREAD

**Issue by KR33PY** [Keksuccino/FancyMenu#142]
**Describe the bug**
If ran on MacOS, the game crashes as soon as FancyMenu tries to change main window's title/icon to its custom counterpart.
These operations should be ran on Minecraft's main thread, MacOS is picky about it.

**Crash Log**
The crashlog is fairly dirty and filled with other mods, but I'm sure the problem can be reproduced with only FancyMenu installed.
https://pastebin.com/r9KgZruL

**Basic Informations (please complete the following information):**
 - OS: MacOS
 - FancyMenu 1.7.1
 - Forge 36.0.21
 - MC 1.16.5

**Comment by Keksuccino** [comment]
Hi :) What version of macOS are you using exactly?

**Comment by KR33PY** [comment]
> 
> 
> Hi :) What version of macOS are you using exactly?

I'm not using MacOS, I'm just transferring one of my players' bugreport.
I've dealt with this type of issue before and running rendering operations on main (first) thread helps.

**Comment by Keksuccino** [comment]
Hopefully fixed this in FancyMenu v2.0.0. If it still happens, please tell me, thank you very much!
Tried it with macOS 10.13.6 and it works fine there.
