### ISSUE TITLE
1.16.5 crash on singleplayer menu open

### ISSUE THREAD

**Issue by AlexTheDolphin0** [Keksuccino/FancyMenu#146]
**Describe the bug**

I try to open the singleplayer menu, and it just crashes.
It didn't do that earlier, so I assume it's one of the updated mods or the of new ones.
New: Better Badlands, Cartographer, Fletching Table Mod, JEITweaker, CraftTweaker, Omni, JER, Create Crafts and Additions, More Crafting Tables
Updated: Alex's Mobs, Architectury, Collective, Customizable Elytra, Double Jump, FTB Gui Lib, FTB Quests, Repurposed Structures, Weapon throw. Just hoping somebody could help figure out why, as it seems its a problem with fancymenu 

**To Reproduce**
1. Go to 'The Main Menu(with my current modlist)'
2. Click on 'Singleplayer Menu'
3. Scroll down to 'don't'
4. See crash

**Expected behavior**
A clear and detailed description of what you expected to happen.
It opens the singleplayer menu without crashing

**Crash Log**
If the bug includes a crash, please paste or link it here.
[crash-2021-02-24_18.13.38-client.txt](https://github.com/Keksuccino/FancyMenu/files/6039640/crash-2021-02-24_18.13.38-client.txt)

**Screenshots**
Nah just crashes

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - FancyMenu Version [e.g. 0.2] 1.7.1
 - Forge/Fabric Version [e.g. 31.2.24] Forge 36.0.42
 - Minecraft Version [e.g. 1.15.1] 1.16.5
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] file too big to upload to github. Here is Mediafire download: http://www.mediafire.com/folder/k6cwxuzjkyjxz/mods

**Comment by Keksuccino** [comment]
Hi! Your crash log does not contain any lines retated to FancyMenu.
Could you please send me your full latest.log file (located at `.minecraft/logs/latest.log`) after the crash happened?

P.S.: For general mod help, better ask in the [Discord](http://discord.keksuccino.de).
You will get an answer much quicker than here! :D

**Comment by Keksuccino** [comment]
Closed because general mod help, better use the Discord linked above! :)
