### ISSUE TITLE
[FEATURE] Easing and Interpolation

### ISSUE THREAD

**Issue by mempler** [Keksuccino/FancyMenu#147]
# Easing and Interpolation
There should be a way to have an
E.G Button ease in/out from a Coordinate.

## Simple Example
Let's say you got an Button at coordinate X and you want to move it to coordinate X+10 in 0.2s, it would feel odd if it just pops onto the target coordinate.
So, why not add interpolation, as an example Linear Interpolation
![linear.png](https://user-images.githubusercontent.com/33131394/110654991-f179e900-81be-11eb-9554-c20e504ea635.png)

It would make it possible to have some really fancy menus.

## Interpolation List
List that should be implemented: https://easings.net/

## Might want to consider
The same goes for (A)Alpha Fading, Scaling, Positioning, (RGB)Color fading and Color mixing.
Maybe also a way to declare custom mathematical formulas to create interpolations which can be later used for the things mentioned above.

**Comment by Keksuccino** [comment]
I will maybe add this in a future update via #412 but will close this issue for now.
