### ISSUE TITLE
Game crashes while loading with RandomPatches

### ISSUE THREAD

**Issue by Duatao7055** [Keksuccino/FancyMenu#148]
**Describe the bug**
The game crashes while loading with RandomPatches only with FancyMenu 2.0. Also, the crash only occurs when the config option patchMinecraftClass is true in RandomPatches.

**To Reproduce**
1. Launch the game with the listed mods and forge version.
2. Crash.

**Expected behavior**
The game probably shouldn't crash on startup with RandomPatches installed.

**Crash Log**
[latest.log](https://github.com/Keksuccino/FancyMenu/files/6127681/latest.log)

**Screenshots**
If applicable, add screenshots to help explain your problem. No.

**Basic Informations (please complete the following information):**
 - OS: Linux
 - FancyMenu Version: 2.0
 - Forge/Fabric Version: 14.23.5.2855
 - Minecraft Version: 1.12.2
 - Active Mods: FancyMenu 2.0, Konkrete 1.1.4, MixinBootstrap 1.0.5, RandomPatches 1.22.1.10

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.0.1! Thank you for your report!

**Comment by Duatao7055** [comment]
Really appreciate the quick fixes. I love the mod and am making a modpack, so I'll be making more reports if anything comes up.
