### ISSUE TITLE
[all versions] context menus

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#15]
When right clicking to choose "orientation" for example, depending on where the element is in the layout creator, you cant see all of the options.

The context menu needs to do like Windows, Linux, & Mac does, and move the context part of the menu that getting clipped by the view port into a position where the user can click on any of the context menus options.

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/80416019-098f9500-8899-11ea-86dc-ad22ede65e57.png)

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/80416054-1c09ce80-8899-11ea-9d9b-78dce2b0c532.png)

**Comment by Keksuccino** [comment]
Fixed with FancyMenu v1.1!
