### ISSUE TITLE
Main Menu Crash

### ISSUE THREAD

**Issue by battery3996** [Keksuccino/FancyMenu#150]
**Describe the bug**
When loading into another mods gui, the game crashes with the latest update. I have Content Creator Integration installed for streamers. I added a main menu button that opens the gui for quick easy access. Latest 2 versions have crashed. I can load the `me.ichun.mods.cci.client.gui.cci.firstrun.WorkspaceFirstRun` on Fancy menu v. 1.7.1 but not on 2.0.1 or 2.0.2

needless to say but im staying on version 1.7.1 till this is fixed

**To Reproduce**
1. create a gui button that leads to `me.ichun.mods.cci.client.gui.cci.firstrun.WorkspaceFirstRun` with the mod installed. (dont include ` )
2. click on newly created button
3. crash.

**Expected behavior**
It should load up to the gui menu i linked. However v2 crashes and v. 1.7.1 is the last known version still working. 

**Crash Log**
https://pastebin.com/Wbz2SbBy

**Screenshots**
https://i.imgur.com/1klJJH4.png - this is what it should link to. 

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.0.1 & 2.0.2 (1.7.1 is working)
 - Forge/Fabric Version 35.1.37
 - Minecraft Version 1.16.4
 - Active Mods Alot

**Comment by Keksuccino** [comment]
Hi! I installed the mod you've mentioned and opened the GUI with a custom button in the main menu, but it seems to work fine for me, so I think one of your other mods is causing it.

However, I tried to fix it! Can you please try if the crash is fixed in this version?
https://drive.google.com/file/d/179kWtQUNo-4XPVV-PlsQCBXFFAnqeWOz/view?usp=sharing

Thank you!

**Comment by battery3996** [comment]
The dev build allowed me to open the gui as it use to. Thank you for the change you made. Not too sure on what was causing the issues before but whatever you did fixed it. Ill be on the look out for the curseforge release.

**Comment by Keksuccino** [comment]
Great to hear that! :) CurseForge release will be ASAP!

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.0.3! Thank you for your report!
