### ISSUE TITLE
custom window title not working in latest version (custom icon works tho)

### ISSUE THREAD

**Issue by PQxDev01** [Keksuccino/FancyMenu#151]

**Comment by Keksuccino** [comment]
Closed because no informations given.

**Comment by PQxDev01** [comment]
what kind of more info can I give about that? it just doesn't work
oh maybe that would help: when the client is loading, the custom title appears, but once it reaches the minecraft title screen, it reverts to Minecraft 1.16.5

**Comment by Keksuccino** [comment]
Maybe your MC version, Forge version and yes, a description of the bug would help too :D You know, just like the bug report template tells you.

Custom titles are working fine for me in MC 1.16.5. Do you have any other mods installed? Maybe it’s a mod conflict.

**Comment by PQxDev01** [comment]
Minecraft version: 1.16.5.
Forge version: I tested on 36.0.58 and 36.1.0, same problem.
Description: custom window title reverts to the default one once the mod-pack loading is almost done.
Mods used: https://www.curseforge.com/minecraft/modpacks/dungeons-and-creations  (DnC 3.0 version).

**Comment by Keksuccino** [comment]
Thank you for the informations!
Do you maybe know if one of these mods has a feature to change the window title? Maybe you disabled this feature, but it could still be in conflict with FM.

**Comment by PQxDev01** [comment]
I finally found the mod that has the same feature! it was Random Patches, thank you for the help!
