### ISSUE TITLE
[1.16.5-Forge] Crash with the mod Chisels And Bits when opening the Iron Chisel GUI.

### ISSUE THREAD

**Issue by Gbergz** [Keksuccino/FancyMenu#152]
**Describe the bug**
The game crashes when opening the Iron Chisel GUI from Chisels And Bits.
Looks like a cross interaction with Fancy Menu & Chisels And Bits. Might also be tied to the fact I've customized the Game Menu ingame. (the escape menu where you go into the options etc.)

**To Reproduce**
1. Have FancyMenu installed.
2. Have Chisels And Bits installed.
2.5 Customize the ingame pause menu. (might be tied to the issue)
3. Grab an Iron Chisel
4. Open the Iron Chisel GUI.
5. Crash.

**Expected behavior**
Game not crashing when opening the Chisel GUI from Chisels And Bits.

**Crash Log**
https://pastebin.com/7kf8DciT

**Basic Informations:**
 - OS: Windows
 - FancyMenu Version 2.0.3
 - Forge Version 36.0.58
 - Minecraft Version 1.16.5
 - Active Mods
 https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3239322 (Scroll down)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.0.4! Thank you for your report!
