### ISSUE TITLE
Animations are not being detected at all

### ISSUE THREAD

**Issue by scarha** [Keksuccino/FancyMenu#153]
**Describe the bug**
Install the mods latest release 2.0.3 for forge and make a custom layout and try to add an animation either as a background or just in general and the animations dont get detected. I have tried a folder named animation (implies i followed all the steps) with images in it in png format first then jpeg and then jpg, I've also tried gifs of varying sizes from 150mb to 300kb and it never detects my animations. And yes i have created a blank properties.txt for all of them.

**To Reproduce**
1. Go to 'layout editor'
2. Click on 'new elements - animations - (type in the name)'
3. And it doesnt detect any animations. (Same for the BG animation, does not detect any animations)

**Expected behavior**
For the mod to detect animations..

**Crash Log**
If the bug includes a crash, please paste or link it here.

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.0.3
 - Forge/Fabric Version 36.1.0
 - Minecraft Version 1.16.5
 - Active Mods 293 other mods excluding optifine. The list is quite long.

**Comment by Keksuccino** [comment]
> And yes i have created a blank properties.txt for all of them.
Have you filled it with the necessary stuff too?
http://fm.keksuccino.de/link/35#bkmrk-setting-up-the-anima

**Comment by scarha** [comment]
I did not find that on wiki, all i found was a line saying "leave it blank" Thanks for the link though. I got around it by just importing the gif as image and putting it behind every other element and stretching to width and height.

**Comment by Keksuccino** [comment]
No problem! :)
Btw, I really recommend you to join the Discord, if you want. You will get help much faster! http://discord.keksuccino.de

**Comment by ALPHAGAMER42** [comment]
Is there any new links for discord as domain of that link has expired

**Comment by Keksuccino** [comment]
https://discord.gg/UzmeWkD

There’s a Discord button on the project pages of all my mods. These will always work! :)
