### ISSUE TITLE
Crashes when trying to open inventory while using Carry On

### ISSUE THREAD

**Issue by ironsnake345** [Keksuccino/FancyMenu#155]
**Describe the bug**
When pressing the "open inventory" key while carrying a mob or tile entity using the Carry On mod, the game freezes for a moment, then crashes.

**To Reproduce**
1. Open up a world while running both Fancy Menu and Carry On
2. Shift-right-click a mob or tile entity to grab it
3. Press "open inventory" key (default is E)
4. Game crashes

**Expected behavior**
When pressing E, either the inventory opens up like normal, or it just doesn't open; it doesn't crash.

**Crash Log**
Link to crash log generated by Not Enough Crashes mod:
https://gist.githubusercontent.com/natanfudge/4503828f307846dc41b2667c6e70084e/raw/aa9dcced6dd4d9caadbdd24ddc8feea26f034e0f/crash.txt

**Screenshots**
Not applicable.

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 2.0.1_MC_1.16.2-1.16.5
 - Forge/Fabric Version: Forge 36.0.42
 - Minecraft Version: 1.16.5
 - Active Mods: From submitting this to the Carry On issue page, it was determined that the crash is specifically from how this mod interacts with Carry On. However, I am playing a modpack, just in case that might play into this. The modpack is Automation Nation, and here is the link: https://www.curseforge.com/minecraft/modpacks/automation-nation

Note: I personally have not tested this on a world with JUST Carry On and Fancy Menus; I'm not entirely sure how to do that, sorry.
I previously submitted this as an issue with Carry On, and it was determined that the issue lay in this mod, so I was told to submit the report here.

**Comment by Keksuccino** [comment]
Thank you for your report! Will be fixed in the next update! :)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.0.4! Thank you for your report!
