### ISSUE TITLE
[1.16.5] Crash when opening inventory while holding entity using CarryOn mod

### ISSUE THREAD

**Issue by JaisDK** [Keksuccino/FancyMenu#156]
**Describe the bug**
While holding an animal (as part of the CarryOn mod) and trying to open your player inventory, the game crashes.

This happened to me while playing the "All in One  Modded One Block" pack, I have not had time to reproduce in a separate environment.

**To Reproduce**
1. Load the pack
2. Sneak right click an animal, I was holding a Bee
3. Press 'E'
4. Crash

**Expected behavior**
Open player inventory

**Crash Log**
[debug-1.log](https://github.com/Keksuccino/FancyMenu/files/6216544/debug-1.log)

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows]
 - FancyMenu Version [e.g. 0.2] fancymenu_2.0.3_MC_1.16.2-1.16.5
 - Forge/Fabric Version [e.g. 31.2.24] Forge 36.1.0
 - Minecraft Version [e.g. 1.15.1] 1.16.5
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] No Optifine

**Comment by Keksuccino** [comment]
This already got fixed in FancyMenu v2.0.4 (#155), please update the mod :)
