### ISSUE TITLE
The Pixelmon Modpack crash

### ISSUE THREAD

**Issue by srnyx** [Keksuccino/FancyMenu#159]
**Describe the bug**
The instance crashes before MC is even launched.

**To Reproduce**
1. Install GDLauncher
2. Add [The Pixelmon Modpack](https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack) via the Twitch option
3. Launch the instance
4. Experience crash

**Expected behavior**
The instance should've launched fine

**Crash Log**
https://paste.srnyx.xyz/ecebinikoh.yaml

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 2.0.6
 - Forge Version: 14.23.5.2855
 - Minecraft Version: 1.12.2
 - Active Mods: [The Pixelmon Modpack](https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack)

**Comment by Keksuccino** [comment]
MixinBootstrap is a dependency for FancyMenu 1.12, which isn’t installed in your instance, that’s the problem.

**Comment by Keksuccino** [comment]
This modpack uses a way older FM version, why do you have FM 2.0.6 active? I think the layout of this pack isn’t even compatible with 2.0.6 ^^

**Comment by srnyx** [comment]
> This modpack uses a way older FM version, why do you have FM 2.0.6 active? I think the layout of this pack isn’t even compatible with 2.0.6 ^^

Oh, do you think not having FM installed cause any issues? Weird how The Pixelmon Modpack doesn't include MixinBootstrap.

**Comment by Keksuccino** [comment]
It doesn’t have MixinBootstrap as dependency, because the version used in the pack doesn’t depend on it. That’s why I asked you why you’re using the newest version. Maybe it’s a bug in your launcher.

It wouldn’t cause problems, you can remove FM from the pack :)

**Comment by srnyx** [comment]
> It doesn’t have MixinBootstrap as dependency, because the version used in the pack doesn’t depend on it. That’s why I asked you why you’re using the newest version. Maybe it’s a bug in your launcher.
> 
> 
> 
> It wouldn’t cause problems, you can remove FM from the pack :)

It didn't work before I updated it though either

**Comment by srnyx** [comment]
> It doesn’t have MixinBootstrap as dependency, because the version used in the pack doesn’t depend on it. That’s why I asked you why you’re using the newest version. Maybe it’s a bug in your launcher.
> 
> 
> 
> It wouldn’t cause problems, you can remove FM from the pack :)

It didn't work before I updated it though either

**Comment by Keksuccino** [comment]
You’ve manually updated FM to that version? What exactly didn’t worked before you updated it? It can’t be the same error as shown above, that’s simply not possible.

**Comment by srnyx** [comment]
> You’ve manually updated FM to that version? What exactly didn’t worked before you updated it? It can’t be the same error as shown above, that’s simply not possible.

I'll look into it again.

**Comment by srnyx** [comment]
> I'll look into it again.

Alright, you were right. Sorry about that.
It doesn't give me any errors, and it starts fine when not updating the mod.
What exactly does FancyMenu do for The Pixelmon Modpack? Like, am I able to play without it completely fine?

**Comment by Keksuccino** [comment]
Yep, it’s save to remove it. It only tweaks the main menu to a very cool new one, it doesn’t add new menus or something :)
