### ISSUE TITLE
Music carrying over into other menus

### ISSUE THREAD

**Issue by BLUcat5995** [Keksuccino/FancyMenu#161]
**Describe your idea**
An example would be: you are on the main menu with music playing, and then you click on options and the music doesn't stop but it continues and same thing when you go back.
Edit: Same thing with backgrounds

**Comment by Keksuccino** [comment]
That’s already a thing. Just add the same music to both menus and then it will continue (without restarting) when going from one menu to the other one.

Same for backgrounds.
You literally just need to add the background to both menus :D

**Comment by BLUcat5995** [comment]
Ok thanks :)

**Comment by Keksuccino** [comment]
np!
