### ISSUE TITLE
It doesn't load unless I press ctrl g (keybinding to toggle customization)

### ISSUE THREAD

**Issue by Henryws** [Keksuccino/FancyMenu#162]
**Describe the bug**
When it loads, and I press options and then done, the menu doesn't load unless I press ctrl g (keybinding to toggle customization buttons). The weird thing is, my character model is still there, but not the buttons like single-player multiplayer.
**To Reproduce**
1. Download the necessary files (1.7.1) and launch the game
2: Click options and click done. It doesn't show anything until I press ctrl g

**Expected behavior**
I don't have to press ctrl g

**Screenshots**
https://ufile.io/e0f8xfc9

**Basic Informations (please complete the following information):**
 - OS: Arch Linux
 - FancyMenu 1.7.1
 - Fabric 1.16.5
 - 1.16.5
 - Fancy Menu 1.7.1
 - Koncrete 1.1.6
 - Phosphor 1.16.3
 - LazyDFU 0.1.2
 - Maililib 1.16.4-0.10.0
 - Tweakeroo 1.16.4-0.10.0
 - Architectury 1.10.139
 - SlightGUIModifications 1.6.1
 - Smoothboot 1.16.5-1.6.0
 - InventoryHUD 3.2.2
 - Optifabric
 - Armorhotswap 1.16-1.2

**Comment by Keksuccino** [comment]
FancyMenu v1.7.1 is not the newest build. Please download the newest version (v2.0.5-1) and check if this fixes your problem.

**Comment by Henryws** [comment]
The newest one crashes with null error

**Comment by Keksuccino** [comment]
Try to start the game with only FancyMenu and Konkrete installed, please.

**Comment by Henryws** [comment]
It works. What mod would be the issue?

**Comment by Henryws** [comment]
It was slight gui modifications

**Comment by Keksuccino** [comment]
Check [this](http://fm.keksuccino.de/books/fancymenu-v20x/page/20x-incompatibility-list). Maybe it starts when you disable GUI animations and the uncap FPS feature. If not, please let me know so I can update the incompatibility list! Thank you very much :)

**Comment by Henryws** [comment]
It works with these settings:
```
{ 
	"fluidAdvancements": true,
	"fluidStatusEffects": true,
	// Whether we should unlimit the hard 60 fps limit placed on the title screen.
	"unlimitTitleScreenFps": false,
	"openingAnimation": { 
		"fluidChatOpening": true,
		"fluidOpenSlideFromBottom": false,
		"fluidOpenFade": false,
		"fluidAnimationDuration": 105,
		"affectsGameMenus": false,
		"affectsInventories": true,
		"ignoreSlideWhenRedirected": true,
		"ignoreFadeWhenRedirected": false
	},
	"textFieldModifications": { 
		// Whether this module is enabled.
		"enabled": false,
		/* Set to Color to use the Border and Background Color.
		   Set to Texture to use resource pack:
		   /assets/minecraft/textures/gui/text_field.png
		   
		   More documentations on website.
		*/
		"backgroundMode": "COLOR",
		"borderColor": 10526880,
		"backgroundColor": 0,
		"selectionMode": "INVERT",
		// Whether Text Fields should allow right click actions.
		"rightClickActions": false
	},
	"sliderModifications": { 
		// Whether this module is enabled.
		"enabled": true,
		"grabberWidth": 8,
		/* Whether to use custom texture:
		   /assets/slightguimodifications/textures/gui/slider(_hovered).png
		   or
		   /config/slightguimodifications/slider(_hovered).png
		*/
		"customBackgroundTexture": false
	},
	"debugInformation": { 
		"showFps": false
	},
	"customScaling": { 
		"vanillaScaleSlider": false,
		"scale": 1.0
	},
	"slotHighlight": { 
		// Whether this module is enabled.
		"enabled": true,
		"color": -2130706433
	},
	"tooltipModifications": { 
		// Whether this module is enabled.
		"enabled": false,
		"backgroundColor": -267386864,
		"outlineGradientTopColor": 1347420415,
		"outlineGradientBottomColor": 1344798847
	},
	// Whether GUI should allow right click actions.
	"rightClickActions": false,
	"satisfyingScreenshots": true
}
```
But I really liked the animations for inventory and stuff. At least the chat slide still works...
