### ISSUE TITLE
Option to center button tooltips

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#166]
![image](https://user-images.githubusercontent.com/3880072/117439627-afd49880-aef8-11eb-93b5-7c6b2b02ee4b.png)

I think it's a bug, could be a feature request

minecraft: 1.16.5
forge: 36.1.16
fancy menu: 2.06-1_MC_1.16.2-1.16.5
konkrete: 1.1.6_MC_1.16.2-1.16.5

**the happening**:
tool tips render to the right or left of the mouse

**expected to happen**:
tool tips to render centered on the mouse

**Comment by Keksuccino** [comment]
That’s not a bug, the tooltip is just too long for the screen, dude. You can add a new line with the newline formatting code. I think it was `%n%`, but better check the tooltip of the Tooltip button, the correct formatting code is there.

**Comment by kreezxil** [comment]
change this bug report to a feature request to add a new option to center a
tooltip on the mouse pointer. like if %c% is found as the first character,
but only there, then the entire tooltip is centered on the mouse. no line
by line centering, not asking for that.

yes I did reformat using the %n% and that just made the tooltip go right or
left depending on the side of the screen I was on.

**Comment by Keksuccino** [comment]
Will not add that, sorry.
But maybe support for FM's Markdown renderer in the future, which would also mean adding support for alignment formatting codes.
