### ISSUE TITLE
File Dialogs

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#17]
When entering in paths for where textures live, it would be nice to a have a `browse` button that would in turn open a file dialog that would allow us to pick the texture that way. The code then can write that out in a linux compatible (universal) file path. This would go a long way in alleviating the issue #16 where manually typed paths if entered windows style can cause problem on linux and mac systems.

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.1!
