### ISSUE TITLE
[FABRIC] Delay: off, but Automatic Button Click

### ISSUE THREAD

**Issue by ArkQuark** [Keksuccino/FancyMenu#170]
**Describe the bug**
By clicking on the button, right-click on the singleplayer (vanilla button) and delay appearance and Delay: off . After that, the automatic button clicks opens.

**Expected behavior**
Delay config

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: fabric_2.0.5-1_MC_1.16.3-1.16.5
 - Fabric Version: 0.11.3-1.16.5
 - Minecraft Version 1.16.5
 - Active Mods: appleskin, betterbiomeblend, cloth, craftpresence, dynamicfps, enchantmentdescription, fabricapi, chunkpregen, voxelmap, fabriczero, ferritecore, hwyla, modmenu, optifabric, optifine, phosphor, randompatches, rer,
rei, smoothboot, spark

**Comment by Keksuccino** [comment]
Not reproducible in Forge, will check it later in Fabric.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
