### ISSUE TITLE
Game crash NoClassDefFoundError: net/minecraft/client/gui/GuiButtonLanguage

### ISSUE THREAD

**Issue by nacjm** [Keksuccino/FancyMenu#171]
**Describe the bug**
Game crashes showing a Noclassdeffound error.
**To Reproduce**
1. launch game
2. wait a few moments
3. see error

**Expected behavior**
A clear and detailed description of what you expected to happen.
modpack should load up
**Crash Log**
If the bug includes a crash, please paste or link it here.
https://gist.github.com/nacjm/5da94f32e57aae0e383cdfcc52aeebe7
Note: Randompatches is already set to not patch minecraft class and was removed when I still got this crash
**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - FancyMenu Version [e.g. 0.2]2.07
 - Forge/Fabric Version [e.g. 31.2.24]14.23.5.2855
 - Minecraft Version [e.g. 1.15.1]1.12.2
 - Active Mods [e.g. Optifine, 5zig, TooManyItems]
[MOD LIST REMOVED BC CULPRIT FOUND]

**Comment by nacjm** [comment]
Figured out the cause, Dalek Mod's Main Menu overrode it. I suggest adding it to the incompatibility list. Turning off Dalek mods Main menu fixed the bug.

**Comment by Keksuccino** [comment]
Thank you for reporting back the cause of the crash! Will add it to the incompatibility list and will look a bit deeper into the crash, because it shouldn't throw that error by only overriding the main menu. Thank you for telling me!

**Comment by Keksuccino** [comment]
Reopened again because the error happened for another user. oof

**Comment by Psykrot** [comment]
Fabric 1.17 
Fancy Menu does not load with Optifine (useing Optifabric) 
Maybe the user who reported it has the same issue.
The game is crashing on startup but not producing a crash report.

**Comment by nacjm** [comment]
This issue was on 1.12 forge and was caused by ice and fires main menu overwriting fancy menus and crashing the client. Ima just say that a **highly doubt yours is the same**

**Comment by Keksuccino** [comment]
> Fabric 1.17
> Fancy Menu does not load with Optifine (useing Optifabric)
> Maybe the user who reported it has the same issue.
> The game is crashing on startup but not producing a crash report.

I will not start fixing Optifine bugs on Fabric. There are so much alternatives for Fabric and every single one of them is working more stable than Optifine. Why does one even want to use OF there??

**Comment by RDKRACZ** [comment]
>Why does one even want to use OF there??

Well, the only reason is shaders.
