### ISSUE TITLE
Change Resource Pack Button Action

### ISSUE THREAD

**Issue by guipleys20** [Keksuccino/FancyMenu#172]
Idk if this already on the mod and I'm blind or something, but my idea is: add a button action that changes the current resourcepack on the game (and a button action for change shaderspack)

(and if possible, can you teach me how to enable the video settings button configuration?)

**Comment by Keksuccino** [comment]
Resource packs should be easy to do, will try to add this in one of the next updates! But shader packs are a bit different. You mean shader packs from Optifine, right? Will try to add this, but I’m not sure if I can add this in a good way.

To the video settings button thing: Do you mean how you can edit the buttons of the video settings? If so, this is sadly not possible, I’m sorry. These buttons are part of a scroll area and FancyMenu can’t edit scroll areas :/ (Would be way too difficult to add)

**Comment by guipleys20** [comment]
No worries for the part of the video settings, I give my way, but thank you for listen to my suggestion!

**Comment by guipleys20** [comment]
No worries for the part of the video settings, I give my way, but thank you for listen to my suggestion!

**Comment by Keksuccino** [comment]
Well, I decided to not add this, because I don't want to mess with resource loading and handling more than I have to. Sorry :/
