### ISSUE TITLE
Advancements gui not supported

### ISSUE THREAD

**Issue by Duatao7055** [Keksuccino/FancyMenu#174]
**Describe the bug**
The advancements gui is unable to be opened by a button that uses open gui and then uses the correct menu identifier for the advancements gui.

**To Reproduce**
1. Open your inventory.
2. Create a button that uses open gui with the correct menu identifier for the advancements gui
3. Click on the button
4. Unable to open GUI

**Expected behavior**
The button should open the advancements gui.

**Crash Log**
If the bug includes a crash, please paste or link it here.

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Linux
 - FancyMenu Version 2.0.7-1
 - Forge/Fabric Version 14.23.5.2855
 - Minecraft Version 1.12.2
 - Active Mods FancyMenu, Konkrete

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.1.0! Thank you for your report!
