### ISSUE TITLE
Labels get stuck on screen after closing the editor.

### ISSUE THREAD

**Issue by githubbingitup** [Keksuccino/FancyMenu#177]
Glitch 1:
Example: you create a label box that links to a Discord.
Sometimes after moving it around, saving and exiting the editor you'll see one in the new place and one in the old place.

The old one won't show up in the editor so it can't be deleted. If you delete the new one, the old one is still stuck there.
There's no way to remove it in the config file that I can find.

The only way to fix it is to start over. Only seems to happen to external links. 

Glitch 2:
Sometimes exiting the editor makes all the vanilla labels (for singleplayer, etc.) appear in their original spots.
Easiest way to replicate this is going into an editor on a loading screen, which really bugs things out.

**Comment by Keksuccino** [comment]
Do you use any other mods? If so, please try to start the game with only FM + dependencies installed.

And please include MC version, launcher, used mods and everything from the template. I can’t help you if I don’t know anything about your setup, dude.

**Comment by Keksuccino** [comment]
I wasn't able to reproduce this in a clean instance with FancyMenu + dependencies installed.
It's most probably a mod conflict, so I will close this for now.
Thank you for your report!
