### ISSUE TITLE
Game shows the background when escaping out of the config menu

### ISSUE THREAD

**Issue by Spiderfffun** [Keksuccino/FancyMenu#178]
**Describe the bug**
Game shows the background when escaping out of the config menu

**To Reproduce**
1. Click the icon in the upper left corner
2. Press esc
3. See the background screen (buttons clickable)

**Expected behavior**
The buttons are clickable, but im stuck on the background screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/85702798/122989372-0875cd00-d3a3-11eb-9f41-0fe662fe2a6b.png)

**Basic Informations (please complete the following information):**
 - OS: Win 10
 - FancyMenu Version 2.1.1
 - Forge/Fabric Version Latest
 - Minecraft Version 1.17
 - Active Mods (I have too much, so i will put screenshots)

**Comment by Spiderfffun** [comment]
I just relised that you have to not save something for it to happen.

**Comment by Keksuccino** [comment]
I wasn't able to reproduce this in a clean instance with only FancyMenu + dependencies installed.
It's most probably a mod conflict, so I will close this for now.
Thank you for your report!
