### ISSUE TITLE
[1.17] Log Spam everytime I enter or exit fullscreen (F11)

### ISSUE THREAD

**Issue by Fogrits** [Keksuccino/FancyMenu#179]
FancyMenu 2.1.1
Konkrete 1.2.0
![image](https://user-images.githubusercontent.com/14002834/123181049-e0e63980-d462-11eb-8931-ceeeaf4cdf2d.png)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.1.2! Thank you for your report!
