### ISSUE TITLE
FancyMenu treating different ways of dying as different death menus

### ISSUE THREAD

**Issue by SpencerMeow** [Keksuccino/FancyMenu#180]
I have to re-make all the features of my menu for every different source I die from for them to actually happen. I'll die and the respawn buttons will be there instantly and I'll go and for example set a delay on the respawn button (even though it shows the menu layout as enabled however I die) and it will show the delay upon exiting the menu editor, but next time I die that way or any other way it won't do it. I also can't get any sounds to play on the death screen.
So I set a sound to play on the death screen, and when I die, it doesn't play, but when I open the layout editor it plays in there just fine.
Additionally, the menu open sound also plays when the menu closes, even though I didn't specify a menu close sound.

 - OS: Windows 10
 - FancyMenu Version 2.1.0
 - Forge 14.23.5.2854
 - Minecraft 1.12.2

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.7.1! Thank you for your report!
