### ISSUE TITLE
Option for making layout apply to all sub-menus (same as white/blacklist for universal layouts)

### ISSUE THREAD

**Issue by SpencerMeow** [Keksuccino/FancyMenu#181]
Let's say I want the music playing in the options menu to play in allll the sub-menus in options like video settings, controls, etc. instead of making a whole new menu for each one it would be easier to have a button to check that says "Apply layout for all submenus" or something.

**Comment by Keksuccino** [comment]
I could add an option to enable layouts for multiple menus. So let’s say you make a layout in menu A, then go to menu B and pick it from a menu to also enable it in this menu. Other things would be very complicated for how FM works atm :/

**Comment by SpencerMeow** [comment]
> I could add an option to enable layouts for multiple menus. So let’s say you make a layout in menu A, then go to menu B and pick it from a menu to also enable it in this menu. Other things would be very complicated for how FM works atm :/

That sounds great. It would also be awesome if it could be for 1.12.2 as well as the latest version.
