### ISSUE TITLE
Menu panorama (vanilla) is accelerating strangely

### ISSUE THREAD

**Issue by Kaleidio** [Keksuccino/FancyMenu#182]
**Describe the bug**
The panorama builds up speed then suddenly loses speed, accelerating like this over and over infinitely.  I've removed some mods that mixin with the main menu and I've found it happens no matter what.

**Basic Informations (please complete the following information):**
 - OS: (any)
 - FancyMenu Version (any)
 - Forge/Fabric Version (any)
 - Minecraft Version 1.16.5
 - Active Mods: Optifine G8, Kaleidio's Battle Pack

**Comment by Kaleidio** [comment]
Update: further testing shows it happens at literally any framerate.

**Comment by Keksuccino** [comment]
I wasn't really able to reproduce this, sorry. If it's still a thing in the new versions (especially 1.17+), please open a new issue. Thank you very much for your report!
