### ISSUE TITLE
Player Entities: Support for old 1.7 skins

### ISSUE THREAD

**Issue by ItsFaldo** [Keksuccino/FancyMenu#183]
I found that some skins are not rendering correctly on the player entity
Providing a direct image of the skin fixes it in some cases, but not always.

1. Create a new GUI or use an existing one
2. Add a Player Entity Element
3. Set the player name to Faldo (this is my name and this bug effects my skin)

Expected behavior:
For the skin to appear correctly (as seen in the second image)

**Screenshots**
![image](https://user-images.githubusercontent.com/84880814/123905743-c6ccbf80-d96a-11eb-859c-b02060e109c2.png)
![image](https://user-images.githubusercontent.com/84880814/123905773-d4824500-d96a-11eb-8997-8bb3da7bfffa.png)
![image](https://user-images.githubusercontent.com/84880814/123906244-b5d07e00-d96b-11eb-8f06-8b67492e581b.png)

 - OS: Windows 7
 - FancyMenu Version 2.1.2 For MC 1.16.2-1.16.5
 - Forge Version 36.1.0
 - Minecraft Version 1.16.5
 - Active Mods (see image 3)

**Comment by ItsFaldo** [comment]
i should also mention that my skin has been the same since around beta 1.7.3

**Comment by Keksuccino** [comment]
Not really a bug, the player entities simply do not support 1.8 skins atm ^^ Will add that soon, but for now only the new skins work.

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.2.0! Thank you for your suggestion!
