### ISSUE TITLE
Button Formatting Bug

### ISSUE THREAD

**Issue by Pjw03292** [Keksuccino/FancyMenu#186]
**Describe the bug**
Whenever I take my game out of full screen all the button formats get messed up and it looks like a mess

**Screenshots**
![image](https://user-images.githubusercontent.com/87955239/126933138-b5d9cd65-7667-43f9-b7b5-7b3d312771c9.png)

**Comment by Keksuccino** [comment]
That’s not a bug, you just need to use the correct orientations for your elements.
http://fm.keksuccino.de/link/59#bkmrk-3.-understanding-ele
