### ISSUE TITLE
Incompatible with Memory Usage Screen

### ISSUE THREAD

**Issue by X9DF** [Keksuccino/FancyMenu#187]
**Describe the bug**
Crashes when used alongside Memory Usage Screen

**To Reproduce**
1. Put both FancyMenu and Memory Usage Screen in the mods folder (with their respective libs)
2. Try to boot the game
3. Observe a crash

**Expected behavior**
No crashes happen

**Crash Log**
https://ghostbin.co/paste/mduf

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 2.2.0
 - Forge/Fabric Version: Fabric 0.11.6
 - Minecraft 1.17.1
 - Active Mods: FancyMenu, Memory Usage Screen, NotEnoughCrashes

**Comment by Keksuccino** [comment]
Should be fixed in FancyMenu v2.2.2! Thank you for your report!
