### ISSUE TITLE
Exiting menus doesn't exit the menu background

### ISSUE THREAD

**Issue by Mistyttm** [Keksuccino/FancyMenu#188]
**Describe the bug**
Exiting any menu from the main menu (possibly ingame as well, haven't been able to test) makes the game get stcuk on the options menu background

**To Reproduce**
1. Open any menu from the main menu
2. Press escape, or exit out of the menu
3. See frozen menu background

**Expected behavior**
Exiting a menu takes you back to the main menu

**Screenshots**
![image](https://user-images.githubusercontent.com/51770769/128342741-b044c28d-94cf-4af1-9ac2-abbcb621c2cd.png)

**Basic Informations:**
 - OS: Windows 21H1
 - FancyMenu Version 2.2.0
 - Fabric Version 0.11.6-1.17.1
 - Minecraft Version 1.17.1
 - Active Mods Accurate Block Placement, Appleskin, Architectury API, Auth Me, autoreconnect, axolotl item fix, better biome blend, better F3, boosted brightness, cherished worlds, cloth api, cloth config, controlling for fabric, Cull Leaves, Damage Tilt, damage tint, drip sounds, dynamic fps, dynamic music, easier villager trading, egg tab, entity culling, fabric api, falling leaves, fancy menu, fireplace lib, illuminations, item model fix, konkrete fabric, lazy dfu, litematica, lock minecraft view, malilib, minihud, mod menu, music duration reducer, name pain, nbt tool tip, not enough crashes, ok zoomer 5.0.0 beta, op items, optifabric, pling, optifine preview HD U G9 pre32, replay mod, right click clear, sheep consistency, shulker box tool tip, slight gui modifications, smoothboot fabric, status effect timer, textbook, world edit beta 2

**Comment by NRDsstuff** [comment]
i have the same problem on elementary os 6 and MC 1.16.5

**Comment by Keksuccino** [comment]
Is this still a problem? Because I wasn't able to reproduce this.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
