### ISSUE TITLE
1.12.2 Minecraft Logo deletet? 

### ISSUE THREAD

**Issue by Titoo8899** [Keksuccino/FancyMenu#19]
Hi,
how can I the Front with "Minecraft Java Editions" Image what from minecraft come delete?

<img width="960" alt="Anmerkung 2020-05-02 121245" src="https://user-images.githubusercontent.com/42325138/80866318-43440f80-8c8e-11ea-8b9a-6eb3d78c4837.png">

**Comment by Keksuccino** [comment]
You can hide the default minecraft logo by changing 'hidelogo' to 'true' in the config :)
The splash text can be hidden with 'hidesplashtext'.
https://github.com/Keksuccino/FancyMenu/wiki/Mod-Configuration#mainmenu
