### ISSUE TITLE
Randomize Option for Slideshows

### ISSUE THREAD

**Issue by szunakabeats** [Keksuccino/FancyMenu#191]
hey,

it would be nice if you could see a different picture every time you start the game. maybe there is the possibility to build in a shuffle mode. the more pictures you have in your slideshow, the more interesting the main menu remains

greetings, szunaka.

**Comment by Keksuccino** [comment]
You can randomize layouts :) This basically does exactly what you want :D 

To do this, right-click the editor background -> Random Mode

**Comment by Keksuccino** [comment]
Will close this for now. Feel free to answer me here if something you want to do isn't possible with the random layout feature :)

**Comment by szunakabeats** [comment]
hey man, i dont get it. if i turn on random mode there is a option "set random group" do i need to put in a number ?

because the Random Mode does not work my for my slideshow. everytime the first picture in the folder comes first
