### ISSUE TITLE
MultiMC MC 1.16: Audio is not playing

### ISSUE THREAD

**Issue by Duatao7055** [Keksuccino/FancyMenu#193]
**Describe the bug**
I have set an audio file to play in a custom gui and there is nothing but silence. I have verified that the audio file I want to play meets the requirements stated in the wiki faq.

**To Reproduce**
1. Create a custom gui
2. Add an audio to it (I used this one: [DramaticInterlude-AlexanderNakarada.wav.zip](https://github.com/Keksuccino/FancyMenu/files/7041425/DramaticInterlude-AlexanderNakarada.wav.zip))
3. Save the layout
4. Listen to the empty silence

**Expected behavior**
The audio should play when the gui is open.

**Crash Log**
No crash log, but here is the game log: https://paste.ee/p/detQc

**Basic Informations (please complete the following information):**
 - OS: Linux
 - FancyMenu Version: 2.2.2-2
 - Konkrete Version: 1.1.6
 - Forge Version: 36.2.2
 - Minecraft Version: 1.16.5
 - Active Mods: None other than Fancy Menu and Konkrete

**Comment by Keksuccino** [comment]
Please take a look at [this FAQ section](http://fm.keksuccino.de/link/54#bkmrk-why-is-my-audio-not-).
If you think you already have the correct bit- and sample rate, try to re-convert it anyway using the web tool linked in the FAQ :)

**Comment by Duatao7055** [comment]
That's the thing, I verified that my file was correct by using the re-converter and fixing the bit and sample rate.

**Comment by Keksuccino** [comment]
I see you're on Linux. Could be a bug related to your distro.
Can you send me your `.minecraft/logs/latest.log` file after adding the audio to a menu, please?

**Comment by Duatao7055** [comment]
I had my volume at 100%, and I put my latest.log file after adding the menu under the crash report.

**Comment by Keksuccino** [comment]
Well, I didn’t see the log, sorry >.<
Looks like an error caused by your distro or maybe a combination of MultiMC and your distro.

What Linux distro do you use exactly?

Oh and it could also be caused by Java. Maybe you’re using some kind of special Java version?

**Comment by Duatao7055** [comment]
I use Ubuntu, and I don't believe I use a special Java version. I am using Java 8.

**Comment by Keksuccino** [comment]
Please try to load the game + mod with the normal launcher (not MultiMC). Could be a MultiMC bug.

**Comment by Duatao7055** [comment]
I will try that, but I just loaded up my 1.12.2 instance with Fancy Menu that also adds custom audio to menus, and it seems to work fine.

**Comment by Duatao7055** [comment]
Okay I finally was able to test it and it does appear to be a MultiMC problem. The audio was working fine when I loaded up minecraft with the config and audio files copied over.

**Comment by Keksuccino** [comment]
I'm sorry, but I'm not fixing stuff for MultiMC anymore. I don't support this launcher anymore. Sorry.
