### ISSUE TITLE
Bug with button Replay mod on MC 1.17.1

### ISSUE THREAD

**Issue by Disguys** [Keksuccino/FancyMenu#195]
**Describe the bug**
Error displaying the Replay mod button from FancyMenu on MC 1.17.1

**To Reproduce**
1. Install Replay mod and FancyMenu on Fabric 1.17.1
2. Turn on the customization menu and make sure that the button associated with replay mod is gone.

! On MC 1.16.5 there was no such mistake. !

**Expected behavior**
Display the replay mod button with the customization menu

**Screenshots**
![](https://cdn.discordapp.com/attachments/589022386620203019/881942150919639171/unknown.png)
![](https://cdn.discordapp.com/attachments/589022386620203019/881942260432896020/unknown.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Pro
 - FancyMenu Version 2.2.2-2
 - last version Fabric loader
 - Minecraft Version 1.17.1

**Comment by Keksuccino** [comment]
Hi! It's on Replay Mod's side to fix this. If they would add their buttons to menus the correct way, this wouldn’t happen. Sorry :/
Try to report the issue to the Replay Mod issue page.
