### ISSUE TITLE
Support 1.12.2

### ISSUE THREAD

**Issue by PixelmonPRO** [Keksuccino/FancyMenu#2]
**Describe your idea**
I would very much like to see support for version 1.12.2, many large mods (as an example, Pixelmon), so far on this version, as well as server (like Sponge).

**Does it frustrates you to not already have this feature in the mod?**
It would be great to see support for mods like:
[CustomMainMenu](https://www.curseforge.com/minecraft/mc-mods/custom-main-menu)
[SplashAnimation](https://www.curseforge.com/minecraft/mc-mods/splashanimation)

**Comment by Keksuccino** [comment]
I'm already working on a 1.12.2 port, but it's a bit tricky, so no ETA for now.

Support for CustomMainMenu is not planned, sorry. This would cause too much issues related to the button customization and other stuff...

I can try to add support for SplashAnimation, but I already planned to add a very similar feature to FancyMenu, so if I find a good way to make these work together, it will probably be added.

**Comment by Archilyte** [comment]
I thought FancyMain was the precursor to this, which supported 1.12...

**Comment by Keksuccino** [comment]
> I thought FancyMain was the precursor to this, which supported 1.12...

FancyMain does NOT fully support MC 1.12. It was never being able to load textures (for animations) out of the user directory. FancyMenu needs the ability to do this, so I can’t backport it to 1.12 before I found a good way for it.

**Comment by PixelmonPRO** [comment]
> > I thought FancyMain was the precursor to this, which supported 1.12...
> 
> FancyMain does NOT fully support MC 1.12. It was never being able to load textures (for animations) out of the user directory. FancyMenu needs the ability to do this, so I can’t backport it to 1.12 before I found a good way for it.

Maybe this mod?) https://github.com/lumien231/Resource-Loader

**Comment by Keksuccino** [comment]
Loading textures is not the problem, but the memory consumption. But I’m making progress with this, so no worries ^^

**Comment by Keksuccino** [comment]
- Added support for MC 1.12.2 -

**Comment by Archilyte** [comment]
where?
cant find it on curseforge
![Annotation 2020-04-01 090250](https://user-images.githubusercontent.com/39607601/78140192-9f014b80-73f7-11ea-843f-64a135fd203d.png)

**Comment by Keksuccino** [comment]
Interesting o.O Is there an option for CurseForge to hide alpha builds of mods?

Can you open the direct link?
https://www.curseforge.com/minecraft/mc-mods/fancymenu/files/2917875

**Comment by Archilyte** [comment]
I am not aware of any options that hide alpha builds...

Then again, CurseForge is very weird about showing alpha suff...

Yes I can open the link, thank you!

**Comment by Keksuccino** [comment]
FancyMenu v0.4.3.1 for MC 1.12 got released as BETA build on CurseForge. Everyone should now be able to see it in the files tab.
