### ISSUE TITLE
reload hotkey

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#20]
I find it inconvenient to activate the custom layout buttons to have access to a reloader for the menu.

I prefer to edit the files manually after I've created the layout.

A key define in the config, default to CTRL R would be cool to reload the menu. Should be on regardless of the state of the buttons.

**Comment by Keksuccino** [comment]
Will be added in the next update!

**Comment by kreezxil** [comment]
:cry: I was hoping that when you said next update, you meant like nearly now. Now I realize you were teasing me.

**Comment by Keksuccino** [comment]
hehe ^^ Shouldn’t take too long to get it done :) I’m currently working on the file chooser implementation for adding textures and some other stuff :D

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.1!

**Comment by kreezxil** [comment]
ok, this is causing a problem. for instance when I'm typing in a server address and the address has an 'f' in it, soon as type r, the line of text is wiped out and replaced with the hotkey value which is r. I know it's your mod because I changed it to 'i' and then it switched to doing the behavior on that hotkey. 

I tried setting it to ctrl+r, but it didn't care if ctrl was held own.

you need to ensure that players can type text in any box. the hotkey needs to check for qualifier keys, and I think honestly it needs to default to ctrl+r or alt-f5, something out of the way and it must require that key, it also should reset text, but I realize that is just an effect of reloading the current screen.

@Keksuccino

**Comment by Keksuccino** [comment]
Well, THAT'S bad. I will push an update to fix this ASAP.

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.1.1! The hotkey is now CTRL + your defined key! Thank you for telling me! ^^
