### ISSUE TITLE
Is it possible to hide the top bar?

### ISSUE THREAD

**Issue by kingarthur0975** [Keksuccino/FancyMenu#200]
Not a bug, but it nags me. On the 1.17.1 fabric version of the mod, is it possible to hide the control bar for the mod located at the top of the screen? If so, how exactly?

**Comment by Keksuccino** [comment]
Hi! You need to click on the little FM icon on the left side of the menu bar to open the settings. Now you can disable the "Customization Controls". You can also toggle the controls via keybind (CTRL + ALT + C by default).

**Comment by kingarthur0975** [comment]
Alight, thanks. Didn't see that setting.

**Comment by Keyhankemal2022** [comment]
i did this but i try undo this ctrl alt c but i think i changed the key and idk which
