### ISSUE TITLE
MixinGuiScreen target net.minecraft.client.gui.GuiScreen was loaded too early

### ISSUE THREAD

**Issue by BlizzardLight** [Keksuccino/FancyMenu#201]
**Basic Information**
Windows 10.0.19043.1165

[latest.log](https://github.com/Keksuccino/FancyMenu/files/7198751/latest.log)

**Comment by Keksuccino** [comment]
One of your core mods is incompatible with FancyMenu, maybe the incompatibility list can help:
http://fm.keksuccino.de/books/fancymenu-v22x/page/22x-incompatibility-list

**Comment by Keksuccino** [comment]
Will close this for now, because it's just a compatibility problem. If you have more questions, please join the Discord: http://discord.keksuccino.de :)
