### ISSUE TITLE
Custom Sliders and Modifying Existing Ones

### ISSUE THREAD

**Issue by CornerBasket** [Keksuccino/FancyMenu#202]
It would be great to have custom sliders that, when set to a value, can then be read by a button script to perform an action. For instance, you could have an "animation speed" slider that goes in increments of 1, from 0-4, that at each value replaces the animations with a slower or faster version.

It would also be really nice to be able to move existing sliders, like the FOV one in the options menu. In addition, being able to use/move those sliders into other GUIs, such as putting the FOV slider into the video settings menu or making a custom GUI that uses sliders from other menus, would be fantastic.

**Comment by PlagueTR** [comment]
I'd really love to have this feature as well!
Also, having an option to change the text written on a button once it is pressed would be also pretty cool for customizing options ...
Example:
Feature X  [    ENABLED    ]
*click*
Feature X [    DISABLED    ]

**Comment by Keksuccino** [comment]
Customizing existing sliders is already possible and you can now add custom sliders to set variables :)
