### ISSUE TITLE
Text Input Fields for Button Action Scripting and Creating Buttons/Elements with Scripts

### ISSUE THREAD

**Issue by CornerBasket** [Keksuccino/FancyMenu#203]
The idea is that we could make place a "Text Input Field" element that allows the user to write text into it when interacting with the menu, and that upon clicking a separate button (such as a "done" button) or deselecting the text field, the input can be passed to a button script.

I almost split this into two feature requests, but I feel like this part ties into the text field request well enough. After having the input passed into a script, it would then be able to be used to create a button or element with custom parameters.

For example, you could have a GUI for the user to create a custom splash text, where after putting in the desired splash text and hitting the done button, the entered text is used in a button script to create a new text element with that input as the text value.  And this element could be set to either persist thereafter, or delete itself upon exiting the menu. This could also be used to create a custom server list, where a custom GUI is opened to input the server IP and name, and then a button is created in the previous server list GUI that, upon being clicked, takes you to the specified server.

**Comment by Keksuccino** [comment]
There are now input fields where you can set variables. These variables can be used in other text-based elements via placeholder and in visibility requirements. This should cover most of what you requested :)
