### ISSUE TITLE
Screen flashing with unloaded animation resource pack

### ISSUE THREAD

**Issue by viceversagames** [Keksuccino/FancyMenu#206]
If the resource pack an animation is using is not available, the entire screen flashes repeatedly. OBS isn't picking it up but it's flashing extremely fast, near the refresh rate of the animation. I'm making another bug report because this is potentially dangerous for people with epilepsy to have a full screen flashing at this frequency. I have a friend with it and I don't want to swap to PackMenu over this issue.

Can you please check if the resource pack for the selected animation is loaded, and not play the broken animation? This is not simply user error, there are all kinds of scenarios where this can happen accidentally. For example, if I exported the curseforge profile for the modpack and sent it to a friend, they wouldn't have this resource pack enabled without setting up DefaultOptions. They would get flashing on their first load.

https://user-images.githubusercontent.com/67132971/136675239-0f56c7c1-b203-41a3-8143-1a984126d9e5.mp4

**Comment by Keksuccino** [comment]
There will be a better way to load the animation packs very soon, so it will be enabled by default and will be loaded like other layout resources, so it should fix itself.

I will try to add a check to completely prevent it from happening, but until the update is released, the new method mentioned above will be a very good workaround or even a fix.

Still waiting for the new mod that is needed for this new method to get approved by CurseForge, but should be ready on Monday or Tuesday.

**Comment by Keksuccino** [comment]
[Load My Resources](https://www.curseforge.com/minecraft/mc-mods/load-my-resources-forge) is now available to load the resources on game start. You can download the newest Animation Maker update and repack the animation to convert them to the new format needed for LMR or you can just copy the content of the animation resource pack `assets` folder to `.minecraft/resources`. Don't forget to remove the old animation resource pack from `.minecraft/resourcepacks` :)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.4.0! Thank you for your report!
