### ISSUE TITLE
Add data to clipboard

### ISSUE THREAD

**Issue by MrPeterman** [Keksuccino/FancyMenu#209]
The possiblity to add something (like a string or link) to the users clipboard as a button action would be a nice alternative to the openlink action. This would mimic the functionality of a vanilla gui where you are able to choose between directly opening a link in a browser or getting the link send to your clipboard instead. 
(I actually don't know if this is already possilbe in current FancyMenu versions (mine's is 2.3.3-1.16.5) so basically I'm asking if there is a way to do it)
Vanilla example is from the Accessiblity Menu from Vanilla
![Bild_2021-10-20_022016](https://user-images.githubusercontent.com/34008890/138007658-31a1b3ba-0f87-4d8f-b424-1e114ec97889.png)

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.4.0! Thank you for your suggestion!
