### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#210]
**Outer Space**
I know, it's probably way out there. And I won't hold my breath for it, either. But if it happens, … delicious!

**Describe your idea**
Ability to specify a true type or open type font file on a button so that the text rendered will be thus graphically governed.

I couldn't think of a clear way to say. Hopefully, you get the idea.

**Comment by Keksuccino** [comment]
This is now possible! FancyMenu v3.0.0 added support for using custom fonts in text elements and support for using Minecraft's text components in buttons labels, which also adds support for custom fonts and HEX colors.
