### ISSUE TITLE
Gui got switched up side down

### ISSUE THREAD

**Issue by yuesha-yc** [Keksuccino/FancyMenu#211]
**Describe the bug**
Gui got switched up side down

**To Reproduce**
Add custom locals

**Expected behavior**
Gui should be normal

**Screenshots**
![image](https://user-images.githubusercontent.com/52098789/139532480-a2dd6aab-ba5e-4a04-9d29-44eb07259eed.png)

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows]
 - FancyMenu Version 2.3.5
 - Forge/Fabric Version 36.2.0
 - Minecraft Version 1.16.5
 - Active Mods

**Comment by PolySaken-I-Am** [comment]
This is a built-in 'language' in minecraft, it's very unlikely that this is a FancyMenu bug

**Comment by Keksuccino** [comment]
Are you sure that you don't just need to change your MC language back to English?

"Add custom locals" this is way too unspecific. I don't see any custom locals used in your screenshot. What exactly did you do before this happened?

**Comment by yuesha-yc** [comment]
I added some custom locals to my main menu and it becomes like this. Not only this GUI but every GUI even in game.

**Comment by Keksuccino** [comment]
This is a built-in language. Please check if you don't just have the wrong language selected.

**Comment by yuesha-yc** [comment]
What do you mean by built in language? I just use English US

**Comment by Keksuccino** [comment]
Are you sure? "English (Upside Down)" is a language in MC. This is **exactly** what your menu looks like, that's why I'm asking.

**Comment by yuesha-yc** [comment]
Never mind. I NEVER thought about Minecraft having such a confusing thing. Sorry for disturbing you!

**Comment by Keksuccino** [comment]
Nah, no problem! :) I'm happy you were able to fix it!
