### ISSUE TITLE
The FOV slider can't be edited

### ISSUE THREAD

**Issue by TyraVex** [Keksuccino/FancyMenu#213]
**Describe the bug**
With the latest version of the mod, in 1.17.1, you can't edit the FOV slider

**To Reproduce**
Launch Minecraft
Go into the options
FancyMenu → New layout/Open layout
See that you can't edit the FOV slider

**Expected behavior**
The FOV slider should be editable, like the 1.16.5 version of the mod (v2.3.4 I think)

**Screenshots**
![1](https://user-images.githubusercontent.com/34800546/140155536-ab2caecc-855d-4ce5-a459-241098d2ac80.png)
![2](https://user-images.githubusercontent.com/34800546/140155517-e68f0d70-e65e-4517-9580-2a66780e7865.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.2.0 to 2.3.5 (for 1.17.1)
 - Fabric
 - 1.17.1
 - HMCL Launcher
 - Java SE 16.0.2

**Comment by Keksuccino** [comment]
That's weird o.O Will try to fix this in one of the next updates! Thank you for telling me! :)

**Comment by TyraVex** [comment]
Thanks!

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.4.0! Thank you for your report!

**Comment by TyraVex** [comment]
Cool thanks
