### ISSUE TITLE
Can't access forge version curseforge page

### ISSUE THREAD

**Issue by SettingDust** [Keksuccino/FancyMenu#214]
**Describe the bug**
Redirect to https://www.curseforge.com/minecraft/mc-mods/fancymenu?filter-sort=2. The category for FancyMenu lul.
The https://www.curseforge.com/minecraft/mc-mods/fancymenu/files is ok

**Screenshots**
![图片](https://user-images.githubusercontent.com/19922286/142089893-32f6ecad-dc0f-416a-829c-1a70cb48cd37.png)

**Comment by Keksuccino** [comment]
oh god no lmfao

**Comment by Keksuccino** [comment]
It's fixed now! The new Forge FancyMenu URL is https://www.curseforge.com/minecraft/mc-mods/fancymenu-forge
