### ISSUE TITLE
The animation background is covered by other mods！！！

### ISSUE THREAD

**Issue by yuan746x** [Keksuccino/FancyMenu#215]
**Describe the bug**

The animation background is covered by other mods。

**To Reproduce**
1. Add Ice and fire Mod
2. join Game
3. wait

**Expected behavior**
no

**Crash Log**
no log

**Screenshots**
![image](https://user-images.githubusercontent.com/61259720/142155127-d9af301e-40b6-4559-8fff-2c4236df7fbe.png)

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows]
 - FancyMenu Version 2.3.5
 - Forge/Fabric Version 14.23.5.2855
 - Minecraft Version 1.12.2

**Comment by Keksuccino** [comment]
Hi! Please try if you can disable the custom main menu of the mod in its config. That's the only fix for this, I can't fix this on my end, sadly.

**Comment by yuan746x** [comment]
> 你好！请尝试是否可以在其配置中禁用 mod 的自定义主菜单。这是唯一的解决方法，遗憾的是我无法解决这个问题。
OK, I found the close custom menu option in mod and closed it

**Comment by Keksuccino** [comment]
Great to hear! :)
