### ISSUE TITLE
Button action to change background panorama

### ISSUE THREAD

**Issue by SwordManAWC** [Keksuccino/FancyMenu#217]
Hi! I hope to add a button function for players to choose the panorama, instead of opening the layout editor, like this panorama MOD (https://www.curseforge.com/minecraft/mc-mods/panorama), or compatible Panorama MOD, please! (PS: English is not very good, this is translated by Google, I hope it will not be too hard to understand)

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.9.0! There are now button actions to enable/disable/toggle layouts. Thank you for your suggestion!
