### ISSUE TITLE
Menu music does not respect the music volume slider, only main volume

### ISSUE THREAD

**Issue by NiSiSuinegEht** [Keksuccino/FancyMenu#218]
**Describe the bug**
Per title, the menu music being played is at the volume of the main audio slider, not the music volume slider.

Additionally, setting "B:playmenumusic = false" in "\config\fancymenu\config.txt" seems to have no effect.

**To Reproduce**
1. Adjust music volume slider.
2. Note music volume does not change.
3. Adjust main volume slider.
4. Note music volume does change.

**Expected behavior**
Menu music volume should change according to music volume slider setting.

**Crash Log**
N/A

**Screenshots**
N/A

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: fancymenu_2.2.1_MC_1.16.2-1.16.5
 - Forge/Fabric Version:  Forge 36.2.2
 - Minecraft Version:  1.16.5
 - Active Mods:  (Modpack) Magical Mischief Tour - 1.0.2

**Comment by Keksuccino** [comment]
This is not a bug, it's actually on purpose. Will rework this system at some point and probably give FM audios it's own volume slider.

The config option you're talking about is to disable the vanilla music in menus. Please use the FM settings (little FM icon at the left side of the menu bar) for descriptions of all config options :)
