### ISSUE TITLE
Unable to open Mod Menu GUIs via button action

### ISSUE THREAD

**Issue by Magnotec1** [Keksuccino/FancyMenu#219]
The Mod Menu GUIs are not openable via "open gui" action on button

Create a button that has the button action "open gui" and set it to the menu identifier of a mod in mod menu. The button will not open the gui.

 - OS: Ubuntu 21.10 Linux
 - FancyMenu Version 2.3.0
 - Minecraft Version 1.16.5
 - Active Mods: 	
	- advancedchat
	- advancednbttooltip
	- amecs
	- amecsapi
	- antiautojump
	- anycapes
	- architectury
	- armourtoughnessbar
	- artifice
	- audiooutput
	- aurora_keystrokes
	- auto_third_person
	- autoconfig1u
	- bclib
	- better-local-server
	- betterdroppeditems
	- betterf1
	- betterf3
	- bettermounthud
	- boatiview
	- boostedbrightness
	- borderlessmining
	- chat_heads
	- cherishedworlds
	- classicombat
	- cleardespawn
	- cloth-api
        - cloth-config
	- completeconfig
	- continuebutton
	- controlling
	- cotton-client-commands
	- cr-compass-ribbon
	- craftpresence
	- crowdin-translate
	- Custom Selection Box
	- cullleaves
	- cursormod
	- custom-crosshair-mod
	- customsplashscreen
	- damagetint
	- detailab
	- durability101
	- dynamicfps
	- dynamicsoundfilters
	- enhancedblockentities
	- entity-distance
	- fabric
	- fabric-api
	- fabricloader
	- fallingleaves
	- fancymenu
	- ferritecore
	- fiber
	- firstperson
	- fixmygg
	- flighthud
	- fpsreducer
	- gbfabrictools
	- healthoverlay
	- horsestatsvanilla
	- illuminations
	- inventoryhud
	- itemmodelfix
	- java16
	- kirin
	- konkrete
	- kronhud
	- krypton
	- lazydfu
	- libgui
	- loading-timer
	- lowfire
	- malilib
	- mambience
	- minecraft1.16.5
	- minemenufabric
	- modmenu
	- nmuk
	- nobreak
	- nomoreglowingpots
	- not-enough-servers
	- notenoughanimations
	- notenoughcrashes
	- now-playing
	- oauth-fabric
	- offlineskins
	- okzoomer
	- optifabric
	- particlerain
	- perspectivemod
	- petowner
	- phosphor
	- pin that
	- pling
	- polish
	- presencefootsteps
	- replaymod
	- resolutioncontrol
	- respackopts
	- screenshotclipboard
	- skyblocker
	- slight-gui-modifications
	- slimeblockredstone
	- smooth-chunks
	- smoothboot
	- sneaktweak
	- spark
	- spruceui
	- stevekungs_lib
	- swordblocking
	- timechanger
	- timetolive
	- toolscroll
	- tooltipfix
	- transliterationlib
	- voidfog
	- vanilla_tweaks_downloader
	- waterdripsound
	- windowthonk
	- worldedit
	- worldeditcui

**Comment by Keksuccino** [comment]
I tested this in both 1.16 and 1.18 and it seems to just work fine.
What's the exact menu identifier you're trying to use to open the menu?

**Comment by Keksuccino** [comment]
Closed because no response and not reproducable.
