### ISSUE TITLE
Audio Volume Option

### ISSUE THREAD

**Issue by Shorepion** [Keksuccino/FancyMenu#22]
An option in the customization file to adjust the audio volume, because now its just playing the track with full volume, I guess.
Something like: 
audiovolume = 27 [in a range of 0-100%]

**Comment by Keksuccino** [comment]
The audio volume is linked to minecraft’s master volume. Adding a second "input" for a volume would be a bit hard, but I think I could add a "maxvolume" variable to set the maximum volume of an audio :)

**Comment by Shorepion** [comment]
Oh ok, I didnt know its linked to that.
Maybe you can link it to the minecraft music volume and remove minecraft's music by default?

**Comment by Keksuccino** [comment]
I was thinking about that too but decided to not do it because of the default minecraft music. Maybe some people want to add sounds to manus while keeping the default music and others want to mute it. Wouldn’t be possible if menu sounds would use the same audio channel.

**Comment by Shorepion** [comment]
it's a fair enough comment to make.

**Comment by Keksuccino** [comment]
I decided to not implement the "maxvolume" feature because it would be too difficult to keep volumes synchronized with it. Sorry..
