### ISSUE TITLE
Full Screen once pack loads?

### ISSUE THREAD

**Issue by Boolyman** [Keksuccino/FancyMenu#221]
**Describe your idea**
Anyway you could add an option in the FancyMenu Settings to automatically make the window Full Screen once the pack loads?  It would be nice to have the first impressions when people see our menu for the first time, to be the fullscreen experience.

**Comment by Keksuccino** [comment]
So basically an automatic fullscreen on start?

**Comment by Boolyman** [comment]
Yes

**Comment by Keksuccino** [comment]
Will try to add this in one of the next updates :)

**Comment by Boolyman** [comment]
You're the best!

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.4.0! Thank you for your suggestion!
