### ISSUE TITLE
Server Status falsely showing offline after short time.

### ISSUE THREAD

**Issue by Leolele99** [Keksuccino/FancyMenu#222]
When using the sever status macro, it sometimes shows offline after a couple of minutes, even when the server is evidently online.
After a similar amount of time staying on offline, it shows online again.

To reproduce just put in any server that is online on a text and query its status with the macro.
Wait a couple of minutes.
It should start to randomly switch between offline and online, when it should show online all the time.

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: fancymenu_fabric_2.3.6_MC_1.17-1.17.1
 - Fabric Version: 1.17.1-0.12.5
 - Minecraft Version: 1.17.1
 - Active Mods: Fancy Menu, Fabric API, LoadMyResources, DrippyLoadingScreen

**Comment by Leolele99** [comment]
Found a fix and opened a pull request:
https://github.com/Keksuccino/FancyMenu/pull/224

**Comment by Keksuccino** [comment]
Fix implemented in v2.4.3! Thank you!
