### ISSUE TITLE
joinserver buttons crash on Fabric 1.18

### ISSUE THREAD

**Issue by sachk** [Keksuccino/FancyMenu#226]
**Describe the bug**
The game crashes immediately when pressing any joinserver button

**To Reproduce**
1. Create a joinserver button
2. Click on it

[**Crash Log**](https://gist.github.com/sachk/914091142fc9186fac5307c98a07a32d)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: v2.4.2 either from CurseForge and GitHub
 - Forge/Fabric Version: 0.12.8
 - Minecraft Version: 1.18
  - Active Mods: None other than Konkrete and FancyMenu, also happens when running using gradle runClient

**Comment by Keksuccino** [comment]
This was a bug in Konkrete and is now fixed in v1.3.1! Thank you for your report!
