### ISSUE TITLE
Stuck on pre-rendering animation

### ISSUE THREAD

**Issue by mrtajniak** [Keksuccino/FancyMenu#227]
**Describe the bug**
I have added some animations but I am stuck on pre-rendering

**To Reproduce**
1. Add animations 
2. Start MultiMC

**Screenshots**
![image](https://user-images.githubusercontent.com/33846499/144948297-2c55f219-df57-4e93-9a99-2da87f5aafb5.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Pro
 - FancyMenu Version 2.4.2
 - Fabric Version 12.8
 - Minecraft Version 1.17.1
 - Active Mods:
 ![image](https://user-images.githubusercontent.com/33846499/144948232-bef94b59-74d4-4e2a-9246-aae299fa7cb7.png)

**Comment by Keksuccino** [comment]
Where did you get the animation from? It uses a very old and deprecated animation format that will get removed very soon.
Better use the new one. Maybe you can convert the old animation to the new format.
https://github.com/Keksuccino/FancyMenu/wiki/Animations

**Comment by mrtajniak** [comment]
great, now it works! One more question, when is the main animation playing? After Mojang Studios logo?

**Comment by mrtajniak** [comment]
What is the maximum resolution and frame rate for animations?

**Comment by Keksuccino** [comment]
You shouldn't use more than 24FPS for animations, because MC simply can't show more than that in menus.
There's no real maximum for the resolution, but it's recommended to not go higher than 1920x1080p.

But again, the real issue in your case is that you're using an ancient animation.
Just update the animation to the new format and you will be fine.

**Comment by mrtajniak** [comment]
Ok thank you, that is all I want to know, thank you so much

**Comment by Keksuccino** [comment]
No problem :D Soo, since this evolved to something like a support thread now, I will close it for now, but if you still have questions, feel free to join my Discord (http://discord.keksuccino.de) for faster help! :) Just ping me there and I will help you as fast as I can!
