### ISSUE TITLE
Custom Window Title & splash text won't change 

### ISSUE THREAD

**Issue by I3estOFF** [Keksuccino/FancyMenu#228]
**Describe the bug**
Custom Window Title won't change. I think one of mods is changing it.
Now it says ,,Better Minecraft [FORGE] 1.16.5

Also Splash text won't change, i think The Abyss Chapter II causes this bug

**To Reproduce**
1. Go to Settings
2. Change settings
3. Restart Minecraft
4. See error, nothing changed

**Expected behavior**
Splash text and Window Title changed

**Mod list**
[modlist.txt](https://github.com/Keksuccino/FancyMenu/files/7683954/modlist.txt)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: fancymenu_2.4.2_MC_1.16.2-1.16.5 - Forge/Fabric Version [e.g. 31.2.24]
 - Minecraft Version: 1.16.5
  - Forge: net.minecraftforge:36.2.8

**Comment by Keksuccino** [comment]
Hi! That's not a bug, you just need to disable the custom main menu and window title of the other mod. If this is not possible, I recommend you to tell the dev of the other mod to implement such an option.

**Comment by I3estOFF** [comment]
Oh okay! I was thinking you are able to set priority for your mod somehow. Thanks for answer!
