### ISSUE TITLE
Change placeholder value name "Forge Version" to "Mod Loader Version", to support both Fabric and Forge

### ISSUE THREAD

**Issue by xpe-online** [Keksuccino/FancyMenu#229]
**Describe the bug**
In the mod of fabric versions,when I edit a new text on FancyMenuGUI,'Edit Content'/'Client'/'Forge Version' is wrong.I use it on Fabric,no Forge.

**To Reproduce**
1. Click on 'Expend Menu Bar'
2. Click on 'Current Menu'
3. Click on 'Layout'
4. Open a Layout
5. Edit the Layout
6. Create a new Element,click on 'Element'/'New'/'Text'
7. When you open the 'Edit Content' or 'New Text',click on 'Plus Sign'/'Client'
8. See Error,It is 'Forge Version',but I use it on Fabric
9. When you click 'Forge Version',it will still input '%version:forge%' 

**Expected behavior**
1. 'Forge Version' amend 'Fabric Version', when I click on it ,it will input '%version:fabricloader%' 
2. Add a new Button in the 'Plus Sign' of 'Edit Content' or 'New Text',its names is 'FabricAPI Version' ,it will input '%version:fabric%'

**Crash Log**
No crash**Describe the bug**
In the mod of fabric versions,when I edit a new text on FancyMenuGUI,'Edit Content'/'Client'/'Forge Version' is wrong.I use it on Fabric,no Forge.

**To Reproduce**
1. Click on 'Expend Menu Bar'
2. Click on 'Current Menu'
3. Click on 'Layout'
4. Open a Layout
5. Edit the Layout
6. Create a new Element,click on 'Element'/'New'/'Text'
7. When you open the 'Edit Content' or 'New Text',click on 'Plus Sign'/'Client'
8. See Error,It is 'Forge Version',but I use it on Fabric
9. When you click 'Forge Version',it will still input '%version:forge%' 

**Expected behavior**
1. 'Forge Version' amend 'Fabric Version', when I click on it ,it will input '%version:fabricloader%' 
2. Add a new Button in the 'Plus Sign' of 'Edit Content' or 'New Text',its names is 'FabricAPI Version' ,it will input '%version:fabric%'

**Crash Log**
No crash

**Screenshots**
![image](https://user-images.githubusercontent.com/85062843/145397602-7da61024-7898-491a-8e40-19968a52e8cd.png)
![image](https://user-images.githubusercontent.com/85062843/145397718-71132705-437c-4179-bb1b-479692f40a91.png)

**Basic Informations (please complete the following information):**
 - OS: [Windows 11]
 - FancyMenu Version [2.4.3]
 - Forge/Fabric Version [Fabric 0.12.8 FabricAPI 0.44.0+1.18]
 - Minecraft Version [1.18]
 - Active Mods [Sodium,Iris]

**Screenshots**
![image](https://user-images.githubusercontent.com/85062843/145397602-7da61024-7898-491a-8e40-19968a52e8cd.png)
![image](https://user-images.githubusercontent.com/85062843/145397718-71132705-437c-4179-bb1b-479692f40a91.png)

**Basic Informations (please complete the following information):**
 - OS: [Windows 11]
 - FancyMenu Version [2.4.3]
 - Forge/Fabric Version [Fabric 0.12.8 FabricAPI 0.44.0+1.18]
 - Minecraft Version [1.18]
 - Active Mods [Sodium,Iris]

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.5.0! Thank you for your report!
