### ISSUE TITLE
More Button Customization

### ISSUE THREAD

**Issue by Shorepion** [Keksuccino/FancyMenu#23]
-custom button texture that replaces the default minecraft button image and layout
-button sounds when clicking them
-button "hover-over options": hoverButtonText = changes/displays a (different) text when hover over
                                               hoverButtonSound = plays audio when hover over
                                               hoverButtonImage = changes/displays a (different) image

sry for putting multiple suggestions in one post, but they all fit together.

**Comment by Keksuccino** [comment]
Most of them are already done and will be part of the next update :D Custom sounds and hover text will be added a bit later ^^ Thank you for your request!

**Comment by Shorepion** [comment]
Thanks for the quick reply. 
Cool - looking forward to that!

**Comment by Keksuccino** [comment]
New button actions in FancyMenu v1.1:

- "quitgame" to quit minecraft
- "joinserver" to join a minecraft server
- "loadworld" to load a world
- "openfile" to open a file/folder
- "prevbackground" and "nextbackground" to switch between menu backgrounds

**Comment by Shorepion** [comment]
👍

**Comment by Keksuccino** [comment]
FancyMenu v1.3 should finally add all of your requested button customizations! :)

Aaand I've just realized I posted the wrong changes to this thread the last time :'D
Sorry for that, FancyMenu v1.1 added custom button textures for the normal and hover state!
