### ISSUE TITLE
Framerate inconsistency/stuttering with panorama background

### ISSUE THREAD

**Issue by Hax165** [Keksuccino/FancyMenu#230]
**Describe the bug**
When using a panorama for the background the motion isn't 100% smooth, which appears to be caused by the framerate fluctuating somewhat resulting in stutters. This is also measurable using Fraps. The issue gets progressively worse the more mods are installed which makes the stutters more intense and more frequent.
It is important to mention that when switching off all customization (going back to the vanilla main menu), the motion of the background is perfectly smooth and locked to 60fps.

**To Reproduce**
1. Put on a Panorama background
2. Notice that the background slightly stutters. (Turning up the speed at which the camera looks around makes it way more obvious.)

**Expected behavior**
The framerate should not fluctuate at all when in the main menu and the motion of the panorama background should be just as smooth as in the vanilla main menu.

**Crash Log**
Not a crash and there is no errors in the logs.

**Basic Informations**
 - OS: [Windows 10]
 - FancyMenu Version [2.4.3]
 - Forge/Fabric Version [36.2.22]
 - Minecraft Version [1.16.5]
 - Active Mods [FancyMenu, Konkrete]
 
**Additional Information**
- Java version [1.8.0.51 (64bit), 1.8.0.291(64bit)]
- Processor [i7-9700K]
- Graphics Card [RTX 2080]
- Graphics Driver: 496.13

**Comment by Hax165** [comment]
I just wanted to add that with no other mods installed the framerate consistently fluctuate between 57 and 60 fps. Which may not sound so bad. But it is clearly felt compared to the vanilla main menu. 
That is however a rather subtle issue compared to enabling panorama on a modpack with 200+ mods installed, which makes the framerate drop to a meager 22fps (panorama speed makes no difference).
One thing that is really weird however, is that if you enter editing mode the issue almost completely disappears and just goes back to fluctuating between 57 and 60fps.

**Comment by Hax165** [comment]
If you want to see it for yourself this is where I have the mod deployed: (version: pre5-2.0.0) https://www.curseforge.com/minecraft/modpacks/dynamite2

**Comment by Gbergz** [comment]
I can somewhat add on to this, the framerate in the menus when the menu is customized quite a bit drops the FPS by A LOT.

Monitoring it with fraps as you also mentioned we can see it at 10 fps. When the menus are off i.e vanilla menu. It's stable at 60 fps. Like it should be.. right?..

Here's a vid showing it in action:
https://streamable.com/kn02qd

**Comment by Keksuccino** [comment]
> I can somewhat add on to this, the framerate in the menus when the menu is customized quite a bit drops the FPS by A LOT.
> 
> Monitoring it with fraps as you also mentioned we can see it at 10 fps. When the menus are off i.e vanilla menu. It's stable at 60 fps. Like it should be.. right?..
> 
> Here's a vid showing it in action: https://streamable.com/kn02qd
> 
> Should mention this is on 1.18, but happens on 1.17 & 1.16 after an update.
> 
> On 1.16.5 everything is fine on version 2.2.2-2, after that. FPS tanks. All the way down to 10 fps... This update made fps tank by alot: https://www.curseforge.com/minecraft/mc-mods/fancymenu-forge/files/3467954

This has to be some kind of mod conflict.
It's probably related to one or more of the placeholder text values or the visibility requirements I've added in the update you've mentioned.

Thing is, I've tested the pack from the video and you're right, it drops down to 10FPS when loading the full pack, but has completely stable ~60FPS when only FancyMenu, Drippy Loading Screen and Konkrete is loaded. This means that some of your 300+ mods is causing this. Maybe I can fix it on my end, but I can't check 300 mods for incompatibilities.

I also think that the original issue is not really related to this one.
Could be different ones.

![Screenshot_1](https://user-images.githubusercontent.com/35544624/147856920-f6596eec-9308-44ab-9ce4-940bdc5c8860.png)

**Comment by Keksuccino** [comment]
Update:
I was able to narrow it down to placeholders. It has to be some of the placeholders I've added in this one update.
Will try to find the right one and fix it.

**Comment by Gbergz** [comment]
Awesome news! 

Late reply, had some stuff do to.

> Fixed. The fix will be part of the next update! :)

Can't wait. 👍

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.5.0! Thank you both for your reports! :)

**Comment by Gbergz** [comment]
> Fixed in FancyMenu v2.5.0! Thank you both for your reports! :)

So I updated, still getting 10 frames in the menus.. hm..

**Comment by Keksuccino** [comment]
Works fine for me: https://www.youtube.com/watch?v=sTtHlz0wvxs
Did you **really** use v2.5.0?

**Comment by Gbergz** [comment]
> Did you really use v2.5.0?

Yes, using 2.5.0

**Comment by Gbergz** [comment]
Strange the fps doesn't drop for you at all. 🤔

**Comment by Gbergz** [comment]
Deleting every clickable link, test and custom buttons made the fps go up to 60fps.

**Comment by Keksuccino** [comment]
Is this updated pack version already online? Can I download it?

Please show me the FM version number you see in the Mods tab.

Please show me the last button action you see in the Button Action menu of a custom button, when clicking til the last entry of the switcher (right arrow button).

**Comment by Gbergz** [comment]
![image](https://user-images.githubusercontent.com/26634554/148109056-42a6ce4b-68da-42c1-92f0-e5ab49519f98.png)

![image](https://user-images.githubusercontent.com/26634554/148109077-01d03586-2346-4bee-b520-954e87081025.png)

**Comment by Keksuccino** [comment]
not in the launcher, but the actual game Mods menu, please

**Comment by Gbergz** [comment]
Downloaded 2.5.0 manually instead, and now it works. No more fps drops.

**Comment by Keksuccino** [comment]
As I thought :D It's a launcher problem then. That's why I always want the version displayed in the actual game, because I know that launchers like to mess up updating to new mod versions :)

Anyways, I'm happy it works now! Thank you again for reporting it!
