### ISSUE TITLE
add an option to keep buttons in the same place nomatter the resolution?

### ISSUE THREAD

**Issue by PeeblyWeeb** [Keksuccino/FancyMenu#231]
basically i have a problem where when i change my game resolution everything gets shuffled around. is it possible to add a feature that stops that?

**Comment by Keksuccino** [comment]
Hi!

You can do the following to achieve this:

1. Use the correct orientations for your elements. This is always important.
2. There is an auto-scaling feature in 1.16+ that handles the scaling for you, so the layout will work with basically every window size. To do this, right-click the editor background and click on **Auto-Scaling*. It's recommended to set a **Forced GUI Scale** when using auto-scaling. This can be accessed in the same right-click context menu.

**Comment by PeeblyWeeb** [comment]
HOLY S**T THIS ACTUALLY HELPED
