### ISSUE TITLE
Menu Opening

### ISSUE THREAD

**Issue by Thrumptus** [Keksuccino/FancyMenu#232]
I can no longer see the button to open the fancymenu gui in game, i'm unsure if this is something i have inadvertently broken but i don't believe this is the case

Unfortunately i don't understand why this has occurred so am unable to reproduce it 

 - OS: Windows 
 - FancyMenu Version: Have tried with both 2.4.2 and 2.4.1
 - Forge/Fabric Version: Fabric 0.12.12
 - Minecraft Version: 1.17.1
 - Active Mods: Issue occurs with and without other mods

**Comment by Keksuccino** [comment]
You just hit **CTRL + ALT + C**, I think. This will toggle the customization controls visibility.
If this keybind doesn't work, check your MC controls settings for the correct one.

**Comment by Thrumptus** [comment]
Yes that worked thanks, sorry to bother you with something so trivial
