### ISSUE TITLE
[MC 1.17] Fabric 2.4.2 not opening links

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#233]
**Describe the bug**
Made a fabric pack that has fancy menu 2.4.2 mc 1.17-1.17.1 in it. The custom buttons don't open on the links at all. you hear the click sound but nothing happens. Attached is the config folder.
[fancymenu.zip](https://github.com/Keksuccino/FancyMenu/files/7790469/fancymenu.zip)

**Basic Informations (please complete the following information):**
 - OS: Linux
 - FancyMenu Version: 2.4.2
 - Forge/Fabric Version: Fabric 0.12.12
 - Minecraft Version: 1.17.1
 - Active Mods:
*   [Advancement Plaques \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques-fabric) (by [Grend\_G](https://www.curseforge.com/members/grend_g/projects))
*   [Alloy Forgery](https://www.curseforge.com/minecraft/mc-mods/alloy-forgery) (by [LordDeatHunter](https://www.curseforge.com/members/lorddeathunter/projects))
*   [AntiGhost](https://www.curseforge.com/minecraft/mc-mods/antighost) (by [Giselbaer](https://www.curseforge.com/members/giselbaer/projects))
*   [Applied Energistics 2 Wireless Terminals](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals) (by [Mari\_023](https://www.curseforge.com/members/mari_023/projects))
*   [Applied Energistics 2](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2) (by [AlgorithmX2](https://www.curseforge.com/members/algorithmx2/projects))
*   [Architectury API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [Auth Me](https://www.curseforge.com/minecraft/mc-mods/auth-me) (by [Axieum](https://www.curseforge.com/members/axieum/projects))
*   [Auto Config Updated API](https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [Automatic Path](https://www.curseforge.com/minecraft/mc-mods/automatic-path) (by [lebonq](https://www.curseforge.com/members/lebonq/projects))
*   [Awesome Dungeon - Fabric](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-fabric) (by [Jtorleon](https://www.curseforge.com/members/jtorleon/projects))
*   [BackSlot](https://www.curseforge.com/minecraft/mc-mods/backslot) (by [Globox\_Z](https://www.curseforge.com/members/globox_z/projects))
*   [Balm (Fabric Edition)](https://www.curseforge.com/minecraft/mc-mods/balm-fabric) (by [BlayTheNinth](https://www.curseforge.com/members/blaytheninth/projects))
*   [Better Ping Display \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric) (by [Quintinity](https://www.curseforge.com/members/quintinity/projects))
*   [BetterF3](https://www.curseforge.com/minecraft/mc-mods/betterf3) (by [cominixo](https://www.curseforge.com/members/cominixo/projects))
*   [Building Wands](https://www.curseforge.com/minecraft/mc-mods/building-wands) (by [nicguzzo](https://www.curseforge.com/members/nicguzzo/projects))
*   [Caracal Mod](https://www.curseforge.com/minecraft/mc-mods/caracal-mod) (by [AqUpd](https://www.curseforge.com/members/aqupd/projects))
*   [Carrier](https://www.curseforge.com/minecraft/mc-mods/carrier) (by [GabrielHOlv](https://www.curseforge.com/members/gabrielholv/projects))
*   [Cat Eyes - Night Vision Toggle Mod](https://www.curseforge.com/minecraft/mc-mods/cat-eyes-night-vision-toggle-mod) (by [TangoSixxer](https://www.curseforge.com/members/tangosixxer/projects))
*   [Cave Biomes](https://www.curseforge.com/minecraft/mc-mods/cave-biomes) (by [SuperCoder79](https://www.curseforge.com/members/supercoder79/projects))
*   [CC: Restitched](https://www.curseforge.com/minecraft/mc-mods/cc-restitched) (by [merithtk](https://www.curseforge.com/members/merithtk/projects))
*   [Craftable Horse Armour & Saddle \[CHA&S\]](https://www.curseforge.com/minecraft/mc-mods/cha-s) (by [EwyBoy](https://www.curseforge.com/members/ewyboy/projects))
*   [Cherished Worlds (Fabric)](https://www.curseforge.com/minecraft/mc-mods/cherished-worlds-fabric) (by [TheIllusiveC4](https://www.curseforge.com/members/theillusivec4/projects))
*   [ChickensShed](https://www.curseforge.com/minecraft/mc-mods/chickensshed) (by [holmraven](https://www.curseforge.com/members/holmraven/projects))
*   [Chunky Pregenerator (Fabric)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator) (by [pop4959](https://www.curseforge.com/members/pop4959/projects))
*   [Clear Hitboxes](https://www.curseforge.com/minecraft/mc-mods/clear-hitboxes) (by [splzhh](https://www.curseforge.com/members/splzhh/projects))
*   [Clear Skies](https://www.curseforge.com/minecraft/mc-mods/clear-skies) (by [GrondagTheBarbarian](https://www.curseforge.com/members/grondagthebarbarian/projects))
*   [ClickThrough](https://www.curseforge.com/minecraft/mc-mods/clickthrough) (by [Giselbaer](https://www.curseforge.com/members/giselbaer/projects))
*   [Cloth API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/cloth-api) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [Cloth Config API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/cloth-config) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps) (by [Jaredlll08](https://www.curseforge.com/members/jaredlll08/projects))
*   [Collective (Fabric)](https://www.curseforge.com/minecraft/mc-mods/collective-fabric) (by [Serilum](https://www.curseforge.com/members/serilum/projects))
*   [Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling) (by [Jaredlll08](https://www.curseforge.com/members/jaredlll08/projects))
*   [Craft 6 stairs not 4](https://www.curseforge.com/minecraft/mc-mods/craft-6-stairs-not-4) (by [1\_block\_microwave](https://www.curseforge.com/members/1_block_microwave/projects))
*   [Crafting Tweaks (Fabric Edition)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks-fabric) (by [BlayTheNinth](https://www.curseforge.com/members/blaytheninth/projects))
*   [Croptopia \[FABRIC/FORGE\]](https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric) (by [thethonk](https://www.curseforge.com/members/thethonk/projects))
*   [Custom Stars \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/custom-stars) (by [b3spectacled](https://www.curseforge.com/members/b3spectacled/projects))
*   [Cyber Permissions](https://www.curseforge.com/minecraft/mc-mods/cyber-permissions) (by [javazilla\_](https://www.curseforge.com/members/javazilla_/projects))
*   [Dank Storage Fabric](https://www.curseforge.com/minecraft/mc-mods/dank-storage-fabric) (by [tfarecnim](https://www.curseforge.com/members/tfarecnim/projects))
*   [Dark Enchanting](https://www.curseforge.com/minecraft/mc-mods/dark-enchanting) (by [ffrannny](https://www.curseforge.com/members/ffrannny/projects))
*   [Dawn API](https://www.curseforge.com/minecraft/mc-mods/dawn) (by [Hugman\_76](https://www.curseforge.com/members/hugman_76/projects))
*   [Day Dream](https://www.curseforge.com/minecraft/mc-mods/day-dream) (by [SmushyTaco](https://www.curseforge.com/members/smushytaco/projects))
*   [DefaultSettings Fabric](https://www.curseforge.com/minecraft/mc-mods/defaultsettings-fabric) (by [PT400C](https://www.curseforge.com/members/pt400c/projects))
*   [Diggus Maximus](https://www.curseforge.com/minecraft/mc-mods/diggus-maximus) (by [Kyrptonaught](https://www.curseforge.com/members/kyrptonaught/projects))
*   [Dimension Fix (Some Forge Patches Ported)](https://www.curseforge.com/minecraft/mc-mods/dimension-fix-some-forge-patches-ported) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [Dinocraft: Extinction](https://www.curseforge.com/minecraft/mc-mods/dinocraft-dctm) (by [Bonkersboy2017](https://www.curseforge.com/members/bonkersboy2017/projects))
*   [Disenchanter](https://www.curseforge.com/minecraft/mc-mods/disenchanter) (by [gliscowo](https://www.curseforge.com/members/gliscowo/projects))
*   [DragonLoot](https://www.curseforge.com/minecraft/mc-mods/dragonloot) (by [pois1xlive](https://www.curseforge.com/members/pois1xlive/projects))
*   [Eating Animation \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric) (by [theone\_ss](https://www.curseforge.com/members/theone_ss/projects))
*   [Emerald Geodes (+now with Quartz!)](https://www.curseforge.com/minecraft/mc-mods/emerald-geodes) (by [TheDeathlyCow](https://www.curseforge.com/members/thedeathlycow/projects))
*   [Extra Generators](https://www.curseforge.com/minecraft/mc-mods/extra-generators) (by [D4rkness\_King](https://www.curseforge.com/members/d4rkness_king/projects))
*   [Extra TNT](https://www.curseforge.com/minecraft/mc-mods/extra-tnt) (by [Flytre7](https://www.curseforge.com/members/flytre7/projects))
*   [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) (by [modmuss50](https://www.curseforge.com/members/modmuss50/projects))
*   [Bssentials - Essentials for Fabric](https://www.curseforge.com/minecraft/mc-mods/fabric-essentials) (by [javazilla\_](https://www.curseforge.com/members/javazilla_/projects))
*   [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin) (by [modmuss50](https://www.curseforge.com/members/modmuss50/projects))
*   [FancyMenu \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric) (by [Keksuccino](https://www.curseforge.com/members/keksuccino/projects))
*   [Wildfire's Female Gender Mod (Fabric)](https://www.curseforge.com/minecraft/mc-mods/female-gender-fabric) (by [WildfireRomeo](https://www.curseforge.com/members/wildfireromeo/projects))
*   [Fixed Waterlogging](https://www.curseforge.com/minecraft/mc-mods/fixed-waterlogging) (by [KxmischesDomi](https://www.curseforge.com/members/kxmischesdomi/projects))
*   [Forgotten Recipes - Sculk Sensor, Bundle, Leather and Powder Snow Recipe](https://www.curseforge.com/minecraft/mc-mods/forgottenrecipes) (by [Affehund](https://www.curseforge.com/members/affehund/projects))
*   [Full Turtle Armor](https://www.curseforge.com/minecraft/mc-mods/full-turtle-armor) (by [Jackbusters1](https://www.curseforge.com/members/jackbusters1/projects))
*   [GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib) (by [ThanosGecko](https://www.curseforge.com/members/thanosgecko/projects))
*   [Giselbaer's Durability Viewer](https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer) (by [Giselbaer](https://www.curseforge.com/members/giselbaer/projects))
*   [Golden Hoppers](https://www.curseforge.com/minecraft/mc-mods/golden-hoppers) (by [haykam](https://www.curseforge.com/members/haykam/projects))
*   [Grim's Transportables](https://www.curseforge.com/minecraft/mc-mods/grims-transportables) (by [TheGrimsey](https://www.curseforge.com/members/thegrimsey/projects))
*   [Happiness (is a) Warm Gun](https://www.curseforge.com/minecraft/mc-mods/happiness-is-a-warm-gun) (by [cybercat5555](https://www.curseforge.com/members/cybercat5555/projects))
*   [Hookshot](https://www.curseforge.com/minecraft/mc-mods/hookshot) (by [Camellias\_](https://www.curseforge.com/members/camellias_/projects))
*   [I Know What I'm Doing (IKWID)](https://www.curseforge.com/minecraft/mc-mods/i-know-what-im-doing) (by [HeckinChloe](https://www.curseforge.com/members/heckinchloe/projects))
*   [Iceberg \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric) (by [Grend\_G](https://www.curseforge.com/members/grend_g/projects))
*   [Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod) (by [qouteall](https://www.curseforge.com/members/qouteall/projects))
*   [Improved Stations (Fabric)](https://www.curseforge.com/minecraft/mc-mods/improved-stations) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [In-Game Account Switcher](https://www.curseforge.com/minecraft/mc-mods/in-game-account-switcher) (by [The\_Fireplace](https://www.curseforge.com/members/the_fireplace/projects))
*   [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution) (by [GabrielHOlv](https://www.curseforge.com/members/gabrielholv/projects))
*   [Infusion Table](https://www.curseforge.com/minecraft/mc-mods/infusion-table) (by [jptrzy](https://www.curseforge.com/members/jptrzy/projects))
*   [Inv View](https://www.curseforge.com/minecraft/mc-mods/inv-view) (by [potatoboy99999](https://www.curseforge.com/members/potatoboy99999/projects))
*   [Inventory Sorting](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting) (by [Kyrptonaught](https://www.curseforge.com/members/kyrptonaught/projects))
*   [Iron Chests for Fabric](https://www.curseforge.com/minecraft/mc-mods/iron-chests-for-fabric) (by [cyberanner](https://www.curseforge.com/members/cyberanner/projects))
*   [Iron Furnaces \[FABRIC\]](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces-fabric) (by [pizzaatime](https://www.curseforge.com/members/pizzaatime/projects))
*   [Iron Jetpacks Fabric](https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks-fabric) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [Item Model Fix (Fabric)](https://www.curseforge.com/minecraft/mc-mods/item-model-fix) (by [Pepper\_Bell](https://www.curseforge.com/members/pepper_bell/projects))
*   [JumpOverFences](https://www.curseforge.com/minecraft/mc-mods/jumpoverfences) (by [Martmists](https://www.curseforge.com/members/martmists/projects))
*   [Just Map](https://www.curseforge.com/minecraft/mc-mods/just-map) (by [Bulldoq83](https://www.curseforge.com/members/bulldoq83/projects))
*   [Konkrete \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric) (by [Keksuccino](https://www.curseforge.com/members/keksuccino/projects))
*   [Lakeside](https://www.curseforge.com/minecraft/mc-mods/lakeside) (by [Juicebus](https://www.curseforge.com/members/juicebus/projects))
*   [LambDynamicLights](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights) (by [LambdAurora](https://www.curseforge.com/members/lambdaurora/projects))
*   [Lava Clear View (Fabric)](https://www.curseforge.com/minecraft/mc-mods/lava-clear-view-fabric) (by [Snownee\_](https://www.curseforge.com/members/snownee_/projects))
*   [LazyDFU](https://www.curseforge.com/minecraft/mc-mods/lazydfu) (by [tuxed](https://www.curseforge.com/members/tuxed/projects))
*   [Leaf Decay](https://www.curseforge.com/minecraft/mc-mods/leaf-decay) (by [Draylar1](https://www.curseforge.com/members/draylar1/projects))
*   [Flytre Lib (FlytreLib)](https://www.curseforge.com/minecraft/mc-mods/lib) (by [Flytre7](https://www.curseforge.com/members/flytre7/projects))
*   [Library Ferret - Fabric](https://www.curseforge.com/minecraft/mc-mods/library-ferret-fabric) (by [Jtorleon](https://www.curseforge.com/members/jtorleon/projects))
*   [Light Overlay (Rift/Forge/Fabric)](https://www.curseforge.com/minecraft/mc-mods/light-overlay) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [Lovely Snails](https://www.curseforge.com/minecraft/mc-mods/lovely-snails) (by [LambdAurora](https://www.curseforge.com/members/lambdaurora/projects))
*   [Luminous Wool](https://www.curseforge.com/minecraft/mc-mods/luminous-wool) (by [zoeytheegoist](https://www.curseforge.com/members/zoeytheegoist/projects))
*   [MC Dungeons Artifacts](https://www.curseforge.com/minecraft/mc-mods/mcdar) (by [chronos\_sacaria](https://www.curseforge.com/members/chronos_sacaria/projects))
*   [MCDoom](https://www.curseforge.com/minecraft/mc-mods/mcdoom) (by [AzureDoomC](https://www.curseforge.com/members/azuredoomc/projects))
*   [MC Dungeons Weapons](https://www.curseforge.com/minecraft/mc-mods/mcdw) (by [chronos\_sacaria](https://www.curseforge.com/members/chronos_sacaria/projects))
*   [MedievalWeapons](https://www.curseforge.com/minecraft/mc-mods/medievalweapons) (by [Globox\_Z](https://www.curseforge.com/members/globox_z/projects))
*   [megane](https://www.curseforge.com/minecraft/mc-mods/megane) (by [badasintended](https://www.curseforge.com/members/badasintended/projects))
*   [Mo Glass](https://www.curseforge.com/minecraft/mc-mods/mo-glass) (by [alexander9892](https://www.curseforge.com/members/alexander9892/projects))
*   [Mobs Attempt Parkour](https://www.curseforge.com/minecraft/mc-mods/mobs-attempt-parkour) (by [Barribob](https://www.curseforge.com/members/barribob/projects))
*   [Modern Industrialization](https://www.curseforge.com/minecraft/mc-mods/modern-industrialization) (by [thetechnici4n](https://www.curseforge.com/members/thetechnici4n/projects))
*   [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) (by [ProspectorDev](https://www.curseforge.com/members/prospectordev/projects))
*   [Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks) (by [YaLTeR](https://www.curseforge.com/members/yalter/projects))
*   [Nature's Compass](https://www.curseforge.com/minecraft/mc-mods/natures-compass) (by [Chaosyr](https://www.curseforge.com/members/chaosyr/projects))
*   [Nauticality](https://www.curseforge.com/minecraft/mc-mods/nauticality) (by [Motschen](https://www.curseforge.com/members/motschen/projects))
*   [Observable](https://www.curseforge.com/minecraft/mc-mods/observable) (by [tasgon](https://www.curseforge.com/members/tasgon/projects))
*   [Outvoted](https://www.curseforge.com/minecraft/mc-mods/outvoted) (by [HowBoutNo](https://www.curseforge.com/members/howboutno/projects))
*   [oωo (owo-lib)](https://www.curseforge.com/minecraft/mc-mods/owo-lib) (by [gliscowo](https://www.curseforge.com/members/gliscowo/projects))
*   [Paintings++ (Fabric Edition)](https://www.curseforge.com/minecraft/mc-mods/paintings-fabric-edition) (by [AbsolemJackdaw](https://www.curseforge.com/members/absolemjackdaw/projects))
*   [Pipe](https://www.curseforge.com/minecraft/mc-mods/pipe) (by [Flytre7](https://www.curseforge.com/members/flytre7/projects))
*   [Plushie Mod](https://www.curseforge.com/minecraft/mc-mods/plushie-mod) (by [Link\_911](https://www.curseforge.com/members/link_911/projects))
*   [Polymorph (Fabric)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric) (by [TheIllusiveC4](https://www.curseforge.com/members/theillusivec4/projects))
*   [Portable Tables](https://www.curseforge.com/minecraft/mc-mods/portable-tables) (by [thatguynamedalpha](https://www.curseforge.com/members/thatguynamedalpha/projects))
*   [Quartz Elevator](https://www.curseforge.com/minecraft/mc-mods/quartz-elevator) (by [atonkish](https://www.curseforge.com/members/atonkish/projects))
*   [Realistic Fire Spread](https://www.curseforge.com/minecraft/mc-mods/realistic-fire-spread) (by [MoriyaShiine](https://www.curseforge.com/members/moriyashiine/projects))
*   [Reborn Core](https://www.curseforge.com/minecraft/mc-mods/reborncore) (by [modmuss50](https://www.curseforge.com/members/modmuss50/projects))
*   [Replanter](https://www.curseforge.com/minecraft/mc-mods/replanter) (by [Areuthreateningme](https://www.curseforge.com/members/areuthreateningme/projects))
*   [Respawnable Pets](https://www.curseforge.com/minecraft/mc-mods/respawnable-pets) (by [MoriyaShiine](https://www.curseforge.com/members/moriyashiine/projects))
*   [Rhino](https://www.curseforge.com/minecraft/mc-mods/rhino) (by [LatvianModder](https://www.curseforge.com/members/latvianmodder/projects))
*   [Roughly Enough Items Fabric (REI)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) (by [shedaniel](https://www.curseforge.com/members/shedaniel/projects))
*   [Roughly Enough Resources](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources) (by [theorbagain](https://www.curseforge.com/members/theorbagain/projects))
*   [Simple Backpack \[FABRIC\]](https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric) (by [kwpugh](https://www.curseforge.com/members/kwpugh/projects))
*   [Easy Emerald Tools & More \[FABRIC\]](https://www.curseforge.com/minecraft/mc-mods/simple-emerald-tools-fabric) (by [kwpugh](https://www.curseforge.com/members/kwpugh/projects))
*   [Sky Villages \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/sky-villages-fabric) (by [Aureljz](https://www.curseforge.com/members/aureljz/projects))
*   [Smoother Bedrock](https://www.curseforge.com/minecraft/mc-mods/smoother-bedrock) (by [haykam](https://www.curseforge.com/members/haykam/projects))
*   [Sodium Extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra) (by [FlashyReese](https://www.curseforge.com/members/flashyreese/projects))
*   [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium) (by [jellysquid3\_](https://www.curseforge.com/members/jellysquid3_/projects))
*   [Somnus API (Discontinued)](https://www.curseforge.com/minecraft/mc-mods/somnus) (by [TheIllusiveC4](https://www.curseforge.com/members/theillusivec4/projects))
*   [spark](https://www.curseforge.com/minecraft/mc-mods/spark) (by [Iucko](https://www.curseforge.com/members/iucko/projects))
*   [Starlight (Fabric)](https://www.curseforge.com/minecraft/mc-mods/starlight) (by [Spottedstar](https://www.curseforge.com/members/spottedstar/projects))
*   [Sulfur And Potassium - More Gunpowder](https://www.curseforge.com/minecraft/mc-mods/sulfur-and-potassium-make-more-gunpowder) (by [BR4NDER5](https://www.curseforge.com/members/br4nder5/projects))
*   [Talking Villagers](https://www.curseforge.com/minecraft/mc-mods/talking-villagers) (by [TeaJ4y](https://www.curseforge.com/members/teaj4y/projects))
*   [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn) (by [modmuss50](https://www.curseforge.com/members/modmuss50/projects))
*   [The Graveyard (FABRIC)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric) (by [finallion\_13](https://www.curseforge.com/members/finallion_13/projects))
*   [Wild Update Mod \[Fabric\]](https://www.curseforge.com/minecraft/mc-mods/the-wild-mod) (by [lukebattle04](https://www.curseforge.com/members/lukebattle04/projects))
*   [Tom's Simple Storage Mod (Fabric)](https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric) (by [tom54541](https://www.curseforge.com/members/tom54541/projects))
*   [Traveler's Backpack \[FABRIC\]](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric) (by [Tiviacz1337](https://www.curseforge.com/members/tiviacz1337/projects))
*   [Tree Harvester (Fabric)](https://www.curseforge.com/minecraft/mc-mods/tree-harvester-fabric) (by [Serilum](https://www.curseforge.com/members/serilum/projects))
*   [Trinkets (Fabric)](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric) (by [EmilyPloszaj](https://www.curseforge.com/members/emilyploszaj/projects))
*   [Universal Graves](https://www.curseforge.com/minecraft/mc-mods/universal-graves) (by [Patbox](https://www.curseforge.com/members/patbox/projects))
*   [Universal Ores (Fabric)](https://www.curseforge.com/minecraft/mc-mods/universal-ores-fabric) (by [Hugman\_76](https://www.curseforge.com/members/hugman_76/projects))
*   [Upgraded Ender Chests](https://www.curseforge.com/minecraft/mc-mods/upgraded-ender-chests) (by [Kyrptonaught](https://www.curseforge.com/members/kyrptonaught/projects))
*   [ValleyCraft](https://www.curseforge.com/minecraft/mc-mods/valleycraft) (by [llnkle](https://www.curseforge.com/members/llnkle/projects))
*   [Vanilla Excavators](https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators) (by [Draylar1](https://www.curseforge.com/members/draylar1/projects))
*   [Vanilla Hammers](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers) (by [Draylar1](https://www.curseforge.com/members/draylar1/projects))
*   [Villager Names (Fabric)](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric) (by [YumatanGames](https://www.curseforge.com/members/yumatangames/projects))
*   [Wireless Networks](https://www.curseforge.com/minecraft/mc-mods/wireless-networks) (by [GabrielHOlv](https://www.curseforge.com/members/gabrielholv/projects))
*   [Workbench Factory](https://www.curseforge.com/minecraft/mc-mods/workbench-factory) (by [puggan](https://www.curseforge.com/members/puggan/projects))
*   [Workings](https://www.curseforge.com/minecraft/mc-mods/workings) (by [Andrew6rant](https://www.curseforge.com/members/andrew6rant/projects))
*   [WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit) (by [badasintended](https://www.curseforge.com/members/badasintended/projects))
*   [XL Packets Fabric](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) (by [tfarecnim](https://www.curseforge.com/members/tfarecnim/projects))
*   [You're a fish now!](https://www.curseforge.com/minecraft/mc-mods/youre-a-fish-now) (by [LimeShulkerBox](https://www.curseforge.com/members/limeshulkerbox/projects))
*   [YUNG's API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric) (by [YUNGNICKYOUNG](https://www.curseforge.com/members/yungnickyoung/projects))
*   [YUNG's Better Dungeons (Fabric)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric) (by [YUNGNICKYOUNG](https://www.curseforge.com/members/yungnickyoung/projects))
*   [YUNG's Better Mineshafts (Fabric)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric) (by [YUNGNICKYOUNG](https://www.curseforge.com/members/yungnickyoung/projects))
*   [YUNG's Better Strongholds (Fabric)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds-fabric) (by [YUNGNICKYOUNG](https://www.curseforge.com/members/yungnickyoung/projects))

**Comment by Keksuccino** [comment]
Yeah that was a bug in that version, if I'm not wrong >.< but I had planned to not update this version anymore :/ It's 1.17, you should just use 1.18 😅

**Comment by kreezxil** [comment]
I can't just use 1.18 for my modpack, the mods I need are not yet on 1.18
and therein lies the rub. If you're not gonna fix it that's fine. just
saying that is more than sufficient.

**Comment by Keksuccino** [comment]
will try to push a last little update to fix this one :)

**Comment by kreezxil** [comment]
Awesome, thanks!

**Comment by Keksuccino** [comment]
It seems to work just fine on Windows 10.
Can you send me a log after clicking the button, please?

**Comment by kreezxil** [comment]
Odd, it was working when I reported this 28 days ago. But now it is. Most likely a mod conflict that got patched in that amount of time. Thank you for looking into this. I'm closing this with comment. :)
