### ISSUE TITLE
HiDPI screens not scaling correctly.

### ISSUE THREAD

**Issue by MGlolenstine** [Keksuccino/FancyMenu#234]
**Describe the bug**
The GUI doesn't scale correctly on HiDPI screens.

**To Reproduce**
1. Connect a HiDPI monitor to the computer
2. Start the game
3. Go into video settings and change the GUI Scale.

**Expected behavior**
I'd expect the GUI to be scaled alongside the official GUI.

**Screenshots**
This is the lowest GUI scale and it looks like a scale 3:
![This is the lowest GUI scale and it looks like a scale 3](https://user-images.githubusercontent.com/9406770/147759847-4da26bfa-8f03-4b03-91a0-df6d1ef9a442.png)
This is the normal (official) GUI at the same scale:
![This is the normal (official) GUI at the same scale:](https://user-images.githubusercontent.com/9406770/147759906-603e5b7d-ace0-48af-aefe-78f05dac1dec.png)

**Basic Informations (please complete the following information):**
 - OS: Linux (Arch Linux btw)
 - FancyMenu Version: 2.4.3
 - Forge/Fabric Version: 36.2.22
 - Minecraft Version: 1.16.5
 - Active Mods: WoD2 modpack

**Comment by Keksuccino** [comment]
I don't do anything to the GUI scale by default, neither does MC do something special with specific monitors, I think?
Is it maybe a mod you're using to use special scales for your monitor?

**Comment by Keksuccino** [comment]
Wait. Does you GUI scale in the first screenshot change at all when changing the GUI scale in the settings? Because it could simply be a forced GUI scale of 3 in this menu. This is possible with FancyMenu and in this case, it wouldn't be affected by changing the scale.

**Comment by kreezxil** [comment]
I've been trying to make sure all my menus are forced to scale 2. Because, I've been noticing odd scaling issues lately. However, I have not made a bug report because I can't seem to lock it down to user error or program error.

**Comment by Keksuccino** [comment]
Closed because not a bug.
