### ISSUE TITLE
Delayed appearances do not work properly if buttons have identical actionid

### ISSUE THREAD

**Issue by davthenub** [Keksuccino/FancyMenu#235]
Bug:
If you copy/paste a button that has a "delay appearance" effect, it will copy and paste the actionid of the button which seems to also break the "delay appearance" thing. It probably has to do with uuids and stuff but it's something I discovered when duplicating buttons for a "quick access" server list.

1. Create button with a delayed appearance
2. Copy+paste it
3. Restart game
4. Only the first button has a delayed appearance, the other ones appear instantly as if they didn't have a "delayed appearance" effect
5. Checking the menu customization txt file shows that the actionids are identical between the original and pasted button
6. Creating a button and manually giving it the exact same properties works normally

Expected behavior
Copy/pasting buttons should not keep the actionid, the easiest fix might be to regenerate a new actionid every time a button is pasted?

**Crash Log**
<no crash>

Other info:
 - Mac OS 10.15.7
 - FancyMenu 2.5.0 for 1.18-1.18.1
 - Fabric loader 0.12.12, API 0.45.0
 - Active mods other than those listed: LoadMyResources 1.0.1 for 1.18, konkrete 1.3.3 for 1.18-1.18.1

apologies if this is confusing/worded poorly/not enough info

**Comment by Keksuccino** [comment]
I thought I fixed this already o.O Copying action IDs when copying an element is not supposed to happen. Seems like I forgot something. Will look into this, thank you for telling me :)

**Comment by davthenub** [comment]
ok, thanks for the quick reply!

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.5.1! Thank you for your report!
