### ISSUE TITLE
Change placeholder value name "Forge 版本" to "Mod加载器 版本", to support both Fabric and Forge

### ISSUE THREAD

**Issue by xpe-online** [Keksuccino/FancyMenu#236]
**Describe the bug**
When I use FancyMenu 2.5.0,it fixed bug:https://github.com/Keksuccino/FancyMenu/issues/229.
But when I use Chinese language,it still displays 'Forge版本',it means 'Forge Version'.

**To Reproduce**
1. Click on 'Expend Menu Bar'
2. Click on 'Current Menu'
3. Click on 'Layout'
4. Open a Layout
5. Edit the Layout
6. Create a new Element,click on 'Element'/'New'/'Text'
7. When you open the 'Edit Content' or 'New Text',click on 'Plus Sign'/'Client'
8. See Error,it displays 'Forge 版本,but I use it on Fabric
9. Make your mouse hover on 'Forge 版本'
10. See Error,it display '获取 Forge 版本。',it means get Forge version

**Expected behavior**
1. 'Forge 版本' amend 'Mod加载器 版本'
2. '获取 Forge 版本。' amend '获取 Mod加载器 版本。'
Here is Repaired language file,you can overwrite this file directly:[Click me](https://www.mediafire.com/file/u6sl90f34pzjd67/zh_cn.local/file)
You can open the Repaired language file,I amend it on line 607 and line 608

**Screenshots**
![image](https://user-images.githubusercontent.com/85062843/148672083-f90c629e-82c7-46ec-a661-973b2dc0b52a.png)

**Basic Informations (please complete the following information):**
- OS: [Windows 11]
- FancyMenu Version [2.5.0]
- Forge/Fabric Version [Fabric 0.12.12 FabricAPI 0.44.0+1.18]
- Minecraft Version [1.18]
- Active Mods [Sodium,Iris]

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.6.0! Thank you!
