### ISSUE TITLE
1.18.1 won't start

### ISSUE THREAD

**Issue by WildTom1** [Keksuccino/FancyMenu#237]
Minecraft won't start and will give me "error code: 1"

**To Reproduce**
1. Install fancy menu for 1.18.1 on forge (and on manjaro Linux)
2. Launch Minecraft

**Expected behavior**
Minecraft Will launch
**Behavior**
Minecraft crashes instantly
**Crash Log**
[24Jan2022 17:23:11.819] [main/WARN] [mixin/]: Error loading class: de/keksuccino/konkrete/config/Config (java.lang.ClassNotFoundException: de.keksuccino.konkrete.config.Config)

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Manjaro Linux
 - FancyMenu Version: All 1.18.1 versions
 - Forge/Fabric Version: Forge 39.0.59
 - Minecraft Version : 1.18.1
 - Active Mods: None

Please tell me if there is a fix to do, or release a fix.
Thanks,
Wild Tom

**Comment by Keksuccino** [comment]
Please send me your full `.minecraft/logs/latest.log` file, thank you.

**Comment by WildTom1** [comment]
[latest.log](https://github.com/Keksuccino/FancyMenu/files/7929901/latest.log)

**Comment by WildTom1** [comment]
Found the problem, I didn't install Konkrete into my mods folder.
