### ISSUE TITLE
Back to Server List" Button reapears when deleted

### ISSUE THREAD

**Issue by cmod31** [Keksuccino/FancyMenu#238]
I want on my private Modpack for friends only one Button to join our Server in the Main Menu with no Server List.
I changed some Buttons with button scripts and everything is working fine.
But when i want to replace the Back to Server list Button with a opengui Button.

I deleted the "Back to Server List" button but every time the message on the conection lost or kicked or banned gets changed(the Buttons moved) it reapears.
It still uses the same layout file but when i delete the button every time it moves it fixes it but then i would have to delete the button for every possible server error message.

<img src="https://cdn.discordapp.com/attachments/924686967113916446/937687530034331678/2022-01-31_13.35.12.png">

**Comment by Keksuccino** [comment]
That's because the button is changing its position. FancyMenu can't handle buttons that aren't always at the same position, sadly.

**Comment by cmod31** [comment]
maybe an option for disabling certain vanilla buttons comepletely? or is that already what you mean in the title?

**Comment by Keksuccino** [comment]
This should be fixed now! Try to make a **NEW** layout for that menu and delete the button in it. It should keep working even when the message text changes.
