### ISSUE TITLE
WAV File Incompatibility (-24bit, -32bit)

### ISSUE THREAD

**Issue by Shorepion** [Keksuccino/FancyMenu#24]
I found out that the audio only plays, if the wav-file got 16bit of depth. 24bit and 32bit wont work.
_Also, I recommend to maybe use .mp3 or .ogg as the audio file type in your mod.
Wav files are very big in comparison to other ones (~5x bigger than .mp3). This makes modpack bigger just for better audio quality, which isnt really worth it._

**Comment by Keksuccino** [comment]
Unfortunately, WAV and 16bit are limitations by Java, I cannot fix/improve that at the moment, sorry..
Maybe I will rewrite my sound system with a different API at some point, but for now,  that's how it is :/
