### ISSUE TITLE
1.12.2 version breaks with RandomPatches

### ISSUE THREAD

**Issue by brisingraerowing** [Keksuccino/FancyMenu#241]
**Describe the bug**
When RandomPatches and this mod are loaded together, the game crashes on initialization.

**To Reproduce**
1. Run this mod and RandomPatches together

**Expected behavior**
Game loads

**Crash Log**
[Crash Log](https://pastebin.com/V7WdqLhe)

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.6.1
 - Forge: 14.23.5.2860
 - Minecraft Version 1.12.2
 - Active Mods:

Ref: TheRandomLabs/RandomPatches#253

**Comment by Keksuccino** [comment]
Hi! Please try to set `patchMinecraftClass` to `false` in the RandomPatches config and see if this fixes the issue.
