### ISSUE TITLE
Vanilla menu music still playing even when disabled in config

### ISSUE THREAD

**Issue by DaveHyral** [Keksuccino/FancyMenu#242]
**Describe the bug**
FancyMenu [latest Fabric release], is being usurped by Minecraft in sound priority. Default Menu Background music is not being squelched with relevant option active, causing added audio to layer over vanilla menu music, creating a horrific cacophony of noise that only the most august of Slaaneshi Bards could appreciate.

**To Reproduce**
1. Go to 'FancyMenu Settings'
2. Set 'Default MC Menu Music' to DISABLED
3. Behold as it completely fails to Praise The God-Emperor

**Expected behavior**
I expected the Vanilla Menu Music to be muted, made to cease, desist, and play what I have added through your mod.

**Crash Log**
No Crashes, only horrific emanations worthy of Noise Marines.

**Screenshots**
+1 Screenshot added.

**Basic Informations (please complete the following information):**
 - OS: [Windows 10]
 - FancyMenu Version [Latest Fabric Release]
 - Fabric Version [0.12.12-1.18.1]
 - Minecraft Version [1.18.1]
 - Active Mods [None that touch GUI modification, too many to list]
![javaw_UnaqJvtfsc](https://user-images.githubusercontent.com/90770200/152902498-c477d18c-5215-49e1-8387-816c07ce1451.png)

**Comment by Keksuccino** [comment]
> Active Mods [None that touch GUI modification, too many to list]

Well, maybe they aren't touching GUIs, but they are still most probably the reason for the issue. Please try to run the game with only FancyMenu + dependencies installed and see if this fixes the issue.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
