### ISSUE TITLE
Buttons moved outside of dirt areas (server selection screen, ...) stop working

### ISSUE THREAD

**Issue by UltraBlackLinux** [Keksuccino/FancyMenu#243]
**Describe the bug**
Buttons moved outside of the dirt border lose their functionality and don't respond to clicks, only hovering

**To Reproduce**
Buttons moved outside of the dirt border in the server selection don't work anymore: No click action and not even a sound with my config: [exported_fm_setup_19-2-2022-0-9-35.zip](https://github.com/Keksuccino/FancyMenu/files/8100947/exported_fm_setup_19-2-2022-0-9-35.zip)

**Basic Informations (please complete the following information):**
 - OS: Arch Linux
 - FancyMenu Version 2.6.3
 - Fabric Version 0.13.2
 - Minecraft Version 1.18.1
 - Active Mods https://0bin.net/paste/foNYjI40#A8xs0W7WCGtK876TM7ab1fFE0l7p50CPQ8iNQ+1yb7h

(I don't know, if this is already reported, but in my server selection screen you might notice that the entities aren't looking at the cursor directly, but rather the bod

**Comment by Keksuccino** [comment]
Hi! Thank you for your report, but that's probably a Minecraft thing. I can't really change this without overriding the buttons, sorry :/ If you really want to move them outside of the dirt area, create a customn button and use the `mimicbutton` button action to mimic the button in the dirt area, then hide the original button and use the custom one instead. The custom button should work outside of the area.
