### ISSUE TITLE
Suggestion: Add fade animation/delay appearance for splash text

### ISSUE THREAD

**Issue by EGOIST1372** [Keksuccino/FancyMenu#244]
Add fade animation/delay appearance for splash text, since many people use your cave animation it would be great to add fade animation/delay appearance to splash text so it will be coordinated with logo appearance in animation
thanks in advance

**Comment by EGOIST1372** [comment]
@Keksuccino this feature is really needed specially with cave animation so timing it to appear with the minecraft logo with the animation. a fade in animation would be great since you already implemented some option for splash text
thanks <3

**Comment by Keksuccino** [comment]
why don't you just add your own splash text? the custom one supports fade-ins and delays.

**Comment by Keksuccino** [comment]
It's painful to add delays and stuff to vanilla elements. Will probably add an option to use the vanilla splash text file for custom ones. Then you can just add your own vanilla-like splash text and delete the original one.

But I will not add more customizations to the vanilla splash text, sorry.

**Comment by Keksuccino** [comment]
#316
