### ISSUE TITLE
Animation sounds playing when Minecraft window isn't focused (when app is in background or minimized)

### ISSUE THREAD

**Issue by EGOIST1372** [Keksuccino/FancyMenu#245]
**Describe the bug**
intro animation music keep repeating in background, when you are in main menu and have cave animation set up when you hit the windows key and exit the minecraft app you hear cave animation intro music keep playing randomly 

**To Reproduce**
1. set cave animation for fancy menu main screen
2. Click on windows key
3. you keep hearing cave animation into music randomly occurring 

**Expected behavior**
to not hear that intro music randomly while the app is in background

**Basic Informations (please complete the following information):**
 - OS: windows 10
 - FancyMenu fabric_2.6.3_MC_1.18-1.18.1
 - fabric-api-0.46.1+1.18 and latest fabric loader 0.13.3
 - Minecraft Version 1.18.1
 - Active Mods: many :D

**Comment by Keksuccino** [comment]
Animations are gone in FancyMenu v3 (replaced by APNGs), so I'm closing this.
