### ISSUE TITLE
Buttons of Essential mod not customizable

### ISSUE THREAD

**Issue by Kevini-i** [Keksuccino/FancyMenu#246]
**Describe the bug**
When editing the main menu, the buttons from the essential mod disappear. 

**Menu Identifier**
net.minecraft.class_442

**To Reproduce**
1. Download the Essential  mod https://www.curseforge.com/minecraft/mc-mods/essential-mod
2. Open the game
3. Click the current menu on the top left, and enable customization

**Expected behavior**
The avatar to see your character, the friend's list, cosmetics, and the account button go missing.

**Screenshots**
![Before hitting the Customization button](https://user-images.githubusercontent.com/36944018/155230887-927cb923-8903-4a6d-8e6f-0cc41d33e517.PNG)
![After hitting the  Customization button](https://user-images.githubusercontent.com/36944018/155230901-b9806e9a-ec29-4974-a81d-cb9db40a62f9.PNG)

**Basic Informations (please complete the following information):**
 - OS:  Windows
 - FancyMenu Version [fancymenu_fabric_2.6.3_MC_1.18-1.18.1]
 - Fabric Version [0.13.2]
 - Minecraft Version [1.18.1]
 - Active Mods [Essential]

**Comment by Keksuccino** [comment]
That's not FancyMenu's fault. The other mod needs to add their buttons to the screen's button list, otherwise FancyMenu can't see them sadly. I suggest you to open an issue on the other mod's GitHub, if possible.

**Comment by Kevini-i** [comment]
Okay. Thank you.

**Comment by CallOfJuarez** [comment]
This will probably be incompatible forever because apparently they aren't buttons, thus can't be added to the screen's button list.
(my guess is an overlay, supported by Kevini-i's first screenshot where those buttons are on top of the vanilla ones)

**Comment by Keksuccino** [comment]
> This will probably be incompatible for some time (apparently planning to integrate with Fancymenu's api)

Hi! Are you the mod dev? If so, I think it would be much easier to just add the buttons to the button/widget list of the screen.
The API is not designed for that.

**Comment by CallOfJuarez** [comment]
I'm not, I just asked them about it

**Comment by Keksuccino** [comment]
Closing this now, because I can't fix it and don't know when/if the dev will fix this.
