### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by waddon1** [Keksuccino/FancyMenu#25]
**Describe the bug**
The game is crashing on startup, but only after this mod has been added.

**To Reproduce**
1. Start the game

**Expected behavior**
Load up into menu

**Crash Log**
https://pastebin.com/ND5tpL95

**Basic Informations (please complete the following information):**
 - OS: Linux
 - FancyMenu Version: 1.1.1
 - Forge Version: 31.2
 - Minecraft Version: 1.15.2

**Comment by STOKE-STER** [comment]
Same issue here.

OS: Windows
FancyMenu Version: 1.1.1
Forge Version 31.2.0
MC: 1.15.2

https://pastebin.com/n7J9mwrx

**Comment by Keksuccino** [comment]
That’s because of the new forge build (31.2) that breaks many mods. I have to update the mod first before it can be used with the newest forge.

**Comment by Keksuccino** [comment]
FancyMenu v1.2 added support for forge v31.2.0 and should fix this crash.
