### ISSUE TITLE
improve volume handling for background audios

### ISSUE THREAD

**Issue by JetpackRescue** [Keksuccino/FancyMenu#250]
Can you please link the music to the MUSIC channel. At the very least provide a config option to change it from MASTER to MUSIC. I've normalized my song as high as possible, but the master volume level cannot be set to 100%.

1.16.5

**Comment by Keksuccino** [comment]
You can now set the channel of the audio in the new audio extension for FancyMenu v2.6.4-1+ :)

Fabric: https://www.curseforge.com/minecraft/mc-mods/audio-extension-for-fancymenu-fabric
Forge: https://www.curseforge.com/minecraft/mc-mods/audio-extension-for-fancymenu-forge
