### ISSUE TITLE
UI Scaling issues with 3440 x 1440p monitor

### ISSUE THREAD

**Issue by TDderpy** [Keksuccino/FancyMenu#251]
HI there, 
I've recently been playing a modpack which uses's your mod but unfortunatly i've had to disable it due to UI issues when playing on my primary 3440 x 1440p monitor. 

I've taken seenshots on both my 1440 and 1080p monitos attached and as you can see when playing on GUI scaling Auto, some of the buttions in the game pasue menue fall offscreen.

1080p
![1080p](https://user-images.githubusercontent.com/44139414/158013420-3002e88a-bb4b-4fd6-b897-6f1ec6881a7c.png)

3440 x 1440
![3440 x 1440](https://user-images.githubusercontent.com/44139414/158013421-7ebc725a-b184-43f1-b95d-bbd49d38cbcf.png)

 let me know if you need any more info or help troubleshooting i know not everyone has an ultawide monitor to test with.

**Comment by Keksuccino** [comment]
Hi! I don't think that's a bug in the mod, but in the layout of that modpack. It probably forces a specific GUI scale for that menu.

However, I don't really have a 4K Monitor to test this, so I'm not sure.

Will try to "simulate" this resolution on my 1080, so I can debug it.

**Comment by TDderpy** [comment]
Yes it could be an issue for the modpack layout, i did wonder that. I just wanted to report it to you to help out in case it is a bug.  

The monitor itsself isn't 4k, its a 1440p ultawide. So it has a failrly exotic aspect ratio, with the width being about twice the usual for the hight. 

As for testing i'm happy to help out and i know it's hard to reporduce without your own montor with the same resolution.

**Comment by Keksuccino** [comment]
I wasn't able to reproduce this. It worked no matter the screen resolution.

Will close this for now, but I keep an eye on it.
