### ISSUE TITLE
UI elements overlap with Mine together on GUI scale < 2

### ISSUE THREAD

**Issue by TDderpy** [Keksuccino/FancyMenu#252]
**Describe the bug**
Not sure where the issue here lies but when playing a modpack with Minetogther, UI elements overlap when GUI scaling is set to any value greater then 2. 

**To Reproduce**
1. Go to video settings
2. set GUI scaling to a value greater then 2
3. Return to the main pause menu

**Expected behavior**
I'd expect to see the UI elements here to still scale but keep the format shown below when the GUI scaling is set to 2. 
This beahvour only shows itself when mine together is insalled and works as exptected when that mod is disabled. 

**Screenshots**
GUI scaling Auto (4)

![image](https://user-images.githubusercontent.com/44139414/158014066-bb108391-8918-4151-b0ee-865998942ce4.png)

GUI Scaling 4

![image](https://user-images.githubusercontent.com/44139414/158014108-3ea88223-3fbe-46b0-8493-719b1e6190da.png)

GUI Scaling 3

![image](https://user-images.githubusercontent.com/44139414/158014121-59d9149f-fae6-456f-ab49-d335bc6f2c3f.png)

GUI Scaling 2

![image](https://user-images.githubusercontent.com/44139414/158014079-c11fb0cf-9ec7-4137-af3f-e40467f4dec7.png)

GUI Scaling 1

![image](https://user-images.githubusercontent.com/44139414/158014133-c8535021-b9d8-467e-b494-a7d754e6be25.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 2.3.5
 - Forge/Fabric Version: 36.2.21
 - Minecraft Version 1.16.5
 - Active Mods: Modpack https://www.curseforge.com/minecraft/modpacks/not-too-complicated-2 lastest release
 - Resolution: 1080p (Affects are the same at 3440 x 1440)

**Comment by Keksuccino** [comment]
Does this only happen in the pause menu or every menu?

Is MineTogether adding any new buttons to the pause menu?

It works fine without MineTogether installed?

Could this be related to your first issue? So the scaling issues are caused by MineTogether + FancyMenu and don't happen anymore after removing MineTogether?

**Comment by TDderpy** [comment]
It just happens in the pasue menu, other menues seem okay.

Mine togther does add new buttons (the three in the middle firdnds, chat and open to friends)

It doesn't happen when minetogthers is disabled. Scaling works as expcred 

The first issue still represnets it'self on my 1440p monitor without minetogther. Though all screenshots and tests for this were done on my native 1080p monitor to avoid it having an infulance.

**Comment by Keksuccino** [comment]
Unable to fix this on my end, but added it to the incompatibility list! Thank you for your report!
