### ISSUE TITLE
Multiline web text had a stroke [Missing lines, not just empty ones; Better rewrite this]

### ISSUE THREAD

**Issue by syorito-hatsuki** [Keksuccino/FancyMenu#255]
![Screenshot_20220406_024458](https://user-images.githubusercontent.com/33298273/161868813-78fe0877-8f76-4250-8f09-d021293f104e.png)

On the screenshot, u can see web text in Minecraft and in Web Browser. All extra spaces. Tags (Broken, Client library etc) and text splitter (====...) is lost in-game after one time find in text

 - OS: Linux & Windows
 - FancyMenu Version [2.6.4]
 - Fabric Loader Version [0.13.3]
 - Fabric Api [0.48.0+1.18.2]
 - Minecraft Version [1.18.2]
 - Active Mods [Fabric API, FancyMenu, Konkrete]

**Comment by syorito-hatsuki** [comment]
U can also try it yourself
http://play.rivaviva.ru:1540/changelog/terra

**Comment by Keksuccino** [comment]
Try to add a space (" ") at every blank line.

**Comment by syorito-hatsuki** [comment]
> Try to add a space (" ") at every blank line.

Nothing changed

**Comment by Keksuccino** [comment]
Well, that's indeed strange. Will check this, thank you for telling me! :)

**Comment by syorito-hatsuki** [comment]
> Well, that's indeed strange. Will check this, thank you for telling me! :)

Good luck) I just made some test files. Access can be gated from http://play.rivaviva.ru:1540/changelogs (SSL coming soon)

**Comment by syorito-hatsuki** [comment]
Problem is not only with empty lines. Check better screenshot

**Comment by Keksuccino** [comment]
That's like the first time in 1 1/2 years that somebody uses the multiline web text, I haven't tested this thing for ages lmao. Will probably need to rewrite this, because that looks more broken than I thought and I have no idea what update broke it.

**Comment by syorito-hatsuki** [comment]
> Problem is not only with empty lines. Check better screenshot



> That's like the first time in 1 1/2 years that somebody uses the multiline web text, I haven't tested this thing for ages lmao. Will probably need to rewrite this, because that looks more broken than I thought and I have no idea what update broke it.
![image](https://user-images.githubusercontent.com/33298273/162372287-3785cb8c-a7e2-46a0-8bbd-f3ea98ab289f.png)
I fixed in fork :D Wait for pull request :3

**Comment by syorito-hatsuki** [comment]
#256

**Comment by Keksuccino** [comment]
Thank you very much for your effort, but as I said, I'm planning to rewrite it completely, since I wanted to add new features to it for a long time now anyway. Like making the multiline text scrollable and stuff :)
That code was written like 2+ years ago, so I would probably do most of it in a different and better way now, but again, thank you very much for your help!

Oh and to your changes to my build file:
I like local libs and prefer them over automatically downloaded ones. Apart from that, Gradle can be a very frustrating and soul-eating experience, when it comes to dependency management, especially when you need to do it for multiple Gradle versions. That's why I want my build scripts to be as simple as possible :)

**Comment by syorito-hatsuki** [comment]
> Thank you very much for your effort, but as I said, I'm planning to rewrite it completely, since I wanted to add new features to it for a long time now anyway. Like making the multiline text scrollable and stuff :) That code was written like 2+ years ago, so I would probably do most of it in a different and better way now, but again, thank you very much for your help!
> 
> Oh and to your changes to my build file: I like local libs and prefer them over automatically downloaded ones. Apart from that, Gradle can be a very frustrating and soul-eating experience, when it comes to dependency management, especially when you need to do it for multiple Gradle versions. That's why I want my build scripts to be as simple as possible :)

I thinked about **hotfix** for use possibly))

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.6.6! Thank you very much for the fix! :D
