### ISSUE TITLE
Changes only get applied when enabling main menu changes

### ISSUE THREAD

**Issue by TheButterbrotMan** [Keksuccino/FancyMenu#258]
**Describe the bug**
So...

I edited the pause menu, but these changes were not applied. However, after I switched on editing in the main menu and added a button, I went back to the pause menu and the changes were applied.

**To Reproduce**
1. Go to Pause Menu
2. Add a Button and save it 
3. go to main menu edit it and save it
4. go back to pause menu and see changes

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 26.4-1
 - Fabric Version 0.13.3
 - Minecraft Version [1.18.2]

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.6.5! Thank you for your report!
