### ISSUE TITLE
Essentials mod GUI elements on the main menu are not supported by fancymenu

### ISSUE THREAD

**Issue by BookWyrm114** [Keksuccino/FancyMenu#260]
**Describe the bug**
Essentials mod GUI elements on the main menu are not supported by fancymenu

**To Reproduce**
1: Install the essentials mod
2: attempt to edit the main menu
3: realize all essentials elements disappear when customization is enabled on the home menu

**Expected behavior**
All essentials mod GUI elements would be supported

**Screenshots**
![image](https://user-images.githubusercontent.com/79489385/165391519-34d8f4b3-929e-44fc-8a9b-b9df5022e120.png)
![image](https://user-images.githubusercontent.com/79489385/165391560-0a62069a-3746-4f10-ba2a-5b863c3f0532.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 2.6.6 Fabric
 - Minecraft Version: 1.18.2
 - Essentials Mod: https://essential.gg/

**Comment by Keksuccino** [comment]
Duplicate of #246
