### ISSUE TITLE
I can't open an image.

### ISSUE THREAD

**Issue by netcore10** [Keksuccino/FancyMenu#261]
**Describe the bug**
Every time i try to open a logo.png it give's me an 'unsupported character's' screen even though it's titled 'logo.png'
**To Reproduce**
I have no idea.

**Expected behavior**
let me use the image. Could it be because it's transparant in parts?

**Screenshots**
Cant import showcase:
https://user-images.githubusercontent.com/181536/165396021-503d0dc4-5073-4e42-9091-2389fa59c014.mov

Image open in G.I.M.P:
![image](https://user-images.githubusercontent.com/181536/165396356-a5582728-3b0a-41c0-ad27-b3f271da9a09.png)

**Basic Informations (please complete the following information):**
 - OS: windows
 - FancyMenu Version 2.6.6
 - Forge/Fabric Version fabric 0.13.3
 - Minecraft Version 1.18.2
 - Active Mods only fancymenu and addons

**Comment by netcore10** [comment]
Note: Can't open a gif either.

**Comment by netcore10** [comment]
okay, i got it to work, but it took several renames of the file.

**Comment by Keksuccino** [comment]
It's probably more the path of the name and not the actual file name.

What was the full path to the file?

**Comment by Keksuccino** [comment]
Well, no it WAS the file name. Your file's name wasn't `logo.png`, but `LOGO.png`, which is not supported, just like the message tells you.

**Comment by netcore10** [comment]
Yeah that was an oversight, sorry for wasting your time.
