### ISSUE TITLE
Crash when customizing meteor client menus

### ISSUE THREAD

**Issue by BookWyrm114** [Keksuccino/FancyMenu#263]
**Describe the bug*

When customization is enabled for a meteor client menu the game will crash upon startup without any errors in the log

**To Reproduce**
1. Download Meteor Client and fancymenu
2. Go to a meteor client menu and turn customization on
3. Close the game and try starting it up again

**Expected behavior**
The game would start

**Crash Log**
Unfortunately not, the lack of error messages made figuring out the issue very difficult 

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 0.6.6 Fabric
 - Minecraft Version: 1.18.2
 - Active Mods: FancyMenu, Meteor Client

**Comment by Keksuccino** [comment]
> will crash upon startup without any errors in the log

This is not really possible, I think. Can you send me your `.minecraft/logs/latest.log`, after the crash happened, please?

**Comment by BookWyrm114** [comment]
sure, but there's no error that I could see
[latest.log](https://github.com/Keksuccino/FancyMenu/files/8578363/latest.log)

All I know is that as soon as I went in the config and disabled customization for the meteor client menu I had enabled it for, the game started. I made no other changes that time, so that was the issue. I don't know what could be causing it though, it seems like it shouldn't happen, but it does somehow.

**Comment by Keksuccino** [comment]
Oh, that's a hacking client. I thought it's a mod. Well, clients mostly use their own GUI systems and there is no way for me to add support for these kind of menus, I'm very sorry.

**Comment by BookWyrm114** [comment]
It is technically a mod, not a client. And thanks anyway! Before you forget about this issue for good though, is there at least a way to prevent the game from crashing on startup when unsupported GUIs have customization enabled?

**Comment by Keksuccino** [comment]
The easiest way is to delete the `.minecraft/config/fancymenu/customizablemenus.txt` file and restart the game :) This will reset the customization toggle for all menus, so you will need to enable them again, but it's the best way :)

**Comment by BookWyrm114** [comment]
Ok, I went into the file and manually deleted just the meteor menu from it, that works too. Thank you!
