### ISSUE TITLE
Resourece pack menu does not work with custom backgrounds

### ISSUE THREAD

**Issue by BookWyrm114** [Keksuccino/FancyMenu#264]
**Describe the bug**
adding a custom background to the resource back menu deletes the right side of the menu

**To Reproduce**
try adding a custom background to the resource pack menu

**Expected behavior**
for custom backgrounds to work on the resource pack menu

**Screenshots**
![image](https://user-images.githubusercontent.com/79489385/165624475-b052b841-b7f2-4322-a127-03cc71114843.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 0.6.6 Fabric
 - Minecraft Version: 1.18.2

**Comment by Keksuccino** [comment]
This is due to how that screen is made and I can't really fix this without messing with the screen and I don't want to do this, because the resource screen is kind of important, so I don't want to be the reason for broken resources.

Will not fix that, sorry.
