### ISSUE TITLE
Rare crash related to visibility requirements

### ISSUE THREAD

**Issue by Jetpack-Cat** [Keksuccino/FancyMenu#265]
**Describe the bug**
I clicked on a button to open a custom gui, crash.

**To Reproduce**
On the pause screen I have an element with visibility set to if optifine is installed, another set to if fullscreen. I was not in fullscreen and optifine was disabled. It crashed when I clicked a button on the pause screen to open a custom ui, the custom ui it opens just has a single image on it.

This crash happens whether or not I have it in fullscreen and optifine is enabled. So the visibility of the elements with visibility settings don't seem to matter? but this didn't happen before I added those.

Also had a splash text that becomes visible when hovering over the open to lan button.

**Crash Log**
If the bug includes a crash, please paste or link it here.

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: windows
 - FancyMenu Version 2.6.6 forge 
 - Forge/Fabric Version 36.2.33
 - Minecraft Version 1.16.5
 
[crash-2022-04-29_02.18.34-client.txt](https://github.com/Keksuccino/FancyMenu/files/8589746/crash-2022-04-29_02.18.34-client.txt)

**Comment by Keksuccino** [comment]
Hi! Can you please export your setup (Setup -> Export) and send it to me, together with your `.minecraft/logs/latest.log`, after the crash happened? Thank you very much!

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.8.0! Thank you for your report!
