### ISSUE TITLE
Audio Extension: Sounds restart when switching from/to a custom GUI, even if same sounds in both menus

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#266]
> Fancy menu with audio extension, music keeps restarting when going between main menu and custom guis, even when I copy pasted the background music audio element between them all. It plays in every menu i've added it to but restarts the song when going back and forth most of the time. At times it will continue the song. 1.16.5 forge 

> I believe it's when you have 2 random main menus, when you go to another scene then go back to the main menu and it loads the other main menu it freezes for 5 or so seconds

https://discord.com/channels/704163135787106365/704164602455523359/969391760784633906

**Comment by MattB70** [comment]
This happens with two menus regardless of if they are random or not. Continuously switching will stack multiple of the audio tracks on top of each other. If you wait for them to finish, it will return to normal. It seems that switching back to the main menu causes the audio to play again without looping.

**Comment by Keksuccino** [comment]
This should be fixed in v1.0.1 of the audio extension. If there are still issues, please open a new issue or comment here! :)
