### ISSUE TITLE
Universal elements

### ISSUE THREAD

**Issue by BookWyrm114** [Keksuccino/FancyMenu#267]
**Describe your idea**
Elements that can be set as "universal", meaning they are automatically applied on every GUI that has customization enabled, unless specifically disabled for that GUI. and any changes made to a universal element are applied across every GUI, like adding or removing songs from an audio track which would really help when trying to add audio to alot of GUIs, because I just went through every GUI in minecraft to copy&paste an audio element and then thought of this idea.

**Comment by Keksuccino** [comment]
Yeah, I would implement this as a type of layout that loads for every menu ^^ I have this on my to-do list for a long time now, but never actually implemented it >.< Will try to add it asap! :)

**Comment by BookWyrm114** [comment]
Thanks!

**Comment by Keksuccino** [comment]
Added in FancyMenu v2.7.0! Thank you for your suggestion! :)

**Comment by BookWyrm114** [comment]
Yay! Thank you!
