### ISSUE TITLE
1.2.1 crash when loading background texture for the first time (Linux)

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#27]
https://paste.ee/p/6mKFa

I used your new cool AF file dialogue to find and select my background texture. Then I hit done. then a creeper blew up minecraft. :(

**Comment by kreezxil** [comment]
srsly, tho that file dialogue is the shizzle!

**Comment by Keksuccino** [comment]
Could be a linux thing. The texture is "null", which should never ever be the case. I will look into this asap! :)

**Comment by Keksuccino** [comment]
I wasn't able to reproduce this bug :/ Could you please try if the bug is still present in FancyMenu v1.3? Maybe I fixed it without knowing it :'D Thank you very much!

**Comment by Keksuccino** [comment]
Not reproducable.
