### ISSUE TITLE
Crash at game start when loading layout for a custom GUI that doesn't exist anymore

### ISSUE THREAD

**Issue by UnforgotenX** [Keksuccino/FancyMenu#272]
**Describe the bug**
After a crash on a world preview screen (From a different mod) it no longer wishes to launch the game and just keeps saying 
**FancyMenu (fancymenu) has failed to load correctly**
java.lang.ExceptionInInitializerError: null
[Screenshot](https://user-images.githubusercontent.com/28698025/169676413-537b3098-49e4-4fd6-ab47-d7d877085df1.png)

**To Reproduce**
No clue how to reproduce this as it happened after a crash and wasn't happening before

**Crash Log**
[crash.txt](https://github.com/Keksuccino/FancyMenu/files/8748675/crash.txt)
[latest.log](https://github.com/Keksuccino/FancyMenu/files/8748677/latest.log)

**Basic Informations:**
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.34
 - Operating System: Windows 10 (amd64) version 10.0
 - Java Version: 1.8.0_51, Oracle Corporation
 - Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 - Memory: 2114505080 bytes (2016 MB) / 3635937280 bytes (3467 MB) up to 15957229568 bytes (15218 MB)
 - CPUs: 12
 - FancyMenu Version: 2.7.2
 - Active Mods: 354 active mods [modlist.txt](https://github.com/Keksuccino/FancyMenu/files/8748679/modlist.txt)

**Comment by Keksuccino** [comment]
- Try to re-download FancyMenu + dependencies
- Try to launch the game with only FancyMenu + dependencies installed
- If it runs with only FM + dependencies, try to re-download your other mods

**Comment by UnforgotenX** [comment]
I will try to redownload all the mods and see if that fixes it

**Comment by UnforgotenX** [comment]
I redownloaded every mod and it gave me the same issue, I dont know what happened with the crash.

**Comment by Keksuccino** [comment]
> I have tried it with only FancyMenu and it loads all the animations

So it works with only FancyMenu + dependencies?
Then it's probably a mod conflict that doesn't crash the game every time. Maybe it worked the first few times and now it's crashing. You have 350+ mods, which is an insane amount, so it's absolutely possible that things like this happen.

Another possible fix would be to re-download Forge.

But just in case it's really a bug in FancyMenu, I will see if I can reproduce it in a few hours. Just need some sleep first.

**Comment by Keksuccino** [comment]
Ohhh, so you made a layout for a mod GUI, then uninstalled the mod and it started crashing at game start?

Interesting! I think it tries to find the GUI when loading layouts, but that shouldn't crash the game o.O

Will check this, thank you for telling me!

**Comment by UnforgotenX** [comment]
I created a custom gui with fancy menu and deleted the gui without deleting the layout

**Comment by Keksuccino** [comment]
Hmm, I wasn't able to reproduce this. I think this was just a weird combination of many factors that caused this. It's fixed now, so if it doesn't happen again, it's fine I guess.

But if it happens again, please tell me and I will take a further look into it!
