### ISSUE TITLE
Please Enable the "Project Distribution Toggle" on CurseForge for your Porojects

### ISSUE THREAD

**Issue by MSandro** [Keksuccino/FancyMenu#274]
Since the new CurseForge regulations it is no longer possible to download FancyMenu with 3rd party tools like Packwiz. Many modpack developers use external software such as Packwiz to manage their modpacks.

![image](https://user-images.githubusercontent.com/10937159/169803978-064f0b6a-af82-4a8a-9103-5c97ef2df5ca.png)
![image](https://user-images.githubusercontent.com/10937159/169803327-781b18a2-36c5-461d-841e-fa6ffed395df.png)

**Comment by Keksuccino** [comment]
Hi, please read the license of FancyMenu.
