### ISSUE TITLE
Integration of gui FTB Quests

### ISSUE THREAD

**Issue by Abbadon999** [Keksuccino/FancyMenu#275]
I want to create a button in the "Quests" pause menu, so that this button directs to the gui FTB Quests
Is it possible to implement this?

**Comment by Abbadon999** [comment]
It would make an incredible improvement to my modpack

**Comment by Abbadon999** [comment]
If there are no plans to integrate FTBQuests. Then I have a question - Is it possible to make it so that when you click on the created button, the button on the keyboard will be pressed?

**Comment by Keksuccino** [comment]
Is there a command to open FTB quests? If so, use the `sendmessage` button action and let it execute the command.
Other support for FTB quests is not planned, sorry.

> Is it possible to make it so that when you click on the created button, the button on the keyboard will be pressed?

No, this is not possible, sorry.
