### ISSUE TITLE
[Maybe only 1.12] Buttons show as default when clicking on a custom button while the menu is set to background rendering order

### ISSUE THREAD

**Issue by Abbadon999** [Keksuccino/FancyMenu#277]
When you click on a created custom button, all other buttons reset their design to the standard

1. Create a custom button 
2. Make it your own design
3. Assign transition to game GUI
4. Press

I want all the other buttons not to reset their customized look to the standard when you click

**Basic Informations:**
 - Windows
 - FancyMenu_forge_2.7.2_MC_1.12-1.12.2
 - Forge Version 14.23.5.2860
 - Minecraft Version 1.12.2

**Comment by Keksuccino** [comment]
Hi! Please try to start the game with only FancyMenu + dependencies installed and see if this fixes the issue, thank you!

**Comment by Abbadon999** [comment]
I only installed 4 mods(But the problem remains):
_MixinBootstrap-1.1.0
fancymenu_forge_2.7.2_MC_1.12-1.12.2
konkrete_forge_1.3.3_MC_1.12-1.12.2
ResourceLoader-MC1.12.1-1.5.3

Here are my menu settings - https://www.dropbox.com/s/q3jaj1ycuy1atf2/exported_fm_setup_31-5-2022-16-26-29.rar?dl=0

**Comment by Abbadon999** [comment]
The error was in the parameter - "renderorder", the value was background, and replacing it with foreground, everything was fixed.

**Comment by Keksuccino** [comment]
Well, then this is a bug and I need to fix it, so please don't close this issue.

Thank you for taking your time to find what's causing it!

**Comment by Abbadon999** [comment]
Once again, I apologize for the editing.
In the thread above, I left a link to the layout file, as the problems remained #280 
Even after I left only the necessary mods for FancyMenu

**Comment by Keksuccino** [comment]
This is also something I never noticed, but probably only happens in 1.12.
It's also barely noticeable for me and way more visible in your GIFs. Will see if I can fix it, but it's a strange bug indeed.

**Comment by Keksuccino** [comment]
FancyMenu v3 is a full rewrite, so I'm closing this for now. If it still happens, please open a new issue.
