### ISSUE TITLE
add a comment to the top of the config

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#28]
ability to comment out blocks in the config file

**Comment by Keksuccino** [comment]
You mean comment out customization sections in customization files? That’s already possible with the prefix // ^^

**Comment by kreezxil** [comment]
ok, then have the default config have a comment in it at the top so we can readily realize that's how you comment and thank you for your great work. do you have a patreon?

**Comment by Keksuccino** [comment]
Oh wait, do you really mean adding comments to the CONFIG (config/fancymenu/config.txt)? I don’t know if commenting is possible in the config system, but I’m RELATIVELY sure I’ve added commenting by using // ^^ If that’s not the case, it will be added with the next update! :)

No problem! :) I’m doing this for fun :D 

Yes, I have a patreon! Link: https://www.patreon.com/keksuccino

**Comment by kreezxil** [comment]
cool.

**Comment by Keksuccino** [comment]
Well.. adding commenting to the config system (used for the fancymenu config.txt file) would need to rewrite half of it and sadly I don't have time for that.. I'm really sorry but I will not add this feature.

Sorry..
