### ISSUE TITLE
[Probably All Versions] The button changes its position after you press it

### ISSUE THREAD

**Issue by Abbadon999** [Keksuccino/FancyMenu#280]
The "Multiplayer" button changes its position after opening any menu and returning to the main menu. The "Multiplayer" button returns to the correct position, but after a couple of milliseconds and this is noticeable.

![javaw_4Ni1w9S12n](https://user-images.githubusercontent.com/42169608/171234898-3bfe0a91-4fa7-437f-b16b-b2b73d9535a9.gif)
The strangest thing is that only the button - Multiplayer behaves so "badly" and all the other buttons work well and do not move.

**Basic Informations:**
 - Windows
 - FancyMenu_forge_2.7.2_MC_1.12-1.12.2
 - Forge Version 14.23.5.2860
 - Minecraft Version 1.12.2

**Comment by Keksuccino** [comment]
I think there's something really wrong with your layout in general.
There's no way you find so many obvious bugs in like 1 day and nobody has noticed them before :D

You shared your layout in the other issue, but you removed the file. Please just upload the file, keep it on the file hoster and PLEASE STOP EDITING YOUR POSTS. It's confusing as hell and doesn't help.

**Comment by Keksuccino** [comment]
Well, was able to reproduce this, but again, only in your layout lmao

I don't know why this happens and will need time so find a fix for it, but I know a way to workaround it.
Delete/hide the original Multiplayer button and create a custom button that opens the MP menu.

**Comment by Keksuccino** [comment]
FancyMenu v3 is a full rewrite, so I will close this for now. If it still happens, please open a new issue.
