### ISSUE TITLE
Absorbion info?

### ISSUE THREAD

**Issue by VirtualGaming1** [Keksuccino/FancyMenu#281]
Hi I just want to see if we can get absorption info like health bar and text.
For the Health bar could have an option to cover part of depend of how much absorption comparing of the max health.
As a text way can add as text for detail/info could be "Player absorption" and for me I would do ["Player current health" / "Player max health" + "Player absorption"]

**Comment by Keksuccino** [comment]
Are you sure you're not talking about SpiffyHUD or something? Because FancyMenu has nothing to do with player health :D

**Comment by VirtualGaming1** [comment]
> Are you sure you aren't talking about SpiffyHUD or something? Because FancyMenu has nothing to do with player health :D

forgot about that. opps will make one on that one.

**Comment by VirtualGaming1** [comment]
Moved over to this

https://github.com/Keksuccino/Spiffy-HUD/issues/16
