### ISSUE TITLE
Only Multiplayer/Singleplayer visibility requirement not working

### ISSUE THREAD

**Issue by Ahsumcrafter** [Keksuccino/FancyMenu#282]
I set one of the buttons to only show when in multiplayer and it shows in both singleplayer and multplayer until I reset the condition manually.

**Comment by Keksuccino** [comment]
Hi! What exactly do you mean by "resetting the condition manually"?

**Comment by Keksuccino** [comment]
Not reproducible in Forge 1.19. If you were using an older MC version or mod loader, please tell me. Will close this for now.
