### ISSUE TITLE
New World Menu not compatible with button action?

### ISSUE THREAD

**Issue by zarzwour** [Keksuccino/FancyMenu#287]
**Describe the bug**
I'm replacing the default buttons with my own and i got every button to work except "net.minecraft.client.gui.screen.CreateWorldScreen" says to contact the developer to add functionality. Does anyone else have this issue?

**To Reproduce**
1. Go to The customization screen
2. Create a new button
3. Under button action select "Open GUI" and paste "net.minecraft.client.gui.screen.CreateWorldScreen"
4. Save exit and click the button.

**Expected behavior**
a menu should pop up reading 
"The GUI you want to open either does not exist or isnt supported!
If this is an existing GUI, Please contact the develop;er of fancymenu to add support for it"

**Screenshots**
![image](https://user-images.githubusercontent.com/20389570/172962949-6beed861-5682-4e61-b8b0-12a5d960ee0f.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version fancymenu_forge_2.7.2-1_MC_1.16.2-1.16.5 (1)
 - Forge/Fabric Version 33.0.61
 - Minecraft Version 1.16.5
 - Active Mods konkrete_forge_1.3.3_MC_1.16.2-1.16.5

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.8.0! Thank you for your report!
