### ISSUE TITLE
Publish on Modrinth

### ISSUE THREAD

**Issue by enderger** [Keksuccino/FancyMenu#289]
Currently, the only way to download builds of this mod is through Curseforge. Modrinth, a new platform with an emphasis on open development, might be a good place to consider as a secondary download location. If you wish, I can create a PR with the needed build file updates (a process which is fairly easy due to their gradle plugin), though as of right now payouts are WIP.

(disclosure: I am afilliated with Modrinth)

**Comment by Keksuccino** [comment]
I have to plans to publish my mods on Modrinth atm, sorry.
