### ISSUE TITLE
replace mojang loading with static image

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#29]
Not sure if it can be done but it would be awesome if the loading happened in the background and the animation i chose played over and over until the pack was loaded.

**Comment by Keksuccino** [comment]
The game intro animation is getting loaded too in that loading process ^^ I could prioritize the pre-rendering and stuff for the game intro and render it over the loading screen after it's done, but that would probably be a very laggy slideshow adventure :D 

Tl;dr: Nope, that’s not possible, sorry :/

Only thing I could add is a little preview of the animation that is currently getting loaded ^^

**Comment by kreezxil** [comment]
thought I would ask.

Would it be possible to put a new static screen up that the Mojang Logo and the memory data bars would run on top of?

**Comment by Keksuccino** [comment]
You mean a static background image? That would be possible!

**Comment by kreezxil** [comment]
sweet

**Comment by Keksuccino** [comment]
Well.. this will not work like I wanted it to work..
Would be too much work.. I'm really sorry :/
