### ISSUE TITLE
Add support for Sodium Extra (if not already the case)

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#291]
https://www.curseforge.com/minecraft/mc-mods/sodium-extra

**Comment by Keksuccino** [comment]
I don't talk about the menus of that mod, but if they are compatible :) there will never be support for such custom-looking menus.

**Comment by TheButterbrotMan** [comment]
It seems like. Yes, they are compatible. I am not encountering any crashes with them together.

**Comment by Keksuccino** [comment]
Confirmed to work with FancyMenu v2.8.0 on Fabric 1.19 using:

- sodium-fabric-mc1.19-0.4.2+build.16
- sodium-extra-0.4.5+mc1.19-build.43
- reeses_sodium_options-1.4.3+mc1.19-build.43
