### ISSUE TITLE
No Custom Pause Screen

### ISSUE THREAD

**Issue by TheButterbrotMan** [Keksuccino/FancyMenu#296]
**Describe the bug**
After the update i am unable to make a custom menu at pause screen.

**To Reproduce**
1. Download my modpack.
2. Update FancyMenu
3. Load up the game, load up a world.
4. Checkout pause screen

**Expected behavior**
See my custom screen.
**Screenshots**
![unknown](https://user-images.githubusercontent.com/64548098/174129407-efaf820f-eb9d-402e-a4a5-516456df0968.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version fancymenu_fabric_2.8.0_MC_1.18.2
 - Fabric Version Loader 0.14.7 + fabric-api-0.56.0+1.18.2
 - Minecraft Version 1.18.2
 - Active Mods https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.8.0-1! Thank you for your report!
