### ISSUE TITLE
replace the anvil hammer animation

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#30]
Would like to replace the anvil hammer animation that forge uses during load with my own animation, is this possible?

**Comment by Keksuccino** [comment]
Isn't the anvil only present in older forge versions? Like for MC 1.12?
Sorry, but if that's the case, I won't implement it, because it's too different to alter the MC 1.12 forge loading screen.. Sorry..

**Comment by kreezxil** [comment]
you're right. it's only 1.12.2.
