### ISSUE TITLE
Menu background changes to dirt texture when using background panorama

### ISSUE THREAD

**Issue by BercPlays** [Keksuccino/FancyMenu#305]
When i want to set a panorama the background changes to the minecraft dirt texture,regardless what i do to the background, sometime when i change the background the dirt texture gets blurry.

Image with bug:
![image](https://user-images.githubusercontent.com/64261439/175057659-5853682d-67b1-4011-be4f-d9a4b4979990.png)

Panorama config
![image](https://user-images.githubusercontent.com/64261439/175058234-7eef24c9-d0dd-417a-b220-983e15936706.png)
![image](https://user-images.githubusercontent.com/64261439/175058297-14ffad9a-cfa6-4095-8898-69110f98bf16.png)

 - OS: [Win 10]
 - FancyMenu Version [2.8 (tried downgrading to 2.7.1 didnt work)]
 - Forge Version [14.23.52859]
 - Minecraft Version [1.12.2
 - Active Mods(64) [
![image](https://user-images.githubusercontent.com/64261439/175058851-eaa2eb55-d302-4049-8ccf-4a734d242b51.png)
![image](https://user-images.githubusercontent.com/64261439/175059027-2f9c2488-6901-418e-9077-ed4323a611a1.png)
]

Thanks for reading hope you respond.

**Comment by Keksuccino** [comment]
- Please send me your `.minecraft/logs/latest.log` **after** you encountered the issue
- Please try it with only FancyMenu + dependencies installed
- Please send me the `properties.txt` file of your panorama

**Comment by BercPlays** [comment]
Sorry for being late but [here it is](https://www.dropbox.com/s/enxe8u536labcc9/latest.log?dl=1) 

[properties.txt](https://www.dropbox.com/s/a3fv0hj4e82620b/properties.txt?dl=1)

And i forgot to say in the original post that the panorama worked before.

**Comment by BercPlays** [comment]
Sorry for being late but [here is it](https://www.dropbox.com/s/enxe8u536labcc9/latest.log?dl=1).

[properties.txt](https://www.dropbox.com/s/a3fv0hj4e82620b/properties.txt?dl=0)

I forgot to say in the original post that the panorama worked before.

**Comment by Keksuccino** [comment]
Thank you! But you have a ton of mods installed, so please try it with only FancyMenu + dependencies installed.

**Comment by Keksuccino** [comment]
This is not reproducible in a clean 1.12 instance, so it's most probably a compatibility issue.

Will close this for now, but if it still happens without other mods installed, please comment here or open a new issue! Thank you very much!
