### ISSUE TITLE
[Fabric 1.19] Crash when adding player entity element

### ISSUE THREAD

**Issue by Eatham532** [Keksuccino/FancyMenu#317]
**Describe the bug**
Fancy Menu crashes minecraft

**To Reproduce**
1. Create a new layout
2. Add a Player Entity
3. Observe the crash

**Expected behavior**
The player entity to be added 

**Crash Log**
https://bytebin.lucko.me/juk99fLjuK

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.9.1
 - Forge/Fabric Version: Fabric 0.14.8
 - Minecraft Version 1.19
 - Active Mods: 
![image](https://user-images.githubusercontent.com/78714349/176982324-510065f2-51c9-4de0-833d-d7271f37ac17.png)

**Comment by Keksuccino** [comment]
Please try it with only FancyMenu + dependencies installed and see if this fixes the issue.

**Comment by Eatham532** [comment]
Sorry, I think it was because of a mod incompatibility. I did have Inventory Hud and that was an incompatibility. Would you like to see my list of mods?

**Comment by Keksuccino** [comment]
It works fine for me, so it probably really is a compatibility issue. No need for the mod list, but thank you very much!

Does it work without Inventory HUD installed?

**Comment by Keksuccino** [comment]
Will close this for now, but if it still doesn't work when you only have FancyMenu + dependencies installed, please comment here or open a new issue! Thank you very much!
