### ISSUE TITLE
1.18.2 options background freeze when back to main menu

### ISSUE THREAD

**Issue by Mark1ed** [Keksuccino/FancyMenu#318]
if I, for example, go into multiplayer mode and go back to the main menu, I will not have a menu, just a option background (dirt)

1. go from main menu to any button (settings, multiplayer, e.t.c)
2. back to main menu
3. dirt background (bug)
but at the same time, all buttons work, including reloading the menu, if you reboot, everything will work fine, but I would not like to click on the reboot button every time when it is not visible

**Screenshots**

**Basic Informations (please complete the following information):**
 - Windows
 - FancyMenu Version 2.9.1
 - Fabric Version [e.g. 31.2.24]
 - Minecraft 1.18.2
[config.txt](https://github.com/Keksuccino/FancyMenu/files/9032731/config.txt)
[latest.log](https://github.com/Keksuccino/FancyMenu/files/9032732/latest.log)
P.s. I'm bad in english and in many places I used a translator.

**Comment by Keksuccino** [comment]
Please try it with only FancyMenu + dependencies installed and see if this fixes your issue.

**Comment by Mark1ed** [comment]
Yes! it's helped! thank you, but I want to see what mod or mods your mod conflicts with. If I see which mod is causing this bug, I'll let you know.

**Comment by Mark1ed** [comment]
This bug is caused by the 'Slight' Gui Modifications mod. This mod creates animations for the settings menu, etc. So, to solve this error, you need to remove this mod. Or we will wait for an update in which there will be compatibility between these mods. Thanks for helping.
