### ISSUE TITLE
Can you please add a selection of GUIs that has the IDs for the Menu?

### ISSUE THREAD

**Issue by NichoGamerTv** [Keksuccino/FancyMenu#328]
Hello. I wanna to have a custom gui but it's hard to remember what ID is to use like for example Resource Packs and I tried many attempts but it doesn't work. So please, can you add it to make it easier to navigate to different menus?

**Comment by Keksuccino** [comment]
Do you want an easy way to get the identifier of a menu? If so, click on **Tools -> Menu Info** to show the identifier of the current menu in the top-left corner. Then **left-click** the identifier to copy it to the clipboard.

**Comment by NichoGamerTv** [comment]
oh...

**Comment by Keksuccino** [comment]
So it's solved? :D

**Comment by NichoGamerTv** [comment]
I have 0 IQ 😂

**Comment by Keksuccino** [comment]
Nah, you just missed a setting :) It happens.

**Comment by NichoGamerTv** [comment]
I mean it happens when someone first using the mod like me.

**Comment by NichoGamerTv** [comment]
It's not working
