### ISSUE TITLE
need addClickSound

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#33]
As in the following section where the sound plays when hovered, need one for the sound playing when clicked.

### addhoversound

Add a short sound to default buttons which will be played when the button is getting hovered.

| Variable | Assignable value(s) | Mandatory | Description | Examples |
| --- | --- | --- | --- | --- |
| identifier | Button key or id | Yes | The button identifier. This can be the button ID (written as `%id=<button id>%`) or its key. Both can be found by using the "Button Info" feature in menus. Just hover over a button with your mouse to get useful informations. | identifier = %id=1%
\-\-\-\-
identifier = the.button.key |
| path | The sound path | Yes | The path to the hover sound. **Only WAV files are supported!** | path = sounds/mysound.wav |

**Comment by Keksuccino** [comment]
Will try to add this in the next update!

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.5! Thank you for your report!
