### ISSUE TITLE
[Fabric] Crash when adding player entity element while Bobby (mod) is installed

### ISSUE THREAD

**Issue by videosambo** [Keksuccino/FancyMenu#333]
**Describe the bug**
I just updated FancyMenu to 2.10.0 for fabric and when starting the game, I realized that my player character that I did add for my main menu has been disappeared. After that I tried to add my player character to current layout using new Player Entity button and then game crashes.

**To Reproduce**
1. Go to 'Current Menu' >'Layouts' > 'Manage Layouts' and click your layout
2. Go to 'Element' > 'New'
3. Click 'Player Entity'
5. Game crashes

**Expected behavior**
By clicking Player Entity, new player entity should appear to menu.

**Crash Log**
[Pastebin link for crashreport](https://pastebin.com/UMUFDMAP)

**Screenshots**
![image](https://user-images.githubusercontent.com/29887391/178139300-83a26d3c-d0ff-4f19-b67f-3e34bac6dd91.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.10.0
 - Fabric Version: Loader 0.14.8 Api 0.57.0
 - Minecraft Version 1.19.0
 - Active Mods:
 

> 3dskinlayers-fabric-1.4.7-mc1.19, appleskin-fabric-mc1.19-2.4.0, architectury-5.8.29-fabric, auudio_fabric_1.0.3_MC_1.19, badpackets-fabric-0.1.2, balm-fabric-4.3.0+0, BetterF3-1.3.1-Fabric-1.19, BetterThirdPerson-Fabric-1.19-1.8.1, BiomeWeatherEffects-3.4.9, blur-2.6.0, Boat-Item-View-Fabric-1.19-0.0.3, bobby-4.0.0, boosted-brightness-2.1.2+1.19, c2me-fabric-mc1.19-0.2.0+alpha.8.2, camerautils-1.19-1.0.0, chesttracker-1.19-1.1.17, ClearDespawn-fabric-1.19-1.1.8, clickthrough-1.19-fabric0.53.3-0.4, cloth-api-4.0.65, cloth-config-7.0.72-fabric, continuity-2.0.0+1.19, Controlling-fabric-1.19-10.0+2, craftingtweaks-fabric-1.19-15.0.1, custom-crosshair-mod-v1.5.0-fabric-mc1.19, DamageTilt-1.19-fabric-0.1.2, drippyloadingscreen_fabric_1.6.4_MC_1.19, easiercrafting-1.19-fabric0.53.3-1.7, eating-animation-1.8.1, extrasounds-2.3.1+1.19, fabric-api-0.57.0+1.19, fallingleaves-1.12.1+1.19, fancymenu_fabric_2.10.0_MC_1.19, indium-1.0.6+mc1.19, InventoryHUD-fabric-[1.19]+-3.4.2, InventoryProfilesNext-fabric-1.19-1.5.3, iris-mc1.19-1.2.5, itemscroller-fabric-1.19-0.16.0, konkrete_fabric_1.3.3-3_MC_1.19, lambdynamiclights-2.1.2+1.19, lazydfu-0.1.3, light-overlay-7.0.0, litematica-fabric-1.18.2-0.11.3, litematica-fabric-1.19-0.11.3, lithium-fabric-mc1.19-0.8.0, logical_zoom-0.0.15, malilib-fabric-1.19-0.12.1, maptooltip-fabric-1.19-2.0.1, minihud-fabric-1.19-0.22.0, modmenu-4.0.0, NoFog-1.3.0_1.16.5-1.19-fabric, notenoughanimations-fabric-1.6.0-mc1.19, physics-mod-2.7.6-mc-1.19-fabric, plasmovoice-fabric-1.19-1.2.17, PresenceFootsteps-1.6.0, reeses_sodium_options-1.4.3+mc1.19-build.43, rer-2.6.0, RoughlyEnoughItems-9.1.503, sheepconsistency-1.0.4, shulkerboxtooltip-3.0.10+1.19, sodium-extra-0.4.5+mc1.19-build.43, sodium-fabric-mc1.19-0.4.2build.16, starlight-1.1.1+fabric.ae22326, torohealth-1.19-fabric-1, tweakeroo-fabric-1.19-0.13.3, visuality-0.5.0, waveycapes-fabric-1.2.0-mc1.19, worldedit-mod-7.2.11-beta-01, wthit-fabric-5.5.1, XaerosWorldMap_1.24.0_Fabric_1.19, Xaeros_Minimap_22.10.1_Fabric_1.19

**Comment by Keksuccino** [comment]
Please start the game with only FancyMenu + dependencies and see if this fixes the issue, thank you very much.

**Comment by Keksuccino** [comment]
It's an incompatibility with [Bobby](https://www.curseforge.com/minecraft/mc-mods/bobby).

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.11.0! Thank you for your report!
