### ISSUE TITLE
SinglePlayer/Multiplayer Background Image not showing

### ISSUE THREAD

**Issue by MeinKraft** [Keksuccino/FancyMenu#34]
**Describe the bug**
If you add a background to the Multiplayer screen, it does not show outside of edit mode

**To Reproduce**
1. Goto Multiplayer GUI
2. Add a background image
3. Save and Close the Edit Mode

**Expected behavior**
The background image to show on the Multiplayer GUI.  It does however work for the Options menu.  

**Screenshots**
https://imgur.com/a/MFgkcT7

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version fancymenu_1.3_MC_1.14.4
 - Forge Version 28.2.18
 - Minecraft Version 1.14.4

**Comment by Keksuccino** [comment]
Will be fixed in the next update! :)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.4!
