### ISSUE TITLE
Incopmability with Immersive Fx

### ISSUE THREAD

**Issue by Smartin-b** [Keksuccino/FancyMenu#340]
Crash before reaching the Main Menu

 - OS: Windows
 - fancymenu_forge_2.10.1_MC_1.18.2.jar 
 - forge - 40.1.0
 - ImmersiveFX 1.0.0gm 1.18.2.jar

CrashLog:
https://gist.github.com/Smartin-b/633b44e3613678854189ac039745ae67

Immersive Fx Issue
https://github.com/Y3Z0N/ImmersiveFX/issues/17

**Comment by Keksuccino** [comment]
- Please send me your full `.minecraft/logs/latest.log` AFTER the crash happened
- If you have the audio extension installed, please try it without the audio extension and Auudio (the dependency of the audio extension)

**Comment by Smartin-b** [comment]
Sorry to bothered you, additional testing showed that this is an issue of ImmersiveFx, not FancyMenu.
It seems that whenever something delays or throws an Error or has a missing dependency ImmersiveFx WILL crash the game instantly with this Error.

**Comment by puppygruel** [comment]
sorry for asking, but how do you fix this? is there a way?

**Comment by Smartin-b** [comment]
Immersive FX throws an error, but its caused by other mods,
Remove Immersive FX to see the Actual correct error log
