### ISSUE TITLE
Fullscreen Displaying Bug

### ISSUE THREAD

**Issue by NOYBss** [Keksuccino/FancyMenu#35]
Button display locations change when you go fullscreen or vice versa. I added images to show.

Fullscreen
![image](https://user-images.githubusercontent.com/61475257/84501168-b04fb980-acbe-11ea-878a-ae49d298d392.png)

Not Fullscreen
![image](https://user-images.githubusercontent.com/61475257/84501229-ccebf180-acbe-11ea-9622-f4876b8a82b8.png)

 - OS: Windows
 - FancyMenu Version: 1.3
 - Forge Version: 14.23.5.2854
 - Minecraft Version 1.12.2

**Comment by Keksuccino** [comment]
I think you're using the wrong orientation. Your buttons should have the "bottom-right" orientations if you want them to stay in the bottom-right corner :)

**Comment by NOYBss** [comment]
Thank you, it looks like it was the problem.
