### ISSUE TITLE
FancyMenu not detect jpg/png or others 1.18.2 / forge 40.1.60

### ISSUE THREAD

**Issue by BlackJellyBeans** [Keksuccino/FancyMenu#355]
When I try to add images or animations when I explore the .minecraft folder, the PNG/JPG files do not appear

**Comment by Keksuccino** [comment]
Not reproducible. You probably put your images in a wrong directory. They need to be in your MC instance folder.
Keep in mind that this is not always `.minecraft`.

**Comment by BlackJellyBeans** [comment]
thanks c:
