### ISSUE TITLE
minecraft title overlays the fancy menu one.

### ISSUE THREAD

**Issue by Nathan200608** [Keksuccino/FancyMenu#357]
I know you have gotten reports like this twice before, but I made an account specifically to tell you that the solution you have provided cannot help me. I am using the cave animation and the minecraft title is on top of the animation title, in the previous posts you have suggested looking in the config for the words "hide logo".

"hidelogo" is not a word in the config, let alone the word "hide"
not the _most_ urgent matter, yet I would appreciate the help.
cheers.

**Comment by Keksuccino** [comment]
These elements are now editable in the editor. Just create a new layout, hide all elements you don't need/want and save it :)
