### ISSUE TITLE
[1.18.2] Better Mods Button conflict

### ISSUE THREAD

**Issue by Temm4ancki** [Keksuccino/FancyMenu#359]
(If so, sorry for my English. I used a translator.)
**Describe the bug**
My menu just disappeared and was replaced with... a panorama of the standard menu without the yellow text.
Then I started to double-check the mods and realized that it was the Better Mods Button.

**To Reproduce**
1. Make your own menu.
2. Turn it on
3. See error

**Expected behavior**
Cave animation and the inscription "D&P Edition" should have been included

**Game Log**
https://gist.github.com/Temm4ancki/e3bb222d2c12d06ba212cea8218e23f4

**Screenshots**
Customization OFF
![image](https://user-images.githubusercontent.com/109782178/180369022-f8ec09dd-08c0-4dd1-b9f9-1ce71e72a169.png)

Customization ON and my menu disabled
![image](https://user-images.githubusercontent.com/109782178/180369097-93fddce7-7b2b-4714-ad37-0a74382c4fa5.png)

Customization ON and my menu enabled
![image](https://user-images.githubusercontent.com/109782178/180369135-fbd14c53-57c1-40ca-a549-bdbfdff03ee7.png)

My menu in edit:
![image](https://user-images.githubusercontent.com/109782178/180369190-a86e847c-1e14-4319-9665-5981c2f95df4.png)

Without mod:
![image](https://user-images.githubusercontent.com/109782178/180372263-43d593a8-a22e-4b81-9a33-17656891748b.png)

**Basic Informations**
 - OS: [Windows 11]
 - FancyMenu Version [2.11.1]
 - Forge Version [40.1.67 and 40.1.68] (Tested 2 different forge thinking that the problem is in the updated one)
 - Minecraft Version [1.18.2]
 - Active Mods [A LOT OF. The problem is only in Better Mod Button]

**Comment by Keksuccino** [comment]
I read like 15 reports about this in the last 24h, so I think a recent update of Better Mods Button created this incompatibility. Most parts of FancyMenu work in a very mod-friendly way, so if a mod is incompatible with it, it's probably the other mod that needs to fix things.

That's probably also the case here, so I recommend you to open an issue in the other mod's GitHub repo.
