### ISSUE TITLE
Icons (titlebar and taskbar)

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#36]
## Describe your idea
**It's The Little Things** and **Randompatches** both have icons for titlebars and taskbars. I'm thinking if FancyMenu had those too, I could get rid of at least one mod. Also you could do them one better.

Linux doesn't care what size the source image is for the title bar and will scale it according to the Desktop Environment.

Mac also doesn't care as it is based on Darwin a FREEBSD clone, this is straight up Unix, not Linux, but they're related. However, Mac does prefer the 256x256 icon, or rather will re-render the titlebar icon as such.

Windows cares very much. Too much so. Windows wants the title bar icon to be either 32x32 or 16x16, anything else will crash it on either of the two mods I mentioned.

Where your mod can close this gap.

The pack dev would supply one image for the titlebar icon, let's say our default 400x400 logo from our packs. Your mod would then scale that one image file for whichever operating system it finds itself running on and as such choose the highest rendition.

## Does it frustrates you to not already have this feature in the mod?
No. It's not infuriating at all.

## Did you change all the headings to hashtag derived headings plus add a third one?
- [x] yes, I did.
- [ ] no, I did not.

**Comment by Keksuccino** [comment]
I will try to add this in the next update :)

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.4!
