### ISSUE TITLE
Menu bug with VanillaFix

### ISSUE THREAD

**Issue by CalaMariGold** [Keksuccino/FancyMenu#361]
Issue is detailed here: https://github.com/CalaMariGold/TREPIDATION/issues/4

I'm not sure if this is on VanillaFix's side or not, but I figured I would report it here. Let me know if you need any other information. Thanks!

**Comment by CalaMariGold** [comment]
I checked the log during this issue and got this 


```
[16:25:03] [Client thread/ERROR]: ########## GL ERROR ##########
[16:25:03] [Client thread/ERROR]: @ VanillaFix GUI Loop
[16:25:03] [Client thread/ERROR]: 1280: Invalid enum
[16:25:10] [Client thread/INFO]: [FANCYMENU] Updating animation sizes..
```

**Comment by Keksuccino** [comment]
VanillaFix always had problems with FancyMenu, that's why it's listed as incompatible with FancyMenu:
http://fm.keksuccino.com/en/incompatibility-list

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
