### ISSUE TITLE
Conflict with "Essential" mod

### ISSUE THREAD

**Issue by bladehorton** [Keksuccino/FancyMenu#363]
Turning on my customizations disables any extra buttons added by the mod from showing up and changed default buttons revert to normal state

BEFORE:
![image](https://user-images.githubusercontent.com/96292503/181213455-2188e93e-f27d-4abb-8ddf-54bf9fc7de53.png)

AFTER
![image](https://user-images.githubusercontent.com/96292503/181213662-ece2fab1-c358-4f0c-b1c2-8949774ee806.png)

 - OS: Linux Mint
 - FancyMenu Version 2.11.1
 - Fabric Version 0.11.0
 - Minecraft Version 1.19
 - Active Mods: Essential (client)

**Comment by Keksuccino** [comment]
http://fm.keksuccino.com/en/incompatibility-list
