### ISSUE TITLE
unicode fonts warning UI always exists

### ISSUE THREAD

**Issue by TRLWeiss** [Keksuccino/FancyMenu#365]
When set "force using unicode fonts" option to ON, there would be a red warning UI appearing on the left top of screen. However, chinese players are quite familiar with unicode fonts, and fancymenu UI works well with unicode fonts. So they prefer to unicode fonts than original one. 
There's no way to turn the warning UI off. What's more, when the player is opening their inventory, the warning would appear. It hides some useful buttons, and some functions may work not well with the warning UI. Can players hide the warning UI and use the unicode fonts at the same time?
![image](https://user-images.githubusercontent.com/33795783/181315837-6d48a80e-0ada-43f0-b018-c2236a7f32c9.png)

Basic Informations:
 - OS: Windows 10
 - FancyMenu Version: 2.6.4_MC_1.16.2-1.16.5
 - Forge/Fabric Version: 36.2.39
 - Minecraft Version: 1.16.5
 - Active Mods: Optifine

**Comment by Keksuccino** [comment]
When you hide the customization overlay (customization controls) in the settings, the warning will disappear too.

http://fm.keksuccino.com/en/210x/mod-settings
