### ISSUE TITLE
'Incompatible Video Card Driver' bug

### ISSUE THREAD

**Issue by tudubucket** [Keksuccino/FancyMenu#366]
**Describe the bug**
nothing to describe, everything just in reproduce fields

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Put the mod in
2. Load Minecraft, it still working fine in the 1st time
![image](https://user-images.githubusercontent.com/106295287/181465585-12c6d40e-5c9f-41ab-9eb6-4b7384319046.png)

3. Exit Minecraft, restart Window
4. Start Window & start Minecraft
5. See error

**Expected behavior**
idk

**Game Log**
https://gist.github.com/tudubucket/f3ec3473418b081b66f41982654a5312

**Screenshots**
![image](https://user-images.githubusercontent.com/106295287/181463814-087dac82-5ea0-4060-9a28-443d2fa5e430.png)

**Basic Informations (please complete the following information):**
 - OS: Window
 - FancyMenu Version 2.11.1
 - Fabric Version 0.51.1
 - Minecraft Version 1.18.2
 - Active Mods 
	- alternate-current 1.4.0
	- architectury 4.5.75
	- baritone 1.18.2-SNAPSHOT via meteor-client
	- betterf3 1.2.5
	- caffeineconfig 1.1.0 via sodium-extra
	- clientarguments 1.3.1 via clientcommands
	- clientcommands 2.6.6
	- clientcommands-scripting 1.3.2 via clientcommands
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62
	- clumps 8.0.1
	- com_github_19misterx98_seedcrackerx_seedcrackerx-api master-SNAPSHOT via meteor-rejects
	- com_github_llamalad7_mixinextras 0.0.10 via debugify
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- cullleaves 2.3.2
	- dark-loading-screen 1.6.11
	- debugify 1.11.0
	- e621-hud 0.1
	- entityculling 1.5.1
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via modmenu
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.8
	- fancymenu 2.11.1
	- fastload 1.1.0+1.18.2
	- ferritecore 4.2.1
	- inventoryhud 3.4.2
	- iris 1.2.5
	- java 17
	- konkrete 1.4.0
	- krypton 0.1.9
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- litematica 0.11.3
	- lithium 0.7.10
	- loadmyresources 1.0.1
	- malilib 0.12.1
	- memoryleakfix 1.18.2-0.3.5
	- meteor-client 0.4.9
	- meteor-crash-addon 0.5
	- meteor-rejects 0.2
	- meteor-tweaks 2.0.0
	- meteorplus 1.1
	- midnightlib 0.2.9 via cullleaves
	- minecraft 1.18.2
	- modmenu 3.2.3
	- multiconnect-api 1.5.10 via clientcommands
	- notenoughcrashes 4.1.6+1.18.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_yaml_snakeyaml 1.30 via viafabric
	- pride 1.1.0+1.17 via lambdynlights
	- reeses-sodium-options 1.4.3+mc1.18.2-build.42
	- roughlyenoughitems 8.3.501
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.5+mc1.18.2-build.42
	- spruceui 3.3.0+1.17 via lambdynlights
	- starlight 1.0.2+fabric.89b8d9f
	- vector-addon 0.3.4
	- viabackwards 4.3.0
	- viafabric 0.4.7+5-main
	- viafabric-mc118 0.4.7+5-main via viafabric
	- viarewind 2.0.2
	- viaversion 4.3.0 via viafabric
	- vmp 0.2.0+beta.3.17
	- voxelmap 1.18.2-1.11.1
	- worldedit 7.2.10+1742f98
	- xaerominimap 22.9.3
	- xaeroworldmap 1.23.3

**Edit: I have tested again, that's not a bug from the FancyMenu mod, and it isn't a mod incompatible too. The problem started from the config.**

**Comment by Keksuccino** [comment]
Please try the following:

- Start the game with only FancyMenu + dependencies, to see if it's a mod conflict/if it's caused by another mod
- Try it without FancyMenu and check if it still happens
- If it still happens, try it without any mods installed
- Update your video drivers
- Use another launcher (also try the vanilla one)

**Comment by Keksuccino** [comment]
Just saw the edit, glad you were able to identify the issue!
Your menu looks beautiful btw! :)
