### ISSUE TITLE
I can't see the changes

### ISSUE THREAD

**Issue by xiakkto** [Keksuccino/FancyMenu#368]
I went to update the FancyMenu mod today, but it doesn't show anything.
![image](https://user-images.githubusercontent.com/109633750/181721107-6f87a16f-0703-4ae9-94bc-1f8a9404a9cf.png)

Then when I switch to the previous version it shows again.

![image](https://user-images.githubusercontent.com/109633750/181725030-9c91e0c9-9661-40eb-beed-eb4402f95777.png)

-Minecraft Version [1.16.5]
-Forge Version [36.2.39]
-FancyMenu Version [2.11.1]

**Comment by Keksuccino** [comment]
This looks like you also updated other mods.
What is the version you've used before you updated to v2.11.1?

If you have other mods installed, please start the game with only FancyMenu + dependencies installed.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
