### ISSUE TITLE
raise/lower

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#37]
## Describe your idea
While editing, when you add new stuff, and then select its orientation. That item will go on top of other assets in most cases. Having a right click raise/lower feature would be helpful in trying to grab that new asset and move just it and not the original asset.

## Does it frustrates you to not already have this feature in the mod?
- [x] Yes
- [ ] No[

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.4!
