### ISSUE TITLE
1.16.5 Win FancyMenu loading error (Failed to load correctly)

### ISSUE THREAD

**Issue by OzdorMiZ** [Keksuccino/FancyMenu#370]
An error occuring while loading. It doesn't crash the client, but it don't let me enter the main menu. "FancyMenu has failed to load correctly (java.lang.ExceptionInInitialiserError:null). This error occured when i made a custom menu and relaunched client.

**Steps to reproduce the behavior (e.g.):**
1. Make a custom menu
2. Relaunch the game
3. See error

**Expected behavior**
I expected the mod to load correctly to continue making my custom menu for a modpack.

**Game Log**
https://gist.github.com/OzdorMiZ/d5bbcaf3a5ed68aa9aced176b3f8423e

**Basic Informations:**
 - OS: Windows 10
 - FancyMenu Version: 2.12.0_MC_1.16.2-1.16.5
 - Forge/Fabric Version 36.2.39
 - Minecraft Version 1.16.5
 - Active Mods: (Too many mods, created a gist) https://gist.github.com/OzdorMiZ/d748b16b3a754b4ddf2d77e1466123e9
P.S. Tell me if there are too many mods for you to solve this issue

**Comment by Keksuccino** [comment]
FancyMenu and Create are currently not fully compatible. You probably tried to customize a GUI of the Create mod, right?
You will need to manually remove that GUI from the list of customizable menus, to fix this crash.

Close the game, then open the `config/fancymenu/customizablemenus.txt` file and search for the Create GUI(s). Remove them from the list and save the file.

**Comment by OzdorMiZ** [comment]
Thank you for your help! I love your mod btw, it's very easy and usable
