### ISSUE TITLE
Particles? 

### ISSUE THREAD

**Issue by netcore10** [Keksuccino/FancyMenu#373]
**Describe your idea**
I saw this mod https://www.curseforge.com/minecraft/mc-mods/particle-title-menu

and was wondering if a pseudo feature like it would be possible for fancy menu. It's a bit outdated but it get's my request across.

**Comment by Keksuccino** [comment]
Hi! Thank you for your suggestion!

I decided to not add this, since it wouldn't be used by many people and is just not worth the work.

Maybe somebody can make this as an extension mod for FancyMenu.

**Comment by netcore10** [comment]
sad but fair. I'm just a sucker for mouse interaction.
