### ISSUE TITLE
How can I disable the customization options after my menu is complete?

### ISSUE THREAD

**Issue by YassevZriona** [Keksuccino/FancyMenu#374]
This applies for both drippy loading screen and fancy menu... how can I disable the options in the main menu on the top which allow to edit the menu. Since the main menu is complete now I would like to remove those options from the screen

I asked this here since the discord link was not working...

**Comment by YassevZriona** [comment]
Found it in FAQ.... but can I ask about the discord? is there any?

**Comment by Keksuccino** [comment]
http://discord.keksuccino.com :)
