### ISSUE TITLE
[Not really a bug] Why when I change the size of the button (let's say the width) the button expands in length as well? How to turn it off?

### ISSUE THREAD

**Issue by OzdorMiZ** [Keksuccino/FancyMenu#386]
- OS: Win10
 - FancyMenu Version: V2.12.2 MC
 - Forge Version: 14.23.5.2860
 - MC Version: 1.12.2

Sorry for bothering you with this, but i just can't edit my menu.

**Comment by Keksuccino** [comment]
Do you mean the **height** changes when changing the width? This should only happen when you press SHIFT while resizing an element. Maybe your SHIFT key is stuck or you have a mod installed that messes with key presses?

http://fm.keksuccino.com/en/2-12-X/customization/layout-editor#h-58-shift-click

**Comment by Keksuccino** [comment]
Closed because no response and not really a bug. If you still have questions about the mod, please join [my Discord](http://discord.keksuccino.com), thank you very much! :)
