### ISSUE TITLE
[1.18.2] Issues with MixinLocalPlayer when chatting spams stack traces

### ISSUE THREAD

**Issue by itsdinkd** [Keksuccino/FancyMenu#387]
**Describe the bug**
When i ype a command I receive a whole stack trace from a Mixin fancymenu is using. logs below.

https://github.com/Keksuccino/FancyMenu/blob/forge-1.18/src/main/java/de/keksuccino/fancymenu/mixin/client/MixinLocalPlayer.java coming from this

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Use latest fancy menu
2. type a command
3. see spam in logs

**Expected behavior**
Not to send stack traces when typing

**Game Log**
Latest: https://gist.github.com/itsdinkd/00a37dc7726833f43d007ce916345cac
Debug: https://gist.github.com/itsdinkd/ff913fca4a6a0296e627589603bd2be0

**Screenshots**
![image](https://user-images.githubusercontent.com/35115304/193426950-8d1e9569-4223-4dcf-a963-62789e503f0d.png)

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows]; W11
 - FancyMenu Version [e.g. 0.2]; 2.12.2
 - Forge/Fabric Version [e.g. 31.2.24]; 40.1.80
 - Minecraft Version [e.g. 1.15.1]; 1.18.2
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] too many to list... AQM3 is the modpack, however, I am working on a unreleased update.

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.12.2-1! Thank you!
