### ISSUE TITLE
Disable menu bar by default

### ISSUE THREAD

**Issue by wafflebot2143** [Keksuccino/FancyMenu#389]
Is there any way that I can set the menu bar at the top of the screen to be hidden by default when starting up the game? Any assistance would be appreciated.

**Comment by Keksuccino** [comment]
Press **CTRL + ALT + C** to toggle the customization UI. When you export the setup, the config will also get exported which contains the UI visibility option, so others will start the game with disabled UI by default :)

**Comment by Keyhankemal2022** [comment]
is there a way to undo this?
