### ISSUE TITLE
Undo & Redo

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#39]
**Describe your idea**
While editing the layout. Sometimes the wrong element gets moved, or I want to unmove an element. If we hand undo and redo, those choices and thus positions would be an easy thing to do.

**Does it frustrates you to not already have this feature in the mod?**
Is your feature something you can't live without or is it just something that would be cool to see in FancyMenu? 
- [x] YES

**Comment by Dekamir** [comment]
I still do CTRL-Z by reflex.

**Comment by kreezxil** [comment]
yes to be clear the keys ctrl z for undo and ctrl y for redo would be awesome af, don't need actual buttons for that

**Comment by Keksuccino** [comment]
I understand that undo and redo functions would be awesome, I thought about these long ago and would love to add them, but implementing this in a good way so it feels like you're editing something in PS or similar programs is intense. It is still on my to-do list, but will probably not in the next update. ^^

**Comment by kreezxil** [comment]
you're going to want to have a command stack to do it right

**Comment by kreezxil** [comment]
where each action the designer does is pushed on to the stack, so that ctrl
z removes the last action and ctrl y puts it back on the stack. You're
going to need to 2 stacks actually. The easiest implementation will be the
2 stacks are never more than 2 deep. However, to make it cool and to leech
users from Custom Main Menu and unlimited stack on both sides would be
great. Granted when you hit save, the stack is cleared and the current
state is it for the menu.

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.5! Thank you for your report!
