### ISSUE TITLE
Cannot load worlds with mod installed

### ISSUE THREAD

**Issue by MysticcX** [Keksuccino/FancyMenu#390]
**Describe the bug**
When FancyMenu is installed loading a world results in a crash. I set up a slideshow and formatted the properties correctly and then once I was done I went to go load my world and every time it would crash. I also added/updated a handful of mods when I added FancyMenu so I thought the crashes were due to one of them but then I switched the updated files for their previous versions and my client would still crash. FancyMenu was the last mod I suspected but once removed my world would load just fine
**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Make/save/format slideshow
2. Load Slideshow
3. Load singleplayer world
4. (Will crash after shortly after world loading reaches 100%)

**Expected behavior**
I expected the game to load and have no problems as its pretty much just cosmetic changes to the menu but game would crash until mod was removed.
**Game Log**

[Crash-1(Latest)](https://pastebin.com/U2Yxa27a)

[Crash-2](https://pastebin.com/zmRbyeVv)

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 2.12.2
 - Fabric Version: Loader v0.14.9 - API v0.61.0
 - Minecraft Version 1.19.2
 - Active Mods:
<details>
Additional Additions 5.0.2
Additional Structures 4.1.0
Adorn 3.6.1+1.19
Advanced Movement 22.8.18
Advanced Reborn 1.0.8
AdventureZ 1.4.16
Ambient Environment 8.0+3
Amethyst Equipment 1.0.5
Animal Feeding Trough 1.0.3
AppleSkin 2.4.1+mc1.19
Architectury 6.2.43
ArmorStatues 4.0.0
AttributeFix 17.1.2
ARRP 0.6.4
AutosmeltEnchant 1.1.0
Awesome dungeon 3.0.0
Awesome dungeon nether 3.0.0
Awesome dungeon the end 3.0.0
Balm 4.5.2+0
BCLib 2.1.0
BedBenefits 9.1.2
Better Animals Plus 1.19-11.0.7
Better Beds 1.2.0
Better End 2.1.0
Better Nether 7.1.0
BetterF3 1.3.2
Biome Makeover 1.19.2-1.5.12
Biome Particle Weather 4.0.2
BitsAndChisels 2.7.0
Blockus 2.5.2+1.19.2
Blossom 1.0.5
Boat Item View Fabric 0.0.4
BoatContainer 1.2.2
Bookshelf 16.1.5
BottleYourXP 2.1
Building Wands 2.6.3
Cardinal Components API 5.0.1
Carrier 1.11.0
Charm 4.2.2
CHAS 1.9
ChickensShed 1.3.3
Chimes 1.1.4
Chisel Refabricated 1.4.6
ChoiceTheorem's Overhauled Villages 3.1
ClickThrough 1.19.1-fabric0.58.5-0.4
Cloth Config v8 8.1.77
Clumps 9.0.0+11
Collective (Fabric) 4.52
Comforts 6.0.0+1.19.2
Compostable Rotten Flesh 1.0.0
Continuity 2.0.1+1.19
CoralReef 1.0.2
Crawl 0.11.2
Croptopia 2.1.0
Cull Leaves 2.3.4
Dark Enchanting 1.0.0+1.19.1
DarkPaintings 13.1.2
DarkUtilities 13.1.2
DashLoader 4.1.3
Dawn API 3.5.0
Decorative Blocks 3.0.0
Deeper And Darker 1.0.2b-fabric
Dehydration 1.3.0
Dramatic Doors (Fabric) 1.19.2-1.3.1
DurabilityViewer 0.58.0
DynamicSurroundingsRemastered 0.1.0
Eating Animation 1.9
Ecologics 2.1.9
EdenRing 0.6.4
Effective 1.2.2
Emerald Tools 1.4.30
EMI 0.4.0+1.19
Enchanted Vertical Slabs 1.5
EnchantmentDescriptions 13.0.1
Enderscape 0.3.5-1.19.1
EndGoblinTraders 1.5.1
EnhancedAttackIndicator 1.0.4
EntityCulling-Fabric 1.5.2-mc1.19
Equipment Compare 1.3.1
Exline's Furniture 2.3.0
ExtendedArmorBars
Extended Bone Meal (Fabric) 2.0
Extended Drawers 1.3.3+mc.1.19.1
Fabric API 0.61.0+1.19.2
Fabric Enchantments 0.8.1
FabricLanguageKotlin 1.8.3+1.7.10
FabricLanguageScala 1.10+213.6
Falling Leaves 1.12.2+1.19.2
FallingTree 3.10.0
Farsight Mod 1.19.1-2.0
Fast Load 1.2.0
Flesh2Leather 1.0.3+1.19
ForgeConfigAPI Port 4.2.6
Forgetmechunck 1.0.4
Gear Reborn 1.19-0.1.15
Geckolib 3.1.18
Glass Doors 3.1.0-beta.1+1.19
GoblinTraders 1.5.2
Guard Villagers Fabric 1.19-1.0.16
HealthOverlay 7.1.1
Hoe Tweaks 1.8
Horse Stats Vanilla 4.2.2
Husk Spawn 1.9
Iceberg 1.0.46
Immersive Armors 1.4.2
Incendium 5.1.2
Indium 1.0.9+mc1.19.2
Industrial Quarry Mod 1.0.2
Infusion Table 1.1.0
Inmis-Retextured 2.7.0-1.19
Inventory Profiles Next 1.7.1
Iris 1.3.1
Jade 8.2.1
JamLib 0.4.4
Journeymap 5.9.0beta2
Jump Over Fences 1.1.0
Keebsz's Battle Towers 0.3.3
KleeSlabs 12.1.0
Konkrete 1.5.0
Krypton 0.2.1
LambdaBetterGrass 1.3.0
LambDynamicLights 2.1.2+1.19
Lanterns Belong on Walls 1.4.0-1.19
LargeFluidTank 19.0.565
LazyDFU 0.1.3
Levelz 1.4.0
Library ferret 3.0.0
Litematica 0.12.4
Lithium 0.8.3
LoginProtection 1.6
MaLiLib 0.13.0
MangroveSwampHuts 1.0.0
MC Dungeons Weapons 5.0.4-1.19
Macaw's Bridges 2.0.3
Macaw's Doors 1.0.7
Macaw's Fences and Walls 1.0.6
Macaw's Lights and Lamps 1.0.4
Macaw's Paintings 1.0.4
Macaw's Paths 1.0.1
Macaw's Roofs 2.2.0
Macaw's Trapdoors 1.0.6
Macaw's Windows 2.0.3
Medieval Weapons 1.4.0
MidnightLib 0.6.0
Modern Dynamics 0.3.3-beta
Mod Menu 4.0.6
Moonlight 2.0.29
MoreSlabsStairsAndWalls 1.1.0
More Culling 1.19.1-0.10.0
More Geodes 1.5.1
More Villagers 4.0.2
Mouse Tweaks 2.22
MVS 2.5.8 - (NYI)
Naturalist 2.1.1
Nature's Compass 1.19.2-2.0.4-fabric
NiceMod 1.1
NPC Variety 2.2.2
Nullscape 1.2
Nyf's Quivers Fabric-0.5.0-1.19-rc2
oωo 0.8.1+1.19
Oxidized 1.7.2
OxiRods 1.19.2-5
PassableFoliage
Passive Shield (Fabric) 2.6
Patchouli 1.19.2-76-FABRIC
Physics Mod 2.8.13
PigPen 11.1.2
Plated 2.3.0
Polymorph 0.45.0
PresenceFootsteps 1.6.2
Pretty Beaches 8.0.0
Promenade 2.7.1
Puddles 1.2.2
Puzzles Lib 4.3.1
QfAPI 4.0.0-beta
QuarryPlus 19.1.635
Rare Ice 0.5.0
Reborn Core 5.3.4
Redstone Pen 1.2.18
Reese's Sodium Options 1.4.7+mc1.19.2-build.59
Reinforced Barrels 2.2.1+1.19
Reinforced Chests 2.1.2+1.19
Repurposed Structures 6.1.1+1.19
Reroll 1.6.0-1.19
ResourcefulLib 1.1.1
Right Click Harvest 3.0.0
Ring Of Attraction 1.3.11
Ring Of Teleport 1.2.12
Rocks 1.6.1
Runelic 14.1.2
SimpleTech 2.3.0
Simply Houses 1.1.3-1.19
Simply Light 1.4.3
Simply Swords 1.20-1.19
Skeleton Horse Spawn 2.5
Sky Villages 1.0.2.1
SleepWarp 1.2.0+1.19
SlimeChunkF3 1.4
Slimy Boyos 5.0.0.3
Slimy Floor 1.19.1-1.2.5
Small Ships 2.0.0a1.1.1
SnowRealMagic 5.0.4
Snowy Trees 1.2.0
Sodium 0.4.4+build.18
Sodium Extra 0.4.10+mc1.19.2-build.64
SomeOrdinaryTweaks 1.3.1
spark 1.9.40
Spellbound 1.11.0-test2
Spiders Produce Webs (Fabric) 2.1
Spirit 2.1.12 - (NYI)
Starlight 1.1.1
Stoneholm 1.4.4
Stray Spawn (Fabric) 2.1
Structory 1.2
Supplementaries 2.2.3
Survival Island 0.2.1
Sync (Fabric) 4.3
Tech Reborn 5.3.4
Telepistons 1.1.3
TerraBlender 2.0.1.127
The Graveyard 1.10
This Rocks! 1.6.1
ThonkUtil 2.15.4+1.1
Time & Wind 1.4.3
Towers of the Wild: Additions 1.2.3
Towns and Towers - Structure Add-on 1.8.2
Traveler's Backpack 1.19.2-8.2.1
Traverse 6.0.3
Trinkets 3.4.0
Tumbleweed 0.5.1
UniversalOres 1.4.2
Unstructured 0.5.2+1.19
Visuality 0.5.1
VisualOverhaul 4.1.1
Visual Workbench 4.2.0
Vitalize 1.0.0 - (NYI)
VoidZ 1.0.9 - (NYI)
William Wythers' Overhauled Overworld 3.1.7
Wired Redstone 0.4.8+1.19
WI Zoom 1.4-MC1.19.2
WondrousWilds 1.1.2
WorldEdit 7.2.12+6240-87f4ae1
WorldEditCUI 1.19+01
WorldTime 1.19.1-fabric0.58.5-1.3.1
WraithSilkSpawners 1.1.2
XP Storage 1.4.3+1.19
XP Storage - Trinkets 0.1+1.19
Xtra Arrows 2.0
You're in Grave Danger 1.4.3
</details>

**Comment by Keksuccino** [comment]
You have like 5000 mods installed and the first log is spammed by registry errors and other stuff, which isn't a good thing, you should really fix these as well.

The crash in the second log happens because a method in the `PlayerAdvancements` class is stuck in a loop (StackOverflow).
I don't touch player advancements in FancyMenu.

It's most probably a mod conflict.

If you have customizations enabled for the player advancements screen, try to disable it.
Other than that, the only thing you can do is to start the game without other mods to see if it's really a conflict.
If it's working fine without other mods, try to find the conflicting mod or simply remove FM.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
