### ISSUE TITLE
[Crash] My client keeps crashing, even if only fancy menu is installed.

### ISSUE THREAD

**Issue by OzdorMiZ** [Keksuccino/FancyMenu#391]
Minecraft exits with exit code 1

Also, this happened after i deleted all mods in my modpack, because buttons expanded by their aspect ratio instead of width and height separately. I deleted every mod I had, and that's where minecraft started crashing. I even created new modpacks, deleted the client and reinstalled it again.

**Expected behavior**
Minecraft shouldn't have crashed and I should've expanded buttons not by their aspect ratio

**Game Log**
Latest log: https://gist.github.com/OzdorMiZ/fa5fff785cc19708939d68b8e83f55bb

**Basic Informations (please complete the following information):**
 - OS: Win10
 - FancyMenu Version: v2.12.2
 - Forge/Fabric Version: 14.23.5.2860
 - Minecraft Version 1.12.2

I am really sorry if this is a dumb question again, i just feel like I am really annoying you, so I am apologising

**Comment by Keksuccino** [comment]
MixinBootstrap needs to be installed. It is a dependency of FancyMenu in MC 1.12.
