### ISSUE TITLE
Incompatibility with Colormatic (causes lag and breaks audio elements)

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#397]
https://discord.com/channels/704163135787106365/1030565977353637930/1030565977353637930

**Comment by Brancieq-Paul** [comment]
Will this issue will be fixed eventually? Or is the issue just for reference?

**Comment by Keksuccino** [comment]
Mostly for reference. Maybe I manage to fix it one day, but it's handled like a normal mod incompatibility and there are **currently** no plans to make them compatible.

**Comment by Brancieq-Paul** [comment]
It would be great if fixed because there is no alternative for Colormatic if you want Optifine feature parity with sodium.

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
