### ISSUE TITLE
Version 2.12.3 prevents you from "joining" world.

### ISSUE THREAD

**Issue by DaRealSparky** [Keksuccino/FancyMenu#398]
**Describe the bug**
When joining a world (only tried single-player), the world does load, but the joining world screen appears over top of the loaded world and prevents any interaction with the game outside of anything FancyMenu related.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Install FancyMenu v2.12.3 with Forge v40.1.80 on Minecraft 1.18.2.
2. Launch game.
3. Join a world and wait for loading to finish.
4. You should now see the hot-bar behind a transparent loading screen with the text "Joining World." 

**Expected behavior**
The world should load normally like every other game.

**Game Log**
First game log after updating to the latest version.
(https://gist.github.com/DaRealSparky/deccb1539d8cdde2d553c46ec917c769)

**Screenshots**
Bugged
![bug](https://user-images.githubusercontent.com/97619185/196231180-9af022b3-44be-408b-b160-445bcac430b3.PNG)
After mod update.

Not Bugged
![no bug](https://user-images.githubusercontent.com/97619185/196231240-d95a4b8f-1d76-409a-af7f-d1e3d970acbc.PNG)
After mod downgrade.

**Basic Informations (please complete the following information):**
 - OS: [Windows 10]
 - FancyMenu Version [2.12.3]
 - Forge Version [40.1.80]
 - Minecraft Version [1.18.2]
 - Active Mods [Total 214 mods from Curseforge. Can provide list if absolutely necessary.]

**Comment by choombdev** [comment]
Unsure if I should've made a new issue for this but the issue also exists on 1.16.5, attempted it with nothing but recommended forge (36.2.34), latest Konkrete (1.5.3) and latest FancyMenu (2.12.3).

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.12.4! Thank you for telling me! :)
