### ISSUE TITLE
Crash on startup (with the example animation)

### ISSUE THREAD

**Issue by Archilyte** [Keksuccino/FancyMenu#4]
**Describe the bug**
The mod crashes on startup when I try to load [this](https://drive.google.com/file/d/1sYTf4T5LrXX2MMF2r00USDM4WfEHm-v-/view)

**To Reproduce**
1. Put the animation file on config
2. Run Minecraft
3. Crash ([Log](https://paste.feed-the-beast.com/view/cdd0e28d))

**Expected behavior**
The menu animation should load properly

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 0.4.2
 - Forge Version 2.8.21
 - Minecraft Version 1.14.4
 - Active Mods:  [Optifine HD U F5](https://optifine.net/downloads), [AuthMe](https://www.curseforge.com/minecraft/mc-mods/auth-me/files/2871262), [Performant](https://www.curseforge.com/minecraft/mc-mods/performant/files/2863808)

**Comment by Archilyte** [comment]
Crash Log: https://paste.feed-the-beast.com/view/cdd0e28d

**Comment by Keksuccino** [comment]
That happens because you run out of memory (RAM). Loading large animations requires lots of RAM. You can fix this by assigning some more memory to Minecraft. Around 4GB of RAM should be enough to load big animations.

I will try to add some sort of memory-check in one of the next updates to prevent minecraft from crashing. Thank you for the report!

**Comment by Archilyte** [comment]
umm
i have 8gb allocated...

**Comment by Archilyte** [comment]
ok now it works for some reason

**Comment by Keksuccino** [comment]
I think you had not enough free RAM left (because of too much stuff running in the background) ^^

**Comment by Keksuccino** [comment]
The animation loading process got improved in FancyMenu v0.4.3 and is now more optimized to use less memory.

I hope this helps a little bit. I tried to add a good way to check if an animation would need too much memory to load, but every method to check this would use even more memory.. OutOfMemoryErrors can still happen, but the chance should be lower now.
