### ISSUE TITLE
Layout Creator, Scaled Resize

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#40]
**Describe your idea**
When positioning graphics on the screen. It would be nice to be able to do scaled resize too. Like either hold shift while dragging one of the sides, or have corner handles that when drug do the same thing. Or both.

**Does it frustrates you to not already have this feature in the mod?**
Is your feature something you can't live without or is it just something that would be cool to see in FancyMenu?
- [x] somewhat, but I can live with it

**Comment by Keksuccino** [comment]
Should be easy to do. Will be added in the next update.

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.4! :)
