### ISSUE TITLE
Widget Animation System (Animating the position of buttons, text, etc on screen)

### ISSUE THREAD

**Issue by JeBobs** [Keksuccino/FancyMenu#401]
Having a system to keyframe widget positions and play them back in events like opening/closing menus, pressing buttons, etc, would be invaluable since currently it has to be done through rendering the background panel as an animation and delaying the appearance of buttons until the animation is completed.

**Comment by Keksuccino** [comment]
I'm not sure if I have the motivation to code a frickin keyframe system for elements tbh lmao

**Comment by Keksuccino** [comment]
Closing this because issue moved to #412
