### ISSUE TITLE
Severe Issue - Screen Resize Jumbles Menu - 1.15.2+

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Keksuccino/FancyMenu#41]
**Describe the bug**

If you make a menu but change the desktop size your menu gets destroyed. As of right now I see this as a huge issue.

**To Reproduce**
1. Make a cool new menu and make it awesome!
2. Save your work.
3. Change Monitor Resolutions. 
4. You've met with a terrible fate; haven't you?

**Expected behavior**

Menu stretch or shrink as needed.

**Crash Log**
None.

**Screenshots**
Before.
![image](https://user-images.githubusercontent.com/10351221/84889421-7126bd00-b05e-11ea-95f8-b7ef4684639e.png)
![image](https://user-images.githubusercontent.com/10351221/84889454-80a60600-b05e-11ea-80ab-c7cc694b2c97.png)

After.
![image](https://user-images.githubusercontent.com/10351221/84890089-8bad6600-b05f-11ea-8ba3-f9a15fb9166b.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version fancymenu_1.3_MC_1.15-1.15.2
 - Forge Version 31.2.20
 - Minecraft Version 1.15.2
 - Active Mods (Not valid)

**Comment by P3rf3ctXZer0** [comment]
![image](https://user-images.githubusercontent.com/10351221/84890334-e2b33b00-b05f-11ea-8f55-b73f068f7864.png)

**Comment by erazare** [comment]
BUMP this is STILL a problem in 1.19.2

**Comment by P3rf3ctXZer0** [comment]
Yeah I actually updated to remove the mod because it will respect things at and lower but someone has lets say a 2k monitor but I set it for lets say 1980 1080 that person gets a nightmarish hellscape XD

**Comment by Keksuccino** [comment]
This is not a bug. This happens when using the wrong orientations for elements.

http://fm.keksuccino.com/en/2-12-X/customization/orientations

So, for example, if you want to center a bunch of buttons in the middle of the screen, they should ALL have the `mid-centered` orientation.

Right-click an an element and click on **Orientation**, to change its orientation.

**Comment by P3rf3ctXZer0** [comment]
I did and it still errored :( I understand orientation.

**Comment by erazare** [comment]
i understand i will try it thank you

**Comment by erazare** [comment]
@keksuccino that worked flawlessly.. i didnt mean to report it as a bug so much as i couldnt find any documentation through the curseforge page and was hoping by chiming in the dev would point me in the right direction.. so kudos for taking the right cues :) thanks i love this mod man -Keef
