### ISSUE TITLE
Changing the control option

### ISSUE THREAD

**Issue by MiFliK** [Keksuccino/FancyMenu#410]
need the ability to remove the mention of the mod from the control

I'm trying to make a modpack that doesn't have a mod button or mention mods to make it look like it's a slightly modified vanilla.
![image](https://user-images.githubusercontent.com/80956290/198001151-c81314c9-376c-4c5e-be42-bf52782f5ac9.png)

But in the control tab, mentioning the mod breaks the idea
my version is 1 12 2
The idea in the configs is to add the ability to remove the mention of the mod

Or add it is possible to customize the controls so that you can remove the binds of other mods and vanilla
For example, removing the sprint or something else would be very useful

Sorry if it's spelled wrong my english is not very good
since this is the part that the mod cannot change

**Comment by Keksuccino** [comment]
FancyMenu can't customize scroll areas in general, because adding support for them is pretty difficult.

I'm very sorry, but I have no plans to add support for scroll areas.
