### ISSUE TITLE
Crash with Modern UI

### ISSUE THREAD

**Issue by 764069075** [Keksuccino/FancyMenu#417]
**Describe the bug**
Install the latest fancymenu and modern UI modules at the same time, and click the new drawing board on the main interface, and it will collapse

**Expected behavior**
[crash-2022-11-01_13.22.14-client.txt](https://github.com/Keksuccino/FancyMenu/files/9907191/crash-2022-11-01_13.22.14-client.txt)

**Basic Informations (please complete the following information):**
 - OS: win11
 - FancyMenu Version 2.12.6-1
 - Forge/Fabric Version 31.2.29
 - Minecraft Version 1.16.5
 - Active Mods modernUI fancymunu

**Comment by Keksuccino** [comment]
ModernUI probably makes lots of changes to Minecraft's UI, so there's probably no way to add support for it. I will close this for now, sorry.
