### ISSUE TITLE
Major Request - Layouts Saved based on resolutions

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Keksuccino/FancyMenu#42]
**Describe your idea**

I believe that layouts should save differently based on resolutions. It would prevent things like this.
![image](https://user-images.githubusercontent.com/10351221/84890531-260da980-b060-11ea-9aa9-75c648f6cf9c.png)

Also if a user changes to an unsupported resolution it could just automatically disable fancy menu changes as a fullback for that resolution. 

**Does it frustrates you to not already have this feature in the mod?**

It is frustrating that saves are strictly global. It can be said without this change it renders long term use for the mod moot. Users often change pack resolutions. This is not a simple slap fix.

**Comment by Keksuccino** [comment]
I assume you figured it out by yourself :D You have used the wrong orientations for your menu objects, that caused the resizing glitches ^^

**Comment by P3rf3ctXZer0** [comment]
Indeed
