### ISSUE TITLE
Text Web Source not working (ERROR: UNABLE TO LOAD!)

### ISSUE THREAD

**Issue by t0ssox** [Keksuccino/FancyMenu#422]
**Describe the bug**
Text with web source always outputs only **ERROR: UNABLE TO LOAD!**

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Install this mod and its dependencies
2. Go to FancyMenu Editor and insert text element
3. Set Source Mode to Web Source
4. Try to use any variable

**Expected behavior**
Parsing my variables to normal output.

**Game Log**
https://mclo.gs/OIX9oa6

**Basic Informations (please complete the following information):**
 - OS: Arch Linux
 - FancyMenu Version: 2.12.5 and happens on 2.12.6 too
 - Forge/Fabric Version: 0.14.10
 - Minecraft Version: 1.19.2
 - Active Mods: Too many to write here. You can see in the game log.

**Comment by Keksuccino** [comment]
Hi! Please send me the source you're trying to get the content from and the layout file containing the text element (`config/fancymenu/customization/<the layout file>.txt`)

**Comment by davidjimeneztv** [comment]
Same error!

My web source is "http://davidftp.ga/modpacks/personassinfuturo/anuncios.txt" and not work...

I tried without .txt extension and not work :C

**Comment by Keksuccino** [comment]
You tried to use `http://`, but your website uses `https://`.
Using https://davidftp.ga/modpacks/personassinfuturo/anuncios.txt as source works fine.
