### ISSUE TITLE
Unable to open PackSelectionScreen via button action

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#429]
- https://discord.com/channels/704163135787106365/1037826285386346507/1037826285386346507

**Comment by Keksuccino** [comment]
Unable to fix that.

**Workaround:** Mimic the Resource Pack button in the Options menu.

**Comment by FireController1847** [comment]
> Unable to fix that.
> 
> **Workaround:** Mimic the Resource Pack button in the Options menu.

It seems that in Minecraft 1.19.4 this no longer works. When I have it mimic, "net.minecraft.client.gui.screens.OptionsScreen:345280", it gives the error, "Unable to execute button action! Invalid button locator or unable to open parent screen of button."

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.14.1!
