### ISSUE TITLE
FancyMenu conflict with findme (linux)

### ISSUE THREAD

**Issue by fred21O4** [Keksuccino/FancyMenu#43]
**Describe the bug**
Error on launch

**To Reproduce**
1. install both [findme](https://www.curseforge.com/minecraft/mc-mods/findme/files) and fancymenu to mods folder
2. try to launch
3. 
![image](https://user-images.githubusercontent.com/67189813/85256942-173c5200-b4b9-11ea-954b-e3c93e6d2c54.png)

**Expected behavior**
game to launch without error

**Crash Log**
If the bug includes a crash, please paste or link it here.
[latest.log](https://paste.ee/p/VbBT0)

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: arch linux
 - FancyMenu Version 1.3
 - Forge Version 31.2.21
 - Minecraft Version 1.15.2
 - Active Mods fancymenu findme

**Comment by Keksuccino** [comment]
I will try to find a way to make it compatible with "FindMe", but no promises as it seems the other mod is altering something FancyMenu needs to work.

A possible workaround for the crash is to disable the the FancyMenu system tray icon in its config. Could help to load both mods together (not tested).

**Comment by Keksuccino** [comment]
FancyMenu v1.3.1 added compatibility with the FindMe mod, which should fix this issue! :)
