### ISSUE TITLE
1.12.2 background image not loading

### ISSUE THREAD

**Issue by MeinKraft** [Keksuccino/FancyMenu#44]
**Describe the bug**
Whatever I type into the "enter path" box produces the error of file not found/un-supported
The image im using was taken by pressing F2 in game.  I cant "choose file" because it says "disabled or unsupported".  The wiki says place the image in config/fancymenu folder
my image name is `image.png` and is in the `config/fancymenu` folder

**To Reproduce**
1. Right click "Background Options"
2. Set to "Background Image"
3. Type pathname of image
4. Shows error "Image is unknown or unsupported"

**Expected behavior**
Load the image as the background image

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.3_MC_1.12-1.12.2
 - Forge Version 14.23.5.2854
 - Minecraft Version 1.12.2

**Comment by Keksuccino** [comment]
You’ve disabled the system tray icon if you’re using windows and the choose file screen says "disabled or unsupported".

What you’re describing sounds like problems on macOS, which is a bit weird because this should not happen on windows.

Are you using any other mods with FancyMenu?

**Comment by MeinKraft** [comment]
it _was_ because I had `enablesystemtray=false`

All good now

thank you

**Comment by Keksuccino** [comment]
Reopen because it could be a bug that paths in general getting identified as invalid by the system if the file chooser is disabled.

**Comment by MeinKraft** [comment]
Tested with the Systemtray=false and the file chooser opens perfectly now

thanks for the fix
