### ISSUE TITLE
[FMM] Layouts wont save/load after update

### ISSUE THREAD

**Issue by Saereth** [Keksuccino/FancyMenu#440]
**Describe the bug**
Create a layout, save it, confirm the name, exit editing mode, go to apply the layout and no layouts are shown available.
It does not appear as if the layout is ever written to disk just looking at my git changes after saving

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] Win11
 - FancyMenu Version [e.g. 0.2] fancymenu_forge_2.12.7_MC_1.19-1.19.2
 - Forge/Fabric Version [e.g. 31.2.24] 43.1.43
 - Minecraft Version [e.g. 1.15.1] 1.19.2

**Comment by Keksuccino** [comment]
Hi! Can you send me your /logs/latest.log file after trying to save a layout, please?

**Comment by Saereth** [comment]
sure thing
https://mclo.gs/iDDyQuM
Here you go

**Comment by Keksuccino** [comment]
Fixed in v2.12.8! Thank you for your report!
