### ISSUE TITLE
Translation-Generation file for mainlang

### ISSUE THREAD

**Issue by Wealthsocker** [Keksuccino/FancyMenu#447]
Hello cookie,

thank you for adding my last request to the mod.
In the meantime I have another
If not already available:
Translation-Generation file for mainlang

By this I mean that only the translation keys are generated so that you have to enter/translate the final value yourself afterwards.

And that you can create translations for other languages with this file.

I don't know if this is so easy to implement

**Comment by Keksuccino** [comment]
Well, you need the original text in most cases to be able to translate it. The key alone isn't enough.
I don't think this is worth the effort tbh, I'm very sorry, but thank you very much for your suggestion anyways!
