### ISSUE TITLE
QuestCraft Fails To Load

### ISSUE THREAD

**Issue by LimeDev8756** [Keksuccino/FancyMenu#448]
**Describe the issue**
QuestCraft fails to launch properly with a FancyMenu layout applied, without a layout applied it works but you can't make a layout to apply even if customization is set to on

**Game Log**
https://gist.github.com/LimeDev8756/a1745428416ed1cf2b1ea71b54831dd2

**Screenshots**
N/A Game Fails To Load

**Basic Informations (please complete the following information):**
 - OS: Oculus OS?
 - FancyMenu Version 2.12.9
 - Fabric Version 0.14.10
 - Minecraft Version 1.19.2
 - Active Mods [FancyMenu, Konkrete, AppleSkin, LambDynamicLights, Xaero's World Map]

**Comment by LimeDev8756** [comment]
Update, QC switched to Vivecraft which doesn't appear to work either, the game freezes at the loading screen and will hang indefinitely.

Applied mods : [FancyMenu, Konkrete, All QC core mods(Unable to list atm)]
Minecraft Version 1.19.3
FancyMenu Version 2.13.2
Fabric Version : QC, Unable to list atm

**Comment by Keksuccino** [comment]
Send me a latest.log of the new mod setup in 1.19.3, please.

**Comment by LimeDev8756** [comment]
https://mclo.gs/NKdYEaG

**Comment by Keksuccino** [comment]
Dude I just noticed this is a Pojlib-based port of MC for frickin VR headsets.. Sorry, but I will not add support for any unofficial VR headset setups.. I don't even have a VR headset and even if I would, I still wouldn't add support for such niche stuff.
