### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by CCSNova** [Keksuccino/FancyMenu#449]
**Describe your idea**
Lists which can storage many variables inside and can be picked from a list which could open up a whole new opportunity for people wanting to make menus with lists, these lists could hook into text files to show your to-do list in minecraft and anywhere else on your computer, if this is the case the text files could be grabbed from the web making something like a friend system possible which again, opens up a new opportunity for people.

**Comment by Keksuccino** [comment]
Hi! So you want to be able to pick values from the list, right? Because normal text lists (non-interactive) are already possible. You can get text from a web source and display it as text element. These text elements are scrollable.

**Comment by LimeDev8756** [comment]
I mean have a list system like python's which gives each variable a index and then anything can grab the whole list, one item from the list or the length of the list

**Comment by LimeDev8756** [comment]
To expand the lists could be modified with a list like the audio list where you can choose an index etc.

You could view the lists in a new menu at the FancyMenu menu(confusing to say). Variables could also be created and edited here, sort of like an update to the variables

**Comment by LimeDev8756** [comment]
![Something like this](https://user-images.githubusercontent.com/100384210/203112309-8a4ccab7-82f5-474d-a82d-17c51fcd95d0.png)
