### ISSUE TITLE
[1.3_MC_1.14.4] Intro no longer plays

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#45]
**Describe the bug**
Intro was playing before now it isn't

**To Reproduce**
Update to this version

**Basic Informations (please complete the following information):**
 - OS: Linux
 - FancyMenu Version 1.3_MC_1.14.4
 - Forge Version 28.2.19
 - Minecraft Version 1.14.4
 - Active Mods https://pastebin.com/mEs4GsVx
 - Config Text https://pastebin.com/ShftHwRD

**Comment by kreezxil** [comment]
to be clear it's a 1.14.4 bug, because it still works on the latest forge in 1.15.2

**Comment by Keksuccino** [comment]
With "updated to this version" you mean updated the mod to version 1.3?

Is the intro playing without the other 118 mods active?

I will look into this, thank you for your report! :)

**Comment by kreezxil** [comment]
yes updated to the version in the brackets of the title

**Comment by Keksuccino** [comment]
Support for MC 1.14 was dropped with FancyMenu v1.4, so this will not be fixed anymore, sorry. :/

**Comment by kreezxil** [comment]
if you dropped support for 1.14.4 did you also drop it for 1.12.2?

**Comment by Keksuccino** [comment]
Nope, only for 1.14.
