### ISSUE TITLE
Player Report Button

### ISSUE THREAD

**Issue by PlazmaKG** [Keksuccino/FancyMenu#453]
Is there a way to remove the "Player Report" button in multiplayer **without** removing the "Open to LAN" button in single player? If not, it's not a super big deal if you can or not, or if you update this to be possible, it just serves no purpose with No Chat Reports & pretty much every server that disables it.

Prior to 1.19, Open to LAN just grayed out when in multiplayer.

**Comment by Keksuccino** [comment]
You can use the "Is Multiplayer" visibility requirement layout-wide to check if in multiplayer. That way, the layout that hides the button will only hide it while in MP.

Right-click the editor background to set visibility requirements to layouts.

And don't forget to make a new layout with only that one action (hiding the button).
