### ISSUE TITLE
Progress screen displays but is not really needed

### ISSUE THREAD

**Issue by MeinKraft** [Keksuccino/FancyMenu#46]
**Describe the bug**
When the forge part of the loading screen finishes, a white screen with "Complete" flashes up for a couple of seconds before the main Minecraft Title Screen

I dont use animations but have set `B:showanimationloadingstatus = 'false';` anyway

This is more annoying than anything and I dont really think is needed at all. It may be a bug, but if it could be turned off so that there is a smooth transition between forge and the main title screen, that would be nicer

**To Reproduce**
1. Create a basic main menu
2. Run Minecraft
3. When Forge completes loading watch for white screen to appear

**Expected behavior**
The forge loading screen to finish then go to main menu.  The image in attached picture to not be there at all

**Screenshots**
https://imgur.com/a/Getpjko

**Basic Informations (please complete the following information):**
    OS: Windows
    FancyMenu Version 1.3_MC_1.12-1.12.2
    Forge Version 14.23.5.2854
    Minecraft Version 1.12.2
    Mods: JEI, FancyMenu  (Just 2 mods)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.4! :)
