### ISSUE TITLE
Incompatiable with Replay Mod

### ISSUE THREAD

**Issue by LimeDev8756** [Keksuccino/FancyMenu#460]
**Describe the issue**
The replay mod button is not there but when editing a layout, it appears but it can not be moved and behaves how to button normally would, but it shouldn't while editing. Then after returning back to the menu it is a mix of the default menu and your customized ones which is fixed when going to edit a layout.

**Game Log**
[Game Log](https://gist.github.com/LimeDev8756/48f1b404b9c656fb82a1f57e8304e0cc)

**Screenshots**
![Screenshot 1](https://user-images.githubusercontent.com/100384210/205509417-922cd9f1-d8dd-4eb2-b238-1bdd56b8ec13.png)
![Screenshot 2](https://user-images.githubusercontent.com/100384210/205509419-a5924a86-0a61-445f-a5f1-6781e60e784d.png)
![Screenshot 3](https://user-images.githubusercontent.com/100384210/205509420-f2eef13e-9614-4ef3-bd71-1bc8d21c32a6.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.12.2
 - Fabric Version 0.62.0+1.19.2
 - Minecraft Version 1.19.2
 - Active Mods 
![Mod List](https://user-images.githubusercontent.com/100384210/205509515-f2daba82-7cb2-42ee-bede-ab21ff6fa997.png)

**Edit**
Found something else
![](https://user-images.githubusercontent.com/100384210/205510450-784ba399-17b8-46b3-853a-aa7b5df3d165.png)

**Edit 2**
I pressed a button and it worked before with replay mod on but with this crash, I didn't press a replay mod button but that is what it says I did, here is the crash report[ [](https://gist.github.com/LimeDev8756/28c446b5ad80861db42d39d85efaa985)](https://gist.github.com/LimeDev8756/28c446b5ad80861db42d39d85efaa985)

**Comment by Keksuccino** [comment]
http://fm.keksuccino.com/en/incompatibility-list
