### ISSUE TITLE
Wiki Mod Incorrect Category 

### ISSUE THREAD

**Issue by LimeDev8756** [Keksuccino/FancyMenu#461]
**Describe the bug**
The Replay Mod is in the Forge section in the wiki despite being a fabric only mod as of 1.14.4, this would have saved a headache lol

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to http://fm.keksuccino.com/en/incompatibility-list
2. See that the Replay mod is in forge not fabric

**Expected behavior**
Expected to be in the Fabric section

**Screenshots**
![image](https://user-images.githubusercontent.com/100384210/205515858-40d28420-03e1-4aad-9a20-6bb9c240147e.png)

**Basic Informations (please complete the following information):**
Not needed, website issue

**Comment by Keksuccino** [comment]
Fixed!
