### ISSUE TITLE
Appearance Delay fade-in doesn't work in title screen

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [Keksuccino/FancyMenu#464]
**Describe the bug**
When you set the buttons on the title screen to delay appearance and fade the delay apprentice doesn't work when the game finishes loading and the title screen appears.

**To Reproduce**
Steps to reproduce the behaviour (e.g.):
1. Edit the title screen 
2. Give the Vanilla button the "delay apprentice and fade properties"
3. Save the layout
3. Restart Minecraft
4. The delay apprentice effect does not work after the loading screen is done and the title screen appears

**Expected behaviour**
The game is done loading, the loading screen disappears, the title screen show and buttons fade onto the screen

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Information (please complete the following information):**
 - OS: Ubuntu: 20.04, but it happens on Windows 10 as well
 - FancyMenu Version: fancymenu_fabric_2.13.0_MC_1.19-1.19.2
 - Minecraft Version: 1.19
 - Active Mods: drippy loading screen

**Comment by Keksuccino** [comment]
Probably the same as #756, so I will close this one.
