### ISSUE TITLE
My personalization is not applied

### ISSUE THREAD

**Issue by davidjimeneztv** [Keksuccino/FancyMenu#465]
Once I set all the custom menus and include the rest of the mods in the modpack for some reason, it shows me another customization and if I disable the FancyMenu customization the default menu appears.

There is some mod that modifies the customization and I don't know what it could be.

1. I make the customization to the desired menus.
2. Reboot to check that it works correctly. Personalization is displayed perfectly.
3. I add the rest of the mods from the modpack and start the game.
4. A completely different menu than mine appears.

I think some mod in my modpack does some kind of modification to the FancyMenu to get that weird customization applied.

I have verified that my customization is not deleted or customized but does not apply it when it should, only when edit is clicked.

I've removed the mods I've recently added in case they conflict but I still can't find the mod that causes it.

I have deleted my template and restored it and without the mods in a new folder it loads perfectly but when the mods are added again it appears like this again.

Logs: https://gist.github.com/davidjimeneztv/40eb653254a91d0356675e914a5387ee

![image](https://user-images.githubusercontent.com/72690231/207664747-27c4bc56-aac8-4608-8dad-b957acf58aad.png)
![image](https://user-images.githubusercontent.com/72690231/207665000-4cb33268-b5a9-495a-b680-f3464a5bc59f.png)

Information:
 - OS: Windows 11
 - FancyMenu Version 2.13.0
 - Forge Version: 14.23.5.2860
 - Minecraft Version 1.12.2
 - Active Mods: https://gist.github.com/davidjimeneztv/02a83aa47797f7a55092aa4cd6322e83

**Comment by Keksuccino** [comment]
Check the incompatibility list: http://fm.keksuccino.com/en/incompatibility-list

If you don't have mods from this list installed, try to disable mods that add buttons to the main menu, change the background and other stuff.

**Comment by davidjimeneztv** [comment]
Hello!

I have already discovered which mod caused the failure.

The MalisisCore mod (a core mod of MalisisDoors) is what makes it apply its own customization with FancyMenu when it is installed.

**Comment by Keksuccino** [comment]
Thank you! Will add this mod to the incompatibility list! :)
