### ISSUE TITLE
crash possibly caused by Fancy Menu (loaded with FindMe mod)

### ISSUE THREAD

**Issue by SveetPickle** [Keksuccino/FancyMenu#47]
**Describe the bug**
Plunger 1.14 modpack crashes while loading

**To Reproduce**
1. Used MultiMC to install modpack from zip file downloaded from curseforge

2. Launched modpack from MultiMC

3. Game crashes while loading

**Expected behavior**
Game should have loaded as normal

**Crash Log**
https://paste.ee/p/3fxMe

**Basic Informations (please complete the following information):**
 - OS: Ubuntu 20.04
 - FancyMenu Version 1.3
 - Forge Version 31.2.22
 - Minecraft Version 1.15.2
 - Active Mods Plunger 1.14 modpack

If this isn't caused by Fancy Menu I would be happy to pass it along to Forge or the modpack maker.

**Comment by Keksuccino** [comment]
You’re using the "FindMe" mod which seems to cause crashes when loaded with FancyMenu, could be the same thing as #43. 

I will look into this, thank you for your report! :)

**Comment by Keksuccino** [comment]
FancyMenu v1.3.1 added compatibility with the FindMe mod, which should fix this issue! :)
