### ISSUE TITLE
"File Exists" Visibility Requirement

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#472]
https://discord.com/channels/704163135787106365/1056718130174500974/1056718130174500974

**Comment by ClaudiusMinimus** [comment]
Just wondered if this is in process or if will this be a long wait? BTW: This is for 1.18.2
I really appreciate you making this a feature request!
Thanks, CM

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
