### ISSUE TITLE
Game crashes right after launching it

### ISSUE THREAD

**Issue by ShawnPartridge** [Keksuccino/FancyMenu#474]
I left the game after creating a main menu and now i can't open the game anymore.
When i try launching the game it crashes and i get this error message: The game crashed whilst rendering overlay
Error: net.minecraft.util.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: main menu:sounds.json

I don't have any other mods installed except other mods by Keksuccino

 - OS: Windows 11
 - FancyMenu Version 2.13.2
 - Forge Version 36.2.34
 - Minecraft Version 1.16.5
 
[crash-2022-12-27_15.03.34-client.txt](https://github.com/Keksuccino/FancyMenu/files/10308551/crash-2022-12-27_15.03.34-client.txt)

**Comment by Keksuccino** [comment]
Hi! Do you have a `main menu/sounds.json` file? If so, rename the folder to `main_menu` and fix the location in your layout, then it will stop crashing.

**Comment by Keksuccino** [comment]
Closed because no response and probably already solved when following the instructions of my last message.
