### ISSUE TITLE
Use variables/read files in button scripts?

### ISSUE THREAD

**Issue by k2helix** [Keksuccino/FancyMenu#476]
Hi, I just found FancyMenu and it really is incredible! I was wondering if there is a way to use a variable in a button script.

So, for example, I want to use joinserver on a variable ip which I would get from the runcmd command, but how would I use that value? I could also store the value on a file, but afaik FancyMenu does not have an option to read it. 

I noticed there is a set_variable command, but tbh I do not think I can use it in his case. Is there any way to do this?

**Comment by Keksuccino** [comment]
You can use placeholders in values of actions. Use the placeholder to get a variable. For a list with all placeholders, click on the little button at the right side of the text input box when editing the content of a text element.
