### ISSUE TITLE
Incompatibility with Advanced Creation

### ISSUE THREAD

**Issue by Dev-Hauffman** [Keksuccino/FancyMenu#478]
**Describe the issue**
When both mods are together the game crashes on startup

**Game Log**
https://gist.github.com/Dev-Hauffman/9d6dd9016696d859dec8143c22ef9fb5

**Basic Informations (please complete the following information):**
 - OS: windows 7
 - Fancymenu_forge_2.13.2_MC_1.12-1.12.2
 - Active Mods: AdvancedCreation-1.12.2-alpha2.0

**Comment by Keksuccino** [comment]
Please send the whole `logs/latest.log` file. Code snippets or crash logs don't help.

**Comment by Dev-Hauffman** [comment]
I'm sorry can't recovery it anymore, I'm closing this issue.
