### ISSUE TITLE
文字太小了，我根本看不清楚——The text is so small that I can't read it at all

### ISSUE THREAD

**Issue by HangZhouXZH** [Keksuccino/FancyMenu#485]
**Describe the bug**
A clear and detailed description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to 'home'
2. See error

**Screenshots**
If screenshots would help to explain the issue, please include these.
![捕获](https://user-images.githubusercontent.com/102938713/211185709-9e30ccab-35ca-4c2c-862e-54ff60093dcb.PNG)

**Basic Informations (please complete the following information):**
 - OS: Windows 8.1
 - FancyMenu Version 2.13.2
 - Forge/Fabric Version 0.14.12
 - Minecraft Version 1.18.2
 - Active Mods ModMenu,auudio,konkrete

**Comment by HangZhouXZH** [comment]
英文显示还勉强看得清，但是中文一点也看不清，而且调整页面尺寸没有任何效果

**Comment by Keksuccino** [comment]
Go to the FancyMenu settings (click on the little FM icon in the top-left corner) and set the UI scale to 2, this will fix the issue :)
