### ISSUE TITLE
无法打开某些GUI

### ISSUE THREAD

**Issue by hyplant** [Keksuccino/FancyMenu#488]
**Describe the bug**
某些用户界面是存在的，但尝试打开时会提示无法打开，例如`net.minecraft.client.gui.screen.inventory.CraftingScreen`

**To Reproduce**
1. 尝试自定义一个gui
2. 添加一个按钮用于打开`net.minecraft.client.gui.screen.inventory.CraftingScreen`
3. 会提示无法打开

**Expected behavior**
尝试过其他界面，例如`net.minecraft.client.gui.screen.inventory.InventoryScreen`，可以正常打开，`net.minecraft.client.gui.screen.inventory.CraftingScreen`应该也可以被打开

**Screenshots**
![Screenshot_20230112-105603_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/86937725/211965878-6790220d-776c-49c0-adbf-0ada49bb1067.jpg)![Screenshot_20230112-105640_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/86937725/211966098-abd4918d-024e-4fc3-ba53-1d69284fc874.jpg)

**Basic Informations (please complete the following information):**
 - OS: Android12
 - FancyMenu Version 2.13.2
 - Forge/Fabric Version 36.2.39
 - Minecraft Version 1.16.5
 - Active Mods 
```
fancymenu_forge_2.13.2_MC_1.16.2
-1.16.5.jar
konkrete_forge_1.6.0_MC_1.16.2-1.16.5.jar
loadmyresources_forge_1.0.4_MC_1.16.2-1.16.5.jar
```

**Comment by Keksuccino** [comment]
**English** please.

Also looks like you want to report some bug related to PojavLauncher or something, which I don't plan to add support for.
