### ISSUE TITLE
Player Entity element invisible

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Keksuccino/FancyMenu#489]
**Describe the bug**
I had my character skin display on the main menu. After I updated the mod, it stopped showing up. I also did update Fabric Loader and API to the latest versions. According to the layout customization screen, the UI element is still there. It just doesn't appear when it should. At first I thought something happened with the PNG used for the skin, but I also set the character to appear on the pause menu in singleplayer, and he appears fine there.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Update mod.
2. Start game.

**Game Log**
[latest.log](https://github.com/Keksuccino/FancyMenu/files/10414901/latest.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/60951301/212405077-f376a9f7-6587-4d43-a5f6-c457b6330429.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.13.2
 - Fabric Loader 0.14.12 / Fabric API 0.69.0
 - Minecraft 1.19.2
 - Too many active mods. List is at the start of the log provided.

**Comment by Keksuccino** [comment]
Remove the element -> add it again -> see if it's fixed

**Comment by Keksuccino** [comment]
Closed because not reproducible and no response.
