### ISSUE TITLE
Support for 1.8.9

### ISSUE THREAD

**Issue by DarkPlayerr** [Keksuccino/FancyMenu#49]
**Describe your idea**
It would be great if fancymenu would be ported to Minecraft 1.8.9, a lot of people in the pvp community use that version and it would be nice to have a better menu like you guys on the newer versions

**Does it frustrates you to not already have this feature in the mod?**
I can live w/o FancyMenu but it would be cool to have support for that version.

**Comment by Keksuccino** [comment]
Will not happen, I’m sorry.
https://github.com/Keksuccino/FancyMenu/wiki/FAQ#will-you-backport-the-mod-to-mc-111-and-lower-andor-add-support-for-mc-113
