### ISSUE TITLE
[BUG or IDEA?? idk] Player Entity Capes with MinecraftCapesMOD

### ISSUE THREAD

**Issue by MarkinhosMLP** [Keksuccino/FancyMenu#490]
before the changes with the player entity model in fancymenu, it used to load your custom cape from the mod
idk if it was removed accidentaly or something like that, but it is not detecting your custom cape anymore and applying to it when you select to copy the client player

**Comment by Keksuccino** [comment]
I don't think I will add this back to the mod, I'm sorry. It was never an actual feature, it just worked.
It probably doesn't work anymore because I rewrote the player entity element.
