### ISSUE TITLE
Change the image according to the computer date

### ISSUE THREAD

**Issue by Samlegamer** [Keksuccino/FancyMenu#494]
It's a bit complicated to explain, but why not change the title screen image depending on when we are.
For example at the moment we are in Winter we could use a title screen of an ice biome... but some months later in Spring the image would automatically change to a birch forest.

**Comment by Keksuccino** [comment]
That's already possible. To do this, make 4 layouts (spring, summer, autumn, winter) and only set a background image and nothing else (don't hide vanilla elements, etc.).
Now right-click the background of the editor while having one of the 4 layouts opened and click on **Visibility Requirements**. Enable the **Real Time Month** requirement and set it to show in the correct months (you can separate multiple months by comma).

This will make the layouts to show in the correct season.
