### ISSUE TITLE
1.19.2 support

### ISSUE THREAD

**Issue by vizthex123** [Keksuccino/FancyMenu#497]
**Describe your idea**
As the title says, it'd be great to have this mod on 1.19.2.

**Comment by Keksuccino** [comment]
Well, you could just go to its CurseForge or Modrinth page and download the 1.19.2 version lmao

It already has 1.19.2 support :)

**Comment by vizthex123** [comment]
> Well, you could just go to its CurseForge or Modrinth page and download the 1.19.2 version lmao
> 
> It already has 1.19.2 support :)

yeah, it didn't show up in the app when i posted this issue. Guess it just hadn't synched yet.
