### ISSUE TITLE
ReplayMod GUI cannot be opened by Button Action

### ISSUE THREAD

**Issue by EinsteinMaker** [Keksuccino/FancyMenu#498]
**Describe the issue**
The replay viewer from Replay Mod cannot be opened by a button action.

**Game Log**
<https://gist.github.com/EinsteinMaker/2edb0cea08f12efe1d9b08eafaeb44c2>

**Screenshots**
![image](https://user-images.githubusercontent.com/89540768/215150466-d65f06f8-25a1-45c8-b4cc-bdc4427b1223.png)

**Basic Informations (please complete the following information):**
 - OS: Ubuntu 22.04.1
 - FancyMenu Version: 2.13.2
 - Forge/Fabric Version: 0.14.11
 - Minecraft Version: 1.19.3
 - Active Mods: <https://gist.github.com/EinsteinMaker/fa0af7141f1a98da659785ab46f5b129> (Sorry but I didn't want to type out 151 mods so I copied them from the log)

**Comment by Keksuccino** [comment]
ReplayMod is on the incompatibility list and this will not change, sorry.
