### ISSUE TITLE
Buttons not following window resize with "original" orientation

### ISSUE THREAD

**Issue by AzureDoom** [Keksuccino/FancyMenu#5]
**Describe the bug**
Resizing does not update the buttons, so if you have a the small window and resize to a bigger window, the buttons do not follow the rescaling.

**To Reproduce**
1. Move a button with a small window size EX: The default window size Minecraft launches at.
2. Resize with full window option or resize by hand.
3. buttons do not update

**Expected behavior**
The buttons moving values would follow with the windows resizing. 

**Screenshots**
Small Window:
![image](https://user-images.githubusercontent.com/7415711/77845288-bc29e600-717b-11ea-89bd-2175091e19d6.png)
Large Window
![image](https://user-images.githubusercontent.com/7415711/77845293-c350f400-717b-11ea-8587-6d3d7db49fb0.png)

**Basic Informations:**
 - OS: Windows 10
 - fancymenu_0.4.2_MC_1.15-1.15.2
 - Forge Version 1.15.2 - 31.1.30
 - Minecraft Version 1.15.2

**Config**
https://gist.github.com/AzureDoom/84e9610883b97bfd910cfcf3cbc415c9

**Comment by Keksuccino** [comment]
You are using the "original" orientation, which sadly does not support resizing. In your case, you can use the "bottom-right" orientation!

**Comment by AzureDoom** [comment]
The issue with bottom-right is that the button just vanishes
![image](https://user-images.githubusercontent.com/7415711/77855509-e224aa00-71be-11ea-86c7-d022a769b233.png)
```
customization {
  action = movebutton
  identifier = %id=2%
  x = 0
  y = 0
  orientation = bottom-right
}
```
![image](https://user-images.githubusercontent.com/7415711/77855538-0da79480-71bf-11ea-930c-e184e1abfd82.png)
```
customization {
  action = movebutton
  identifier = %id=2%
  orientation = bottom-right
}
```

**Comment by Keksuccino** [comment]
The bottom-right orientation is the bottom right corner of the window, which means, if you set x and y to 0, the buttons are completely out of the visible area. You have to set negative x coordinate (e.g. -150) >= the width of your button :)

**Comment by Keksuccino** [comment]
With FancyMenu v1.0, the "original" orientation is now deprecated and will be removed in the near future.
