### ISSUE TITLE
Opacity not working for Player Entities Capes

### ISSUE THREAD

**Issue by LopyLuna** [Keksuccino/FancyMenu#501]
**Describe the bug**
Basically opacity not working for Player Entities Capes

**To Reproduce**
1. Make a Player Entity
2. Change Cape to the Cape Texture

**Expected behavior**
Translucent Capes

**Screenshots**
Cape Texture
![cape](https://user-images.githubusercontent.com/100169742/216246173-b9042466-dee9-49b3-8cc8-6e7b27973a74.png)

Ingame
![image](https://user-images.githubusercontent.com/100169742/216246270-ebbbaeed-8706-4e10-8432-3bfa980750a2.png)

 - OS: Windows
 - FancyMenu Version: 2.13.3
 - Forge/Fabric Version: Forge 
 - Minecraft Version: 1.18.2

**Comment by Keksuccino** [comment]
I'm pretty sure this does't work in Vanilla either.

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
