### ISSUE TITLE
Crash on game launch (Image not allocated; maybe related to Drippy)

### ISSUE THREAD

**Issue by PanoptesDreams** [Keksuccino/FancyMenu#507]
Latest update (from 1.6 to 2.x latest) wiped my configs. WTF?
Was using Drippy without Fancy Menu. Did an update, it demanded FancyMenu, added.

All my shits gone. Bruh??
I get you're doing a re-write but at this point just merge the two projects FFS.

**Comment by PanoptesDreams** [comment]
After a second launch my entire main menu is blank/empty and it quickly crashed

https://mclo.gs/8AyzsSI

**Comment by Keksuccino** [comment]
Please start the game with only Drippy + dependencies and FancyMenu + dependencies installed, thank you.

**Comment by Keksuccino** [comment]
And please learn how to treat others with respect. You opened 2 GitHub issues in my projects and both sound rude and disrespecting.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
