### ISSUE TITLE
GUI Scale

### ISSUE THREAD

**Issue by Kaspeck** [Keksuccino/FancyMenu#516]
**Describe the bug**
When you switch the GUI Scale, all the buttons move to different locations on the screen.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Video Settings 
2. Change the GUI Scale.
3. Go Back to menu.
**Expected behavior**
The buttons should stay in their designated location.

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: 2.13.3
 - Forge/Fabric Version 0.14.12
 - Minecraft Version 1.19.2

**Comment by Keksuccino** [comment]
http://fm.keksuccino.com/en/2-13-X/customization/orientations
