### ISSUE TITLE
Add documentation for the usage of vanilla localization keys

### ISSUE THREAD

**Issue by Zappic3** [Keksuccino/FancyMenu#518]
I saw that this feature apparently exists in issue #270 and after some trial and error, I found out how it works.

The documentation doesn't mention this feature, and I only found out about it through the GitHub issue. So I would like to ask if a short explanation of this feature, could be added to the "Localizing Elements" page.

Here is a link to the page in question:
http://fm.keksuccino.com/en/2-13-X/customization/localizing-elements

**Comment by Keksuccino** [comment]
Oops, totally forgot to add that to the docs! I added it as an info box to **1.** :)
Thank you!
