### ISSUE TITLE
[1.15.2] Button delay gone?

### ISSUE THREAD

**Issue by AzureDoom** [Keksuccino/FancyMenu#52]
**Describe the bug**
I can't find in the configs to delay loading the menu buttons, is it gone?

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.3.1
 - Forge Version 31.2.20
 - Minecraft Version 1.15.2

**Comment by Keksuccino** [comment]
Yes, this feature is currently not in the mod anymore, but I will reimplement it with the next content update! :)
