### ISSUE TITLE
[1.19.2] Customization doesn't seem to be applying in Pause Menu 

### ISSUE THREAD

**Issue by Saereth** [Keksuccino/FancyMenu#520]
**Describe the bug**
I've created and applied a custom layout for the pause screen but doesn't seem to be working. The custom menu I made for the main screen does seem to be working properly. 

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create custom layout for pause screen and move a bunch of buttons around
2. save and apply layout
3. Buttons aren't moved

**Copy of my Customization file**
https://gist.github.com/Saereth/6ef9797fa8bab4293e486073a3ce13dd

**Expected behavior**
I would expect the new layout to be used

**Game Log**
(https://gist.github.com/Saereth/bb1353333fb0f227163b38a1a4dcb920)

**Screenshots**

![2023-02-27_11 48 03](https://user-images.githubusercontent.com/9200909/221668389-a2a0c012-8a52-4a82-9a4c-ada4ca8d6882.png)
![2023-02-27_11 48 24](https://user-images.githubusercontent.com/9200909/221668392-b7e0a10c-7e84-497f-9806-1ee4165a23e4.png)
![2023-02-27_11 48 35](https://user-images.githubusercontent.com/9200909/221668402-a638b860-e8ce-49cd-b5df-866ab5c1e486.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: fancymenu_forge_2.13.3_MC_1.19-1.19.2
 - Forge/Fabric Version: 43.2.4
 - Minecraft Version: 1.19.2
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] 
 https://gist.github.com/Saereth/ca19f270de4d2994e7e88819b39ce21f

**Comment by Saereth** [comment]
Upon further testing this does not happy without minetogether installed
![image](https://user-images.githubusercontent.com/9200909/221674811-32f2f22d-51c0-4cfd-9569-1133329291d7.png)

minetogether-forge-1.19.2-6.0.15.jar

Is this something I need to report on their end/is it something they can address or is this something you'd be able to address?

**Comment by Keksuccino** [comment]
MineTogether is incompatible with FancyMenu, but I can’t fix that on my end.

http://fm.keksuccino.com/en/incompatibility-list

#252
