### ISSUE TITLE
[Possible bug] Bad Access to Protected Data in GetField

### ISSUE THREAD

**Issue by firemaster1294** [Keksuccino/FancyMenu#522]
**Describe the bug**
This crash shows up if Draconic Evolution 3.0.29 is installed with a version mismatch to Brandon's Core. Yes, this is a matter of DE being incorrectly synced, but it is odd to me that Fancy Menu ends up throwing the error, so hence I'm reporting it here on the off chance it has highlighted an error in Fancy Menu.

**To Reproduce**
Install DE 3.0.29 and Brandon's Core 3.1.18, as well as both Drippy Loading Screen and Fancy Menu.

**Expected behavior**
Game should crash from the Brandon's Core incompatibility, not the Fancy Menu error seen.

**Game Log**
[latest.log](https://gist.github.com/firemaster1294/44a0d835d7b0aeec76fa3b69c7456197)
[crash.txt](https://gist.github.com/firemaster1294/0f3dd7a21ea346a31397462e39a6dceb)

**Basic Informations (please complete the following information):**
 - OS: Mac
 - FancyMenu Version: 2.13.3
 - Forge/Fabric Version: 40.2.1
 - Minecraft Version: 1.18.2
 - Active Mods: Fancy Menu, Drippy Loading Screen, Draconic Evolution, Brandon's Core + 186 others

**Comment by Keksuccino** [comment]
Same issue as #506 

Hi! Is one of the other 186 mods "Zerocore" by any chance?

**Comment by Keksuccino** [comment]
I've posted a potential fix/workaround for this under that issue: #506 

For future discussions about the issue, please use the issue mentioned above.
