### ISSUE TITLE
default minecraft title screen overlays the custom FancyMenu one.

### ISSUE THREAD

**Issue by LordDecay26** [Keksuccino/FancyMenu#53]
**Describe the bug**
when using the custom Minecraft_Youtube_Outro on the latest version of FancyMenu for minecraft 1.15 the default title screen overlays the custom animated one.

**To Reproduce**
1. install FancyMenu
2.install the custom cave animation from the link on the curseforge page by dragging and dropping the animation and customization folders from the zip into config/fancymenu.

**Expected behavior**
i expected the vanilla title screen to be gone, replaced with the new custom one. instead i got both screens at the same time.

**Crash Log**
N/A

**Screenshots**
https://imgur.com/hEi1EAQ

**Basic Informations (please complete the following information):**
 -  windows 10
 - FancyMenu v1.3.1 MC 1.15-1.15.2
 -  forge-31.2.24
 - minecraft 1.15.2
 - the list of mods would exceed the character limit, even if i did have time to painstakingly write down each and every one listed. Instead, i'll provide a zip folder showing each mod i have installed and you can just peruse it, or put them in your minecraft/mods folder and test it out for yourself and check the logs to see what's going on. it's also going to take over an hour to upload the zipped folder to google drive, to give you an idea.

i do realize that it is entirely possible for one of these mods to be causing a conflict with FancyMenu and it could be entirely out of your control, however i dont have any mods which mess with the main menu except for FancyMenu. most of the mods i have are small ones meant to expand upon vanilla. 
https://drive.google.com/file/d/1IdwdEySqkgv68hpnKChTd-UUv8uRHWqO/view?usp=sharing

**Comment by Keksuccino** [comment]
Hi! That’s not a bug ^^ You have to set "hidelogo" to "true" in the config. And if you want to have the "discover more" footer enabled too, set "showmainmenufooter" to "true" too :)

**Comment by LordDecay26** [comment]
butyou said that in order to get the title screen you displayed all i had to do was install those folders... letdown
