### ISSUE TITLE
[1.19.4] Unable to open resource pack screen via `opengui`

### ISSUE THREAD

**Issue by R1kyy** [Keksuccino/FancyMenu#533]
it's the texturepack menu

**Comment by Keksuccino** [comment]
Could you at least tell me what menu that is?

**Comment by Keksuccino** [comment]
> it's the texturepack menu

Are you sure you're using the latest build of FancyMenu?

**Comment by R1kyy** [comment]
> What MC version, mod loader and FancyMenu version do you use?

1.19, latest FancyMenu versin (2.13.3), Prism Launcher

**Comment by R1kyy** [comment]
![image](https://user-images.githubusercontent.com/121554626/226212945-a96bfe07-a409-459a-aa65-78d6afccbbf5.png)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.14.1!
