### ISSUE TITLE
Animation isn't played until Minecraft window is focused

### ISSUE THREAD

**Issue by Rad586** [Keksuccino/FancyMenu#537]
**Describe the bug**
Animation(intro) sometimes isn't played until Minecraft window is focused.

**To Reproduce**
Actually I can't guarantee this will trigger the bug 100%.
1. Launch the game.
2. Minimize it. This is a must.
3. Restore Minecraft window.

**Expected behavior**
Loading animation even the window is minimized or not focused (like button rendering delay).

**Game Log**
https://gist.github.com/Rad233/d042eca02959206e36499a320d9723a1

**Screenshots**
Nope.

**Basic Informations (please complete the following information):**
 - Win10
 - FancyMenu 2.13.3
 - Fabric 0.14.17
 - Minecraft 1.18.2
 - many mods

**Comment by Keksuccino** [comment]
Animations are deprecated since FancyMenu v3 (replaced by APNGs), so I'm closing this.
