### ISSUE TITLE
2.14.0 Fancy Menu breaks text boxes in Drippy Loading Screen [Fabric 1.19.2]

### ISSUE THREAD

**Issue by SpigotDE** [Keksuccino/FancyMenu#539]
Text boxes don't show in the Drippy Loading Screen when you start the modpack.
They do show in the editor.

[latest.log](https://gist.github.com/SpigotDE/964d076bf3e1a93f4933542e5455ab6b)

Fabric Version 1.19.2
Fabric Loader 0.14.18
Fabric API 0.76.0
Drippy Loading Screen 2.1.1
Konkrete 1.6.0
Load My Resources 1.0.4

When the game starts:
![Screenshot (49)](https://user-images.githubusercontent.com/97298005/229536825-4dde48a0-e410-4560-af85-2096d4adc354.png)

In the editor:
![Screenshot (50)](https://user-images.githubusercontent.com/97298005/229536889-3be20ed1-2288-421e-ae5e-9d6d0fb6369d.png)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.14.1!
