### ISSUE TITLE
Edit Layout button moves the object underneath

### ISSUE THREAD

**Issue by Dekamir** [Keksuccino/FancyMenu#54]
**The bug**
When Edit Layout button is clicked, the object behind it moves to the cursor's location.
_This is a Minecraft bug, but can be worked around via a grace period after clicking the button._
This happens on every button (ex. 'Override existing layout' moves the image underneath when saving)

**To reproduce**
1. Have an object underneath Edit Layout button (ex. image, button)
2. Click on 'Edit Layout'

**Expected behavior**
The object underneath should not move.

**Screen capture**
![ezgif-6-26d450a48675](https://user-images.githubusercontent.com/28929300/86133960-b254ad80-baf1-11ea-91a9-458c024f8c58.gif)

**Basic informations**
 - OS: Windows 10 1909 x64
 - FancyMenu Version 1.3.1
 - Forge Version 31.2.28
 - Minecraft Version 1.15.2

**Comment by Keksuccino** [comment]
I  will try to fix this issue in the next update! Thank you for your report!

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.4! :)
