### ISSUE TITLE
1.19.2 Occasional Client crash

### ISSUE THREAD

**Issue by Saereth** [Keksuccino/FancyMenu#548]
**Describe the bug**
We are getting some users reports (And I finally had it happen myself to get a log) of the Mc instance crashing on load due to an NPE within FMM

**To Reproduce**
Steps to reproduce the behavior (e.g.):
We're usng he FTB Skies 1.19.2 modpack but the reproduction steps are just launch the pack
an rarely it will crash.

**Expected behavior**
I would expect it to consistently launch without a crash

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!
https://gist.github.com/Saereth/4e2e1d5ec0fd1cb5705dd495371f33da

**Basic Informations (please complete the following information):**
 - OS: Win 11 and ubuntuu 22 LTS reported
 - FancyMenu Version: fancymenu_forge_2.14.2_MC_1.19-1.19.2
 - Forge/Fabric Version [e.g. 31.2.24]: Forge 43.2.6
 - Minecraft Version [e.g. 1.15.1]: 1.19.2

**Comment by Keksuccino** [comment]
Should be fixed in FancyMenu v2.14.3! Thank you!
