### ISSUE TITLE
Add slider actions

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#549]
- Actions to set all the stuff you can control in vanilla MC's settings like:
  - FOV
  - Sound (all channels)
  - GUI scale
  - etc.

**Comment by xiPakuL** [comment]
As sliders are already in your current versions we only would need a preset variable we can target to set FOV etc.

**Comment by Keksuccino** [comment]
FancyMenu v3.0.0 added the ability to run actions on slider value change. There's also a "Set Minecraft Option Value" action now that will basically do exactly that.
