### ISSUE TITLE
1.16.1 - sethoverlabel not working on default buttons

### ISSUE THREAD

**Issue by bessiq** [Keksuccino/FancyMenu#55]
**Describe the bug**
Setting hover text works fine on a custom button I've created, but doesn't work on the default buttons, e.g. Singleplayer, Multiplayer, Mods, Quit Game.

**To Reproduce**
1. Set hover label to whatever text you want via GUI or config
2. Save/reload
3. Button text does not change on hover

**Expected behavior**
Buttons should show defined hover text. I'm not sure if this is a limitation of the default buttons and is only supposed to work for custom buttons, but it would be a shame if so!

**Log Snippet**
This is a section of what is spammed to my log whenever I hover over any of the aforementioned buttons:
[https://pastebin.com/0y3E8TFt](https://pastebin.com/0y3E8TFt)

**Screenshots**
n/a

**Basic Informations (please complete the following information):**
 - OS: W10 1909
 - FancyMenu: v1.3.1 MC 1.16.1
 - Forge Version: 31.2.41 (hover text didn't work on previous Forge versions also)
 - Minecraft Version: 1.16.1
 - Active Mods: https://pastebin.com/p7MKpBc3 (mods are changing frequently)

Incidentally (and I can make a separate issue if you want), once you change a button texture the Button Info no longer shows the button ID on hover. This happens on all buttons with a non-default texture.

Thanks for any help you can provide!

**Comment by bessiq** [comment]
It looks like the log errors persist even after removing the sethoverlabel customizations. Could be related to the custom hover texture I am using for buttons. But the texture does switch when I hover over them, so it's working. And there is no error produced in the log when I hover a custom button. Let me know if you need more info!

**Comment by Keksuccino** [comment]
Will be fixed in the next update, thank you for your report! :)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.4! :)
