### ISSUE TITLE
Recursive Resources is incompatible.

### ISSUE THREAD

**Issue by Blisterexe** [Keksuccino/FancyMenu#553]
**Describe the issue**
the game instantly crashes when i open the resource pack menu, it didnt do that before i installed the mod and it doesnt do that after i uninstalled it.

**Game Log**
<script src="https://gist.github.com/Blisterexe/3600e9e115e9e000eed3f14366385be6.js"></script>

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Fedora 38 beta
 - FancyMenu Version : 2.14.3
 - Forge/Fabric Version: Fabric 0.14.19
 - Minecraft Version: 1.19.2
 - Active Mods: too many to count, you can see it in the log.

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
