### ISSUE TITLE
[1.19.4 Fabric] Layout glitched when going from Single Player screen to Title screen

### ISSUE THREAD

**Issue by waddon1** [Keksuccino/FancyMenu#554]
**Describe the bug**
Menu does not load any elements when going back to menu from single player.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create a menu
2. Go into single player exit or back out to menu
3. Nothing loads other than panorama.

**Expected behavior**
Menu loads like it does when you first start the game.

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!
https://gist.github.com/waddon1/c9e41b00f0b00a38b8bfd6bca3a775e5

**Screenshots**
If screenshots would help to explain the issue, please include these.
![image](https://user-images.githubusercontent.com/14033361/234055036-24007bd3-aee1-4372-88cf-1bd7af054c31.png)

**Basic Informations (please complete the following information):**
 - OS: Linux
 - FancyMenu Version 2.14.7
 - Quilt Version 0.18.10
 - Minecraft Version 1.19.4
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] In log

**Comment by waddon1** [comment]
Can also confirm this occurs with just fancymenu installed

**Comment by Keksuccino** [comment]
Does it happen every time?

Can you send me your setup, please? To export your setup, click on **Setup -> Export** in the menu bar at the top of screens.

**Comment by waddon1** [comment]
[exported_fm_setup_25-4-2023-0-44-27.zip](https://github.com/Keksuccino/FancyMenu/files/11315347/exported_fm_setup_25-4-2023-0-44-27.zip)

**Comment by waddon1** [comment]
Forgot to say, but yet it does happen every time

**Comment by Keksuccino** [comment]
So I just tried to reproduce it with your setup and on Fabric, it does load the elements correctly, but the auto-scaling is broken until you resize the screen.
Will try to fix this, thank you for the setup!

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
