### ISSUE TITLE
Incompatibility with Dave's Potioneering and Optifine

### ISSUE THREAD

**Issue by JawboTau** [Keksuccino/FancyMenu#556]
**Describe the issue**
After selectively disabling certain mods at a time, I found that the combination of the 3 mods (5 including libraries) below causes a crash, near the end of loading.

**Game Log**
https://gist.github.com/JawboTau/56bd183f7c4f4ca34e1bf7f8e19340a5

**Screenshots**
![image](https://user-images.githubusercontent.com/129625734/234156540-a169803c-c4d0-4ef7-9686-cefa113c6e3e.png)

**Basic Information (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.14.7
 - Forge Version 36.3.34
 - Minecraft Version 1.16.5
 - Active Mods: 
   - **Dave's Potioneering**, 
   - **FancyMenu**, 
   - GeckoLib, 
   - Konkrete, 
   - **Optifine**, 

I also tried adding OptiForge, in hopes that it would fix the crash, but it does not.
All mods are the latest version compatible with 1.16.5 as of this time.

**Comment by JawboTau** [comment]
Upon further testing, this is not an issue with FancyMenu, but with Dave's Potioneering and Optifine.

**Comment by Keksuccino** [comment]
https://fm.keksuccino.dev/en/wiki/general/verified/optifine-alternatives :)
