### ISSUE TITLE
missing title of window in 1.12.2

### ISSUE THREAD

**Issue by MeinKraft** [Keksuccino/FancyMenu#56]
**Describe the bug**
with a clean install (Forge and FancyMenu), the title of the minecraft window appears blank

**To Reproduce**
1. Install Just Forge and FancyMenu
2. Run Minecraft
3. Watch the title of Minecraft Window
4. It is blank

**Expected behavior**
To have a default title.  Maybe have a default title set in the config of `S:customwindowtitle = 'Minecraft 1.12.2';`

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.4_MC_1.12-1.12.2
 - Forge Version 14.23.5.2854
 - Minecraft Version 1.12.2
 - Active Mods NONE

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.4.1! Thank you for your report! :)
