### ISSUE TITLE
Allow custom slider elements to mimic vanilla slider functionalities such as FOV

### ISSUE THREAD

**Issue by electrified0** [Keksuccino/FancyMenu#561]
I'm trying to override the vanilla options menu because it has a button from the Essential Mod that can't be removed by FancyMenu. The custom GUI is finished for the most part, the only problem is that I can't add back the FOV slider.

My suggestion is that you allow users to assign a vanilla action to the slider element. This can be FOV (all I need right now), and possibly volume and chat settings in the future. This feature would be greatly appreciated!

**Comment by Keksuccino** [comment]
Duplicate of #463
