### ISSUE TITLE
[1.19.2] Misalignment after opening menus

### ISSUE THREAD

**Issue by itsdinkd** [Keksuccino/FancyMenu#562]
**Describe the bug**
After updating i noticed a bug were if I go to the multiplayer menu and back to the main menu my modpack menu is misaligned. 

I was using fancymenu_fabric_2.14.3_MC_1.19 in AQM2 and this issue never happened before... only until I went from 2.14.3 to 2.1.4.7

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Download AQM2 v1.5.2
2. I have two menu types, one for large resolution, other for smaller (< 1920x1440). Issue happens on larger menu for higher resolutions
3. Game Launch
4. Observe Menu and its layout
5. Open Multiplayer
6. Go back to main menu
7. viola. bug.

**Expected behavior**
To stay aligned, and not have elements move around.

**Game Log**
https://gist.github.com/itsdinkd/835d272a7911c84a85a6e2ff41209535

###Screenshots
**Ultrawide Resolution (Pre multiplayer screen, initial menu)**
![image](https://user-images.githubusercontent.com/35115304/235326060-0adf27d0-7214-4fec-8ecf-9c483829ed1b.png)

**Ultrawide Resolution (Post multiplayer screen and going back)**
![image](https://user-images.githubusercontent.com/35115304/235326044-0d583c63-2121-4737-86ac-d735283fca4f.png)

###Basic Informations (please complete the following information)
 - OS: W11
 - FancyMenu Version [e.g. 0.2] fancymenu_fabric_2.14.7_MC_1.19
 - Forge/Fabric Version [e.g. 31.2.24]  0.76.0
 - Minecraft Version [e.g. 1.15.1] 1.19.2
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] a lot... + iris

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
