### ISSUE TITLE
Game freezes with OpenGL "Out of VRAM" error message after setting the background to an animation

### ISSUE THREAD

**Issue by MCAlexisYT** [Keksuccino/FancyMenu#564]
The animation shown on the Curseforge page doesn't work. At all. So I had to redo the entire thing with the animation maker and export it only to to be met with a freeze and "OpenGL debug message: id=1285, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_OUT_OF_MEMORY in (null): (ID: 173538523) Generic error'" being spammed in the logs after I got jumpscared from the sheer volume and took my wired headphones off (bluetooth audio doesn't work with Minecraft: Java Edition in my experience).

https://github.com/Keksuccino/FancyMenu/assets/78766083/288e84c9-d8b1-4aad-820a-a1ffad10f89e

**Comment by Keksuccino** [comment]
Well, as the error message says, you’re out of memory. Use less frames. Recommended max frames for animations are 200 at a max resolution of 1080p.
