### ISSUE TITLE
The position of the full screen and window mode buttons is incorrect

### ISSUE THREAD

**Issue by FanRenLa** [Keksuccino/FancyMenu#566]
**Describe the bug**
A clear and detailed description of what the bug is.
The position of the full screen and window mode buttons is incorrect
**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Full screen
2. window
You can see the obvious change

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!

**Screenshots**
If screenshots would help to explain the issue, please include these.
![image](https://github.com/Keksuccino/FancyMenu/assets/83486178/b106e17f-68c1-4486-a88b-e84e0a54d55a)
![image](https://github.com/Keksuccino/FancyMenu/assets/83486178/00d4b84c-3bbf-4490-9c04-f4d237c61b22)
![image](https://github.com/Keksuccino/FancyMenu/assets/83486178/b1a5d30d-e07e-4289-9093-41f67babc3cc)

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows]
 - FancyMenu Version [fancymenu_forge_2.14.7_MC_1.16.2-1.16.5]
 - Forge/Fabric Version [forge36.2.39]
 - Minecraft Version [1.16.5]
 - Active Mods [konkrete_forge_1.6.1_MC_1.16.2-1.16.5, drippyloadingscreen_forge_2.2.1_MC_1.16.5]

**Comment by Keksuccino** [comment]
https://fm.keksuccino.dev/en/wiki/general/verified/orientations
