### ISSUE TITLE
Where did the 1.8.9 version go?

### ISSUE THREAD

**Issue by sennecoolgames** [Keksuccino/FancyMenu#567]
I know that the 1.8.9 version is no longer supported but I ealso cant find the mod anywhere please bring it back I really need it.

**Comment by Keksuccino** [comment]
Hi! The 1.8.9 version was really unstable and old. That's why it is no longer available.

**Comment by sennecoolgames** [comment]
cant you just release the source code so the more technical people who really want it can compile it themselves?

**Comment by Keksuccino** [comment]
The CurseForge release is public again, but you really should not use this in public modpacks: https://legacy.curseforge.com/minecraft/mc-mods/fancymenu-forge/files/3141749
