### ISSUE TITLE
[1.16.1] Loading Screen Dark Mode removes FML Loading Info (image in desc.)

### ISSUE THREAD

**Issue by Gbergz** [Keksuccino/FancyMenu#57]
**Describe the bug**
Title^, but yeah the FML Loading Info disappears when turning on Dark Loading Theme/Mode.
Turning dark mode off fixes this issue.

**To Reproduce**
1. Have FancyMenu installed.
2. Start the game first to generate config.
3. Turn on Dark Mode in config.
3. Boot the game again
4. FML Loading info gone.

**Expected behavior**
It still being there like in the update before the last one.

**Screenshots**
![infoloadinggone](https://user-images.githubusercontent.com/26634554/87244449-b9f34b00-c43d-11ea-9c63-efe598b3a782.PNG)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.4
 - Forge Version 32.0.63
 - Minecraft Version 1.16.1
 - Active Mods [Modlist](https://github.com/The-Nexus-Project/Limitless-3/blob/master/modlist)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.4.1! Thank you for your report! :)
