### ISSUE TITLE
Impossible to save!

### ISSUE THREAD

**Issue by EntrGame** [Keksuccino/FancyMenu#570]
The layout cannot be saved due to the inability to enter the name of the layout.

1. Go to 'Layout'
2. Click on 'Save As'
3. See...

I just want to keep the layout...

Game Log -
https://gist.github.com/EntrGame/f3ed7ff0d9d075a3119a250bdcc5a1d7

Screenshots -
![image](https://github.com/Keksuccino/FancyMenu/assets/65180019/1f03d98f-aadb-4183-a46d-5e8df93b2aa6)
![image](https://github.com/Keksuccino/FancyMenu/assets/65180019/f58c110a-11c9-4e18-a582-578c5cc96b46)

 - OS: Windows 11
 - FancyMenu Version 2.14.7
 - Forge/Fabric Version 0.14.21
 - Minecraft Version 1.20
 - Active Mods: FcancyMenu, Konkrete, Fabric API, Load My Resouces

**Comment by Keksuccino** [comment]
Update your FancyMenu to the latest version.
