### ISSUE TITLE
Crash when booting game after latest update (v2.14.8-1)

### ISSUE THREAD

**Issue by Gbergz** [Keksuccino/FancyMenu#572]
**Describe the bug**
Crash when booting on latest update ([v2.14.8-1](https://www.curseforge.com/minecraft/mc-mods/fancymenu-forge/files/4600125))

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Download latest update fancy menu, v2.14.8-1
2. Be on latest forge 47.0.14
3. Start game.

**Expected behavior**
No crashes when booting.

**Game Log**: https://gist.githubusercontent.com/Gbergz/db5ec5f732658a5cfeae0abb581aa231/raw/0141ed7b8395a65ad61284630a64495ec2fe90ed/gistfile1.txt

**Crash-report:** https://gist.githubusercontent.com/Gbergz/61b22714004960b24c683fbaa7354f7b/raw/f0fa7924940b887ef533e0fc1a599b1d08045239/gistfile1.txt

**Basic Informations:**
 - OS: Windows 11
 - FancyMenu Version 2.14.8-1
 - Forge/Fabric Version 47.0.14
 - Minecraft Version 1.20.1
 - Active Mods: https://gist.githubusercontent.com/Gbergz/e0cca8d88afe1fd0dcfcae16f6b1db32/raw/e20a461613fffbd7856a726c0246a98e302a26ec/gistfile1.txt

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.14.8-2! Thank you!
