### ISSUE TITLE
help with buttons and options_background

### ISSUE THREAD

**Issue by MolodecKDR** [Keksuccino/FancyMenu#573]
hello! I need help in FancyMenu - when exporting my installation, when transferring the installation to another build, the background of the buttons and options_background are reset. how to fix it??

**Comment by MolodecKDR** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/129216532/7822256f-f8b1-4d48-9e35-04d471067b5a)

**Comment by Keksuccino** [comment]
Your layout resources probably don't get copied over. Copy them manually.

KubeJS has nothing to do with FancyMenu and will not get exported when exporting setups. You need to separately copy all KubeJS stuff.

For future questions, please join the Discord server, thank you very much! :)
#569
