### ISSUE TITLE
[1.18.2]Invalid animation settings

### ISSUE THREAD

**Issue by GufengOnline** [Keksuccino/FancyMenu#574]
**Describe the bug**
Custom animation settings have no effect

**To Reproduce**
1、The animation was created according to the wiki
2、Animate the main menu background
3、The animation is invalid

**Game Log**
https://mclo.gs/f3OoXse

**Screenshots**
The main menu with the animation set
![屏幕截图 2023-06-29 094526](https://github.com/Keksuccino/FancyMenu/assets/137476878/f6aa1de8-587e-4cbe-bba6-ed219c0636b3)
The game's opening animation is stuck
![屏幕截图 2023-06-29 095116](https://github.com/Keksuccino/FancyMenu/assets/137476878/7f7a0435-d4c9-4f5b-9a48-e771ada10c5c)

**Basic Informations (please complete the following information):**
 - OS: Windows11
 - FancyMenu Version 2.14.7
 - Forge/Fabric Version forge40.2.9
 - Minecraft Version 1.18.2
 - Active Mods Create,Project Rankine

**Comment by Keksuccino** [comment]
Please load the game with only FancyMenu + dependencies installed. Could be a mod conflict.

**Comment by GufengOnline** [comment]
Well, I was stupid, I forgot to add the loadmyresources mod

**Comment by GufengOnline** [comment]
> 请在仅安装花式菜单 + 依赖项的情况下加载游戏。可能是模组冲突。

好吧，我很愚蠢，我忘了添加加载我的资源模组

**Comment by GufengOnline** [comment]
> Please load the game with only FancyMenu + dependencies installed. Could be a mod conflict.

Well, I was stupid, I forgot to add the loadmyresources mod
