### ISSUE TITLE
Baby player has oversized cape that does not turn off 

### ISSUE THREAD

**Issue by KajesLorian** [Keksuccino/FancyMenu#576]
**Describe the bug**
When player entity element is present and set to "Copy Current Player" there is no way to turn off the cape, even if it is off in the options. When entity is set to "is baby" the cape stays the same size behind entity. There is no way to turn off the cape when "Copy Current Player" is set to on.

**Expected behavior**
I would like to be able to set the player entity element to baby and take on the appearance of the player who logs on (not only my character) without the cape looking like a banner floating behind them.

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/16963626/83b3c121-5f40-4c6f-9d0e-a4d0ee0c98c3)

**Basic Information**
 - OS: Windows 10
 - FancyMenu Version [Forge] v2.14.7 MC 1.19-1.19.2
 - Forge/Fabric Version 43.2.8
 - Minecraft Version 1.19.2

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
