### ISSUE TITLE
Player entity and splash text not showing in main menu

### ISSUE THREAD

**Issue by Kamix13** [Keksuccino/FancyMenu#581]
Player entity and splash text not showing in the main menu. Everything was working fine, but when I added some resourcepacks (and then turned them off - nothing changed) Player entity and splash text just stopped showing in main menu. The Player entity is an element I can still have interaction with, but it's just invisibile, it has it's grid and everything, but just isn't visible. The splash text tho disappeard without any reason and cannot be interacted with, it doesn't have grid, and options to the element, and not only that, it just disappeard without any reason and warning indeed, it just deleted itself. When I add splash text as a vanilla element, it has it's grid back in and "appears" as an element I can have interaction with, but isn't visible, same like player entity

 - Win 11
 - FancyMenu 2.1.1.0
 - Fabric 
 - Minecraft 1.19

Items are there, can be interacted with, have it's default settings, but are invisible without any reason!
![Zrzut ekranu 2023-07-10 163012](https://github.com/Keksuccino/FancyMenu/assets/136904448/dc6d3a02-7838-4886-8245-105f281b8648)
![Zrzut ekranu 2023-07-10 163018](https://github.com/Keksuccino/FancyMenu/assets/136904448/22bff9e6-58e9-475b-96b5-188d1f3ab03a)
![Zrzut ekranu 2023-07-10 163025](https://github.com/Keksuccino/FancyMenu/assets/136904448/1615e233-922a-4d9b-81a0-ecde187457a5)

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
