### ISSUE TITLE
[1.20.1]The delayed appearance feature of the button doesn't work

### ISSUE THREAD

**Issue by latiaotiao** [Keksuccino/FancyMenu#582]
**Describe the bug**
A clear and detailed description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior (e.g.):

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows]
 - FancyMenu Version [e.g. 0.2]
 - Forge/Fabric Version [e.g. 31.2.24]
 - Minecraft Version [e.g. 1.15.1]
 - Active Mods [e.g. Optifine, 5zig, TooManyItems]

**Comment by JAVIxcr** [comment]
I am using fancymenu_forge_2.14.8_MC_1.20.1.jar and still having this issue

**Comment by adamk33n3r** [comment]
Ya delayed appearance doesn't work for anything I've tested.

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
