### ISSUE TITLE
Last Joined World button shows tooltip while loading

### ISSUE THREAD

**Issue by FooterMan15** [Keksuccino/FancyMenu#583]
**Describe the bug**
When a Tooltip is applied to a button that loads the last joined world, when the button is pressed the tooltip will stick around until the game is loaded.

**To Reproduce**
Make a button that loads the last joined world.
Add a tooltip to it with whatever.
Press the button.

**Expected behavior**
No sticky tooltip 😆 

**Game Log**
https://gist.github.com/FooterMan15/6272ccca0d174efaf1881191ff78d8f2

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/71946346/ee3eb647-313e-4f16-85f6-65f997d49324)

**Basic Informations (please complete the following information):**
 - OS: [Win11]
 - FancyMenu Version [2.14.7]
 - Forge/Fabric Version [🔨 43.2.8]
 - Minecraft Version [1.19.2]
 - Active Mods - https://legacy.curseforge.com/minecraft/modpacks/fun-in-the-sky/relations/dependencies

**Comment by FooterMan15** [comment]
Oops, sorry forgot to mention, the button sound is also late, it'll only play after the world is loaded.

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
