### ISSUE TITLE
Very Little Menu on macOS "basic screen"

### ISSUE THREAD

**Issue by 91leMAC** [Keksuccino/FancyMenu#585]
**Describe the bug**
I use fancy menu, for a while, and I'm on a Macbook 13,3" with a screen : 2560 × 1600. All the Fancy's GUI are very small
**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Use a MacBook pro 13" and launch Minecraft on the retina screen

**Expected behavior**
A normal size GUI, I have it when I play on my external display 1920x1080 (but I can't for the moment use it)

**Screenshots**
I'll giving you screenshot :
https://cdn.discordapp.com/attachments/904114944344195172/1134135564392726588/CleanShot_2023-07-27_at_16.45.092x.png

**Basic Informations (please complete the following information):**
 - OS: macOS
 - FancyMenu (all versions)
 - Forge/Fabric Version (all versions)
 - Minecraft Version (all versions)
 - Active Mods (no specific mods)

PS : 
I try with many others Fancy menu & Minecraft menu versions.

**Comment by Keksuccino** [comment]
That's not a bug, your just need to set FancyMenu's UI Scale to `2`.
To set the UI Scale, open FancyMenu's settings by clicking on the little FM button in the top-left corner.
