### ISSUE TITLE
Button Action Open Link breaks on press "Done"

### ISSUE THREAD

**Issue by spiro-angelakis** [Keksuccino/FancyMenu#586]
**Describe the bug**
A clear and detailed description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Add a Button
2. Manage Actions
3. Add Open Link Action
4. Add Action Value
5. Upon pressing Done, placeholder text will infinitely paste into code box never letting u finish adding the action value

**Expected behavior**
done button shouldnt do anything other than let you finish adding the action value

 - OS: Windows
 - FancyMenu Version 2.14.9
 - Forge/Fabric Version 43.2.21
 - Minecraft Version 1.19.2

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
