### ISSUE TITLE
Mod 1.19.4 Realm notification

### ISSUE THREAD

**Issue by LeSpatiocorne** [Keksuccino/FancyMenu#587]
The presentation video had an option to hide the realm light, but this button isn't anymore in FM menu, and I didn't any config to modify it. Is the feature depreciated or temporarily disabled on this version ?
![image](https://github.com/Keksuccino/FancyMenu/assets/97949654/5dcc0e4a-2b9c-403b-8a4c-6781f05cba41)

(Sorry if it's the wrong place, I wasn't sure about how to get the info)

**Comment by Keksuccino** [comment]
It's an element in the layout editor now. Open a layout of the Title screen in the layout editor and hide the newspaper element.
