### ISSUE TITLE
Choose File doesn't work

### ISSUE THREAD

**Issue by J4V4SCRYPT** [Keksuccino/FancyMenu#59]
I am using your mod on my mbp 2017 with touchbar.
Im not sure why but every time I try to input the filename manually for custom background it wont work. Then clicking choose wont work either

**Comment by Keksuccino** [comment]
- Which mod version
- Which MC version
- Which Forge version
- What do you mean by "it won’t work"

**Comment by J4V4SCRYPT** [comment]
oh thats nice to know but also
my path wont work either
"Invalid picture or path"

**Comment by Keksuccino** [comment]
macOS version
Mod version
MC version
Forge version
What do you mean by "it won’t work"

**Comment by skitzozombie25** [comment]
iam having the   same issue  windows  10 forge version 1.16.1 32.0.66 mod version 1.4.1 the button to choose does not work neither does specifing the location of  buttons

**Comment by Keksuccino** [comment]
Hi! Do you use any other mods along with FancyMenu?

**Comment by Keksuccino** [comment]
@J4V4SCRYPT Is still need more informations, dude ^^ What is your Minecraft version, what is your Forge version, what macOS you're using, what FancyMenu version you’re using and do you use any other mods along with FancyMenu?

There is a bug report template, please try to use this the next time, I can’t help you if I have no informations.

**Comment by J4V4SCRYPT** [comment]
Ok Sorry.
Minecraft Version -> 1.12.2 = Forge
(Forge has to be the same as 1.12.2)
macOS -> Mojave
Architecture -> x64
FancyMenu Version -> fancymenu_1.2_MC_1.12-1.12.2
I use my own hack client. Along with your fancymenu mod. My hack client doesnt mess around with anything except for the ingame GUI
What else do u need? That should be ok right?

**Comment by Keksuccino** [comment]
You’re using a very old build of FancyMenu. The problem you’re describing was a bug in this version. Please update to the newest build and check if it still doesn’t work.

Oh and no, your forge version is not 1.12.2 :D You’re using one of the 1.12.2 builds of forge. You can see your forge version when clicking on the mods button in the main menu and check the version number of the "Forge" entry :)

**Comment by J4V4SCRYPT** [comment]
Thanks. It ended up working it bootcamp windows so i will call it a day 👍  thanks :))

**Comment by Keksuccino** [comment]
But please, you should really update to FancyMenu v1.4.1. The old version you’re using had so much bugs and was really unoptimized..
