### ISSUE TITLE
[MC 1.16.5+] Game crashes at the start with Intel integrated low Graphic Card

### ISSUE THREAD

**Issue by JAVIxcr** [Keksuccino/FancyMenu#592]
**Describe the bug**
I have a Minecraft series called PuchaCraft (you can find it in Twitter or Twitch), and a player has reported that the game crashes when he is trying to start it in the main menu animation. 

I guess, this is happening when the computer doesn´t have a dedicated video card, because the issue is happening with my friend that has an Intel integrated video card, and this user has an Intel too.

My friend, at the start of the series, has the same issue with Fancy Menu, and I just created another Minecraft instancy (client version) without the Fancy menu and it worked.

I don't know if this is the main issue, however, since the error happened twice, I just want to advice it in order to help with this wonderful mod.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
It doesn´t have any steps, the user starts the game, and it crashes.

**Expected behavior**
I just want to advice it if the issue is happening if the user doesn´t have a high end pc gamer

**Game Log**
I don´t have files, however Im getting this info right now

**Screenshots**
No screenshots

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.13.3
 - Forge/Fabric Version 36.2.34
 - Minecraft Version 1.16.5

**Comment by Keksuccino** [comment]
Sounds more like they run out of RAM.
