### ISSUE TITLE
Game freezes every 1 - 3 seconds with this mod on

### ISSUE THREAD

**Issue by Shizzins** [Keksuccino/FancyMenu#593]
**Describe the bug**
A clear and detailed description of what the bug is.

When I enable my Layout and join a game, my game starts to freeze every 1 - 3 seconds and it's unbearable. I have to deactivate my layout for it to play like normal, why is this?

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Select Custom Layout
2. Play game

**Expected behavior**
My Modpack playing as normal.

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!
https://gist.github.com/Shizzins/4b65d2f76383c08d1bf4e3e4a02eea57

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows]
 - FancyMenu Version [e.g. 0.2] - 2.14.9
 - Forge/Fabric Version [e.g. 31.2.24] - 36.2.39
 - Minecraft Version [e.g. 1.15.1] -1.16.5
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] - Better Minecraft Modpack

**Comment by Keksuccino** [comment]
Please send me your layout file located at `config/fancymenu/customization`.

**Comment by Shizzins** [comment]
[ererer.txt](https://github.com/Keksuccino/FancyMenu/files/12403818/ererer.txt)

**Comment by Keksuccino** [comment]
Try to remove the player entities from the layout. Could be some sort of mod conflict.

Layout and log looks okay (even tho the log is a frickin book), it _should_ work fine.

**Comment by Keksuccino** [comment]
Closed because not reproducible and probably just a mod conflict.
