### ISSUE TITLE
Incompatibility with Remove Reloading Screen

### ISSUE THREAD

**Issue by Nukecraft5419** [Keksuccino/FancyMenu#597]
**Describe the bug**
Apparently Fancy Menu has problems with Remove Reloading Screen here is a clip where it shows the problem

https://github.com/Keksuccino/FancyMenu/assets/72621737/264c5ac1-3f24-4087-b4c0-c676ebc84758

**To Reproduce**
Steps to reproduce the behavior (e.g.):

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows 11 [e.g. Windows]
 - FancyMenu Version [e.g. 2.14.7]
 - Forge/Fabric Version [e.g. 0.14.22]
 - Minecraft Version [e.g. 1.20.1]
 - Active Mods https://github.com/LifeMC-Studios/LifeMC/tree/main/Packwiz/1.20.1/mods

**Comment by Nukecraft5419** [comment]
Opened over discord

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!

**Comment by Nukecraft5419** [comment]
Thank you very much you are one of the best developers my modpack is going well thanks also to you who created FancyMenu
