### ISSUE TITLE
Incompatibility with Axiom

### ISSUE THREAD

**Issue by ISteam14** [Keksuccino/FancyMenu#598]
I play on a build with fancymenu and axiom mods, and sometimes the game crashes for no reason, crashes also happen when I try to open the axoim menu using the alt button

**To Reproduce**
1. enter the world
2. press alt
3. the game crashes
Also, crashes sometimes occur, possibly due to minimizing the game while in the axoim edit menu
 
**Game Log**
[latest.log](https://github.com/Keksuccino/FancyMenu/files/12598737/latest.log)

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - FancyMenu Version 2.14.9
 - Fabric Version 0.14.22
 - Minecraft Version 1.20.1
 - Active Mods:
•	alternate-current-mc1.20-1.7.0
•	amecs-1.3.9+mc.1.20.1
•	appleskin-fabric-mc1.20-2.5.0
•	architectury-9.1.12-fabric
•	Axiom-1.2.4-for-MC1.20.1
•	balm-fabric-1.20-7.0.4
•	BetterAdvancements-Fabric-1.20.1-0.3.2.161
•	betterbarriers-1.0.0
•	BetterPingDisplay-Fabric-1.20.1-1.1.1
•	better-selection-1.2
•	BetterSmithingTable-1.1.0-Fabric-1.20
•	biomemoss-1.1.0
•	chat_heads-0.10.20-fabric-1.20
•	chatsounds-1.1.9
•	CITResewn-1.1.3+1.20
•	clickthrough-1.20-fabric0.83.0-0.4.1
•	clienttweaks-fabric-1.20-11.0.0
•	cloth-config-11.1.106-fabric
•	collective-1.20.1-6.65
•	colorfulhearts-fabric-1.20-4.0.0
•	compact-chat-2.0.2
•	ContainerSearch-1.0.0-Fabric-1.20
•	continuity-3.0.0-beta.2+1.20
•	DisableCustomWorldsAdvice-4.1
•	dynamic-fps-2.4.0
•	eating-animation-1.9.4+1.20
•	emotecraft-for-MC1.20.1-2.2.7-b.build.50-fabric
•	EmoteTweaks-4.0.2.27-fabric
•	enhancedblockentities-0.9+1.20
•	entity_model_features_fabric_1.20-0.2.13
•	entity_texture_features_fabric_1.20-4.5.0
•	entityculling-fabric-1.6.2-mc1.20
•	experienceprogress-1.1.0+1.20
•	extremesoundmuffler-3.38-fabric-1.20
•	fabric-api-0.85.0+1.20.1
•	fabric-carpet-1.20-1.4.112+v230608
•	fabric-language-kotlin-1.9.6+kotlin.1.8.22
•	fabricskyboxes-0.7.2+mc1.20.1
•	fallingleaves-1.15.1+1.20.1
•	fastitems-1.0.0-mc1.20.1
•	fastquit-3.0.0-beta.2+1.20+
•	Female-Gender-Mod-fabric-1.20-3.0.1
•	ferritecore-6.0.0-fabric
•	foodeffecttooltips-1.1.1-1.20.0
•	ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
•	Gamma-Utils-1.7.15-mc1.20.1
•	guiclock-1.20.1-4.2
•	held-item-info-1.5.0
•	ImmediatelyFast-1.1.15+1.20.1
•	improved-fire-overlay-1.20.1-v3
•	indium-1.0.25+mc1.20.1
•	konkrete_fabric_1.6.1_MC_1.20
•	lambdynamiclights-2.3.1+1.20.1
•	language-reload-1.5.8+1.20.1
•	litematica-fabric-1.20.1-0.15.3
•	lithium-fabric-mc1.20.1-0.11.2
•	lootbeams-1.0.3
•	make_bubbles_pop-0.1.1
•	malilib-fabric-1.20.1-0.16.2
•	mcwifipnp-1.6.6-1.20.1-fabric
•	mica-1.0.0
•	modernfix-fabric-5.7.2+mc1.20.1
•	modmenu-7.1.0
•	motionblur-1.0.2+mc1.20
•	nbtvoid-1.1.4
•	noHurtCam+-2.3.1-1.20.1
•	no-report-button-fabric-1.5.0
•	no-resource-pack-warnings-1.3.0
•	notenoughanimations-fabric-1.6.4-mc1.20
•	online-emotes-2.1.1-fabric
•	optigui-2.1.2
•	owo-lib-0.11.1+1.20
•	perspective-1.1.2+1.20.x
•	perspektive-1.3.3
•	pingspam-1.3.1+1.20
•	player-animation-lib-fabric-1.0.2-rc1+1.20
•	qfapi-7.2.2_qsl-6.1.2_fapi-0.88.1_mc-1.20.1
•	raised-fabric-1.20.1-2.0.0
•	raisedxappleskin-fabric-1.20.1-2.5.0
•	recursive-resources-2.5.2+1.20
•	replaymod-1.20.1-2.6.13
•	SaveMod-fabric-mc1.20.1-1.4.3
•	screenshot_viewer-1.1.7-fabric-mc1.20
•	Searchables-fabric-1.20.1-1.0.1
•	shulkerboxtooltip-fabric-4.0.4+1.20.1
•	simple-armor-hud-1.20.1-1.3.1
•	skin-restorer-1.2.3
•	sodium-extra-0.5.1+mc1.20.1-build.112
•	sodium-fabric-mc1.20.1-0.5.2
•	spyglass_astronomy-1.0.5-mc1.20+
•	status-effect-bars-1.0.3
•	Sunshine-1.1.1
•	TaxFreeLevels-1.3.3-fabric-1.19
•	titlefixer-1.0+1.20.1
•	tooltipfix-1.1.1-1.20
•	voicechat-fabric-1.20.1-2.4.24
•	whydoesmyglasssoundlikethat-1.1.0
•	worldedit-mod-7.2.15-1.20.1
•	yet-another-config-lib-fabric-3.1.0+1.20
•	Zoomify-2.10.0

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.14.10.

**Comment by Liamgrayskull** [comment]
Is there any possibility this patch could be ported over to the forge version in order to be compatible with Sinytra Connector? I've discovered the same crash occurs with the forge version of all mods but Axiom, and the fabric Fancy Menu and Konkrete currently crash upon loading with Sinytra.
