### ISSUE TITLE
[1.19.2] CRASH with Fancy Menu (unregistered/unidentifiable Konkrete dependency?)

### ISSUE THREAD

**Issue by Wanderer70** [Keksuccino/FancyMenu#599]
The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance
Exit Code -1

[Crash Report](https://mclo.gs/rENQ05z)
[Latest Log](https://mclo.gs/bweuWkj)

**In the latest log it says that I do not have Konkrete installed, but I do.**

**Comment by Keksuccino** [comment]
1. Try to start the game with only FancyMenu + dependencies installed
2. If step 1 fixed it, try to search for what mod is breaking something

The log says something about Iris, but FancyMenu and Iris should work fine together.

**Comment by Wanderer70** [comment]
Nope, having just the 3 installed I still get a crash. Konkrete is not seen by the game. (Forge 1.19.2)
![Screenshot (722)](https://github.com/Keksuccino/FancyMenu/assets/97387920/de0893a5-69e9-42fc-ab70-2694860a4afa)

**Comment by Wanderer70** [comment]
Hey, I downgraded to Konkrete 1.6.0 and now it works! Turns out Konkrete 1.6.1 is not supported by Fancy Menu then?

**Comment by Keksuccino** [comment]
It is supported and should work fine. Maybe the JAR was corrupted or something?

**Comment by Wanderer70** [comment]
Reinstalling the latest version of Konkrete does not solve the problem. Maybe there is some kind of incompatibility between the newer releases of Forge that makes the two not recognize each other?

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
