### ISSUE TITLE
Minecraft Realms issue/request?

### ISSUE THREAD

**Issue by slard3** [Keksuccino/FancyMenu#6]
**Describe your idea**
![image](https://user-images.githubusercontent.com/55768134/78091810-5bc9bd00-73a4-11ea-9e36-65f0eb3f3d0c.png)
There are those MC Realms notification and free trial icons (I'm simply gonna use a resource pack to get rid of them). I'm pointing it out to you, in case you wanted to add to the mod some overriding textures for those icons since the action to "hide a button" doesn't hide them obviously.

By the way this mod is a fantastic upgrade from FancyMain, thanks a lot for this.

**Comment by slard3** [comment]
Giving this a second thought, I think it's easier to simply give directions to people to what they must replace:
the icons are here: assets\realms\textures\gui\realms
and the name of the files to replace are:
news_notification_mainscreen.png
trial_icon.png

**Comment by Keksuccino** [comment]
There is a config option in FancyMenu to disable the realms notification indicators :D 

> By the way this mod is a fantastic upgrade from FancyMain, thanks a lot for this.

Thank you very much! I always try to improve it more and there’s planned some good stuff for the next updates! :D

**Comment by slard3** [comment]
Thanks for the reply! Couldn't find it because it wasn't mentioned in any page, tho dumb of me for not looking thoroughly.
Now, is there a way to move the splash text instead of simply removing it? I kind of like it and in the menu it looks a bit off.

**Comment by Keksuccino** [comment]
No, it’s my fault. I really need to write a wiki page about the config :D 

I want to add some menu-specific actions to the customization system, so I could add an action to move the splash text too :)

**Comment by JJRicks** [comment]
Moving splash text would be great!
