### ISSUE TITLE
[1.12] no panorama overlay

### ISSUE THREAD

**Issue by Moonyol** [Keksuccino/FancyMenu#601]
**Describe the bug**
the panorama overlay is removed when customization is on 

**To Reproduce**
Steps to reproduce the behavior :
0. go to main menu
1. press ctrl alt c to show the bar
2. press current menu and turn on customization
3. the panorama overlay is gone

**Expected behavior**
the panorama having its overlay on and looking 

**Screenshots**
customization off: ![image](https://github.com/Keksuccino/FancyMenu/assets/92951072/9fc8c971-3440-485e-9358-0a146eb139e8)
customization on: ![image](https://github.com/Keksuccino/FancyMenu/assets/92951072/65dd8345-0a39-4f64-ab03-adf4debfcab3)

**Basic Information:**
 - OS: Windows
 - FancyMenu Version 2.14.9
 - forge 14.23.5.2860
 - Minecraft Version 1.12.2
 - Active Mods ![image](https://github.com/Keksuccino/FancyMenu/assets/92951072/578defac-3b86-4086-84b9-7fa975443826)

**Comment by Moonyol** [comment]
just noticed that it also raised the copyright text a few pixels

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.

**Comment by Keksuccino** [comment]
Oh nvm, it's 1.12..
But that looks like a mod conflict. Try to remove all mods except FM + dependencies.
If you have more questions, please join the Discord: #569
