### ISSUE TITLE
[1.12] panorama moving faster

### ISSUE THREAD

**Issue by Moonyol** [Keksuccino/FancyMenu#602]
**Describe the issue**
the panorama is moving faster (when customization is turned on) with any of the mods listed at the bottom

**Game Log**
nothing in log after it happens

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.14.9
 - Forge Version 14.23.5.2860
 - Minecraft Version 1.12.2
 - Active Mods: 
 ![image](https://github.com/Keksuccino/FancyMenu/assets/92951072/02bbf2d2-55c4-46e3-9232-98eb3514d40c)
 ⠀+ any of these; 
![image](https://github.com/Keksuccino/FancyMenu/assets/92951072/0234601e-116f-4d1e-96d9-8ad5dbc84fd2)

**Comment by Keksuccino** [comment]
As you already discovered, it's probably a mod conflict, so try to find the mod that causes it. The only way to fix this is to remove the conflicting mod. If you have more questions, please join the Discord: #569
