### ISSUE TITLE
incompatibility with random patches

### ISSUE THREAD

**Issue by Moonyol** [Keksuccino/FancyMenu#603]
**Describe the issue**
the game crashes on start up with random patches (essential fixes this for some reason)

**Game Log**

[latest.log](https://github.com/Keksuccino/FancyMenu/files/12777407/latest.log)

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.14.9
 - Forge 14.23.5.2860
 - Minecraft Version 1.12.2
 - Active Mods:
 ![image](https://github.com/Keksuccino/FancyMenu/assets/92951072/eb1c0f8a-ce99-454c-9127-52f07f465e85)

**Comment by Keksuccino** [comment]
https://fm.keksuccino.dev/en/incompatibility-list
