### ISSUE TITLE
[1.19.2] Game crashes when changing window size restrictions

### ISSUE THREAD

**Issue by vizthex123** [Keksuccino/FancyMenu#604]
**Describe the bug**
The game crashes due to `Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null`

I manually edited the menu files and it didn't crash, so it's just the UI that's broken.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Load the game
2. Change the window size restriction (I did height, but width should product the same crash)

**Expected behavior**
The game not crashing

**Game Log**
https://gist.github.com/vizthex123/adab19e7da774375a38aaa3742192c57

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 2.14.9
 - Forge/Fabric Version: Forge 43.3.2
 - Minecraft Version: 1.19.2
 - Active Mods: Over 200. I can send the pack if needed, but I'm not listing them one-by-one.

**Comment by Keksuccino** [comment]
Hi!

The "Window Size Restrictions" feature is deprecated and will get removed in FancyMenu v3 (currently in development).

It’s better to use layout-wide loading requirements (Is Window Size requirement) for this :)

Will close this issue because the feature will soon get removed.

Thank you for your bug report!

**Comment by vizthex123** [comment]
> Hi!
> 
> The "Window Size Restrictions" feature is deprecated and will get removed in FancyMenu v3 (currently in development).
> 
> It’s better to use layout-wide loading requirements (Is Window Size requirement) for this :)
> 
> Will close this issue because the feature will soon get removed.
> 
> Thank you for your bug report!

of course it is. Guess I'll have to figure out how to use the layout then.
