### ISSUE TITLE
Bedrockify loading screen Incompatibility

### ISSUE THREAD

**Issue by Its-Just-Luci** [Keksuccino/FancyMenu#606]
**Describe the issue**
Bedrockify's elements cannot be loaded with Fancymenu. I submitted an issue on their mod a few weeks ago, but figured I would here too as I haven't heard anything.

**Game Log**
[debug.log](https://github.com/Keksuccino/FancyMenu/files/12888012/debug.log)
[latest.log](https://github.com/Keksuccino/FancyMenu/files/12888013/latest.log)

**Screenshots**
![269457948-90c6183d-3c96-43b7-bd99-48c0cea59073](https://github.com/Keksuccino/FancyMenu/assets/57868183/70da1a4b-43b0-4fa8-9dca-f2bb53427a46)
![269457950-9701803f-bc75-45ad-a6a2-850fa778a27c](https://github.com/Keksuccino/FancyMenu/assets/57868183/b6e5a4cf-7594-43f9-8106-fc5b6f831c1e)

**Basic Informations (please complete the following information):**
 - OS: [Windows 10]
 - FancyMenu Version [2.14.9-3]
 - Forge/Fabric Version [Forge 47.1.3]
 - Minecraft Version [1.20.1]
 - Active Mods [Sinytra]

**Comment by Keksuccino** [comment]
https://fm.keksuccino.dev/en/incompatibility-list
