### ISSUE TITLE
fancymenu 1.12.2 crashes on startup

### ISSUE THREAD

**Issue by katyusha8138** [Keksuccino/FancyMenu#607]
When I install the mod and start it, it crashes without starting to load

Install Optifine, FancyMenu, Konkrete
↓
Launch Minecraft

**Expected behavior**
It starts normally without crashing and Fancymenu can be use

**Game Log**
https://gist.github.com/katyusha8138/0581bc26d129dcd43a3c396d36961672

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.14.9
 - Forge 1.12.2-14.23.5.2860
 - 1.12.2
 - Optifine, FancyMenu, Konkrete 1.6.1

**Comment by Keksuccino** [comment]
You forgot to install MixinBootstrap.
