### ISSUE TITLE
[1.12] OpenGL error

### ISSUE THREAD

**Issue by CalaMariGold** [Keksuccino/FancyMenu#608]
Main menu completely breaks for some users.
![image](https://github.com/Keksuccino/FancyMenu/assets/57605926/9662bf80-afdc-42c3-8cf0-c55762bcc094)

Error: https://mclo.gs/97jyf2x

Full latest.log: https://mclo.gs/kIpZZXU

**Comment by Keksuccino** [comment]
That looks like a mod incompatibility of some sort, but it's 1.12, so it could be basically everything.

You have three options now:
1. Search for the mod that causes the problems (there's no guarantee it's caused by a mod)
2. Switch to a modern version of Minecraft (1.16+)
3. Remove FancyMenu

**Comment by Keksuccino** [comment]
Will close that for now, because there's absolutely nothing I can do here. It's most probably not a bug in FancyMenu, because you are the first one reporting this and I didn't update FM for 1.12 in the last weeks.
