### ISSUE TITLE
Console crash after new server resource pack download

### ISSUE THREAD

**Issue by nroj95** [Keksuccino/FancyMenu#609]
**Describe the bug**
When I join a new server my console crashes after server resource pack has finished downloading

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Only Fabric API, FancyMenu and Konkrete
2. Join a server and download its resource-pack
3. CRASH

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
https://gist.github.com/nroj95/fdc7a3560d93dc4d2f34f1eb7873dcf6

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.14.10-1
 - Fabric Version 0.14.23
 - Minecraft Version 1.20.2
 - Active Mods: Fabric API, FancyMenu and Konkrete

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v2.14.10-2! :)
(CurseForge needs some more time to approve it, but it's already available for download on Modrinth.)
