### ISSUE TITLE
Default Gui Scale

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#61]
**Describe your idea**
An option in your config to set the default gui scale, which I personally think should be set to 3 because who plays minecraft on a 640x480 monitor anyways?

**Does it frustrates you to not already have this feature in the mod?**
Oh dear god yes, it frustrates me all the way thru the 9 planes of hell and up through all the layers of heaven, forwards and backwards upon the face of the whole earth throughout all of eternity! Yes, very much I say, why does this feature even exists, every time I must set GUI scale to 3.

**Comment by kreezxil** [comment]
I think Jared's mod TipTheScales does this, would be great if you mod did it tho. :)

**Comment by Keksuccino** [comment]
I don’t understand why this would be useful, can’t you just set the scale one time in the settings? o.O If you want to have a custom default scale in your modpack, isn’t it possible to include the minecraft config in modpacks? You could set it to the scale you want as default and include it in the pack ^^

Or do you want to lock the game to a specific scale? That would be a really bad idea in my opinion.. People want to customize its gamesettings. As example, I hate GUI scale 3. Everything is way too big with it, even on my 1920x1080 screen. I only play MC on scale 2. I would deinstall a pack if it doesn’t allow me to change that.. ^^

**Comment by kreezxil** [comment]
i want to default it to a setting not lock it
like i said TipTheScales already does it

**Comment by Keksuccino** [comment]
But again, can’t you just add a minecraft config with the correct scale to your pack? o.O

**Comment by kreezxil** [comment]
my experience says that launchers ignore the options.txt which is why
defaultoptions as a mod exists, also defaultsettings as a mod.

**Comment by kreezxil** [comment]
to clarify it's ignored on first run

**Comment by Keksuccino** [comment]
Option to set the default GUI scale on first launch was added in FancyMenu v1.6.0! Thank you for your suggestion!
