### ISSUE TITLE
[Probably Essential Incompatibility] FancyMenu update breaks FancyMenu in 1.20.1

### ISSUE THREAD

**Issue by Vinesauced** [Keksuccino/FancyMenu#610]
**Describe the bug**
Updating FancyMenu (along with konkrete, drippy loading screen, and fancy menu audio) to the latest versions breaks my layouts in my modpack, as well as the fancy menu gui which has just vanished. The mojang loading screen appears as a blank red screen. I had one universal layout with an animation and one for the main menu, and they still work if I remove the update. 

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Update FancyMenu, Drippy Loading Screen, Konkrete, and Audio Extension for FancyMenu from the previous version to the latest.
2. Launch game.

**Expected behavior**
Mod to function as normal.

**Game Log**
https://mclo.gs/WS4cvkC

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 2.14.10
 - Fabric Version 0.14.23
 - Minecraft Version 1.20.1
 - Active Mods: 
  [✔] accurate-block-placement-1.2
  [✔] ad_astra-fabric-1.20.1-1.15.4
  [✔] AdditionalAdditions-6.0.1
  [✔] Adorn-5.0.0+1.20.1-fabric
  [✔] advancementinfo-1.20-fabric0.83.0-1.4
  [✔] ae2-emi-crafting-1.0.1
  [✔] ae2wtlib-15.1.0-fabric
  [✔] almostunified-fabric-1.20.1-0.7.0
  [✔] appleskin-fabric-mc1.20.1-2.5.1
  [✔] appliedenergistics2-fabric-15.0.13
  [✔] architectury-9.1.12-fabric
  [✔] Armorful-2.0.2+1.20
  [✔] artifacts-fabric-9.1.0
  [✔] AttributeFix-Fabric-1.20.1-21.0.2
  [✔] audioplayer-1.20.1-1.8.3
  [✔] auudio_fabric_1.0.3_MC_1.20
  [✔] AxesAreWeapons-1.7.1-fabric-1.19.3
  [✔] badpackets-fabric-0.4.3
  [✔] balm-fabric-1.20.1-7.1.4
  [✔] bclib-3.0.13
  [✔] bedrockwaters-1.7.7+1.20.1
  [✔] bettercombat-fabric-1.7.4+1.20.1
  [✔] better-craftables-v1.3.0
  [✔] better-end-4.0.10
  [✔] BetterF3-7.0.1-Fabric-1.20.1
  [✔] better-nether-9.0.9
  [✔] betterstats-3.4+fabric-1.20.1
  [✔] bettertrims-2.0.1
  [✔] blur-3.1.0
  [✔] Bookshelf-Fabric-1.20.1-20.0.5
  [✔] BotanyPots-Fabric-1.20.1-13.0.17
  [✔] BotanyTrees-Fabric-1.20.1-9.0.7
  [✔] botarium-fabric-1.20.1-2.2.0
  [✔] brainierbees-1.4
  [✔] chefs-delight-1.0.3-fabric-1.20.1
  [✔] cloth-config-11.1.106-fabric
  [✔] Clumps-fabric-1.20.1-12.0.0.3
  [✔] collective-1.20.1-6.66
  [✔] CompletionistsIndex-v8.0.0-1.20.1-Fabric
  [✔] conjuring-1.0.28+1.20
  [✔] continuity-3.0.0-beta.4+1.20.1
  [✔] cookingforblockheads-fabric-1.20-16.0.1
  [✔] Couplings-1.9.4+1.20
  [✔] create_jetpack-fabric-4.0.0
  [✔] createaddition-fabric+1.20.1-0.9.0
  [✔] create-fabric-0.5.1-d-build.9+mc1.20.1
  [✔] create-structures-0.1.1-1.20.1-FABRIC
  [✔] creeperoverhaul-3.0.1-fabric
  [✔] cristellib-1.1.3-fabric
  [✔] ctov-3.3.5b
  [✔] ctov-chefs-delight-compat-2.0
  [✔] ctov-farmers-delight-compat-2.1
  [✔] ctov-friends-and-foes-compat-2.0
  [✔] cullleaves-fabric-3.2.0
  [✔] dawn-5.0.0
  [✔] Debugify-1.20.1+2.0
  [✔] deeperdarker-fabric-1.20-1.2.0
  [✔] Display Case-fabric-1.20-1.0.7
  [✔] drippyloadingscreen_fabric_2.2.5_MC_1.20.1
  [✔] dungeons-and-taverns-3.0.3
  [✔] DungeonsArise-1.20.1-2.1.57-fabric-release
  [✔] durabilitytooltip-1.1.5-fabric-mc1.20
  [✔] dynamic-fps-3.2.1+minecraft-1.20.0
  [✔] EasyAnvils-v8.0.1-1.20.1-Fabric
  [✔] EasyMagic-v8.0.1-1.20.1-Fabric
  [✔] eating-animation-1.9.4+1.20
  [✔] elytra_trinket-1.0.3
  [✔] elytraslot-fabric-6.3.0+1.20.1
  [✔] emi_loot-0.6.5+1.20.1
  [✔] emi-1.0.23+1.20.1+fabric
  [✔] emiffect-fabric-1.1.1+mc1.20.1
  [✔] emitrades-fabric-1.2.0+mc1.20.1
  [✔] end-gateway-warps-1.2.1
  [✔] endlessMusic-1.20.1-v1.0.0
  [✔] ends_delight-fabric-1.20.1-1.0.1
  [✔] enhancedblockentities-0.9+1.20
  [✔] entityculling-fabric-1.6.2-mc1.20.1
  [✔] essential_1-2-2-2_fabric_1-20-1
  [✔] euphonium-1.0.1+1.20
  [✔] everycomp-1.20-2.6.7-fabric
  [✔] exordium-fabric-1.2.1-mc1.20.1
  [✔] expandeddelight-0.3.0.2
  [✔] ExtendedDrawers-2.0.7+mc.1.20.1
  [✔] extra-mod-integrations-0.4.1+1.20.1
  [✔] fabric-api-0.90.0+1.20.1
  [✔] fabric-language-kotlin-1.10.10+kotlin.1.9.10
  [✔] FallingTree-1.20.1-4.3.0
  [✔] fancymenu_fabric_2.14.10_MC_1.20.1
  [✔] farmers-delight-fabric-mc1.20.1-1.4.2
  [✔] farmersknives-3.0
  [✔] ferritecore-6.0.0-fabric
  [✔] fm_audio_extension_fabric_1.1.2_MC_1.20.1
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] fred-0.9.2-1.20.1
  [✔] friendsandfoes-fabric-mc1.20.1-1.9.7
  [✔] ftb-chunks-fabric-2001.2.2
  [✔] ftb-essentials-fabric-2001.2.1
  [✔] ftb-library-fabric-2001.1.3
  [✔] ftb-teams-fabric-2001.1.4
  [✔] ftb-ultimine-fabric-2001.1.2
  [✔] fusion-1.0.6-fabric-mc1.20
  [✔] Galosphere-1.20.1-1.3.1-Fabric
  [✔] geckolib-fabric-1.20.1-4.2.3
  [✔] global_packs-fabric-1.19.4-1.16.1_fabric
  [✔] graves-3.0.0+1.20.1
  [✔] Hephaestus-1.20.1-3.6.3.232
  [✔] Highlighter-1.20.1-fabric-1.1.6
  [✔] highlight-fabric-1.20-2.0.1
  [✔] Iceberg-1.20.1-fabric-1.1.15
  [✔] ImmediatelyFast-1.2.6+1.20.2
  [✔] Incendium_1.20.2_v5.3.2
  [✔] indium-1.0.27+mc1.20.1
  [✔] inventory-control-tweaks-1.3.27+MC1.20-1.20.1
  [✔] InventoryProfilesNext-fabric-1.20-1.10.7
  [✔] iris-mc1.20.1-1.6.10
  [✔] ItemBorders-1.20.1-fabric-1.2.0
  [✔] jmi-fabric-1.20.1-0.14-45
  [✔] journeymap-1.20.1-5.9.15-fabric
  [✔] konkrete_fabric_1.7.0-1_MC_1.20.1
  [✔] krypton-0.2.3
  [✔] Ksyxis-1.1
  [✔] lambdynamiclights-2.3.2+1.20.1
  [✔] lazydfu-0.1.3
  [✔] LeaveMyBarsAlone-v8.0.0-1.20.1-Fabric
  [✔] LegendaryTooltips-1.20.1-fabric-1.4.4
  [✔] letmedespawn-fabric-1.20-1.1.0
  [✔] libIPN-fabric-1.20-4.0.0
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] loadmyresources_fabric_1.0.4-1_MC_1.20
  [✔] lootery-v2
  [✔] lootr-1.20-0.7.29.75
  [✔] lunade-fastanim-1.6-1.20
  [✔] mavapi-1.1.3-mc1.20.1
  [✔] mavm-1.2.4-mc1.20
  [✔] mcw-bridges-2.1.0-mc1.20.1fabric
  [✔] mcw-doors-1.1.0fabric-mc1.20.1
  [✔] mcw-fences-1.0.7-mc1.20.1fabric
  [✔] mcw-furniture-3.2.0b-mc1.20.1fabric
  [✔] mcw-lights-1.0.6-mc1.20.1fabric
  [✔] mcw-paintings-1.0.4-1.20.1fabric
  [✔] mcw-paths-1.0.3fabric-mc1.20.1
  [✔] mcw-roofs-2.2.4-mc1.20.1fabric
  [✔] mcw-trapdoors-1.1.1-mc1.20.1fabric
  [✔] mcw-windows-2.2.0-mc1.20.1fabric
  [✔] memoryleakfix-fabric-1.17+-1.1.2
  [✔] midnightcontrols-1.8.2+1.20
  [✔] MindfulDarkness-v8.0.2-1.20.1-Fabric
  [✔] minerally-1.20.2-1.0
  [✔] mine-treasure-1.2.9
  [✔] MixinConflictHelper-1.2.0
  [✔] mixintrace-1.1.1+1.17
  [✔] mmcmga-1.20.2-1.0
  [✔] mob-captains-v2.1.2
  [✔] modernfix-fabric-5.8.1+mc1.20.1
  [✔] modmenu-7.2.2
  [✔] modmenu-badges-lib-2023.6.1
  [✔] moonlight-1.20-2.8.51-fabric
  [✔] more_mobs-v1.5-mc1.14x-1.20x-mod
  [✔] moreculling-1.20.1-0.19.0
  [✔] morediscs-1.20.1-32-fabric
  [✔] moremobvariants-fabric+1.20-1.2.2
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] moyai-1.20-2.0.2-fabric
  [✔] mysticaloaktree-1.20-1.11-fabric
  [✔] mythicupgrades-2.3.1+mc1.20.1
  [✔] NaturesCompass-1.20.1-2.2.3-fabric
  [✔] NethersDelight-1.0.0
  [✔] no-telemetry-1.7.0
  [✔] notenoughanimations-fabric-1.6.4-mc1.20
  [✔] Nullscape_1.20.2_v1.2.3
  [✔] numismatic-overhaul-0.2.10+1.20
  [✔] oceansdelight-fabric-1.0.2-1.20
  [✔] openblockselevator-0.0.3-1.20.1
  [✔] OverflowingBars-v8.0.0-1.20.1-Fabric
  [✔] owo-lib-0.11.2+1.20
  [✔] Patchouli-1.20.1-81-FABRIC
  [✔] patchoulibutton-1.0.2
  [✔] Pehkui-3.7.8+1.14.4-1.20.1
  [✔] player-animation-lib-fabric-1.0.2-rc1+1.20
  [✔] Prism-1.20.1-fabric-1.0.5
  [✔] promenade-4.1.1
  [✔] PuzzlesLib-v8.0.24-1.20.1-Fabric
  [✔] realisticbees-1.20.1-3.4
  [✔] rechiseled-1.1.5-fabric-mc1.20
  [✔] rechiseledcreate-1.0.1-fabric-mc1.20
  [✔] reeses_sodium_options-1.6.5+mc1.20.1-build.95
  [✔] RegionsUnexploredFabric-0.5.31.20.1
  [✔] resourcefulconfig-fabric-1.20.1-2.1.0
  [✔] resourcefullib-fabric-1.20.1-2.1.11
  [✔] Resourcify (1.20-1.20.1-fabric)-1.2.1
  [✔] RingsOfAscension-1.20.1-2.0.2
  [✔] Rrls-3.2.0-1.20.1-fabric
  [✔] screenshot-to-clipboard-1.0.9-fabric
  [✔] servercore-fabric-1.3.7+1.20.1
  [✔] shetiphiancore-fabric-1.20.1-1.1
  [✔] shulkerboxtooltip-fabric-4.0.4+1.20.1
  [✔] simplyswords-fabric-1.51.4-1.20.1
  [✔] SkyVillages-1.0.3.1-1.19.2-1.20.1-fabric
  [✔] sliceanddice-fabric-3.0.0
  [✔] sodium-extra-0.5.1+mc1.20.1-build.112
  [✔] sodium-fabric-mc1.20.1-0.5.3
  [✔] spawnanimations-v1.9.2-mc1.17x-1.20x-mod
  [✔] stack-to-nearby-chests-mc1.20.1-0.5.0
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] Steam_Rails-1.5.1+fabric-mc1.20.1
  [✔] Structory_1.20.2_v1.3.3
  [✔] Structory_Towers_1.20.2_v1.0.5
  [✔] StylishEffects-v8.0.0-1.20.1-Fabric
  [✔] subterrestrial-fabric-1.20-2.2.0
  [✔] supermartijn642configlib-1.1.8a-fabric-mc1.20
  [✔] supermartijn642corelib-1.1.15-fabric-mc1.20.1
  [✔] supplementaries-1.20-2.6.13-fabric
  [✔] suppsquared-1.20-1.1.10-fabric
  [✔] tectonic-mod-mc1.19.3+-v2.1.1
  [✔] TerraBlender-fabric-1.20.1-3.0.0.169
  [✔] Terralith_1.20.2_v2.4.7
  [✔] terraqueous-fabric-1.20.1-1.1
  [✔] terrestria-6.0.10
  [✔] things-0.3.1+1.20
  [✔] Towns-and-Towers-1.11.1-Fabric+Forge
  [✔] trashcans-1.0.18-fabric-mc1.20
  [✔] travelers-backpack-1.20.1-9.1.6
  [✔] TravelersTitles-1.20-Fabric-4.0.1
  [✔] treeplacer-fabric-1.20.1-1.2.0
  [✔] trinkets-3.7.1
  [✔] true-ending-1.0.1a
  [✔] UniversalBoneMeal-v8.0.1-1.20.1-Fabric
  [✔] UniversalEnchants-v8.0.0-1.20.1-Fabric
  [✔] vanilla-refresh-1.4.17c
  [✔] villagespawnpoint-1.20.1-4.0
  [✔] visuality-0.7.1+1.20
  [✔] VisualWorkbench-v8.0.0-1.20.1-Fabric
  [✔] voicechat-fabric-1.20.1-2.4.27
  [✔] vt-downloader-2.0.8+1.20.1
  [✔] waystones-fabric-1.20-14.0.2
  [✔] WilderWild-2.1.10-Fabric+1.20.1
  [✔] wmitaf-fabric-mc1.19.3-3.2.0
  [✔] wso16-fabric-1.2
  [✔] wthit-fabric-8.4.0
  [✔] wwoo-3.2.1-fabric
  [✔] yet-another-config-lib-fabric-3.2.1+1.20
  [✔] YungsApi-1.20-Fabric-4.0.2
  [✔] YungsBetterDesertTemples-1.20-Fabric-3.0.3
  [✔] YungsBetterDungeons-1.20-Fabric-4.0.3
  [✔] YungsBetterEndIsland-1.20-Fabric-2.0.4
  [✔] YungsBetterJungleTemples-1.20-Fabric-2.0.4
  [✔] YungsBetterMineshafts-1.20-Fabric-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Fabric-2.0.5
  [✔] YungsBetterOceanMonuments-1.20-Fabric-3.0.3
  [✔] YungsBetterStrongholds-1.20-Fabric-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Fabric-3.0.3
  [✔] YungsBridges-1.20-Fabric-4.0.3
  [✔] YungsExtras-1.20-Fabric-4.0.3
Edit: in my original post I forgot to turn on loadmyresources, please ignore that.

**Comment by Keksuccino** [comment]
Please try to start the game with only FancyMenu, Drippy, FM Audio extension and their dependencies enabled, thank you.

**Comment by thesh1xx** [comment]
I also had this bug on 1.20.1 Fabric. I figured out that its conflicts with essential mod

**Comment by Crawpa** [comment]
I think it is because of essential mod incompatibility with FancyMenu. It seems like for me whenever I use any mod pack with essential and their own menu mod, the game doesn't seem to work in many ways. For Crazy Craft Updated it always says incompatible FML modded server when trying to join a friend or other servers even though all mods installed are the exact same. This is the same with pixelmon (I'm actually not sure if my pixelmon mod uses FancyMenu but same point) But even other mods with different menu mods like Better Minecraft 4 (BMC4) or Pixelmon, any menu mod for me causes problems. BMC4 will straight up says 1 mod is incompatible when only essential was added

**Comment by Keksuccino** [comment]
Soo that indeed seems to be an incompatibility with some **newer builds** of FancyMenu, but there's no reason for why Essential's GUI stuff should completely break FM's customization system. They just add new elements to existing GUIs if I remember correctly, so there's no reason to break other GUI mods in such a way. **I can't fix that on my end.**

**Comment by thesh1xx** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/96383317/3e6866ae-1d45-4598-b17f-1998faad808d)
i talked with them, so now all we have to do is wait
