### ISSUE TITLE
[1.16.5] Game crashes if I enable layout customization

### ISSUE THREAD

**Issue by SirRoderic2** [Keksuccino/FancyMenu#611]
**Describe the bug**
If I enable menu customization, the game crashes immediately, and after that, once I launch the game, the game just crashes just before it finishes loading, and I'll have to delete the fancymenu config folder to fix the crashes

**To Reproduce**
Steps to reproduce the behavior (e.g.):
launch the game
click to enable layout customization

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
https://gist.github.com/SirRoderic2/29953b883c3c36bcdfe321ef35c8270b

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - windows 10 pro
 - FancyMenu Version [v2.14.9]
 - Forge/Fabric Version [36.2.34]
 - Minecraft Version [e.g. 1.16.5]

**Comment by Keksuccino** [comment]
FancyMenu v3 is out now and with it, support for MC 1.16 got dropped (for now, could come back in the future). I will close this for now.
