### ISSUE TITLE
[Bug]: Fance menu don't work for 1.20.1 Ice And Fire Alpha 4

### ISSUE THREAD

**Issue by DonorKrovi** [Keksuccino/FancyMenu#612]
**Describe the issue**
![image](https://github.com/Keksuccino/FancyMenu/assets/60231586/a2244031-504c-41e3-9842-92fcc1589192)

I want to add an foneto the foreground instead of the IAF main menu, but it doesn't work and still remains the background of the IAF main menu

**Game Log**
There are no errors in the logs**Screenshots**

If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - FancyMenu Version [e.g. 0.2] fancymenu_forge_2.14.9-1_MC_1.20.1
 - Forge/Fabric Version [e.g. 31.2.24] 1-47.1.75
 - Minecraft Version [e.g. 1.15.1] 1 20 1
 - Active Mods [e.g. Optifine, 5zig, TooManyItems]
Ice And Fie and Fancy Menu

**Comment by Keksuccino** [comment]
You can disable the custom main menu of Ice and Fire in its config.
https://fm.keksuccino.dev/en/incompatibility-list
