### ISSUE TITLE
Load normal layouts AFTER universal layouts

### ISSUE THREAD

**Issue by Saereth** [Keksuccino/FancyMenu#615]
**Describe the bug**
This is a weird bug first of all. It happens consistently on Mac, its only been reported by a few windows users but we do have reports there as well. We have a custom main menu defined with buttons and all that, then we have a default also setup for all the other pages that has a music file and static background image and nothing more. For all mac users and a very small subsection of windows users the background image that is shown is the one assigned to the default layout not the main menu as would be expect.

All of the buttons from the main menu do still show just the background is wrong

This is how it would be expected to look and does on the majority of windows installs
<img width="1918" alt="image" src="https://github.com/Keksuccino/FancyMenu/assets/9200909/53b4013f-719b-4fe6-a9a3-094dd8817cf9">

This is how its looking for all mac/linux users and some subset of windows users
![image](https://github.com/Keksuccino/FancyMenu/assets/9200909/600911ec-e088-4bd3-b0a3-268bab52b77e)

So the buttons are all there (and are not part of the default layout) but the default layout's background is showing instead of the one defined for the main menu

**Basic Informations (please complete the following information):**
 - OS: Windows 11/MacOS Sonoma
 - FancyMenu Version [e.g. 0.2]fancymenu_forge_2.14.9_MC_1.19-1.19.2
 - Forge/Fabric Version [e.g. 31.2.24] forge 43.2.21
 - Minecraft Version [e.g. 1.15.1] 1.19.2
 - Active Mods [e.g. Optifine, 5zig, TooManyItems]

Pack is FTB Genesis, happy to provide any additional info I can

**Comment by Keksuccino** [comment]
The loading order of layouts is not always the same. It depends on the OS and OS settings (file order).
That's probably why that happens ^^

But will add to my to-do to load normal layouts AFTER universal layouts :)

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
