### ISSUE TITLE
Vanilla-style splash text in layout crashing game

### ISSUE THREAD

**Issue by LunaHD24** [Keksuccino/FancyMenu#616]
**Detailed Walkthrough**
When I try to create a new menu layout in-game and click on 'Vanilla-Like Splash Text' the game crashes instantly. For a short moment it says 'Saving World' but then crashes with a rendering error (exit code -1).

**Steps to Reproduce**
Steps to reproduce the behavior (e.g.):
1. Click on 'Universal Layouts'
2. Click on 'New Layout'
3. Click on 'Element', then 'New' and select 'Splash Text', then 'Vanilla-Like Splash Text'

**Expected Behaviour**
It should create a normal splash text in the layout editor with the vanilla prompts.

**Game Log**
https://gist.github.com/LunaHD24/474c5a8f3a67063707b5273de809234e

**Basic Informations (please complete the following information):**
 - OS: Windows 11 22H2
 - FancyMenu Version 2.15.9-3
 - Forge Version 47.2.0
 - Minecraft Version 1.20.1
 - Active Mods: Modlist (https://gist.github.com/LunaHD24/da67a51b4767d5de040a23654bcacbe6)

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
