### ISSUE TITLE
Custom menu and default menu overlapping each other

### ISSUE THREAD

**Issue by X-XLebyshek** [Keksuccino/FancyMenu#617]
**Describe the bug**
I made a custom main menu, but when I turn it on, the elements of the default menu stay, and they overlap. Also my menu does not adapt to change Fullscreen -> Default resolution, but maybe I did something wrong.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Launch my modpack
2. Activate custom menu
3. See bug

**Expected behavior**
My menu functioning properly.

**Game Log**
https://gist.github.com/X-XLebyshek/e773fe2bb261a0f696d1c60ad307e58d

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/139650255/929dfaef-0712-4ad7-92c6-1e8e3b441666)
You can see a transparent cobblestone background

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 2.14.19
 - Forge/Fabric Version 43.3.5
 - Minecraft Version 1.19.2
 - Active Mods: https://gist.github.com/X-XLebyshek/1a674d135707110827de6e4a79ec6891

**Comment by GamingAmateur233** [comment]
This problem was occurring for me too

**Comment by Keksuccino** [comment]
That's most probably caused by **EnhancedVisuals**.
https://fm.keksuccino.dev/en/incompatibility-list

**Comment by X-XLebyshek** [comment]
The cobblestone background disappeared when I deleted enhanced visuals, but the main issue still persists. I've seen in the tutorial, that when I create new layout, there must be all the buttons, which I can then delete and create my own, but there aren't any in my case. So they just stay there
