### ISSUE TITLE
RewardZ mod support

### ISSUE THREAD

**Issue by freezzz-y** [Keksuccino/FancyMenu#618]
Add support for opening menu [RewardZ mod](https://modrinth.com/mod/rewardz)
`net.rewardz.screen.RewardsScreen`

**Comment by Keksuccino** [comment]
I don't add support for mod menus anymore. Most incompatible menus are pretty difficult to add support for (from both the other mod's side and FancyMenu's side). Sorry.

**Comment by freezzz-y** [comment]
Thanks for the answer. Then it turns out that the error message is misleading, perhaps it is worth fixing lang `custombuttons.action.opengui.cannotopengui`

**Comment by Keksuccino** [comment]
Well, that's already "fixed" in FancyMenu v3 (currently in development), because that message does not exists anymore in v3 ^^
