### ISSUE TITLE
[Question] unpackzip action to main game folder?

### ISSUE THREAD

**Issue by fibberclip** [Keksuccino/FancyMenu#619]
Hey! Is there any way to make the unpackzip action on a button extract the zip contents into the main game folder instead of onto a specific one? (aka extract everything to the folder where the mods, resourcepacks, config, etc folders are). I'm making a custom updater for a modpack i manage and i wanna be able to ship configs and resource pack updates on Modpack updates, not just new mods. 

Is there any way i can make this? I tried setting the 2nd value "/" and also leaving it empty but it doesn't seem to work. I'm on Minecraft 1.18.2, Forge 40.2.9 and FancyMenu 2.14.7, Thanks!
btw sorry for opening an issue for a question, i tried joining the discord but the invite shows as invalid :(

**Comment by Keksuccino** [comment]
https://github.com/Keksuccino/FancyMenu/issues/569
