### ISSUE TITLE
1.16.1 Can't see menu identifier

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#62]
Because of the Beta Warning in 1.16.1, when you are viewing the the menu ID on the main menu you can't see what it is.

![image](https://user-images.githubusercontent.com/3880072/87679965-756bf600-c742-11ea-8bba-12c5422e5c04.png)

**Comment by kreezxil** [comment]
I recommend having a box that goes around that with a dark background that obliterates other artifacts thus allowing us to see it.

**Comment by Keksuccino** [comment]
Fixed in v1.4.2, thank you for your report! :)

**Comment by kreezxil** [comment]
glad to be a fan of yours.
