### ISSUE TITLE
Text element appearance and alignment is delayed by a few frames

### ISSUE THREAD

**Issue by lumiscosity** [Keksuccino/FancyMenu#620]
**Describe the bug**
Text elements occasionally take a few frames to appear, and if the text has an alignment, it'll take a few frames before it is processed (might be related to #563).

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Add a text element to a menu
2. Repeatedly close and open the menu
3. The text elements will sometimes take a few frames to load properly

**Expected behavior**
Just like all other elements, text elements should be fully loaded by the time the menu appears.

**Game Log**
[No relevant logs are produced for this issue; this is purely a visual bug.](https://mclo.gs/BNWjKOD)

**Screenshots**

Briefly after reloading (happens on toggling the menu):
![image](https://github.com/Keksuccino/FancyMenu/assets/26834471/3335bcc5-3665-4fed-9ab3-14ae3166f907)

Correct behaviour:
![image](https://github.com/Keksuccino/FancyMenu/assets/26834471/8d947d03-2667-4559-82e8-c97b0439dd87)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 2.14.10
 - Forge/Fabric Version: Fabric 0.14.24
 - Minecraft Version: 1.20.1
 - Active Mods: None

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
