### ISSUE TITLE
Pop-up menus can be clicked through

### ISSUE THREAD

**Issue by lumiscosity** [Keksuccino/FancyMenu#621]
**Describe the bug**
Pop-up menus like the right click button menu or the top bar are click-through, causing options to be erroneously selected.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Open the layout editor
2. Open any pop-up menu (top bar menus, right click menu, etc.) over an element
3. Click on an option in the menu positioned above the element
4. Notice that the element is selected

**Expected behavior**
Menus properly handle their click inputs.

**Game Log**
[No relevant logs are produced for this issue.](https://mclo.gs/BNWjKOD)

**Screenshots**

![javaw_EBU6dMU3Ew](https://github.com/Keksuccino/FancyMenu/assets/26834471/8e96c45e-0133-4758-8aed-c7eda768967e)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 2.14.10
 - Forge/Fabric Version 0.14.24
 - Minecraft Version: 1.20.1
 - Active Mods: None

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
