### ISSUE TITLE
i cant open gui of fancy menu

### ISSUE THREAD

**Issue by VGWARDEN** [Keksuccino/FancyMenu#623]
**Describe your idea**
A detailed and clear description of what you want to see in the mod.
The feature should fit the mod's lore. Stuff like "add speaking potatos ridden by Trump" will be ignored.

**Comment by Keksuccino** [comment]
Closed because no description. Please open a new issue with proper information about the issue, thank you.

**Comment by Keksuccino** [comment]
And in case it's just a question: https://github.com/Keksuccino/FancyMenu/issues/569
