### ISSUE TITLE
When connecting to the server, interaction with the game is restricted

### ISSUE THREAD

**Issue by DonorKrovi** [Keksuccino/FancyMenu#624]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. I've added several buttons when opening the chat, so when a player presses 'T,' they should appear within 0.4 seconds. However, instead of that, players are getting stuck when connecting to the world.

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
https://mclo.gs/Bjyfzp0

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/60231586/337e2d8e-e566-47b0-a765-a87c8ff00204)

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - FancyMenu Version [e.g. 0.2] fancymenu_fabric_2.14.10-2_MC_1.20.1
 - Forge/Fabric Version [e.g. 31.2.24] fabric 0.14.25
 - Minecraft Version [e.g. 1.15.1]1.20.1
 - Active Mods [e.g. Optifine, 5zig, TooManyItems]

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
