### ISSUE TITLE
scale an image with window size

### ISSUE THREAD

**Issue by ItsDoomOne** [Keksuccino/FancyMenu#625]
ok so i made a logo for my modpack and put it in the top, in the minecraft logo area.

Full screen:

![image](https://github.com/Keksuccino/FancyMenu/assets/85998702/4ba7a978-7956-469e-914d-26651ab29856)

Windowed:

![image](https://github.com/Keksuccino/FancyMenu/assets/85998702/ee250254-da06-4008-8238-39e93d14cb80)

If i swap minecraft.png (logo) for my logo in a res pack

![image](https://github.com/Keksuccino/FancyMenu/assets/85998702/612cc270-647f-4d45-a2ac-696efa1fea52)
my issue is simple: i resize the window, logo goes brr with scaling. i want scaling like default minecraft logo
the buttons are oriented at the logo. how can i swap the minecraft logo to QoL++ without any scaling issues?

**Comment by Keksuccino** [comment]
#569
