### ISSUE TITLE
crash on 1.20.4 fabric

### ISSUE THREAD

**Issue by KiritoGuugk** [Keksuccino/FancyMenu#626]
**Describe the bug**
crash on 1.20.4 fabric.

**To Reproduce**
Steps to reproduce the behavior (e.g.):

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
```js
https://gist.github.com/KiritoGuugk/543825d65b9d8d780f817f699d696802
```

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS:archlinux
 - FancyMenu Version 2.14.10-4
 - Forge/Fabric Version 0.15.3
 - Minecraft Version 1.20.4
 - Active Mods AS BELOW
 
![image](https://github.com/Keksuccino/FancyMenu/assets/35999227/2c8ed1cf-2566-44c0-a8ce-8aa7d4fc982e)

**Comment by Keksuccino** [comment]
FancyMenu does not exist for Minecraft 1.20.4.
