### ISSUE TITLE
Joining a server causing the game to close/crash

### ISSUE THREAD

**Issue by NoThrottle** [Keksuccino/FancyMenu#627]
**Describe the bug**
Using a custom button with the button action "join server", upon pressing it, the game shows the "Saving world" screen then closes.
This should not be because of the server itself as I can join the server no problems using the multiplayer screen.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create a custom button
2. Add an action 'joinserver'
3. Set the value to 'mc.hypixel.net'
4. Save the layout and exit editing
5. Press the button

**Expected behavior**
Opens the server, similar to opening the multiplayer screen then pressing the list item of a server.

**Game Log**
https://gist.github.com/NoThrottle/7be359ce95b117ff9fab2aa425226e3f
Causes "java.lang.NullPointerException: Screen cannot be null"

**Basic Informations (please complete the following information):**
 - OS: Windows 10 22H2
 - FancyMenu Version: 2.14.10
 - Forge/Fabric Version: 0.14.25
 - Minecraft Version: 1.20.1
 - See Logs

**Comment by NoThrottle** [comment]
Bug only applies when using the button on the main menu.

**Comment by cad3264** [comment]
I happen to have the same issue, i really hope the devs fix this soon, but for now just make any buttons that connect to servers just go to the multiplayer menu i guess

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
