### ISSUE TITLE
Dirt background instead of animation, even the example one

### ISSUE THREAD

**Issue by dikovmaxim** [Keksuccino/FancyMenu#628]
**Describe the bug**
When I insert my custom made animation, everywhing i saw was the default dirt background. I thought its an animation error, so I tried to install the default animation (the one showed as an example), but got the same result. Everything is being recognized correctly, but i just see the dirt background.

**To Reproduce**
1) Download the default animation
2) replace config and resources folder
3) Start minecraft
4) Select an animation
5) click save and return to the normal menu

**Expected behavior**
After returning to the normal game menu the animation should start

**Game Log**
https://gist.github.com/dikovmaxim/4b8f63d29e97db704c80aa5a12519029

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/48867428/c746866d-b0cc-4ec8-b53f-1fb432d80d8c)

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Pro
 - FancyMenu Version fancymenu_forge_2.14.9_MC_1.18.2
 - Forge/Fabric Version forge 40.2.14
 - Minecraft Version 1.18.3
 - Active Mods Konkrete-Mod-Forge-1.18.2, fm_audio_extension_forge_1.1.1_MC_1.18-1.18.2, fancymenu_forge_2.14.9_MC_1.18.2, auudio_forge_1.0.3_MC_1.18-1.18.2

**Comment by Keksuccino** [comment]
You need [Load My Resources](https://modrinth.com/mod/load-my-resources) for animations.
