### ISSUE TITLE
New Simplified Chinese Translation

### ISSUE THREAD

**Issue by LonelyxiyaOVO** [Keksuccino/FancyMenu#629]
Human-translated Simplified Chinese should be error-free.
[zh_cn.zip](https://github.com/Keksuccino/FancyMenu/files/13796951/zh_cn.zip)

**Comment by Keksuccino** [comment]
Thank you very much for this, but I sadly can't use it, because FancyMenu v3.0.0 just got released and it basically makes all old localizations useless, I'm very sorry for this.

FancyMenu now has a Crowdin page: https://crowdin.com/project/fancymenu
