### ISSUE TITLE
FancyMenu leaking a LOT of RAM

### ISSUE THREAD

**Issue by lucasboss45** [Keksuccino/FancyMenu#63]
**Describe the bug**
FancyMenu leaks a lot of Memory (3-

5GB of memory usage to the java binary while only 2GB is assigned to the VM) while using main manu animations

**To Reproduce**
1. Have 100MB worth of frames for the main menu
2. Start game
3. Memory is through the roof

**Expected behavior**
Not use this much RAM?

**Screenshots**
![firefox_EWSfqXpoA7](https://user-images.githubusercontent.com/29255472/87808403-f0740000-c859-11ea-831f-90fb05e960d7.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 1.4
 - Forge Version 31.2.31
 - Minecraft Version 1.15.2
 - Active Mods Optifine, PreMenuScreen, ItsTheLittleThings

**Comment by Keksuccino** [comment]
Not a bug. That’s just how Minecraft handles external textures. This process is already optimized, trust me.

Animations are not supposed to have hundreds of frames. Just use a shorter animation or optimize its size.

**Comment by lucasboss45** [comment]
Is it normal that it somehow uses RAM that I didn't allocate to the VM?
