### ISSUE TITLE
Text Editing

### ISSUE THREAD

**Issue by Memeruler-k** [Keksuccino/FancyMenu#630]
It would be cool if it was possible to make buttons with colored text like red, blue and green

**Comment by kianagit** [comment]
That is already possible with &-Colorcodes. Here's a list of the colorcodes minecraft itself supports:

&0 - Black
&1 - Dark-Blue
&2 - Dark-Green
&3 - Dark-Aqua
&4 - Dark-Red
&5 - Purple
&6 - Gold
&7 - Gray
&8 - Dark-Gray
&9 - Blue
&a - Lime/Green
&b - Aqua
&c - Red
&d - Pink
&e - Yellow
&f - White
&k - Obfuscated (randomly cycling characters)
&l - Bold
&m - Strikethrough
&n - Underlined
&o - Reset (from what i know always resets to normal-white)

These can be used like: `&c&lHello &r&aWorld`, where "Hello" is Bold-Red, and "World" is Normal-Lime.
