### ISSUE TITLE
Text-Fields (of Fancymenu itself) aren't clickable/focusable

### ISSUE THREAD

**Issue by kianagit** [Keksuccino/FancyMenu#633]
**Describe the bug**
Whenever trying to focus/activate a textbox from fancymenu (eg. when trying to set a custom path for anything) the widget is not clickable, nor tab-able, making it unable to be used.
This results in some custom widget-options being un-removable, like custom click/hover sounds, without removing the whole widgets.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
- Try to Click any Textbox (eg. when setting a background-image)
- Nothing happens

**Expected behavior**
The Textbox gets focused and accepts text-input

**Game Log**
https://gist.github.com/kianagit/8305dcf0dffb5be5ece400237464e737

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/80840951/59c0d3a0-d289-4a5b-97a6-f8e6f237a3cc)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 2.14.10
 - Forge/Fabric Version: 0.15.3
 - Minecraft Version: 1.20.4
 - Active Mods: [Fabric-API, Konkrete, Fancymenu]

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
