### ISSUE TITLE
Latest FancyMenu requires an unexistant version of Konkrete

### ISSUE THREAD

**Issue by SigmaFlame** [Keksuccino/FancyMenu#634]
Hello,

The new version of FancyMenu (2.14.13) needs Konkrete 1.8.0 that doesn't exists, the latest version if 1.6.1-2.
Need to downgrade since the game refuses to start.

**Comment by katubug** [comment]
Came here to report same issue.

**Comment by Keksuccino** [comment]
That's CurseForge.. They like to manually approve all of my files every frickin time and for some reason they instantly approved some new FM builds this time but Konkrete needs to get manually approved.. I will set the new FM version to private until CurseForge gets its shit together, sorry for the inconvenience! In the meantime you can download the new builds from [Modrinth](https://modrinth.com/mod/fancymenu)! :)

![Screenshot_2](https://github.com/Keksuccino/FancyMenu/assets/35544624/005909ba-0854-45e4-b98f-3891a85e4db1)

**Comment by Keksuccino** [comment]
All builds are approved now.
