### ISSUE TITLE
Player Entity doesn't support semi-transparent skin layers

### ISSUE THREAD

**Issue by OfficialCRUGG** [Keksuccino/FancyMenu#635]
**Describe the bug**
When a skin has transparency that's != 0% or 100% on a skin layer, it's not rendered correctly. See Screenshot attached

**To Reproduce**
1. Add a Player Entity Element
2. Use a skin that has a semi-transparent skin layer (e.g. my skin, `CRUGG`, as of creating this issue)

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
https://gist.github.com/OfficialCRUGG/a0f738fff7f96216143b4e633b9cce7e
Although I don't think there's anything relevant in there?

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/25248999/17052a22-cf7b-4e98-9c80-b7764ae3e937)
(it's supposed to be glasses, showing the eyes underneath:)
![image](https://github.com/Keksuccino/FancyMenu/assets/25248999/43c60bb1-1e75-4a93-b244-5358c9f1ff43)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 2.14.13
 - Forge/Fabric Version Fabric 0.93.1 (Loader 0.15.3)
 - Minecraft Version 1.20.4
 - Active Mods: Fabric API, FancyMenu, Konkrete

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue.
