### ISSUE TITLE
Add support for StonecutterScreen when using opengui command in button action

### ISSUE THREAD

**Issue by jasperalani** [Keksuccino/FancyMenu#636]
You can add actions to a button that happen on click and one of them is 'opengui'.
An error saying 'This gui doesn't exist/is not supported' comes up when trying to open `net.minecraft.client.gui.screens.inventory.StonecutterScreen`

This menu identifier is the menu info shown when the stonecutter gui is open.

I tried to add it myself by editing `menu-identifiers.db` but couldn't get it to work.

**Comment by Keksuccino** [comment]
Will not add this, sorry.
