### ISSUE TITLE
[Crash]: On Loading Screen - id is null

### ISSUE THREAD

**Issue by xR4YM0ND** [Keksuccino/FancyMenu#638]
[Crash Report](https://gist.github.com/xR4YM0ND/e78c0fdbc7b1a3bfd4cfc7a2c6d1066c)
[Aged Modpack v2.2.2](https://modrinth.com/modpack/aged/version/2.2.2)

```js
Description: Registering texture

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.method_12832()" because "id" is null
```

**Comment by Keksuccino** [comment]
FancyMenu v3 is now out and it's a full rewrite, so I'm closing this for now. If it still happens, please open a new issue, thank you.
