### ISSUE TITLE
[Unnecessary Feature] Set Orientation notification should be asked once.

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#64]
When creating a gui or editing a layout for elements not modified you're informing us on each one about something. I feel that should be asked once at the start of the creation, if at all.

**Comment by Keksuccino** [comment]
What do you mean by the orientation notification? The message that you cannot move vanilla buttons without applying an orientation to it?

**Comment by kreezxil** [comment]
that is exactly what I mean.

**Comment by Keksuccino** [comment]
Option to "not show this message again" was added in FancyMenu v1.5! Thank you for your report!
