### ISSUE TITLE
When use with CustomSkinLoader mod, cape displays error

### ISSUE THREAD

**Issue by Qian-F** [Keksuccino/FancyMenu#640]
![image](https://github.com/Keksuccino/FancyMenu/assets/111696321/bbfe4de7-9997-43ba-b426-258cf48884f0)

**Basic Informations (please complete the following information):**
 - OS: windows
 - FancyMenu Version 3.0.0
 - Forge/Fabric Version 43.3.7
 - Minecraft Version 1.19.2

**Comment by Qian-F** [comment]
My suggestion is to either increase the relevant compatibility or provide an option to completely disable cape.

**Comment by Keksuccino** [comment]
Isn't there already a toggle to disable the cape of player entity elements?

**Comment by Qian-F** [comment]
When use the "Copy Client Player" mode, "Auto type" is disabled but the cape still appear.

**Comment by Qian-F** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/111696321/a991e71f-f7f8-4237-b4c0-3d48c86af3b2)

**Comment by Keksuccino** [comment]
Dude no offense, but if I would try to add support for every single mod I would die of stress tomorrow.

**Comment by Qian-F** [comment]
I don't want my words to make you feel pressured. I'm just suggesting this because, after all, this compatibility issue has been around for a long time.
