### ISSUE TITLE
1.12.2 Support for Version 3 of FancyMenu

### ISSUE THREAD

**Issue by Titoo8899** [Keksuccino/FancyMenu#641]
Hi,
I love your mod and all thinks what you have in the last years have add. But I hope you can the 1.12.2 Mod with the new Features of Version 3 of your mod adding.

**Comment by Keksuccino** [comment]
Sorry, no 1.12 support for v3. It’s almost impossible to backport the modernized v3 code to 1.12 and it's also pretty difficult to keep FM up-to-date for all these MC versions.
