### ISSUE TITLE
A Couple bugs found [Single player menu uneditable and background issues]

### ISSUE THREAD

**Issue by DelviousCrafts** [Keksuccino/FancyMenu#643]
**Describe the bug**
1) Editing of the single-player menu is impossible. When you enter the single-player menu, the fancy menu toolbar stops reacting. It will not accept any clicks whatsoever. This includes the creation of a new world menu as well.
2) The dirt message screen does not override the dirt texture for the background after it's set. It appears when editing the menu, but not after you exit the editor. You can place an image and stretch it horizontally and vertically as a workaround.
3) same as 2, but for the receiving level screen.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to Single player menu
2. Click on the fancy menu bar
3. nothing will happen

1. Go to dirt message screen or receiving level screen.
2. Change the background.
3. Close the editor.
4. See the original dirt texture for the loading screen.

**Expected behavior**
Expect to have the ability to edit single player menu, and to have the dirt texture replaced when replacing the background of the dirt message menu and receiving level screens

**Game Log**
[Latest Log](https://gist.github.com/DelviousCrafts/ddf87eb65777315c2058ab4fdc582b1c)
[Debug Log](https://gist.github.com/DelviousCrafts/f9de683d69394588279e1784bd544407)

**Screenshots**
![Screenshot 2024-01-26 052629](https://github.com/Keksuccino/FancyMenu/assets/46658624/8eac3a94-c11c-4497-9a37-dd55f231957b)
![Screenshot 2024-01-26 052704](https://github.com/Keksuccino/FancyMenu/assets/46658624/1024f8b4-1133-4c27-8143-49e0504bc37a)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: 3.0.1
 - Forge Version: 47.2.20
 - Minecraft Version: 1.20.1
 - Active Mods: Drippy Loading Screen: 3.0.0, Konkrete: 1.8.0, Melody: 1.0.2

**Comment by Keksuccino** [comment]
Thank you, but please don't put multiple bugs in one issue. Will close this because I split the bugs into separate issues.
