### ISSUE TITLE
SingleplayerScreen breaks FM (only 1.20.1+ ??)

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#645]
- #643 
- FM 3.0.1
- MC 1.20.1
- Forge 47.2.20

**Comment by Musikid-Official** [comment]
I'm getting the same thing on 1.20.4 Fabric 0.15.6

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.0.3!
