### ISSUE TITLE
[bug] orientation data hanging off screen

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#65]
When the element to position is on the right of the screen, the right side information will hang off the screen.

![image](https://user-images.githubusercontent.com/3880072/87883982-bf6a0b80-c9d0-11ea-86f9-ee0cbf535fea.png)

idea solution is to have it detect the edge and move to the other side of the element

**Comment by Brittank88** [comment]
Just wanted to add that a similar thing happens with the context menu pushing through the top / bottom of the screen.

**Comment by Keksuccino** [comment]
> Just wanted to add that a similar thing happens with the context menu pushing through the top / bottom of the screen.

Not really a bug ^^ You need to lower your GUI scale, make your MC window bigger or lower the scale of these popup/context menus by clicking on the little settings button in the side menu of the editor :)

**Comment by Brittank88** [comment]
Well.. I understand I can lower the GUI scale to fix it, however, I don't know how that can not be considered an issue, especially considering the difficulty that adds to evaluating how the menu looks at GUI scale 3. I'm not at any weird windows size - it's simply a 1080p monitor running MC in fullscreen. I'm sure many, many people view MC this way and will have the same problem.

It would be like the Minecraft developers telling you it's not their problem that GUI options are off-screen unless you change your video settings - that simply makes no sense.

Is it really impossible to at least improve the 'decision code' that chooses whether the context menu displays above or below the cursor? A lot of the 'overhangs' would be fixed if it would simply flip to the other side...

However, I know all development has limits, so if it's really hard to do a proper fix, I understand! I guess I just wanted to at least discuss it a bit and get a better understanding of why this may not be so easily worked on. c:

**Comment by Brittank88** [comment]
P.S. I'm starting to wonder if I came across as confrontational...this was not my intention! I just wanted to throw my own two cents in about it. Apologies!

**Comment by Keksuccino** [comment]
I will completely rework the whole editor UI soon and will try to improve the context menus with it.

**Comment by Brittank88** [comment]
Awesome, I look forward to that!

**Comment by Keksuccino** [comment]
Added/Fixed in FancyMenu v3.0.0!
