### ISSUE TITLE
[1.12] Bug server + crash 

### ISSUE THREAD

**Issue by riroute** [Keksuccino/FancyMenu#652]
hi,
I modified my menu of my games and my games crash since launch and also when I am connected to my server I have freezes every 3 seconds in the console of my games a spam message saying that fancy menu n 'is not on the server and when I put it on the server my server crashes
(1.12.2)
[crash-2024-01-28_14.15.21-client.txt](https://github.com/Keksuccino/FancyMenu/files/14076159/crash-2024-01-28_14.15.21-client.txt)

**Comment by Keksuccino** [comment]
This is not a bug, it's a mod conflict with some Core mod. Try to remove "The Camping Mod 2". If that doesn't help, search all your core mods for conflicts.

For future questions: #569
