### ISSUE TITLE
Appearance Delay not working on startup (probably Forge only)

### ISSUE THREAD

**Issue by adamk33n3r** [Keksuccino/FancyMenu#654]
**Describe the bug**
Delayed fade in on elements on the main menu isn't working on first load. They work with a refresh or by going into a menu and back. But on first load, they are already there. I even tried setting the delay on an element to 5 minutes and it was still there immediately on load.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Set an element on the main menu to fade in with a delay
2. Restart your game
3. Once the main menu shows, notice that the element is there without a delay

**Expected behavior**
The elements on the main menu with delays are delayed on game load

**Game Log**
[latest.log](https://github.com/Keksuccino/FancyMenu/files/14081190/latest.log)

**Basic Information:**
 - OS: Windows
 - FancyMenu Version: 3.0.2
 - Forge/Fabric Version: Forge 47.2.17
 - Minecraft Version 1.20.1

**Comment by Keksuccino** [comment]
- Seems to be an issue only on Forge

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.0.3!
