### ISSUE TITLE
Fade in doesn't work with the Player Entity element

### ISSUE THREAD

**Issue by adamk33n3r** [Keksuccino/FancyMenu#655]
**Describe the bug**
The delay works, but it just pops in. No fade

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Set delay and fade on the player entity element
2. Reload and notice the delay works but it just pops in without a fade

**Expected behavior**
The player entity fades in after the delay

**Game Log**
[latest.log](https://github.com/Keksuccino/FancyMenu/files/14081647/latest.log)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 3.0.2
 - Forge/Fabric Version: Forge 47.2.17
 - Minecraft Version: 1.20.1

**Comment by Keksuccino** [comment]
This will never work, sorry.
