### ISSUE TITLE
[1.12.2] big freeze every 3s when I have fancymenu

### ISSUE THREAD

**Issue by riroute** [Keksuccino/FancyMenu#657]
hey, I have a big bug when I connect to my server, my games freeze every 3 seconds and when I remove fancymenu I no longer have the bug, in the game console (clientside) FML spam that client and core mods are missing on the server but when I put them my server crashes
[Uploading latest.log…]()

**Comment by Keksuccino** [comment]
Mod incompatibility. Check which core mods are causing the lag.

If you have more questions: #569
