### ISSUE TITLE
[Feature Request] Group select

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#66]
Could use the ability to group select elements for group level functions, such as move, align, delete for starters.

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.7.0! Thank you for your suggestion!

**Comment by kreezxil** [comment]
how do you group select? is it in the wiki anywhere?

**Comment by kreezxil** [comment]
i don't see it 
![image](https://user-images.githubusercontent.com/3880072/117440179-528d1700-aef9-11eb-8a12-a094a5712cd5.png)

**Comment by Keksuccino** [comment]
It’s already in the wiki :p
http://fm.keksuccino.de/books/fancymenu-v20x/page/20x-layout-editor#bkmrk-shortcuts

Thank you very much for your kind words!

**Comment by kreezxil** [comment]
I'd like to suggest opening the github wiki up to the world, let us edit it
for you. As it stands you have the wiki broken up over your currently 3
versions, soon to be many versions. It would be better to have a legend at
the front to say what versions a feature is from and then when a feature
isn't in all the versions we can use the symbols from the legend. That
maybe too complicated too, we can just say what versions it's found in,
yeah that would be better.

Granted I can always make an unofficial one, we're at the stage now
with the reach of this mod. :)

**Comment by Keksuccino** [comment]
I don’t think I will do that, sorry. The wiki is a documentation for the mod and I always need to know where everything can be found to easily link to it. Well, and I don’t have enough time to check user edits for errors, etc.. Sorry, but it’s just easier for me like that :/

**Comment by kreezxil** [comment]
the problem is as if you can't tell, only 2.0 has group select, anyone
using any of the other versions won't know this and will ask for it as a
feature. sure it hasn't happened yet, but it can. perhaps you've had
similar instances with other features that were requested that do not exist
on the older versions and not the newer.
