### ISSUE TITLE
Player Entity Not Updating Skin [old skin URL gets cached in element maybe]

### ISSUE THREAD

**Issue by SkightMeow** [Keksuccino/FancyMenu#660]
**Describe the bug**
The Player Entity element is not updating. I updated my skin, but it is stuck on my old skin. i couldn't find any other duplicate issues similar to mine and i'm lost if there is anything i can do. i tried everything from restarting to refreshing to changing skin again.

**To Reproduce**
Change player skin

**Expected behaviour**
Player Entity element to update with player skin changes.

**Game Log**
Log not relevant

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/156274940/3d3772ec-53cd-49c2-be81-f2d8a484a56d)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version [2.14.13]
 - Fabric Version [0.15.6]
 - Minecraft Version [1.20.1]
 - Active Mods [not relevant]

**Comment by Keksuccino** [comment]
Just noticed that this is about FancyMenu v2, which should not have bugs related to incorrectly showing auto skins, so I think it's just the API I'm using that is caching your old skin in some way maybe.

If it still shows your old skin, check if you maybe set an actual hardcoded skin URL by accident or something. Also try toggling "auto skin" off and on again.

Will close this for now, but if you still have questions, please join the Discord server: #569

**Comment by SkightMeow** [comment]
I tried everything you said before creating the Issue, may i ask which API are you using?

**Comment by Keksuccino** [comment]
I'm using this API: https://api.ashcon.app/mojang/v2/user/<USER_NAME_HERE>

**Comment by adamk33n3r** [comment]
Checking that API, it's returning the URL for my old skin. Here's my stuff [https://api.ashcon.app/mojang/v2/user/adamk33n3r](https://api.ashcon.app/mojang/v2/user/adamk33n3r)
It returns http://textures.minecraft.net/texture/957c4f863d249cf5e0b4dc4a7d9b87c3726ac7940bc409d40936872ef566b2d8
but my current skin that shows up on minecraft.net is 
![image](https://github.com/Keksuccino/FancyMenu/assets/1350444/f3992ab9-d925-43ad-b3c9-7cae78db46ae)
https://textures.minecraft.net/texture/38228bf58c41bd0c9ca62941ddeca8c49e3ec4d5ce928515cab7ff444bdb9b71

You can see the old one is even an outdated resolution without the extra layers.

So it looks like that API isn't working anymore as it should.

**Comment by adamk33n3r** [comment]
If you wanted to do it yourself using minecraft's api.
1. Get id from [https://api.mojang.com/users/profiles/minecraft/adamk33n3r](https://api.mojang.com/users/profiles/minecraft/adamk33n3r)
2. Get profile data from here using the id from step 1 [https://sessionserver.mojang.com/session/minecraft/profile/b63fa9dfdbd74f8b9bdbeaa486781115](https://sessionserver.mojang.com/session/minecraft/profile/b63fa9dfdbd74f8b9bdbeaa486781115)
3. Base64 decode `properties[name=textures][value]` to get the json which gets this
```json
{
  "timestamp" : 1706860788807,
  "profileId" : "b63fa9dfdbd74f8b9bdbeaa486781115",
  "profileName" : "adamk33n3r",
  "textures" : {
    "SKIN" : {
      "url" : "http://textures.minecraft.net/texture/38228bf58c41bd0c9ca62941ddeca8c49e3ec4d5ce928515cab7ff444bdb9b71"
    },
    "CAPE" : {
      "url" : "http://textures.minecraft.net/texture/f9a76537647989f9a0b6d001e320dac591c359e9e61a31f4ce11c88f207f0ad4"
    }
  }
}
```
4. Then you can get `textures->SKIN->url`

**Comment by SkightMeow** [comment]
I can't seem to get it to update to my current skin no matter what... This is exasperating
