### ISSUE TITLE
Player Entity: Auto-Skin doesn't set slim skin type

### ISSUE THREAD

**Issue by Liamgrayskull** [Keksuccino/FancyMenu#661]
![image](https://github.com/Keksuccino/FancyMenu/assets/129421895/bdcb4d3e-475f-4a02-80a7-ccd8b4b8457f)

When using the autoskin function, it doesn't register the player's skin format, instead opting to default to the thicker armed skin. Along with this, it seems to default to a tan cape- is there any way to toggle these things with the autoskin enabled, or to let it read more player info?

**Comment by Liamgrayskull** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/129421895/7279fb13-b135-423f-af80-ca2d4739fbf1)

Autoskin & Copy Client Player both have this same issue

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.0.5!
