### ISSUE TITLE
Issues with "Skin Shuffle" mod

### ISSUE THREAD

**Issue by Saiko125** [Keksuccino/FancyMenu#670]
when using both FancyMenu and Skin Shuffle mod the skin select menu displays a lot of info

latest log: (sorry that it's a link but I don't want to look thru my instance to find the latest one) https://mclo.gs/3IF4k6P

![image](https://github.com/Keksuccino/FancyMenu/assets/86660217/6731c0c2-44f0-4c87-9534-028857d8b5e4)

 - OS: Windows 10
 - FancyMenu Version [3.0.4]
 - Fabric Version [0.15.6]
 - Minecraft Version [1.20.4]
 - Active Mods [as mentioned above Skin Shuffle]

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.0!
