### ISSUE TITLE
Can't hide mods notification icon

### ISSUE THREAD

**Issue by MakotoPD** [Keksuccino/FancyMenu#673]
I cant hide mods icon from ModMenu

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/48807218/10dab879-1c1c-463b-9025-f78cf55d6de3)

**Basic Informations:**
 - OS: Windows 11
 - FancyMenu Version 3.0.4
 - Fabric Version 0.15.6
 - Minecraft Version 1.20.1

**Comment by Keksuccino** [comment]
That's the ModMenu "Mods" button icon and you can disable it in ModMenu's settings. This is not a bug.
