### ISSUE TITLE
Panorama seems to speed up randomly

### ISSUE THREAD

**Issue by Stoutscientist** [Keksuccino/FancyMenu#674]
**Describe the bug**
Panoramas speed up sometimes

**To Reproduce**
Create a universal layout with a panorama, it will speed up on some menus, like for me it's normal in options but fast on the main menu and super fast when closing the game.

-    OS: Windows
-    FancyMenu Version 3.0.4
-    Forge/Fabric Version Fabric 0.15.6
-    Minecraft Version 1.20.4
-    Active Mods Sodium and related mods.

**Comment by Keksuccino** [comment]
This is related to MC having different FPS caps for the Title screen than most other menus in (I think) MC 1.20+.
I noticed this, but I would probably need to rewrite the full panorama rendering to fix this, so I will give it a low priority for now, sorry.

**Comment by Stoutscientist** [comment]
> I think this is related to MC having a different FPS cap for the Title screen than most other menus in (I think) MC 1.20+. At least that would explain the weird panorama rendering behavior, but I didn't check this theory yet.
> 
> I noticed this, but I would probably need to rewrite the full panorama rendering to fix this, so I will give it a low priority for now, sorry.

That's kind of what I was thinking but I opened MSI Afterburner's OSD and the FPS was the same in all the menus

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.0!

**Comment by Stoutscientist** [comment]
> Fixed/Added in FancyMenu v3.1.0!
ok actually how are you so good??

**Comment by Keksuccino** [comment]
I just moved the angle logic/calculation to another thread, so it isn't bound to the FPS anymore :D
