### ISSUE TITLE
Options go off screen on set Minecraft option

### ISSUE THREAD

**Issue by Stoutscientist** [Keksuccino/FancyMenu#675]
**Describe the bug**
Options go off screen on set Minecraft option

**To Reproduce**
Create a button and select the action set Minecraft option then click on the box, the suggestions will go offscreen

-    OS: Windows
-    FancyMenu Version 3.0.4
-    Forge/Fabric Version Fabric 0.15.6
-    Minecraft Version 1.20.4
-    Active Mods Sodium and related mods.

**Comment by Keksuccino** [comment]
Make your MC window big enough and don't use an abnormally big GUI scale, then everything should work.

<img width="1023" alt="Screenshot_1" src="https://github.com/Keksuccino/FancyMenu/assets/35544624/e02256d2-8edb-4fc3-890b-4f0b3158fcd1">
