### ISSUE TITLE
MidnightLib still incompatible

### ISSUE THREAD

**Issue by CSMMaster** [Keksuccino/FancyMenu#676]
**Describe the issue**
Mod Menu will not open when Fancy Menu is installed. Removed Fancy Menu, and Mod Menu functions properly. Tried making the change mentioned in the Incompatibility list on your wiki. Did not work for this issue.

**Game Log**
https://gist.github.com/CSMMaster/949f357ad1accf9c861f0819ba54c724

**Basic Informations (please complete the following information):**
 - OS: Ubuntu 22.04.3LTS
 - FancyMenu: Fabric 3.0.4 (the log says 3.0.3, but file name says 3.0.4)
 - Fabric Version: 0.15.6
 - Minecraft Version: 1.20.1
 - Active Mods: LOTS. Please read the log for a full list

**Comment by Keksuccino** [comment]
This is an incompatibility with MidnightLib and not Mod Menu. I tried to fix this incompatibility already but seems like it still happens for some reason.

**Comment by CSMMaster** [comment]
Okay. Thank you for the clarification.

**Comment by Keksuccino** [comment]
Should be fixed in FancyMenu v3.0.6! If it still happens, please open a new issue with new logs, thank you very much!
