### ISSUE TITLE
Incompatibility with "Modpack Update Checker" (mod is not updated to work with FMv3 yet)

### ISSUE THREAD

**Issue by 69ShadesOfPeanut** [Keksuccino/FancyMenu#679]
**Describe the issue**
Game crashes on startup when both fancy menu and modpack update checker are enabled

**Game Log**
latest.log doesnt provide any info weirdly enough. the crash report file does however
[https://mclo.gs/HO8sSLj](https://mclo.gs/HO8sSLj)

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 3.0.5
 - Forge/Fabric Version Fabric 0.15.6
 - Minecraft Version 1.20.1

**Comment by Keksuccino** [comment]
please send the `logs/latest.log` after experiencing the crash, thank you very much!

**Comment by 69ShadesOfPeanut** [comment]
heres a log from when it crashes, it doesnt provide much if anything
[https://mclo.gs/uisoytX](https://mclo.gs/uisoytX)

**Comment by Keksuccino** [comment]
Nvm, that's just because Modpack Update Checker is not updated to work with FancyMenu v3 yet. It adds a bunch of custom placeholders to FancyMenu and the API used to do that changed in v3. That's why it crashes. If you want to use Modpack Update Checker, you need to use FancyMenu v2 for now.

**Comment by Keksuccino** [comment]
Fixed in Modpack Update Checker v0.12.1.
