### ISSUE TITLE
[Feature Request] File Choose should remember last directory it was in

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#68]
it would be awesome if File Chooser could remember the last directory it was in and start there. Instead it starts at the root of the pack everytime. 
![image](https://user-images.githubusercontent.com/3880072/87884137-e70da380-c9d1-11ea-8506-c15d32331f2f.png)

**Comment by Keksuccino** [comment]
Added in FancyMenu v1.5! Thank you for your report!
