### ISSUE TITLE
After button desappears tooltip is still visible

### ISSUE THREAD

**Issue by Caisenn** [Keksuccino/FancyMenu#680]
**Describe the bug**
Title says it.

**To Reproduce**
1. Create button, that can hide other buttons and be hidden if specific varible is false
2. Create same button, but must have a a tooltip and be hidden by default, but shown if that specific variable is true 
3. Press it
4. Enjoy your tooltip, that can be hidden only if you press another button.

**Expected behavior**
Tooltip shouldve been desappear when i press the button

**Basic Informations:**
 - OS: Windows 10
 - FancyMenu Version 3.0.5
 - Neoforge 47.1.97
 - Minecraft Version 1.20.1
 - Active Mods FancyMenu, Melody, Konkrete
 
 **Video**

https://github.com/Keksuccino/FancyMenu/assets/136863281/b77fda7f-d780-4c86-815b-bd52fa11daf7

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.0!
