### ISSUE TITLE
[Feature Request] left side menu should move when it overlaps elements

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#69]
When the left side menu overlaps elements it becomes tedious access it.

![image](https://user-images.githubusercontent.com/3880072/87884228-964a7a80-c9d2-11ea-93d6-3b9be225a223.png)

Ideally, having it part of a submenu on right click context menu would be great, or having it move dynamically.

**Comment by Keksuccino** [comment]
Why is it hard to open the side menu? It should open just fine, even when it overlaps layout objects :o

**Comment by kreezxil** [comment]
it's inconvenient when it overlaps elements, i'm not agile like you, i'm
old like 53, so things happen.

**Comment by Keksuccino** [comment]
Ohh you mean it’s hard to see?
Sorry, I just want to understand what exactly you mean >.<

**Comment by kreezxil** [comment]
I don't mean it's hard to see. Maybe it should be part of a right click
context menu, that would make it better honestly.

**Comment by kreezxil** [comment]
I can make a video explaining what I'm failing to convey with words

**Comment by Keksuccino** [comment]
That would be great, thank you! ^^

**Comment by Keksuccino** [comment]
Will close this for now. If you still struggle to use the side menu, please open a new report with a video of what doesn’t work like you want it to work and I will see what I can do to improve the handling with it! :D Thank you very much!
