### ISSUE TITLE
Simple percentile sizing

### ISSUE THREAD

**Issue by SLimeyMC** [Keksuccino/FancyMenu#693]
**Describe your idea**
Simple percentile sizing that can be toggled by user, if user opt to priotize percentile sizing when editing element it will reflect that on the size value, could also be toggled to be affected by GUI sizing.

Basically what percentile sizing does is that it will resize the GUI as minecraft windows size changes.

This is way easier than to use placeholder

**Comment by Keksuccino** [comment]
This is called "Auto-Scaling" in FancyMenu and is already a thing ^^
Right-click the editor background to configure auto-scaling.
