### ISSUE TITLE
Slider variable usage unclear

### ISSUE THREAD

**Issue by xlifi** [Keksuccino/FancyMenu#695]
*Is there a lore reason I needed to look into source code to find out slider's variable is `$$value`? Am I stupid?*

**Describe your idea**
Add a docs article for slider.
Add a text somewhere in-game that tells user the variable and describes how it works.

**Comment by Keksuccino** [comment]
> Am I stupid?

<img width="434" alt="Screenshot_1" src="https://github.com/Keksuccino/FancyMenu/assets/35544624/612add7d-1b35-4235-ab77-272895ccdacd">
