### ISSUE TITLE
Add support for NeoForge 1.20.1

### ISSUE THREAD

**Issue by EndangeredNayla** [Keksuccino/FancyMenu#697]
**Describe the issue**
NeoForge targets Forge 47.1.x, please change forge requirements to 47.1.x instead of 47.2.x

**Comment by Keksuccino** [comment]
FancyMenu does not support NeoForge yet and will never support NeoForge builds before MC 1.20.2.

**Comment by Keksuccino** [comment]
Well actually, let me see what I can do. But no promises. If 47.1.X breaks my workspace I will not support it, sorry.

**Comment by ddaodan** [comment]
I modified the `mods.toml` forces loading in neoforge and it looks like it works fine
![image](https://github.com/Keksuccino/FancyMenu/assets/40017293/1df1a541-0904-4106-93c2-9163612c14c4)

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.0!
