### ISSUE TITLE
Allow custom cursors to be used everywhere.

### ISSUE THREAD

**Issue by PolyframeX** [Keksuccino/FancyMenu#699]
**Describe your idea**
Hi, This mod does have support for custom cursors, however they are only used on layouts its specified on. Sure you can use universal layouts, but that only applies to pages with customization enabled. Which can be an issue if you want the cursor to show everywhere. So a independent option for this would be really great!

**Comment by Keksuccino** [comment]
Enabling customizations is only a problem with some mod screens. And the custom cursor itself could also be a problem in some mod screens, so it would be a bad idea to enable the custom cursor for all screens, just like with other customizations. I will not add this, sorry.
