### ISSUE TITLE
FR Translation

### ISSUE THREAD

**Issue by Mozork01** [Keksuccino/FancyMenu#702]
[fr_fr.json](https://github.com/Keksuccino/FancyMenu/files/14319673/fr_fr.json)

FR translation 🎁

**Comment by Keksuccino** [comment]
That's great, thank you!

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.0!

**Comment by Keksuccino** [comment]
This translation is also on [Crowdin](https://crowdin.com/project/fancymenu) now for easier updating/fixing!
