### ISSUE TITLE
There is no way to make a custom background or image.

### ISSUE THREAD

**Issue by CarlGamer2024** [Keksuccino/FancyMenu#703]
**Describe the bug**
You can't make a background or image.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to 'set a background (or add image)'
2. Click on 'image and configure background then choose image then source type local (or any one where you can choose the file.) then type a image file in the resource source'
3. Scroll down to '...'

**Expected behavior**
Set the background or image to the file

**Basic Information:**
 - OS: [e.g. Windows 11 pro]
 - FancyMenu Version [e.g. 3.0.6]
 - Forge Version [e.g. the forge version for 1.20.4]
 - Minecraft Version [e.g. 1.20.4]
 - Active Mods [e.g. required mods.]

**Comment by Keksuccino** [comment]
What exactly do you mean? I'm pretty sure setting backgrounds works fine everywhere (menu backgrounds, button backgrounds, etc.).

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
