### ISSUE TITLE
Can't move Splash Text Anymore

### ISSUE THREAD

**Issue by KakashoLin** [Keksuccino/FancyMenu#705]
**Describe the bug**
Updating to the latest update, V3 version. You no longer can move the splash text, and since the update not only did it move from where it was now you can't even move it around. A big circle with a line through it appears. 

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Update to the latest, v3.
2. Go to the main menu
3. Open FancyMenu editor
4. Try and move splash text.

**Expected behavior**
You should be able to move the splash text and pin it to the screen.

**Comment by Keksuccino** [comment]
And the big red circle didn't make you think it's on purpose? It's not a bug. You need to delete it and add a custom splash text. You can make that custom text display Vanilla splash text content.
