### ISSUE TITLE
Another big update - another crash

### ISSUE THREAD

**Issue by Proxwian** [Keksuccino/FancyMenu#708]
**Describe the bug**
Maybe it's mixing issue, but I'm not sure. Previous version of mod (latest 2.*) works well.

**To Reproduce**
1. Install latest TerraFirmaAdventure modpack
2. Update FancyMenu + DrippyLoadingScreen
3. Get a crash

**Expected behavior**
Game will launch

**Game Log**
[crash-2024-02-21_08.24.04-client.txt](https://github.com/Keksuccino/FancyMenu/files/14354433/crash-2024-02-21_08.24.04-client.txt)

[latest.log](https://github.com/Keksuccino/FancyMenu/files/14354435/latest.log)

**Basic Informations (please complete the following information):**
 - OS: macOS Sonoma 14.2.1
 - FancyMenu Version 3.1.0
 - Forge/Fabric Version 47.2.20
 - Minecraft Version 1.20.1
 - Active Mods - see latest.log

**Comment by Proxwian** [comment]
Also my old configs was rewritten and when I downgrade back to 2.14.13, them not work

**Comment by Keksuccino** [comment]
This is caused by Chat Heads and is already known as incompatible: https://docs.fancymenu.net/en/incompatibility-list

The v2 config does not work in v3, so this works as intended: https://github.com/Keksuccino/FancyMenu/blob/master/changelog.txt

**Comment by Proxwian** [comment]
> This is caused by Chat Heads and is already known as incompatible: https://docs.fancymenu.net/en/incompatibility-list
I don't see Chat Heads in list above

**Comment by Keksuccino** [comment]
sorry, I had the wrong name in mind. I meant "Chat Colors".

Chat Heads should work now actually :) It was incompatible, but the dev released an update, so at least the latest version of Chat Heads should be compatible!
