### ISSUE TITLE
Audio on Global Layout playing twice

### ISSUE THREAD

**Issue by fibberclip** [Keksuccino/FancyMenu#709]
**Describe the bug**
So i've been using a Global Layout that applies to all main menus when launching the game to play menu music, the audio element has multiple audio files (.ogg), chooses between them at random and plays everytime you're in the game menus outside of a world, worked just fine.
However, after updating my modpack, adding a few mods (leaving it at around 250 mods) and modifying the main menu layout, now the menu music plays twice on game load, once as soon as the game finishes loading and the menu shows up, and one a few seconds after. And one of those instances of menu music (the one that starts first) is somehow global?? Even playing when opening the FancyMenu editor, and only stopping if lowering the game's master volume to 0 and back to whatever it was (haven't tried entering a world/server to see if it stops)
My guess is it's loading the audio element wrong bc of the greater amount of mods causing the game to load slower? Idk, is there any way to fix this?

**To Reproduce**
1. Create a Global Layout with only an audio element in it
2. Add various .ogg sound files to the audio element
3. Enable customization on all main menus (mod menu, settings, resource packs, etc)
4. Re-Launch the game

**Expected behavior**
Audio should only play once, not twice, and audio probably shouldn't continue playing in the fancymenu editor

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 2.14.7
 - Forge/Fabric Version: 40.2.9
 - Minecraft Version: 1.18.2
 - Active Mods: The mod list is huge to send here, but here's a couple mods i consider could be the issue;

1.  Tinkers Construct
2. Silent Gear
3. Simple Splash Screen
4. Ding
5. FancyMenu Video extension
6. Load my Resources

**Comment by Keksuccino** [comment]
Please update to the latest version of FancyMenu (v3.1.0). It solves this and lots of other issues.
