### ISSUE TITLE
Recources Fail To Load Correctly On Latest Sodium Version

### ISSUE THREAD

**Issue by PolyframeX** [Keksuccino/FancyMenu#713]
**Describe the bug**
When loading into the game with the latest sodium, all of fancy menu fails to load.

**To Reproduce**
1. Create a simple custom title screen
2. Reload the game
3. See the title not load

**Expected behavior**
Game should load all recources fine.

**Game Log**
https://pastebin.com/B5PKjiBr

**Screenshots**
Not applicable

**Basic Informations (please complete the following information):**
 - OS: [Windows 11]
 - FancyMenu Version [3.1.0]
 - Forge/Fabric Version [Fabric 0.15.7]
 - Minecraft Version [1.20.1]
 - Active Mods [Many mods present, view logs for list]

**Comment by Keksuccino** [comment]
Please try it with only Sodium + FancyMenu. Does it still happen?

**Comment by PolyframeX** [comment]
It must be a mod incompatibility, as it works fine with just FancyMenu and sodium.

**Comment by Keksuccino** [comment]
Are you sure it's even related to Sodium in any way? Is it loading all resources when you have ALL other mods EXCEPT Sodium installed?

**Comment by PolyframeX** [comment]
It happens when I update sodium to the latest version oddly enough. But works fine when on an older version. I'm not sure why.

When going in the game, everything else seems to load perfectly fine, its just fancymenu. Maybe something else is messing with it as well but I honestly couldn't tell you what it would be.

**Comment by PolyframeX** [comment]
Issue has been determined to be caused by another mod. Not related to FancyMenu.
