### ISSUE TITLE
Command/Text Entering Action

### ISSUE THREAD

**Issue by RepeatGitHub** [Keksuccino/FancyMenu#714]
**Summary**
Currently, as of the latest version, there is an Action trigger able via buttons called "Paste to Chat". It's really useful, but the problem with it is that it doesn't allow you to actually send the message that is pasted in chat.

**Potential Uses**
One way this could be used is to utilize server commands. For example, imagine I'm working on a custom client for a Minecraft server, and I want to add a button that, when pressed by a player, makes that player input the command /shop. Currently, the button would only be able to open chat and paste /shop into the chat box. However, if this were to be added (perhaps as an option in the text value section of the command, similar to the Append Text option), it would vastly improve the possibilities of this action.

**Comment by Keksuccino** [comment]
There is a "Send Message or Command" action that does exactly that already.

**Comment by RepeatGitHub** [comment]
omg i feel idiotic i literally just saw it ingame lmaooooo
