### ISSUE TITLE
Image element at different positions in editor and actual GUI [1.18.2]

### ISSUE THREAD

**Issue by xFirefalconx** [Keksuccino/FancyMenu#716]
**Describe the bug**
Uhh... insert confused lenny face here. Edit mode preview =/= what is saved?!?
I dunno how this happened but the image of my odd jar is a wanderer. Look at screenshots.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
Difficult to reproduce I think, this layout is from my 2.x GUI screen (custom GUI). Might happen elswhere too though?
I can send the layout if you tell me how to pack it so you can check if it does that for you as well. 
For me, 
1. Open this GUI and confirm PNG location
2. Go to Edit and look at it
3. Jar is suddenly where it should be. 
4. Save and exit, jar jumps back to this place.
Extra info, I got a rectangle above it to make it look greyed out, maybe that's an issue?

**Expected behavior**
Edit mode actually is the same as the saved output. 

**Game Log**
https://gist.github.com/xFirefalconx/9a9a8d1b4dec4ebb182a709942c39188
Might not be helpful tho..

**Screenshots**
![grafik](https://github.com/Keksuccino/FancyMenu/assets/106652912/737703f7-1276-447b-8d22-ee57dd4060e6) ![grafik](https://github.com/Keksuccino/FancyMenu/assets/106652912/518e817e-5305-4fba-aead-4434a9f9911d)

**Basic Informations (please complete the following information):**
 - OS: Win 10 64x
 - FancyMenu 3.1.0
 - Forge 40.2.17
 - Minecraft 1.18.2
 - Active Mods ..... a LOT. https://gist.github.com/xFirefalconx/1342d4aab223943fe0fcfaf7c5c53bf8

**Comment by Keksuccino** [comment]
If it's a converted layout, just remove the Image element and add it again. v2 -> v3 conversion does not have a 100% success rate.

**Comment by Keksuccino** [comment]
This could be related to #724.

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v3.1.2!
