### ISSUE TITLE
Crash during startup when... setting window to large (windows button between - and x, top right corner)(1.18.2)

### ISSUE THREAD

**Issue by xFirefalconx** [Keksuccino/FancyMenu#718]
**Describe the bug**
Disclaimer: I dunno if this a FM or Drippy loading screen issue! But it's never happened before the 3.0+ upgrade. 
Game crashes when I click on largen window (or however you call that button) during startup. I can confirm this happens only when watermedia and video extension (from sr rapero) are enabled, I clicked like a maniac on my modpack without those two, didn't crash. 

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Click that make window large/make window small button
2. It should crash

I tested, it even crashes without doing that, but maybe the crash is not the same message. Please test both situations accordingly. I need to find the log where that happened, it got buried. Will add it once found! And update this note. 

**Expected behavior**
Usual behavior without any crashes. Maybe the game freezes and that causes issues? Idk. 

**Game Log**
https://gist.github.com/xFirefalconx/d5df3ff80856134efea2a85b5e2dabc9

**Screenshots**
N/A

**Basic Informations (please complete the following information):**
 - OS: Win 10
 - FancyMenu 3.1.0
 - Forge 40.2.17
 - Minecraft 1.18.2
 - Active Mods uh... have a whole list. https://gist.github.com/xFirefalconx/1342d4aab223943fe0fcfaf7c5c53bf8 <- put on top of that also fancymenu_video-1.18.2-2.2.0.jar and the dependency watermedia-2.0.28.jar as causes, meaning this *very likely* is an incompatibility issue.

**Comment by SrRapero720** [comment]
you ask me on my discord about watermedia... why you report a bug about ``FancyMenu: Video Extension``? are different things...
FM Video extension is not compatible with FM 3.0+ and is not intended to work.

**Comment by SrRapero720** [comment]
I can confirm a 1.20.1 version of the extension compatible with FM v3, nothing older. and is not gonna happen soon

**Comment by xFirefalconx** [comment]
Apologies then. Back when FM 3.0 was announced I asked (iirc) about [can I still use the extension, that is footing on watermedia, or not] and I understood that it was possible because as far as I understood it from what I read... "watermedia is what everything is depending on, so it should work fine." (not what you said but what I understood) 
Guess I misunderstood just as much. 
Will see if I stay on legacy until there's an update for 1.18.2 then or if there will be an other solution to play youtube videos in the future, idk. Thanks for clarifying the situation though. At least I know what I can work with now.
