### ISSUE TITLE
Custom window icons not loading correctly [1.18.2]

### ISSUE THREAD

**Issue by xFirefalconx** [Keksuccino/FancyMenu#719]
**Describe the bug**
The game does not display the custom set icon on Windows (10), only if I "refresh" that. 

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Start modpack and wait for menu to load
2. The icons should be broken both on task bar and window bar
3. Go to the menu point where you can set them, click disable
4. Go to the menu point where you can set them, re-enable them!
5. It works now, but why not on startup?

**Expected behavior**
I don't have to do this above. (Plus, my pack users might not be able to do this. It looks unprofessional. Positive thing, it at least *seems* to reliably overwrite once re-enable toggled, other than 2.x versions of FM, so thumbsup, improvement.)

**Game Log**
https://gist.github.com/xFirefalconx/f7cdd6ba0f278232636a1339e6a37027

**Screenshots**
N/A

**Basic Informations (please complete the following information):**
 - OS: Win 10 (64x) (if it matters, this PC got upgraded from Windows 7(64x), originally. Ask anything related to that if necessary plz!)
 - FancyMenu 3.1.0
 - Forge 40.2.17
 - Minecraft 1.18.2
 - Active Mods uh... have a whole list. https://gist.github.com/xFirefalconx/1342d4aab223943fe0fcfaf7c5c53bf8

**Comment by Keksuccino** [comment]
This is 100% a mod confllict. Setting and loading custom window icons works fine.

**Comment by xFirefalconx** [comment]
Okay, will go on a hunt for the incompatible mods then (will not be soon though), I'll post whatever I find in here then!

**Comment by Keksuccino** [comment]
Closed because not reproducible.
