### ISSUE TITLE
Optifine menus don't open 

### ISSUE THREAD

**Issue by lucasboss45** [Keksuccino/FancyMenu#72]
**Describe the bug**
Optifine menus don't open in video settings

**To Reproduce**
1. Go to video settings with default layout
2. Click any of the optifine buttons

**Expected behavior**
The optifine menu should open

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.4.3.1
 - Forge Version 31.2.31
 - Minecraft Version 1.15.2
 - Active Mods:
- FancyMenu 1.4.3.1
- Optifine OptiFine_1.15.2_HD_U_G1_pre30

**Comment by lucasboss45** [comment]
On top of that the "Done" button is also broken in the video settings

**Comment by Keksuccino** [comment]
Fixed in v1.4.4! Thank you for your report!

**Comment by lucasboss45** [comment]
Sweet, thank you!
