### ISSUE TITLE
Crash when Audio Ext for Fancy Menu (Forge) is added

### ISSUE THREAD

**Issue by SquirrelCraft** [Keksuccino/FancyMenu#720]
**Describe the bug**
Was updating my mod packs when I updated FancyMenu, Drippy Loading Screen and now the game crashes. I created a new profile with same Forge version, and added Fancy Menu. Game works. Added DrippyLoading, still works. Added Audio Ext for Fancy Menu and I get the crash. 

In the debug log there is a hint here
```
[26Feb2024 16:01:53.281] [main/DEBUG] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Found 22 mod requirements (18 mandatory, 4 optional)
[26Feb2024 16:01:53.281] [main/DEBUG] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Found 1 mod requirements missing (0 mandatory, 1 optional)
[26Feb2024 16:01:53.281] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Unsupported installed optional dependencies:
	Mod ID: 'fmextension_audio', Requested by: 'fancymenu', Expected range: '[9999.9.9,)', Actual version: '1.1.1'
```

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. New Profile, Forge 47.2.20, MC 1.20.1
2. Add Fancy Menu (3.1.0), Drippy Loading (3.0.1)
3. Start game, should start Ok, close the game
4.  Add  Audio Ext for Fancy Menu (1.1.1) 
5. Start game, crashes

**Expected behavior**
Should not crash out of the box

**Game Log**
[latest.log](https://gist.github.com/SquirrelCraft/980fac436fdd024c6542ca27b116ae7e)
[debug.log](https://gist.github.com/SquirrelCraft/34310f54a2ac942755588e648b50d734)
[crash-2024-02-26_16.02.00-client.txt](https://gist.github.com/SquirrelCraft/68ee2287c505b8e4bfeabce2d9398118)

**Basic Informations (please complete the following information):**
 - OS: MacOS 13.6.4
 - FancyMenu Version: 3.1.0
 - Forge/Fabric Version: 47.2.20
 - Minecraft Version: 1.20.1
 - Active Mods: FancyMenu, DrippyLoading, Audio Ext

**Comment by Keksuccino** [comment]
There simply is no Audio extension for FancyMenu v3. Remove the extension.
