### ISSUE TITLE
The armor on the player doll

### ISSUE THREAD

**Issue by 4EEZE** [Keksuccino/FancyMenu#725]
It would be really cool if the doll could have armor and items in its hands like the doll in the player's inventory.
![изображение](https://github.com/Keksuccino/FancyMenu/assets/76529316/4d3604f3-e32e-42e8-91a9-26f98a99de2f)

**Comment by 4EEZE** [comment]
Oh yes, I forgot to say that if this doll will be in the pause menu or other interfaces that the player opens in the world, the ekepirovaniya on the doll will be dynamically updated depending on what the player is wearing, well, and problems with other mods I think it will not cause.

**Comment by Keksuccino** [comment]
There are currently no plans for adding the ability to set armor and weapons to Player Entity elements, sorry.
