### ISSUE TITLE
Custom splash texts don't match the position of vanilla ones.

### ISSUE THREAD

**Issue by Wanderer70** [Keksuccino/FancyMenu#726]
I wanted to recreate the main menu screen from before 1.20.1 (or 1.19.3, I'm not sure) because in 1.20.1 the scale/positioning of the Minecraft logo is broken and you can't achieve the same look of the logo from older versions of the game with resourcepacks. 

To do that, I made a clean 1.19.2 install to copy the positioning of the Minecraft logo, edition and splash texts into 1.20.1
While doing so, I discovered that if you make a custom splash text with the exact same dimensions as the vanilla one, you won't be able to match the two if you put them in the exact same coordinates. I had to move the custom splash text to achieve the desired look. I don't know if that applies to every variation of the texts, or if every variation has a different offset. If so, that would be... really problematic.

I couldn't find a way to move the text inside the splash text box without moving the box itself. If there is a way to do that, I'm sorry for reporting this. I'd be happy with any kind of help!

Screenshots:
Here the scale and position of the splash text box are exactly the same, yet they do not match.
![Screenshot (937)](https://github.com/Keksuccino/FancyMenu/assets/97387920/fc390368-0c6d-49d7-a7fc-7b6f7d5c45b8)

How it should be:
![Screenshot (938)](https://github.com/Keksuccino/FancyMenu/assets/97387920/568e45b3-4737-4425-8fe5-da236e1bafe3)

What I aim to recreate: (ignore the missing edition text)
![Screenshot (936)](https://github.com/Keksuccino/FancyMenu/assets/97387920/bb29e055-bd33-40e5-b0f5-45eff0809f03)

**Comment by Keksuccino** [comment]
That's not really a "bug", it's just that the Custom Splash element probably uses slightly different code for calculating the splash position than the Vanilla element. Sorry but I won't "fix" that. It works perfectly fine, it's just not exactly the same position calculation than Vanilla, which is okay. You will need to work around that, sorry.

**Comment by Wanderer70** [comment]
No problem! I get it. Thanks for the reply)
