### ISSUE TITLE
FancyMenu complains about invalid URL when it is not

### ISSUE THREAD

**Issue by lucasboss45** [Keksuccino/FancyMenu#73]
**Describe the bug**
FancyMenu complains about an invalid URL when trying to add a perfectly valid URL

**To Reproduce**
1. Add the following URL as a Web Text on any Layout `https://songs-of-war.com/getserverinfo.html`

**Expected behavior**
It should be added without problems

**Screenshots**
![image](https://user-images.githubusercontent.com/29255472/89531965-574d5f00-d7f1-11ea-92f4-b668092dc221.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.4.3.1
 - Forge Version 31.2.31
 - Minecraft Version 1.15.2
 - Active Mods: OptiFine_1.15.2_HD_U_G1_pre30

Note: This also happens with the "Web Image" feature

**Comment by Keksuccino** [comment]
Hi! Did you solved it? What was it?

**Comment by lucasboss45** [comment]
Hey, yeah it was an issue apparently an HTTP Code other than 200 makes it believe the URL is "invalid", I think my webserver was returning a 403 error which caused it to be detected as an invalid URL.

**Comment by Keksuccino** [comment]
Ohh okay, glad you got it working! :)
