### ISSUE TITLE
Localization Spanish (Spain)

### ISSUE THREAD

**Issue by C4BR3R4** [Keksuccino/FancyMenu#732]
> Well thank you very much for the translation, but there's lots of ASCII stuff (emojis) in it. I am honest with you. I would like to include it, but not with the emojis.

I added the symbols in v2 and I understand that in the official language file of v3 I should not include them.
I have already removed the ASCII Symbols and the color codes added: [es_es.json](https://github.com/Keksuccino/FancyMenu/files/14546121/es_es.json)

I forgot to say, I have added two missing strings:
fancymenu.helper.editor.items.features.advanced_sizing.width
fancymenu.helper.editor.items.features.advanced_sizing.height

PS. It took me a long time to convert from .lang to .json and translate the new strings. To help me I had to sort the alphabet lines.

**Comment by Keksuccino** [comment]
There are still multiple ASCII symbols in the translation, ma guy.

And there should be no missing strings in the [official language file](https://github.com/Keksuccino/FancyMenu/blob/v3-1.20.4/common/src/main/resources/assets/fancymenu/lang/en_us.json). [Crowdin](https://crowdin.com/project/fancymenu) should show you all the stuff that's too much or missing.

**Comment by Keksuccino** [comment]
Closed because no response.
