### ISSUE TITLE
1.20.1 Forge 47.2.7 Texture Missle

### ISSUE THREAD

**Issue by Krimatoria** [Keksuccino/FancyMenu#733]
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
watermedia-2.0.28.jar
fancymenu_forge_2.14.7-3_MC_1.20.jar

https://gist.github.com/Krimatoria/36ddd11a86c971f4b0b604b5bb046e50

**Comment by Keksuccino** [comment]
Please update your mods. Latest FMv2 for 1.20.1 is 2.14.13 (and latest FMv3 is 3.1.2).
