### ISSUE TITLE
Unable to create instance of Smithing Table Screen via `ScreenInstanceFactory`

### ISSUE THREAD

**Issue by AntoineDehan** [Keksuccino/FancyMenu#737]
**Describe your idea**
Hi, the "net.minecraft.client.gui.screens.inventory.SmithingScreen" gui screen (gui screen of the smithing table) is simply not supported when trying to open it with the "/openguiscreen" command.

**Comment by Keksuccino** [comment]
I decided to not add support for these types of inventory-based screen for now, which includes the Smithing screen, Smoker screen, Beacon screen, Grindstone screen and other similar screens.
