### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gjmhmm8** [Keksuccino/FancyMenu#738]
[crash-2024-03-16_02.14.40-client.txt](https://github.com/Keksuccino/FancyMenu/files/14619337/crash-2024-03-16_02.14.40-client.txt)

**Comment by Keksuccino** [comment]
Dude this isn't even related to FancyMenu..

`ava.lang.IllegalStateException: Item has no registry name: 1 golden_sacrificial_bowl BlockItem(occultism:golden_sacrificial_bowl)`
