### ISSUE TITLE
Global actions (Add/Set to all) in layout editor

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#74]
**Describe your idea**
Add option to set global hover and normal textures for buttons. That are only overrode when a texture is explicitly chosen for a button.

**Does it frustrates you to not already have this feature in the mod?**
- [x] Yes it's frustrating to apply the same two textures to each button
- [x] I can live without it
- [x] Quality of Life improvement estimates at least 210%

**Comment by Shorepion** [comment]
Just had a similar idea and wanted to add:
-global buttonclick sounds, hoverbutton sounds
-global widgets.png overriding
-global background
.. for all submenus

**Comment by Keksuccino** [comment]
Global layouts will not be added because it would probably break too much, but multi-selection and button actions for multiple selected buttons got added in FancyMenu v1.7.0!
