### ISSUE TITLE
Disabling hotkeys

### ISSUE THREAD

**Issue by RedCrafter07** [Keksuccino/FancyMenu#741]
**Describe your idea**
My idea is to bring back the useful config option to disable the keyboard shortcuts so people don't directly mess with your GUI; they need "more know-how" to do that - especially useful for the distribution in modpacks

**Comment by Keksuccino** [comment]
People without know-how will not know the hotkey to enable the customization menu. I removed the option to disable hotkeys because this lead to problems where modpacks creators disabled everything in the config and then forgot how to manually enable it again.

**Comment by Keksuccino** [comment]
I will not add this, sorry.
