### ISSUE TITLE
Executing `/fmvariable` command via `/execute as` command doesn't work

### ISSUE THREAD

**Issue by Mowzy-Graphics** [Keksuccino/FancyMenu#745]
**Describe the bug**
- Setting a FmVariable using `/fmvariable set test true Wawawoui` works, but once you try to apply the variable to another user, by using the vanilla `/execute as {player} run fmvariable set test true Wawawoui`, you'll get a message saying _"Invalid boolean, expected 'true' or 'false' but found 'Wawawoui' ... set test Wawawoui true"_.

I believe the arguments are turned around for some reason. Using `/execute as {player} run fmvariable set test true true Wawawoui` will return "FancyMenu Variable value set to: Wawawoui true".
Using `/execute as {player} run fmvariable set test true true Wawawoui Wawazar` will return "FancyMenu Variable value set to: Wawawoui Wawazar true".

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go in game
2. use command to set fmvariable `fmvariable set test true Wawawoui` in a command block, console, or even in chat after a `execute as @s run `
3. Watch the mod have a cardiac arrest

**Expected behavior**
Should not switch argument's position.

**Game Log**
Not sure the whole log will be of any help, so have my snippets :
`[23:02:50] [Render thread/INFO]: [System] [CHAT] �y[FancyMenu] Variable value set to: �zWawawoui
[23:02:56] [Render thread/INFO]: [System] [CHAT] Invalid boolean, expected 'true' or 'false' but found 'Wawawoui'`

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: [Windows 10]
 - FancyMenu Version [3.1.2]
 - ForgeVersion [47.2.20]
 - Minecraft Version [1.20.1]
 - Active Mods [issue unrelated to mods, someone else had the issue without my mods https://discord.com/channels/704163135787106365/1220819654369480824 ]

**Comment by Keksuccino** [comment]
Is this a Vanilla command? I've never heard about it o.O
Well it's absolutely possible that FM's commands don't work via `/execute as`, since FM's commands are a bit special because they need to work purely client-side in some situations.

**Comment by Mowzy-Graphics** [comment]
> Is this a Vanilla command? I've never heard about it o.O Well it's absolutely possible that FM's commands don't work via `/execute as`, since they are a bit special because they need to work purely client-side in some situations.

Yes,  the /execute as command is native to Vanilla Minecraft. It allows for the execution of a command as though it were initiated by a specific player (or any entity).

You can compare it to the `/sudo`  command from the plugin Essentials.

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.3!
