### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gjmhmm8** [Keksuccino/FancyMenu#748]
[crash-2024-03-23_21.51.27-client.txt](https://github.com/Keksuccino/FancyMenu/files/14731776/crash-2024-03-23_21.51.27-client.txt)

**Comment by Keksuccino** [comment]
The crash is probably not even related to FancyMenu and it's also not helpful to just throw a crash log at me without giving any context of how and when the crash happened, why you think it's caused by FancyMenu, etc.
