### ISSUE TITLE
More Layoutable Screens

### ISSUE THREAD

**Issue by VioletTheKitty** [Keksuccino/FancyMenu#749]
Like that you can create custom layouts for the settings screen for example.

**Comment by Keksuccino** [comment]
You can create layouts for every Vanilla screen in the game and even many mod screens.
If the menu bar isn't visible in the settings screen, you probably have a mod installed that overrides that screen, like OptiFine for example.

Editing stuff inside scroll areas (like in some settings screens, the singleplayer screen and multiplayer screen) is not possible and will never be.
