### ISSUE TITLE
Rendering Screen NPE

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#76]
# Describe the bug
A player on my new Survive The Nether pack hit the 'n' key and subsequently crashed.

## Client Crash Report
https://pastebin.com/buCcB4f1

**Comment by T0uchMeSenpai** [comment]
The n key is assigned to voxelmap's waypoint menu. Based on the crash report (and consequently the latest.log file), I suspect a problematic interaction between FancyMenu and voxelmap. I will do a couple tests and see if there is anything to add.

**Comment by Keksuccino** [comment]
@kreezxil do you have "legacybuttonids" enabled in the mod config?

@T0uchMeSenpai Most likely yes. It opens a menu, so I assume some of the buttons of the voxelmap menu are added in a weird way or something.

Will check this out later! :)

**Comment by kreezxil** [comment]
It's not a conflict with voxelmap, i've remapped voxelmaps keys and it's still happening.

new client crash report:
https://gist.github.com/81137f8ea53e9ea4ecf91cbc1844c8dd

new client latest.log:
https://gist.github.com/158ba68e8f5d9fa77f4f5731edd09012

new client debug.log:
https://gist.github.com/408bff70b2e20814eadb525f56058e26

and we use a launcher such as GDL so it doesn't even launch the packs from that location.

**Comment by kreezxil** [comment]
the config.txt:
https://gist.github.com/f72dc1f1abf3d99ed4c55b4787dd4a3a

you said legacy ids, is that the source of the issue here?

**Comment by kreezxil** [comment]
ok, i turned off using legacy ids and the crashes went away

**Comment by Keksuccino** [comment]
`Screen name: com.mamiyaotaru.voxelmap.gui.GuiAddWaypoint`

It's crashing in a voxelmap GUI, I’m pretty sure it’s a conflict with it :D 

I just asked if you’re using legacy IDs, because the crash happens in a method related to it. Wasn’t sure if not using the legacy system would fix it ^^

**Comment by Keksuccino** [comment]
@kreezxil Does excluding voxelmap menus fixed your issue?

**Comment by kreezxil** [comment]
just 2 comments back I said that turning off legacy ids worked. **https://github.com/Keksuccino/FancyMenu/issues/76#issuecomment-674601226**
