### ISSUE TITLE
Conflict of layers involving subtitles

### ISSUE THREAD

**Issue by seriousfreezing** [Keksuccino/FancyMenu#761]
I have no way of modifying this top center text. Do you have any solutions or tips to fix this?

**To Reproduce**
Make some changes to the resource packs screen and place an element at the top.

**Game Log**
https://paste.atlauncher.com/view/9bc26502-fe6b-452a-bb81-44a0208b2713

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/300567b9-c0ef-464a-ab8e-4d6ca4e38720)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu 3.1.2
 - Forge/Fabric 0.15.7
 - Minecraft 1.20.4
 - Active Mods [e.g. Optifine, 5zig, TooManyItems]

**Comment by seriousfreezing** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/431f0cd3-2c8b-4bb6-b550-dfced0aa9580)
In fact, it seems that this also affects the keyboard screen. It has this strange visual bug

**Comment by Keksuccino** [comment]
Again: You have mods installed that mess with screens. Please start the game with only FancyMenu + dependencies installed. It's most probably a mod conflict.

**Comment by seriousfreezing** [comment]
Again, my nobleman
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/710217af-ed37-48e8-b82f-19eec007b06f)

**Comment by Keksuccino** [comment]
Do you talk about the "drag and drop" text in the first screenshot? You can't edit that text, sorry. You shouldn't edit the resource pack screen in general tbh, that screen never worked rgreat for any type of customizations.

But that's not related to the visual bug in the second screenshot. The second screenshot shows a list entry text glitching through a custom (?) header texture? It is a custom header texture?

**Comment by seriousfreezing** [comment]
I knew that these screens where there is little customization can be full of problems because you can't customize so much, but that's okay.

I know the second screenshot doesn't have much to do with it, but it's related because it's something about layers. And yes, it's a customized texture for the header.

**Comment by Keksuccino** [comment]
Okay so I just checked the screen and there's no screen-wide header and footer texture for that screen, but two headers and footers for the two lists (as expected), which means you simply placed an Image element at the top, right? You need to tell me that stuff _in detail_. "I placed an element" can be anything. The Image element is placed over the text, so you expect it to be hidden behind the element. Is this correct?

The text glitching through the texture in sadly a Minecraft rendering bug. They always had problems with text rendering and one of the bugs is that it sometimes glitches through images. I can't fix that, sorry.

**Comment by seriousfreezing** [comment]
Ok ok, I'm sorry I didn't say it was a picture, I didn't think it was such an important detail either. But it's good to know that it's Mojang's fault from time to time :D
