### ISSUE TITLE
Header/Footer customizations not taking effect

### ISSUE THREAD

**Issue by seriousfreezing** [Keksuccino/FancyMenu#762]
**Describe the bug**
I've already changed the texture of the header and footer via FancyMenu but no change occurs, nor do the features to deactivate the shadow work.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to a menu page, no matter if it has been changed before or not.
2. Activate the header/footer options to deactivate the shadow or change the texture

**Game Log**
https://paste.atlauncher.com/view/cc8cdacc-f4a4-4bc7-9a0e-cbfe3400f927

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/e1a2b038-6d56-4844-b898-ec742013335f)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu 3.1.2
 - Forge/Fabric 0.15.7
 - Minecraft 1.20.4

**Comment by Keksuccino** [comment]
Please start the game with only FancyMenu + dependencies installed. You definitely have mods installed that mess with screens, so it's very possible this is a mod conflict.

**Comment by seriousfreezing** [comment]
Sure!

**Comment by seriousfreezing** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/6b0c78c3-dc72-4166-b74e-1c745176609b)
I've just tested it with the mod and it still doesn't change anything

**Comment by Keksuccino** [comment]
Where's the back button in the top-left coming from?

**Comment by seriousfreezing** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/0ae53f3a-0b0c-4273-a910-81a567a4be83)
It's just a button that I created to import into all the interfaces

**Comment by Keksuccino** [comment]
The header/footer textures work fine for me in a clean Fabric 1.20.4 instance with FancyMenu 3.1.2.
_But_ by checking that I discovered a different visual bug. For some reason the footer texture is in front of the Vanilla buttons. This is probably a 1.20.4+ bug.

<img width="667" alt="Screenshot_1" src="https://github.com/Keksuccino/FancyMenu/assets/35544624/e3ab35c7-96fd-4cf1-9a33-2187a47bfb3f">

**Comment by seriousfreezing** [comment]
Oh, I didn't even know it was a bug. I've experienced this bug several times, and in order to solve it I had to redo all the buttons (Vanilla) that were bugged to one made in FancyMenu.

**Comment by seriousfreezing** [comment]
Would you like me to send you my files so you can take a look and tell me what would be the alternative to fixing my bug?

**Comment by Keksuccino** [comment]
> Oh, I didn't even know it was a bug. I've experienced this bug several times, and in order to solve it I had to redo all the buttons (Vanilla) that were bugged to one made in FancyMenu.

Several times? I've checked multiple screens and the only screen I found was the MP screen. What screens exactly did you find?
And how exactly where you able to encounter it several times if earlier it sounded like you wasn't able to get the header/footer feature to work? o.O

**Comment by seriousfreezing** [comment]
I had found this on another screen, which is paused during the game (ESC). I had to redo some of the buttons to make them still visible because of the image background.

**Comment by seriousfreezing** [comment]
In fact, I'm still not sure how to make this background completely clean in Multiplayer, without shadows/headers/footers.

**Comment by Keksuccino** [comment]
It is not recommended to make the screens "clear" in pre-1.20.5 anyway. They are not made to have no headers/footers and removing the header/footer texture can cause render glitches and other weird stuff.

**Comment by seriousfreezing** [comment]
Ohh, got it! I didn't know that, but why pre-1.20.5? Does it have to do with the change they made to blur the interfaces?

**Comment by Keksuccino** [comment]
Just tested it and setting fully transparent textures for header/footer and disabling the shadows seems to do exactly what you want, ignoring the button glitch of course.

<img width="767" alt="Screenshot_2" src="https://github.com/Keksuccino/FancyMenu/assets/35544624/605bd3b1-9de3-4259-bd34-4584a19a3836">

**Comment by seriousfreezing** [comment]
Hmmm, so in for me to achieve the effect I want, I must put something in the background, it can't be an empty .png image, can it?

**Comment by Keksuccino** [comment]
You need a fully opaque background texture. There's nothing behing screen backgrounds, so using a transparent texture there will do _very_ weird stuff. You can try it, but only for science :)

Actually in some cases there should be the dirt texture BEHIND the custom background, but not in all cases.

So yes, you need to set a custom background, which should override the dirt background and then set a fully transparent header/footer texture. Maybe it's enough to change the header/footer and not the background, but you will need to try that. It could vary from screen to screen.

**Comment by seriousfreezing** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/2bcee1bc-7aeb-42ad-8fa8-edd623ddf7f3)
Let me know if that's what it would be like:
I've changed the background texture via resourcepack but the header and footer I've always left with an empty texture and nothing happens yet

**Comment by Keksuccino** [comment]
I don't exactly know what you expect should happen tbh 😅

**Comment by seriousfreezing** [comment]
Oh sorry, I just wanted a solid background in one color. But I can't do it, so I'm going to close this issue so I can only get help via discord.
