### ISSUE TITLE
Custom screen title not being changed.

### ISSUE THREAD

**Issue by seriousfreezing** [Keksuccino/FancyMenu#763]
**Describe the bug**
Well, I'm already using this formula to be able to delete any existing letter or title from pages, but in this case it doesn't work and I'd like to know why.

**Game Log**
https://paste.atlauncher.com/view/ae4fb433-7bab-47c6-91d1-7f44a4a468ce

**Screenshots**
![Captura de tela 2024-03-30 004235](https://github.com/Keksuccino/FancyMenu/assets/66693072/a5add1e6-638b-4e8b-81bd-846a281d9fa4)
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/6939de12-a96a-4665-b779-de6e29cca5dd)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu 0.3.2
 - Forge/Fabric 0.15.7
 - Minecraft 1.20.4

**Comment by Keksuccino** [comment]
Again: You have mods installed that mess with screens. Please start the game with only FancyMenu + dependencies installed. It's most probably a mod conflict.

**Comment by seriousfreezing** [comment]
![image](https://github.com/Keksuccino/FancyMenu/assets/66693072/622d7792-9bb9-430d-9c14-5a1a372e4327)
Same.

**Comment by Keksuccino** [comment]
Is that a Custom GUI or the normal Credits screen, but edited? It's very possible that screen hard-codes the screen title, in which case FancyMenu sadly can't edit it.

**Comment by seriousfreezing** [comment]
Well, it's a slightly modified version of the credits screen. So in that case, there's no way to fix it?

**Comment by Keksuccino** [comment]
Uhm nvm, I just tested it and it works fine, it's just simply not an actual title as in other screens, but a text widget. Just right-click the text and set its "Widget Text".

**Comment by seriousfreezing** [comment]
LOLOLOL, THANKS!
