### ISSUE TITLE
Vanilla button in Credits screen not working

### ISSUE THREAD

**Issue by seriousfreezing** [Keksuccino/FancyMenu#766]
**Describe the bug**
I was using the original button on the credits screen and it simply doesn't work anymore. I tried to solve it by creating another button for that screen and it still doesn't work.

I've removed all the mods to check if it's a conflict and it still doesn't work.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to the credits and attributions screen
2. Click on the button, it should work the first time, but not any more

**Game Log**
https://paste.atlauncher.com/view/ef9cf5d2-0188-4c8b-ae94-4a17784c88b1

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu 3.1.2
 - Forge/Fabric 0.15.7
 - Minecraft 1.20.4

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.2.3!
