### ISSUE TITLE
Markdown: Quote not working correctly

### ISSUE THREAD

**Issue by otowm** [Keksuccino/FancyMenu#769]
after the empty line the quote continues happening

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to 'Screen Editor'
2. Create any Text Element
3. Write any quote

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/78005264/52270e78-da76-4cc9-93fb-8ed5085dcfbe)
text taken from fancymenu docs https://docs.fancymenu.net/en/text-formatting
![image](https://github.com/Keksuccino/FancyMenu/assets/78005264/89547c98-2ab0-4680-89b2-65b2e37ac83d)

**Basic Informations:**
 - OS: Windows 11
 - FancyMenu Version 3.1.2
 - Forge/Fabric Version 0.15.9
 - Minecraft Version 1.20.1

**Comment by Keksuccino** [comment]
Is there a space or some other invisible character on that empty line?

**Comment by otowm** [comment]
> Is there a space or some other invisible character on that empty line?

im sure that is any char there, its an empty line
i tried to write direct on the text element and on a md file with vscode, here the file
[update.md](https://github.com/Keksuccino/FancyMenu/files/14861156/update.md)

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.3!
