### ISSUE TITLE
HTML or RSS Feed support

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Keksuccino/FancyMenu#77]
**Describe your idea**
Support would basic HTML displays or RSS Feed support would be fantastic. This would you you could dynamically import data like changelogs, player statistics, community updates or even a chat interface. Perhaps even iFrames could displays properly which in practice means you can embed websites and whatever content is present there (images, photos and other interactive content). The possibilities are endless!

**Does it frustrates you to not already have this feature in the mod?**
Not really, especially since I know this is a feature that would be extremely difficult to implement and maintain.

**Comment by Keksuccino** [comment]
Hi! There is already a similar feature in FM to add web texts by URLs :) Has some very basic markdown-like headline support and supports MC formatting codes.

**Comment by HenrikoMagnifico** [comment]
Oh wow, that's awesome! Do you think adding support for video playback is
feasable, too?

Den fre 28 aug. 2020 14:49Keksuccino <notifications@github.com> skrev:

**Comment by Keksuccino** [comment]
Tried that too :/ Sadly not possible without using third party APIs, which I try to avoid.

**Comment by Keksuccino** [comment]
Close because solved.
