### ISSUE TITLE
[NeoForge] Unable to join servers when FancyMenu is installed (only servers without FancyMenu??)

### ISSUE THREAD

**Issue by waddon1** [Keksuccino/FancyMenu#770]
**Describe the bug**
When attempting to join a server using a button or the multiplayer menu an error appears, when FancyMenu is removed it joins successfully (shown in screenshot)

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create a FancyMenu on NeoForge
2. Attempt to join a server

**Expected behavior**
Join server successfully

**Game Log**
https://gist.github.com/waddon1/57575ca2c1857fc80e5bcb6aed443822

**Screenshots**
If screenshots would help to explain the issue, please include these.
![image](https://github.com/Keksuccino/FancyMenu/assets/14033361/6616dfaa-ec06-4752-8399-06f973d656a3)

**Basic Informations (please complete the following information):**
 - OS: Linux
 - FancyMenu Version 3.1.2
 - Forge/Fabric/NeoForge Version 20.4.219
 - Minecraft Version [e.g. 1.15.1] 1.20.4
 - Active Mods [e.g. Optifine, 5zig, TooManyItems]

**Comment by waddon1** [comment]
The title change is incorrect the server is also running NeoForge of the same version

**Comment by Keksuccino** [comment]
Oh that's interesting, another user reported it only happens when joining Vanilla servers, but I guess it happens on all servers without FancyMenu installed maybe?

**Comment by waddon1** [comment]
Just put FancyMenu on the server and it successfully joined

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.3!
