### ISSUE TITLE
GIF library fails to get loop count of GIF image

### ISSUE THREAD

**Issue by NickHam13** [Keksuccino/FancyMenu#773]
**Describe the bug**
GIFs will loop indefinitely even if they are not set to loop

**Expected behavior**
The GIF should not loop

**Game Log**
[latest.log](https://github.com/Keksuccino/FancyMenu/files/14901519/latest.log)

**Screenshots**
[alpha_1.0.4_logo.gif](https://github.com/Keksuccino/FancyMenu/assets/49380508/bf99c688-2bf7-43bc-bac3-b38e3b64526e)
This is the GIF that I'm trying to use

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 3.1.3
 - Forge/Fabric Version: Fabric 0.15.7
 - Minecraft Version: 1.20.1

**Comment by Keksuccino** [comment]
_where_ do you try to play it?

**Comment by Keksuccino** [comment]
Yeah well nvm, looks like the library I'm using to decode GIFs fails to get the loop count for some reason. Not sure if that's true for every GIF or just for yours tho.

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v3.1.4!
