### ISSUE TITLE
Ears Support

### ISSUE THREAD

**Issue by glassPortal86** [Keksuccino/FancyMenu#778]
Currently, the "Player Entity" element doesn't display visual features from the [Ears](https://modrinth.com/mod/ears) client mod.

Not sure if this is relevant feature request but I'd be pretty happy to see support for it.

Here is a side-by-side comparison of how my character looks like in the Player Entity element vs in-game.
![comparison](https://github.com/Keksuccino/FancyMenu/assets/162492048/682f9783-5e64-4440-8f26-17e1829c2bf8)

Thanks for considering!

Edit: I also feel like it would be nice if the Player Entity could display the current in-game player character appearance like armours and held items. Just like in the survival inventory screen.

**Comment by Keksuccino** [comment]
Will probably not add support for that mod, sorry.
It's also not really possible to reflect the world player, because you're not always in a world when Player Entity elements are shown.
