### ISSUE TITLE
Crash When Saving

### ISSUE THREAD

**Issue by Darkfiend009** [Keksuccino/FancyMenu#78]
**Describe the bug**
When i try to save my layout after editing/moving buttons, adding a background and adding music, my client crashes. I clicked "save and disable other layouts"

**To Reproduce**
1. Edit buttons
2. Edit background
3. Add music
4. Click save, then crash

**Expected behavior**
I expected the layout to save.

**Crash Log**
https://pastebin.com/LHUHG46r

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Win 10
 - FancyMenu Version 1.4.6.1
 - Forge Version 33.0.22
 - Minecraft Version 1.16.2
 - The list of mods can be found in the crash log.

**Comment by Keksuccino** [comment]
Hi! Thank you for reporting a bug!

Could you please send me your full log file, located at '.minecraft/logs/latest.log'?

**Comment by Darkfiend009** [comment]
Sure thing!

https://pastebin.com/CrEBDCM4

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.5! Thank you for your report!
