### ISSUE TITLE
Add more placeholders and requirements related to the current world/server

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#782]
## Placeholders

- [x] World Time 
- [x] World Difficulty ( returns difficulty as string )
- [x] Active Hotbar Slot
- [x] Slot Item ( returns the current item in the given slot as registry key (resource location) )
- [x] Current Player Health
- [x] Max Player Health
- [x] Player Health In Percent ( returns value between 0.0 and 1.0 (0% - 100%) )
- [x] Current Player Absorption Health
- [x] Max Player Absorption Health
- [x] Player Absorption Health In Percent ( returns value between 0.0 and 1.0 (0% - 100%) )
- [x] Current Player Hunger
- [x] Max Player Hunger
- [x] Player Hunger in Percent ( returns value between 0.0 and 1.0 (0% - 100%) )
- [x] Current Player Armor
- [x] Max Player Armor
- [x] Player Armor In Percent ( returns value between 0.0 and 1.0 (0% - 100%) )
- [x] Current Player Experience Level Progress ( returns value between 0.0 and 1.0 (0% - 100%) )
- [x] Current Player Experience ( returns total current experience )
- [x] Current Player Level ( returns current level, not experience )
- [x] Current Mount Health
- [x] Max Mount Health
- [x] Mount Health In Percent ( returns value between 0.0 and 1.0 (0% - 100%) )
- [x] Mount Jump Meter In Percent ( returns value between 0.0 and 1.0 (0% - 100%) )
- [x] Boss Health In Percent ( takes index of boss bar ; returns value between 0.0 and 1.0 (0% - 100%) )
- [x] Active Bosses Count ( returns current boss bar count ) 
- [x] Active Effects Count
- [x] Active Effect ( takes the "index" of the active effect ; returns the effect's registry key or an empty string if no effect is active for that index )
- [x] Current Title ( takes title line (1 or 2) ; returns empty string if no title is shown )
- [x] Current Player X Coordinate
- [x] Current Player Y Coordinate
- [x] Current Player Z Coordinate
- [x] Current Server IP
- [x] Player Attack Strength Percentage ( value between 0.0 and 1.0 (0% to 100%) )
- [x] Gamemode ( returns game mode as string )
- [x] Player View Direction ( north, east, south, west )

## Requirements

- [x] Is Hotbar Slot Active ( takes slot as number )
- [x] Is Slot Filled ( takes slot as number )
- [x] Is Left-Handed
- [x] Is Clear Weather
- [x] Is Raining
- [x] Is Thundering
- [x] Is Snowing (only if possible in an easy way)
- [x] Is Player Running
- [x] Is Player Sneaking
- [x] Is Player Swimming
- [x] Is Player Jumping
- [x] Is Player In Biome (takes registry key (resource location) of biome)
- [x] Is Player Under Water
- [x] Is Player In Water
- [x] Is Player In Lava
- [x] Is Player In Fluid (all types of fluids, also modded ones)
- [x] Is Player In Dimension (takes registry key (resource location) of dimension)
- [x] Is Entity Nearby ( takes radius in blocks and registry key of entity (resource location) )
- [x] Is Player Riding Entity
- [x] Is Player Riding Jumpable Entity
- [x] Is Player Riding Entity With Health
- [x] Is Gamemode ( takes gamemode )
- [x] Is Effect Active ( takes registry key of effect type if possible )
- [x] Is Any Effect Active ( returns true if at least one effect is currently active )
- [x] Is Player In Powder Snow
- [x] Was Player In Powder Snow
- [x] Is Player Wearing Pumpkin
- [x] Should Show Attack Indicator ( if player attack strength is smaller than 100% )
- [x] Is Player Flying With Elytra
- [x] Is Player Flying (Creative or Spectator)
- [x] Has Player Absorption Health
- [x] Is Player Withered
- [x] Is Player Fully Frozen
- [x] Is Player Poisoned
- [x] Is Difficulty ( Takes difficulty as value )

**Comment by SrRapero720** [comment]
has caps locked or not
has block num or not
system volume
game volume (pid volume)

player is flying
player is death
player direction

(1.20.5+) current server stored cookies
current server ping

**Comment by KaaayKaay** [comment]
I'm not asking for anything here but... these placeholders would work really well for some kind of HUD overlay or replacement.

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
