### ISSUE TITLE
Add Option to set a timeslot to audios.

### ISSUE THREAD

**Issue by LinuxDetected** [Keksuccino/FancyMenu#783]
Good afternoon,

On the audios you can set that they reproduce on a specific hour, but you cannot set a timeslot. 

It would be a good idea to add that so for example somebody can put an audio during the times they want instead of having to have 24 audio blocks.

**Comment by Keksuccino** [comment]
That's already possible. Use the "Is Number" requirement in combination with the time placeholders. You should be able to set the requirement to "equals", "bigger than" and "smaller than". Use two requirements and let the first one check for "bigger than" and the second one for "smaller than".
