### ISSUE TITLE
Ticker not saving its tick delay value

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#786]
# Ticker on za za weeee woo weeee wooo

Every time I select a tick deleay and click enter, when I check back it is back to 0, I have being having this bug for a while now and another user has reported it. It seems to be happening across multiple versions of fancymenu.

I'm still gonna list a few things

Fabric 1.20.1
Windows
No drippy or other fancymenu addons
Soz if this is a horrible bug report with little information, I am on my phone in bed right now xD

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.2.0!
