### ISSUE TITLE
Support for Main Menu Scale Mod

### ISSUE THREAD

**Issue by Mysticpasta1** [Keksuccino/FancyMenu#79]
https://paste.atlauncher.com/view/8be865eb
1.12.2 on this modpack --> https://atlauncher.com/pack/MysticsCubicChunksModpack
I remove custom main menu and added fancy menu then pushed create layout it crashes with and doesn't respond (Kreezxil told me to post this ask him for more info).

**Comment by Mysticpasta1** [comment]
I turns out it was main menu scale.

**Comment by tilda** [comment]
I think this should be considered a bug, it does crash the game after all.

This only happened after I added Main Menu Scale. Attempting to go into an existing layout's editor crashes as well.

[Crash report is located here.](https://mystb.in/SalonMusclePublishing.sql) (thank god for vanillafix)

**Comment by Keksuccino** [comment]
https://github.com/Keksuccino/FancyMenu/wiki/Incompatibility-List

**Comment by Keksuccino** [comment]
Option to force-scale menus was added in FancyMenu v1.5.
