### ISSUE TITLE
A draggable element that other elements can anchor to

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#791]
This would help me re-create windows in minecraft.

Could also help Modpack developers create a simple way for the users to edit their GUI's without using fancymenu tools.

Also if possible some kind of way to have it so a requirement has to be met for it to be draggable.

I found a way to do this but it requires 3 layouts, a button, 2 variables and a ticker and can take a while to set up, also it does not scale or anchor since it requires advanced positioning to work.

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
