### ISSUE TITLE
Overlay to in-game hud

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#792]
I know that there was a mod for this in the past but I just want a simple way to add an in-game overlay

# This does not mean to make vanilla elements moveable or editable

All I want is a type of UI that overlays vanilla whilst still not stopping movement or mouse movement.

Also possibly a keybind to add the grey background, disable mouse movement and keyboard movement to click buttons placed on the overlay.

To make this better in future, you could make vanilla elements editable, but for now, just keep them where they are or just have a way to hide them.

This alongside draggable elements and keybinds could be **AMAZING** for creating an overlay like what most modern Clients have.

**Comment by Keksuccino** [comment]
This does not really belong here, since FM is not supposed to customize the HUD, but I'm currently working on something that could be interesting for you.
