### ISSUE TITLE
Cloth Config Support

### ISSUE THREAD

**Issue by KorbynTalks** [Keksuccino/FancyMenu#794]
I really want this to be added because imagine you are making a Modpack right, and you make a Custom GUI with buttons that lead you to configs from other mods, but when you try to make a button redirect a config that is made in Cloth Config, you see that incompatibility screen, making you have to scrap the button or make it grayed out incase they add support for it.

Well, I am one of those people, and I REALLY hate this and I really want it to be added at some point,
yes, I am aware with the workaround of mimicking a button, but what about fabric users that are using Mod Menu, and when they mimic the configure button, nothing happens?

**Comment by Keksuccino** [comment]
I will not add support for Cloth Config, sorry.
