### ISSUE TITLE
Set opacity of elements

### ISSUE THREAD

**Issue by rainyatrium** [Keksuccino/FancyMenu#795]
It would be very useful to be able to adjust elements' (or more specifically images') opacity on the fly. Would allow for users to much more easily create smooth effects & transition variants (fade-in progress tied to variables, etc*) without the need for lots of images or specially-assembled asset variants/anims. Right now I think it's conceptually possible to set up a variable-based opacity with that kind of system, but it would be super cumbersome to make adjustments to and quickly eat up storage space.
also, to memory, I think it's possible to adjust fade in time when elements load? but while useful, that isn't as versatile as this ability would be.
I think this would be a pretty powerful addition to the toolkit as far as menu interactivity & responsive elements.

It's come up a few times in the discord in the past couple months as well, so I know I'm not the only one who would find use in this!
- ankiolyne

*a couple example use cases-- slow fade between weather or time variants of a menu pulling from the system clock, elements that increase in opacity as the mouse nears them

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
