### ISSUE TITLE
full screen and windowed bug

### ISSUE THREAD

**Issue by Thunderrock424242** [Keksuccino/FancyMenu#796]
**Describe the bug**
A clear and detailed description of what the bug is. when ever I go into window mode it messes up my menu then full screen puts it to normal

**To Reproduce**
Steps to reproduce the behavior (e.g.):

**Expected behavior**
A clear and detailed description of what you expected to happen.
not be buggy
**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**. 
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE
[latest.log](https://github.com/Keksuccino/FancyMenu/files/15047285/latest.log)
!

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] windows
 - FancyMenu Version 3.1.5
 - Forge/Fabric Version forge 47.2.0
 - Minecraft Version 1.20.1
![Screenshot 2024-04-20 032037](https://github.com/Keksuccino/FancyMenu/assets/119463825/b47b5081-8ae5-4a1a-925b-ef6de8f1c12c)
![Screenshot 2024-04-20 032046](https://github.com/Keksuccino/FancyMenu/assets/119463825/c8a39add-db7c-4c6b-90bd-d3d5f1a3584d)

 - Active Mods [e.g. Optifine, 5zig, TooManyItems]

**Comment by Keksuccino** [comment]
that's not a bug, you just used the wrong anchor points.
https://docs.fancymenu.net/en/home#positioning-elements
