### ISSUE TITLE
Support for MC 1.16

### ISSUE THREAD

**Issue by maicol07** [Keksuccino/FancyMenu#8]
**Describe your idea**
Port the mod to 1.16 using Fabric. Forge don't support it at the moment

**Does it frustrates you to not already have this feature in the mod?**
I can't use the mod in 1.16

**Comment by Keksuccino** [comment]
A Fabric port is currently not planned, sorry.
I will update the mod to 1.16 once Forge for 1.16 is released.

**Comment by JJRicks** [comment]
Can I pay you for a Fabric port? ;D

**Comment by Keksuccino** [comment]
Nah, I’m not taking money for such stuff ^^ Sorry, but Fabric is too different and I don’t have enough time atm to port it. Maybe in the future, but definitely not now.

**Comment by dujinhuachinaeddie** [comment]
FFFFFFFFFAAAAAAAABBBBBBBBRRRRRRIIIIIICCCCCC
AAAAA           PPPPPPP           I
A.        A         P.             P         I
AAAAAA        PPPPPPP            I
A.         A        P                         I
A.         A.       P                         I

**Comment by Keksuccino** [comment]
N NNNNNNNNNNNOOOOOOOOOOOOOOOOOO

**Comment by Keksuccino** [comment]
FancyMenu now supports MC 1.16.1! :)
