### ISSUE TITLE
Waiting for a web page to load freezes the game

### ISSUE THREAD

**Issue by lucasboss45** [Keksuccino/FancyMenu#80]
**Describe the bug**
The game freezes when FancyMenu tries to load an unresponsive webpage (One that takes a while to load)

**To Reproduce**
Use the web text feature in Fancy Menu with a slow webpage

**Expected behavior**
No freezes

**Basic Informations (please complete the following information):**
 - OS: Any (Reproduced on Windows Linux Mac)
 - FancyMenu Version 1.4.6
 - Forge Version 31.2.31
 - Minecraft Version 1.15.2
 - Active Mods: Fancy Menu

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.5! Thank you for your report!
