### ISSUE TITLE
Ability to change orientation of (not hide!) the copyright text

### ISSUE THREAD

**Issue by rainyatrium** [Keksuccino/FancyMenu#800]
I totally understand & support the rationale behind not allowing us to hide the copyright text in V3-- but it would be useful to have maybe some degree of control over positioning for it, even if just selecting which corner to place it in (wouldn't want people dragging it offscreen) so it is less obstructive to certain menu designs! 

(in the current Pixelmon menu, for instance, it now covers up some text for some scenarios-- ultimately not a huge hindrance but just being able to move it up to the top left where it was initially designed to be placed would be a huge boon and allow for more menu design variants in other contexts too)

**Comment by Keksuccino** [comment]
Uhm.. you can already change the anchor point of the copyright lmao
