### ISSUE TITLE
LUA scripting for advanced usage

### ISSUE THREAD

**Issue by Merith-TK** [Keksuccino/FancyMenu#801]
may I suggest adding a form of "scripting" in a soft-external sense?
Where a user can use a bit of lua code that runs for the specied UI
(pause_menu will only run pause_menu.lua for example)
And can interact with elements by using their ID?

that way we can have scripts  that run without getting reset when layouts change

**Comment by Keksuccino** [comment]
But what would be needed for that to be actually useful? Wouldn't it be important to interact with the element's properties? Like size, position, visibility and all the stuff that exists only for specific element types.

That's a lot of work for the feature being used by like 4 people in total :D

**Comment by Keksuccino** [comment]
There are Ticker elements. You could use these to set a X or Y position variable. Best would be to use the Calculator and Random Number placeholders for that. The elements then would use the position variables via Advanced Positioning (right-click the element).

Actions have an easy to understand scripting "language" level, so everyone understands it. Like the "program a robot" games in school to show kids how programming works.

I am very sorry, but I don't think I will implement this.

**Comment by Merith-TK** [comment]
Fair enough, I like the idea of action script as it is but as someone coming from programming kubejs and computercraft scripts, far, *far* too many clicks, 

The menus definitely could use slot of enhancement (perhaps make action script elements have a similar edit UI as a layout element?)
