### ISSUE TITLE
Add user confirmation to "Run System Command" action (If action is found in action script, show confirmation before running any actions)

### ISSUE THREAD

**Issue by Merith-TK** [Keksuccino/FancyMenu#803]
I find it *highly concerning* for safety for a user to download a modpack, and have no idea that the current layout, has the capability to run commands on the host, or that it can just download files to run if its setup to do so?

**Comment by Keksuccino** [comment]
**Messages from Discord:**

It's part of a modpack in most cases. There can always be mods inside that do bad stuff. It's on you to only download modpacks from people you trust. FancyMenu does nothing more than every other mod out there. Tbh I wouldn't use a frickin menu customization mod to run my virus when I can just pack a JAR with the modpack.

Even if I would add a confirmation, you could always just patch it out with a simple mixin.

I will add a confirmation but it will change/solve absolutely nothing except upsetting users who need to confirm every button click 😄

**Comment by Keksuccino** [comment]
Btw: Even CurseForge thinks it's fine the way it is, because they manually check my FancyMenu builds every time and every time they say everything is fine after checking.

**Comment by Keksuccino** [comment]
**Update:** I don't really know how I should add a confirmation to Ticker elements tbh. I can't show a confirmation screen every time a ticker runs a system command..

**Comment by Keksuccino** [comment]
Will not add a confirmation before the action is getting executed, but instead make it an addon and remove it from base FM.
I will close this for now, because the issue moved to #805
