### ISSUE TITLE
I try to make an fancy menu, but when my friend try it its bugged

### ISSUE THREAD

**Issue by ElDreamsOFF** [Keksuccino/FancyMenu#807]
the bug its when my friend try the menu its bug

i think that the menu for him its bug or its my problem, he download the mods like i have so i dont know what

![image](https://github.com/Keksuccino/FancyMenu/assets/161099989/46553b43-64b0-4051-9886-944cecf68d93)

 Windows 11
 - FancyMenu Version 3.1.5 
 - Forge Version 47.2.30
 - Minecraft Version 1.20.1
 - Active Mods embiddium

**Comment by KaaayKaay** [comment]
Anchor your elements correctly
https://docs.fancymenu.net/en/positioning-elements
