### ISSUE TITLE
Ability to translate text based on the language you select

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#808]
Some kind of way to convert the English (or whatever language you use on your layouts) into another language you select from in minecrafts options.

This could be done automatically using something like google translate or it could be an option/toggle when making or editing an element to add a translation.

**Comment by Keksuccino** [comment]
That's already in the mod, but it doesn't translate your layouts. You need to localize them, which is the only correct way to do that.
https://docs.fancymenu.net/en/localization
