### ISSUE TITLE
layering issue

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#81]
**Describe the bug**
Splash layer is appearing behind the logo.

**Screen**
![image](https://user-images.githubusercontent.com/3880072/92483463-794e4e80-f1ae-11ea-88a6-14c5157c8997.png)

**Related Issues**
#9 

The player that reported this will be here shortly to add to it.

**Comment by Fade-X** [comment]
OS: Windows 10
Forge Version: 1.16.2 (33.0.42)
Minecraft Version: 1.16.2
Fancy Menu Version: 1.16.2 (1.4.6.1)

Issue is: Is there an ability to put images,text, etc. behind the background splash text?

**Comment by Keksuccino** [comment]
You can choose a rendering order for layouts. By choosing the "background" render order, your layout will be rendered behind other menu objects.

In the layout editor: Rightclick the editor background -> Renderorder
