### ISSUE TITLE
Ability to play .gif or .apng only once for button hover

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#811]
Ability to play .gif or .apng once upon button hover then stick to the last frame until your cursor atops hovering, then re-play animation once when you hover again and so on.

I want to add a hover slide-in-style animation to the buttons in my modpack but the hover animation repeats over and over, making it look janky.

**Comment by Keksuccino** [comment]
That already works. You just need to make your GIF/APNG not loop and then disable "Restart Animated Textures On Hover" for the button.

If you brainstorm ideas and you think "this should be possible already", please ask in Discord first before opening issues, thank you 😅
