### ISSUE TITLE
(Compat Request) bendy-lib + Player Entity Element = Advanced Player Model Editing

### ISSUE THREAD

**Issue by Yukiharuwu** [Keksuccino/FancyMenu#813]
"bendy-lib" essentially allows mods to bend a player model more than normal, such as having elbows/knees and the like. 
I feel that this would be a good addition to FancyMenu that would allow menu makers to be more creative with how they use the Player Entity Element.

**Comment by Keksuccino** [comment]
I decided not to add this, sorry.
