### ISSUE TITLE
Ram leak geckolib

### ISSUE THREAD

**Issue by Gniewko112** [Keksuccino/FancyMenu#815]
Fancy menu 3.1.7 for 1.20.1 with forge 47.2.30 cuse ram leak with gecko lib 4.3 and up,
i also use melody, loadmyresources and konkrete but evrything was fine with them, ram leak happend after adding fancy menu with problem also occurs when custom animated menu is diseabled

**Comment by Gniewko112** [comment]
![Uploading 5675675.png…]()

**Comment by Gniewko112** [comment]
![5675675](https://github.com/Keksuccino/FancyMenu/assets/168778403/531c09fc-33ae-40b8-bed8-55aaf5b0f014)

**Comment by Gniewko112** [comment]
I was wrong, ram leak is caused by loadmyresources

**Comment by Keksuccino** [comment]
I am pretty sure you just have a big animation or slideshow that uses a lot of RAM.

**Comment by Gniewko112** [comment]
Yes, but everything is fine if i use geckolib 4.2, i tested geckolib with mamy mods and it didn't cause any trouble, it's loadmyresources that couse ram leak if fancy menu, konkretne, melodie and geckolib 4.3 and up are in mods folder, i tried older versions for fancy menu, melodie and konkretne and ram leak still occured, can you somehow fix that bug?

**Comment by Keksuccino** [comment]
Just don't use LMR then. It's discontinued anyways. You only need LMR for FancyMenu's old animation format which gets replaced in the next FancyMenu update :)
