### ISSUE TITLE
Someone should fix this

### ISSUE THREAD

**Issue by CelestialDodo** [Keksuccino/FancyMenu#817]
**Describe the bug**
It says "Save", The bug is for "FancyMenu System Interactions Addon"

**To Reproduce**
1: Launch the Game

**Expected behavior**
im pretty sure it should say "Safe"

**Game Log**
No Game Logs Needed

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/120543993/3909eaa2-795f-4578-ad90-cef12ae1ae73)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: V1.0.0 MC 1.20.1
 - Forge/Fabric Version: Forge 47.2.0
 - Minecraft Version: 1.20.1
 - FancyMenu System Interactions Addon & FancyMenu
 
It even says it in the Curseforge and Modrinth screen shot 🤣

**Comment by Keksuccino** [comment]
- It's a typo, it's not the worst thing in the world?
- Of course it's also in the screenshot, why should it be different there?
- This is the wrong repository. FMSIA has its own repo and the typo is already an open issue there.
