### ISSUE TITLE
Incompatibility with "Oculus"

### ISSUE THREAD

**Issue by ANomralNoob** [Keksuccino/FancyMenu#818]
**Describe the issue**
every time i start up my game it crashes 

**Game Log**
Crash-Report: https://gist.github.com/ANomralNoob/051971293db28636b3ce48c433bdccdb

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 3.2.0 1.19.2
 - Forge/Fabric Version: forge - 43.3.0
 - Minecraft Version: 1.19.2
 - Active Mods: 
Oculus
Rubidium

**Comment by Keksuccino** [comment]
Oculus works fine with FancyMenu. You simply need to use a newer Forge version (43.3.5+).

**Comment by ANomralNoob** [comment]
ok! Thank You

**Comment by mahjerion** [comment]
Hi @Keksuccino,

Just an FYI that this problem persists even with the latest forge. Oculus mc1.20.1-1.7.0 seems to cause issues with FancyMenu.

Tried FancyMenu 3.2.X, 3.1.X and crash persists on start up. Only ran with FancyMenu, Drippy, Oculus. Happened on Forge 47.2.32 and 47.2.18 (1.20.1).

Not a big deal, I don't think Oculus 1.7.0 really does anything so I'm continuing to run 1.6.15a - thought I'd give you a heads up though.
