### ISSUE TITLE
Credits Screen Not Supported

### ISSUE THREAD

**Issue by NicholasJDi** [Keksuccino/FancyMenu#819]
**Describe the bug**
I'm Trying To Make A Custom Button That Takes You Directly To The Credits Screen (ID: win_screen) you cant, Its Impossible to Mimic The Button As Well, (For Mimic It Seems To Rely On The Screen ID Most likely Because Its The Same Screen As The End Poem And The Credits Version Doesn't Have The Poem, I May Be Wrong) 

**To Reproduce**
1. Create A Button In Any Screen (Other Than Credits And Attribution) 
2. Set To Open Screen (ID: win_screen) or Set To Mimic (ID: 39566)
3. Press Button

**Expected behavior**
Open The Credits Screen

**Game Log**
don't think this will be much help.
https://gist.github.com/NicholasJDi/b8b6899bf4c274439b8f8aa844e0ceb2

**Basic Information:**
 - OS: Linux Mint 21.1 Vera 64-bit
 - FancyMenu Version: 3.2.0
 - Forge/Fabric Version: Forge 47.2.0
 - Minecraft Version: 1.20.1
 - Active Mods: (WIP Modpack Sorry) https://gist.github.com/NicholasJDi/25449ad99b6be11c77c12dfa78bbf9cf

**Comment by Keksuccino** [comment]
Mimic works fine. You can mimic the Credits button in the Credits & Attribution screen.
Use `credits_and_attribution_screen:39566` as value for the **Mimic Button** action.
