### ISSUE TITLE
npe while editing layout

### ISSUE THREAD

**Issue by Fade-X** [Keksuccino/FancyMenu#82]
**Describe the bug**
Pressing {Edit Layout} crashes the launcher while theres a current layout that is to be edited.
**To Reproduce**
1. Go to 'customize'
2. Click on 'EditLayout'

**Expected behavior**
To give me the layout editor

**Crash Log**
https://gist.github.com/Fade-X/d7518b3923c289f9eed2d36cb8db4657

**Basic Informations (please complete the following information):**
 - OS: [Windows 10]
 - FancyMenu Version [1.4.6.1]
 - Forge Version [33.0.42]
 - Minecraft Version [1.16.2]
 - Active Mods [Optifine,OptifForge]

**Comment by Fade-X** [comment]
New Mention: It happens when other menus are edited. Tried editing it without having other menus do and i was able to edit the layout withoutcrashing

**Comment by Keksuccino** [comment]
Hi! Thank you for reporting a bug!

What do you mean by "other menus are edited"?
What other menus?

**Comment by Fade-X** [comment]
other menus/multiplayer menu, options menu

**Comment by Keksuccino** [comment]
So you mean it happens with all menus, not just the one you tested it with first?

**Comment by Fade-X** [comment]
yes

**Comment by Keksuccino** [comment]
I wasn't able to reproduce this, sorry.. :/
