### ISSUE TITLE
Button Sounds Not Playing

### ISSUE THREAD

**Issue by MaybeNovice** [Keksuccino/FancyMenu#820]
**Describe the bug**
Attempting to replace preexisting button sounds with a custom one. When changing to the new file, no sound plays. Other buttons with default Minecraft sound still play.

**To Reproduce**
Create a sound using Audacity and ensure using 48kh and 16-bit sample and bit rates respectively
Export as wav file
Edit any menu button
Click "Click Sound"
Change sound to new sound

**Expected behavior**
Expected to play new audio.

**Game Log**
(https://gist.github.com/MaybeNovice/faeb8cc3726ee780f9397ebd0d642c39)

**Basic Information:**
 - OS: Windows 11
 - FancyMenu Version: 3.2
 - Forge/Fabric Version: 37.2.3
 - Minecraft Version: 1.20.1
 - Active Mods: Too many to type but I can if necessary

**Comment by Keksuccino** [comment]
https://docs.fancymenu.net/en/fix-audio

**Comment by MaybeNovice** [comment]
I tried the listed fixes. I didn't have any success with them.
