### ISSUE TITLE
Positions of customized Vanilla buttons reset their position to default when opening the layout in the editor (only in some screens)

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#824]
- Happens in the Options screen (maybe only while in a world)
- I remember seeing this in the Credits screen, but not 100% sure rn
- https://discord.com/channels/746096190592122911/912100384410062848/1238117861395005540

**Comment by KaaayKaay** [comment]
This sounds similar to the issue I was happening to me with the 'Open to LAN/Player Reporting' button.

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.2.3!
