### ISSUE TITLE
Crash when choosing Image

### ISSUE THREAD

**Issue by Valyrianer** [Keksuccino/FancyMenu#825]
**Describe the bug**
As soon as I want to assign a texture to a button, the game crashes. It doesn't matter whether the layout is new or old, whether in the main menu or in the loading screen (drippy loading screen...) The game crashes. Version is the 1.20.6 Modversion is probably no matter which one (newest, oldest and one tested in the middle).

**To Reproduce**
1. Start the Game with Fancymenu and melody.
2. Create a new layout or edit a existing one.
3. Rightclick a Vanilla or Custom Button.
4. Goto "Button Texture"
5. Hover above "Set"
6. Hover above "Normal Background"
7. Click on "Choose Resource"
-> It should crash right now.

**Expected behavior**
As soon as I have pressed the corresponding button, a window for selecting the texture should appear, just as it does when selecting a texture for an image.

**Game Log**

**Screenshots**
If screenshots would help to explain the issue, please include these.
[crash-2024-05-10_18.37.14-client.txt](https://github.com/Keksuccino/FancyMenu/files/15277692/crash-2024-05-10_18.37.14-client.txt)
[latest.log](https://github.com/Keksuccino/FancyMenu/files/15277701/latest.log)
![image](https://github.com/Keksuccino/FancyMenu/assets/169480141/2e3a0eb8-73b4-43d4-bbe2-0718c7199f46)

**Basic Informations (please complete the following information):**
 - OS: Windows 11 version 23H2
 - FancyMenu Version 3.2.2 MC1.20.6 or v3.1.6 MC 1.20.5-1.20.6 (Both the same error)
 - Forge/Fabric Version 0.15.11
 - Minecraft Version 1.20.6
 - Active Mods
► Architectury API
► Barista - Window Title Editor
► Cloth Config
► Detail Armor Bar
► Drippy Loading Screen
► Fabric API (0.98.0)
► Kotlin for Fabric
► Fancy Menu
► Indium
► Iris Shaders
► Konkrete
► Lithium
► Mica
► Melody
► Mod Menu
► More Chat History
► Mosue Tweaks
► Noxesium
► Nvidium
► Simple Rich Discord Presence
► Sodium
► YetAnotherConfigLib

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.2.3!
