### ISSUE TITLE
System Interactions Addon - System related text placeholders, actions and requirements

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#826]
**I have asked for this before** but the answer has been a "**NO!**" by everyone, but now that we have a warning screen on system interactions, there is really **no limit** on what we can do (not in the technical way).

# Placeholders

**Current user directory** _(Windows)_

**".minecraft" directory** _(if exists, I'm pretty sure that you need this to run minecraft on any launcher tho)_

**absolute path to the %appdata% directory** _(if windows)_

# Requirements

**Does user have multiple drives** _(explains itself)_

**Does drive exist** _(checks if user has a [letter]: drive, e.g does user has a P: drive?)_

**Is OS windows** _(Use other methods to check if the OS is windows rather than using text placeholder to check if the OS name contains windows since some windows enhancement applications (e.g AtlasOS) change the registry to say something else, therefore ruining it)_

# Actions

**Shut down PC** _(why would anyone need this?)_

**Comment by Keksuccino** [comment]
Please move this issue to: https://github.com/Keksuccino/FancyMenu-System-Interactions-Addon/issues 
Thank you very much!
