### ISSUE TITLE
Ability to open folders, .json and .txt files without system interactions addon

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#827]
On an older version of my pack I had a button that **opened the mods folder and a filtered modrinth page for 1.20.1 fabric mods** and a few buttons that opened .txt files for instructions and other things, but in newer versions of fancymenu this is impossible, I get why you would block it from running some files but .txt's, .json's and folders are completely harmless.

There will probably be more people wanting this functionality, not just me.

**Comment by Keksuccino** [comment]
The Open File action will not get moved back to the base mod, not even in a very limited version. Sorry.
