### ISSUE TITLE
Ability to have assets outside the "fancymenu/assets/" folder - LET ME COOK

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#828]
I have wanted this in the past but I can't remember what I needed/wanted this for.

I have an image that I would like to use as a display for the latest screenshot taken using placeholders and the /screenshots folder, but this is impossible without the System Interactions Addon _(I dread using it in my modpack because it scares users away and users will disable it anyway)_.

**Comment by Keksuccino** [comment]
No, please use the `assets` folder like everyone else. Having assets outside this folder makes things a lot more complicated for me and I don't want to deal with that anymore.
