### ISSUE TITLE
Activate a keybind with an action script + reminder that #715 exists

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#829]
An example of this in use would be having a button using this action script, you set the value of the action script to "key_key.togglePerspective", when you click this button it now toggles your perspective.

 + Suggestion for #715, allow the key listener to function outside of a menu via an option on a universal layout or something, basically just being able to use this in game for custom key binds. I would expect the ability to click a button, it listen for a keybind then set a keybind to the key pressed via the "change minecraft option value" function or "set variable value" function somehow, just like the vanilla options screen does but a lil' more *custom*.

This combined with the "Key listener" element from #715 would be insane.

**Comment by Keksuccino** [comment]
Please stop opening issues for reminding me about another OPEN ISSUE.
This is just issue spam, dude. You don't need to remind me of issues when they are still open. I can see that with my own eyes..

If you want the "Trigger Keybind with Action" feature, please open a new, clean issue without the useless reminder stuff, thank you very much.
