### ISSUE TITLE
context menus on default video too big

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#83]
![image](https://user-images.githubusercontent.com/3880072/92526384-0616fd80-f1eb-11ea-9bde-5dce1199aefc.png)

This is on 1.4.6.1_fancymenu_1.16.2

no other mods installed

**Comment by Keksuccino** [comment]
Your MC window is just too small, make it a little bigger or downsize it a bit more so MC downscales itself to the smallest scale :)

**Comment by kreezxil** [comment]
Yes i know that, but i didn't think you would surreptitiously close this
either based on that. I would have thought that detecting the smaller
layout your mod would choose to use a smaller font so that the context menu
will fit.

**Comment by Keksuccino** [comment]
That would be too much work for something the user can fix by just resizing the window :/ Sorry.. :/
