### ISSUE TITLE
Black screen during preloading

### ISSUE THREAD

**Issue by ABSKrum** [Keksuccino/FancyMenu#833]
**Describe the bug**
Black screen during loading from pre-loading recourses

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Preload something (in my case its an animation)
2. Restart minecraft

**Expected behavior**
Regular mojang or drippy loading screen

**Game Log**
https://mclo.gs/GgZS3Jq

**Screenshots**
It looks normal in screenshots

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - 3.2.2
 - 0.15.11
 - 1.20.1
 - Language Reload 
Sodium 
Mod Menu 
Debugify 
Memory Leak Fix 
ImmediatelyFast 
CIT Resewn 
BCLib 
Fabric Language Kotlin 
Puzzle 
Capes 
Borderless Mining 
OptiGUI 
AdvancementInfo 
Konkrete 
Melody 
Xaero's Minimap 
Indium 
EntityCulling-Fabric 
FastQuit 
FabricSkyBoxes 
FancyMenu 
YOSBR 
MoreChatHistory 
ModernFix 
Simple Voice Chat 
MixinTrace 
Dynamic FPS 
Continuity 
Zoomify 
Origins 
Enhanced Block Entities 
FerriteCore 
Fabrishot 
YetAnotherConfigLib 
e4mc 
FabricSkyBoxes Interop 
Lithium 
Reese's Sodium Options 
No Chat Reports 
Cloth Config v11 
Model Gap Fix 
RP Renames 
Better End 
LambDynamicLights 
Iris 
Sodium Extra 
Fabric API 
Pehkui 
Entity Model Features 
Entity Texture Features 
Animatica 
Main Menu Credits 
Controlify 
More Culling 
Better Mount HUD 
Drippy Loading Screen

**Comment by ABSKrum** [comment]
Odd, in the screenshot looks normal
Maybe its an issue with my monitor?

**Comment by Keksuccino** [comment]
This is 100% not a bug in FancyMenu. It works fine in all MC versions.
Probably a GPU driver issue or mod conflict.
