### ISSUE TITLE
Excessive consumption of RAM by Minecraft

### ISSUE THREAD

**Issue by Sergo467** [Keksuccino/FancyMenu#834]
**Describe the bug**
Excessive consumption of RAM by Minecraft when using fancy menu. I also want to mention that Minecraft has only 2 gigabytes of RAM allocated.

**To Reproduce**
Just launching minecraft.

**Expected behavior**
That minecraft won't consume so much RAM.

**Game Log**
There are no logs, this is not a critical error.

**Screenshots**
RAM consumption with fancy menu:
![image](https://github.com/Keksuccino/FancyMenu/assets/67155404/85ee07bb-791e-42c3-b90a-7ff892849ca0)
RAM consumption without fancy menu:
![image](https://github.com/Keksuccino/FancyMenu/assets/67155404/78371056-05eb-4074-9ec1-539e4ab6f33f)

**Basic Informations:**
 - OS:
Windows 10 Pro 22H2
 - FancyMenu Version:
 fancymenu_forge_3.2.2_MC_1.20.1
 - Forge/Fabric Version:
 Forge_47.2.23
 - Minecraft Version:
 1.20.1
 - List of mods in the entire build:
ae2wtlib-15.2.3-forge.jar
AmbientSounds_FORGE_v5.3.9_mc1.20.1.jar
appleskin-forge-mc1.20.1-2.5.1.jar
Applied-Mekanistics-1.4.2.jar
appliedenergistics2-forge-15.1.1.jar
architectury-9.2.14-forge.jar
arseng-1.1.5.jar
ars_nouveau-1.20.1-4.9.0-all.jar
AttributeFix-Forge-1.20.1-21.0.4.jar
badpackets-forge-0.4.3.jar
balm-forge-1.20.1-7.2.2.jar
BetterF3-7.0.2-Forge-1.20.1.jar
betterfoliage-5.0.2.jar
catalogue-forge-1.20.1-1.8.0.jar
chat_heads-0.10.32-forge-1.20.jar
chunksfadein-v1.0.5-1.20.1.jar
cleanswing-1.20-1.5.jar
cloth-config-11.1.118-forge.jar
Connector-1.0.0-beta.43+1.20.1.jar
craftingtweaks-forge-1.20.1-18.2.3.jar
CreativeCore_FORGE_v2.11.27_mc1.20.1.jar
cristellib-1.1.5-forge.jar
CullLessLeaves-Reforged-1.20.1-1.0.5.jar
curios-forge-5.9.0+1.20.1.jar
drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar
dynamic-fps-3.4.3+minecraft-1.20.0-forge.jar
eating-animation-1.20+1.9.61.jar
ecologics-forge-1.20.1-2.2.0.jar
embeddium-0.3.17+mc1.20.1-all.jar
embeddiumplus-1.20.1-v1.2.8.jar
emi-1.1.6+1.20.1+forge.jar
emi_loot-0.6.5+1.20.1+forge.jar
endrem_forge-5.2.3-R-1.20.X.jar
entityculling-forge-1.6.2-mc1.20.1.jar
fabric-api-0.92.1+1.11.8+1.20.1.jar
fancymenu_forge_3.2.2_MC_1.20.1.jar
ferritecore-6.0.1-forge.jar
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
geckolib-forge-1.20.1-4.4.4.jar
geophilic-v2.2.0-mc1.20u1.20.2.jar
immersive_weathering-1.20.1-2.0.1-forge.jar
Jade-1.20.1-forge-11.8.0.jar
jei-1.20.1-forge-15.3.0.4.jar
Kiwi-1.20.1-Forge-11.8.1.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
LeavesBeGone-v8.0.0-1.20.1-Forge.jar
loadmyresources_forge_1.0.4_MC_1.19.3.jar
lootr-forge-1.20-0.7.33.83.jar
lucent-1.20.1-1.5.5.jar
MaxHealthFix-Forge-1.20.1-12.0.2.jar
megacells-forge-2.3.6-1.20.1.jar
Mekanism-1.20.1-10.4.6.20.jar
Mekanism-MoreSolarPanels-1.20.1-1.5.9.jar
MekanismAdditions-1.20.1-10.4.6.20.jar
MekanismGenerators-1.20.1-10.4.6.20.jar
MekanismTools-1.20.1-10.4.6.20.jar
MekanismWeapons-1.20.1-1.5.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
memoryleakfix-forge-1.17+-1.1.5.jar
modelfix-1.15.jar
modernfix-forge-5.17.0+mc1.20.1.jar
moonlight-1.20-2.11.17-forge.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
multimine-1.20.1.3.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
nyfsspiders-forge-1.20.1-2.1.1.jar
oculus-mc1.20.1-1.7.0.jar
Paxi-1.20-Forge-4.0.jar
PickUpNotifier-v8.0.0-1.20.1-Forge.jar
Placebo-1.20.1-8.6.1.jar
PlayerRevive_FORGE_v2.0.25_mc1.20.1.jar
PuzzlesLib-v8.1.19-1.20.1-Forge.jar
Quark-4.0-441.jar
radium-mc1.20.1-0.12.3+git.50c5c33.jar
repurposed_structures-7.1.15+1.20.1-forge.jar
smoothboot(reloaded)-mc1.20.1-0.0.4.jar
SnowRealMagic-1.20.1-forge-10.4.3.jar
snowundertrees-1.20.1-1.4.4.jar
sound-physics-remastered-forge-1.20.1-1.3.1.jar
specialised_cells-1.0.0.jar
spisok.txt
Terralith_1.20_v2.5.0.jar
ToastControl-1.20.1-8.0.3.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
TravelersTitles-1.20-Forge-4.0.2.jar
TreeChop-1.20.1-forge-0.19.0.jar
voicechat-forge-1.20.1-2.5.14.jar
YungsApi-1.20-Forge-4.0.4.jar
YungsExtras-1.20-Forge-4.0.3.jar
YungsMenuTweaks-1.20.1-Forge-1.0.2.jar
Zeta-1.0-16.jar

**Comment by Keksuccino** [comment]
You are probably loading pretty large sound files or pretty large animated textures (APNG, GIF, FMA), slideshows, cubic panoramas or FancyMenu's old animation format (deprecated now). FancyMenu will never consume 6-7GB of RAM without using way too large assets.

If you don't load large assets, try to start the game with only FM + dependencies installed. Could be a mod conflict then.
