### ISSUE TITLE
[Feature Request] Add dynamic and customisable camera tilt, rotation, angle and FOV to panoramas in the main menu.

### ISSUE THREAD

**Issue by Wanderer70** [Keksuccino/FancyMenu#835]
Apart from being a useful tweak, it would also allow to recreate the old Minecraft panorama rotation. Back then the view of the main menu panorama used to go up and down while moving to the right. That is a great example of what I want to achieve with this. You would be able to customise how big this "wave" would be and the camera would follow the trajectory of this wave while rotating to the right. Also there would be an option to make the "wavelength" and FOV change while the panorama is rotating, hence called dynamic.

![Screenshot (1022)](https://github.com/Keksuccino/FancyMenu/assets/97387920/58fdcc43-f939-4569-9778-8fefc1ac6586)

**Comment by Keksuccino** [comment]
Will probably not add that, sorry. You can already customize FOV, angle and speed, just not dynamically.
Sorry, but there's just too many feature requests to add all of them. Maybe someone adds a custom panorama background with these features as an addon for FancyMenu :)

**Comment by Wanderer70** [comment]
That's ok!
