### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by al-wei** [Keksuccino/FancyMenu#839]
**Describe the bug**
A clear and detailed description of what the bug is.
Close edit, display error; Open edit, display correct.
And this element cannot be deleted, it will still be displayed.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
[video](https://flowus.cn/share/ad3d5846-1f4a-4ceb-9bb1-8ddf657270ac?code=UD7B6E)

**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!
https://gist.github.com/al-wei/fa4e9e25682e6438d39392a208b7e4e2

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows 10-64]
 - FancyMenu Version [e.g. fancymenu_forge_2.14.9_MC_1.12-1.12.2]
 - Forge/Fabric Version [e.g. 1.12.2-forge-14.23.5.2860]
 - Minecraft Version [e.g. 1.12.2]
 - Active Mods [e.g. OptiFine_1.12.2_HD_U_G5, censoredasm5.20, vintagefix-0.4.2, redirectionor-1.3 for 1.12.2-1.8.8, RenderLib-1.12.2-1.3.4, UniversalTweaks-1.12.2-1.10.0]

**Comment by Keksuccino** [comment]
You are using FancyMenu v2, which is not supported anymore, sorry.
