### ISSUE TITLE
Button with link as action does not open link

### ISSUE THREAD

**Issue by hypherionmc** [Keksuccino/FancyMenu#84]
**Describe the bug**
When placing a button with a link as the action, the link is not opened when you click on the button. You can hear the click sound, but nothing else.

**To Reproduce**
1. Add a button to a menu with a link as the action
2. Click on the button and you should hear a click, but link doesn't open

**Expected behavior**
Open the link in my browser

**Crash Log**
N/A

**Screenshots**
Nothing atm

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] - Windows 10
 - FancyMenu Version [e.g. 0.2] - FancyMenu v1.4.5 MC 1.12-1.12.2
 - Forge Version [e.g. 31.2.24] - 1.12.2-14.23.5.2847 
 - Minecraft Version [e.g. 1.15.1] - 1.12.2
 - Active Mods Too many to list, but optifine was present in testing

**Comment by Keksuccino** [comment]
Hi! Please send me your latest.log file (located at .minecraft/logs/latest.log) after you’ve clicked the link button.

This bug should not happen, I think it has something to do with the link you’re trying to open or one of your other mods.

**Comment by hypherionmc** [comment]
I will send it tonight when I get home :) I didn't notice anything in the log when I checked, but may have overlooked it. The link is a discord invite and I know someone else (who actually told me about your mod) that uses it and it seems to work for him (or he hasn't tested it)

**Comment by Keksuccino** [comment]
Thank you! :)

**Comment by hypherionmc** [comment]
[debug.log](https://github.com/Keksuccino/FancyMenu/files/5258468/debug.log)
[latest.log](https://github.com/Keksuccino/FancyMenu/files/5258474/latest.log)

**Comment by hypherionmc** [comment]
Sorry for the wait

**Comment by Keksuccino** [comment]
Thank you for the log, will try to fix this in the next update! :)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.5! Thank you for your report!

**Comment by hypherionmc** [comment]
Thank you :) Will update my pack
