### ISSUE TITLE
how do I fix it?

### ISSUE THREAD

**Issue by zlykinss** [Keksuccino/FancyMenu#842]
![javaw_u5v4TG8Wch](https://github.com/Keksuccino/FancyMenu/assets/68995347/1403bf20-351d-401f-9dad-a79e7dd7f9f7)
![explorer_aftyMZdpsq](https://github.com/Keksuccino/FancyMenu/assets/68995347/d94672e0-2f4b-4acc-b932-33056a4c0022)

**Comment by Keksuccino** [comment]
#569
