### ISSUE TITLE
Unable to change dirt background of any screen (Fabric 1.20.1)

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#843]
Upon changing the background image or asset on any screen other than title screen, the background is still dirt and does not change.

I noticed this when updating my pack to the latest FancyMenu version and realising that backgrounds are broken.

What it looks like:

![Screenshot 2024-05-15 183428](https://github.com/Keksuccino/FancyMenu/assets/137423230/28290970-4250-462f-83d3-c89d89b38345)

Fabric 1.20.1
FancyMenu 3.2.3

**Comment by Keksuccino** [comment]
Unable to reproduce. Works fine for me. It's probably caused by the client you're using.

<img width="787" alt="Screenshot_1" src="https://github.com/user-attachments/assets/8b82afa7-107e-4e94-acfc-fa541d359e24">
