### ISSUE TITLE
Resource Pack background only partially changing

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#846]
Has existed for as long as time

This is what you are greeted with upon changing the dirt background of the resource pack screen (dark dirt backgrounds not changing).

![image](https://github.com/Keksuccino/FancyMenu/assets/137423230/bd295555-bf7f-4023-b209-7cbfc93cbc6a)

I would like to mention that this is **not a copy of #843**, this issue has happened whilst still being able to change other screens and has **existed for ages**.

Fabric 1.20.1
FancyMenu 3.2.0

**Comment by Keksuccino** [comment]
Will probably not fix that one, sorry.
This is not the same as #843
