### ISSUE TITLE
Update 3.2.3 Breaks Animations

### ISSUE THREAD

**Issue by KakashoLin** [Keksuccino/FancyMenu#849]
**Describe the bug**
Updating the mod fancy menu to the latest version of 3.23 causes your resources/menu not to load and loads a generic Minecraft menu instead of the right menu. 

I think it might be related to a change in how it parses animation/config reading, but the config is the same format as the one the AnimationMaker makes, and everything was working prior to updating the mod, and reversing the update fixes it. 

**To Reproduce**
Steps to reproduce the behavior (e.g.):
Be on update 3.2.2
Have a menu that features a working animation.
Update and then start game again.
Menu fails to load.
**Expected behavior**
Menu loads without issue. 

**Game Log**
[Latest.log](https://gist.github.com/KakashoLin/009f0fb47873f7dcb96df443715ddcd5)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 3.23
 - Forge/Fabric Version 4.2
 - Minecraft Version: 1.20.1
 - Active Mods: [List](https://www.curseforge.com/minecraft/modpacks/velox-resurrected/relations/dependencies)

**Comment by Keksuccino** [comment]
You are talking about the deprecated old animation system. Please switch to FMA files for animations: https://docs.fancymenu.net/en/fma
