### ISSUE TITLE
Rework Element Opacity Handling

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#851]
- [x] Make elements control their fade-ins (don't use fade-in thread in ScreenCustomizationLayer anymore)
- [x] Make "fade-in" and "delay appearance" separate settings
- [x] Add fade-out feature (useful when elements change their visibility without changing or resizing the screen, like when loading requirements are used)
- [x] Make fade-in trigger again when the element's visibility changed without resizing/changing the screen, like when loading requirements are used)
- [x] Make base opacity of elements editable (#795)

**Comment by KaaayKaay** [comment]
It could also be **SO COOL** to have a way to **replace the invisible background** or whatevs its called *(the transparent parts)* of your image or button background to be **blurred** just like UI's with **actual depth** similar to the **Apple Vison Pro** menu's and would revolutionize FancyMenu.

![image](https://github.com/Keksuccino/FancyMenu/assets/137423230/aeb45234-6ec6-4356-bf16-9234bb057bda)

**Comment by Keksuccino** [comment]
Blur is not the same as opacity. I would love to have a way to blur parts of the screen and maybe even apply a rounded corner mask to the blurred area, but I didn't manage blurring only parts of the screen yet. I mean I managed to do it, but it looks bad because MC's blur shader is not meant to be applied to only parts of the screen, as it seems. I am really bad with shaders, so I'm not sure if I get this to work on my own. But if somebody wants to help me out with that, feel free to make a PR with maybe a blur element to apply blur to parts of the screen or something? Would appreciate it! :)

**Comment by KaaayKaay** [comment]
> Blur is not the same as opacity. I would love to have a way to blur parts of the screen and maybe even apply a rounded corner mask to the blurred area, but I didn't manage blurring only parts of the screen yet. I mean I managed to do it, but it looks bad because MC's blur shader is not meant to be applied to only parts of the screen, as it seems. I am really bad with shaders, so I'm not sure if I get this to work on my own. But if somebody wants to help me out with that, feel free to make a PR with maybe a blur element to apply blur to parts of the screen or something? Would appreciate it! :)

Could you make your own? Or possibly get one from somewhere on GitHub or an open source shader. I'm not even lying when I say this, I would pay for blur in FancyMenu one way or another.

**Comment by Keksuccino** [comment]
I tried to pay people for that in the past and nobody wanted my $200 :D (or $150, not 100% sure anymore)

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
