### ISSUE TITLE
Incompatibility with "Trade Uses"

### ISSUE THREAD

**Issue by auuruum** [Keksuccino/FancyMenu#852]
**Describe the issue**
When click on villager trade in trader from Easy villagers crashes

**Game Log**
[(https://pastebin.com/fL0v2b6A)](https://pastebin.com/fL0v2b6A)

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Winodws
 - FancyMenu Version 3.1.5
 - Forge/Fabric Version 43.3.13
 - Minecraft Version 1.19.2
 - Active Mods Trade uses, Easy villagers, Fancymenu

https://modrinth.com/mod/trade-uses
https://modrinth.com/mod/easy-villagers

**Comment by Keksuccino** [comment]
Please update to the latest version of FancyMenu and be more precise about which mod is the conflicting one. You say "Trade Uses" in the title and "Easy Trading" in the message and link to both mods.

**Comment by auuruum** [comment]
Sorry i wrote trade uses because Not enough crashes write that trade uses are conflicts

**Comment by auuruum** [comment]
Without trade uses all working fine

**Comment by AoSankaku** [comment]
Still same here with 3.3.2-Forge47.3.0-1.20.1
log: https://mclo.gs/udEfz5n#L11655

**Comment by Keksuccino** [comment]
I added it to the [incompatibility list](https://docs.fancymenu.net/e/en/incompatibility-list).
