### ISSUE TITLE
When removing mods button doesn't remove new update for a mod icon

### ISSUE THREAD

**Issue by Grass69z** [Keksuccino/FancyMenu#854]
**Describe the bug**
When you remove the mods button from the start menu, it doesn't remove the little blue icon indicating a mod you're using has an update.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Have an outdated mod installed
2. Click on Customization
3. Click on 
4. Scroll down to layouts
5. Edit Layouts
6. Delete mods button
7. Save and exit editor
8. The blue icon will still be there

**Expected behavior**
The mods button will disappear as it should, but the blue icon will not

**Basic Information**
 - OS: [Windows 11]
 - FancyMenu Version [3.2.3-1.20.1-fabric]
 - Forge/Fabric Version [Fabric]
 - Minecraft Version [1.20.1]
 - Active Mods [FancyMenu, Fabric API, Melody, Konkrete, Mod Menu]

Screenshots
![image](https://github.com/Keksuccino/FancyMenu/assets/108395363/5ea7b713-c186-444a-a8ac-479ba05085d6)

**Comment by Keksuccino** [comment]
This icon is added by Mod Menu and you can disable it in its settings. This is not a bug.
