### ISSUE TITLE
Wait {amount} second/s action script

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#855]
# What is this?
This is simply an **action script** that adds a **delay inbetween the actions** in your button or ticker just like scratch's
![image](https://github.com/Keksuccino/FancyMenu/assets/137423230/21084606-6e93-459a-9194-50eadda5e482)
block, it would allow for **more customization** following **timings, delays and counting/countdowns**.

# How is this useful
This would be useful to **create animations** like the ones seen in **Katie Razzbunny's animation seen in this message** [`Kekscord > service-request > Taking Commisions for menu customization and creation!`](https://discord.com/channels/704163135787106365/1225865852453392485/1225867865874239518) without needing **multiple layouts, tickers and delays**, this could **increase performance** with animations, make it easier and **more accessible** to make.

**Comment by Keksuccino** [comment]
This is not possible, because tickers can run on the game thread. It would basically block the game thread and by doing that, freeze the game.

**Comment by KaaayKaay** [comment]
> This is not possible, because tickers can run on the game thread. It would basically block the game thread and by doing that, freeze the game.

I meant like a delay between actions not a whole pause yk

**Comment by Keksuccino** [comment]
This is the same.
