### ISSUE TITLE
Cannot move the element close to the edge

### ISSUE THREAD

**Issue by Kitieshka** [Keksuccino/FancyMenu#856]
**Describe the bug**
It's pretty simple, I didn't find any duplicate posts. You cannot move any element close to the edge of the window. This makes it very difficult when I have to do something to hide, there is still free space.

**To Reproduce**
Go to the Editor, create element, select anchor point on right center and try to move reght

**Expected behavior**
I want to be able to move the elements close to the edge of the screen

**Screenshots**
![image](https://github.com/Keksuccino/FancyMenu/assets/132190588/cc29dc4d-52a1-4ee3-ae8f-e92c8c1af551)

**Basic Informations**
 - OS: Win 11
 - FancyMenu Version: 3.2.3
 - Forge/Fabric Version 0.5.11 Fabric
 - Minecraft Version 1.20.6

**Comment by Keksuccino** [comment]
Disable "Stay On Screen" for the element. This is not a bug.
