### ISSUE TITLE
Elements never tounches the corner and forcing them causes you can't move it back

### ISSUE THREAD

**Issue by SrRapero720** [Keksuccino/FancyMenu#859]
**Describe the bug**
Moving elements (like progressbar) to corners will never let element being placed on the corner, 
always restricting it with 2p margin
![image](https://github.com/Keksuccino/FancyMenu/assets/29090346/7c04ff84-31a9-4b5a-a801-2ac5597ee3d1)

Now, what happend if i forced it to be in the corner... nothing, i can still move the mouse freely and the element never changes its positions below 2p, but there's causes another bug

If you after move your element to the corner with no sucess and continue moving the mouse to the corners (a little bit more) and then attempts to move the element USING THE ARROW KEYS of yout keyboard, the element will not move depending how deep you move the mouse into the corners - Extra: testing it again, you can reproduce same behavior with the mouse, in fact, you can still click on the element, move it more deeper into the corner and still will go more deeper (not visually).

https://github.com/Keksuccino/FancyMenu/assets/29090346/fd292cf1-97a8-43f5-802d-13d462cf5ee4

https://github.com/Keksuccino/FancyMenu/assets/29090346/87e2abd4-93cf-4eac-bd2b-152f70b81e31

i suspect elements positions are still counting its position on negative values but renderer limits position into 2

**Expected behavior**
Can have elements on corners

**Game Log**
https://gist.github.com/SrRapero720/f1f6a0ea102ae7bbf66de5dad93847dd

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 3.2.3
 - Forge/Fabric Version 47.2.20
 - Minecraft Version 1.20.1
 - Active Mods

**Comment by Keksuccino** [comment]
You can move it back, you just need to drag it a bit further.
To move elements off-screen, disable "Stay On Screen" for the element.
This is not a bug.
