### ISSUE TITLE
Add option to enable customizations for the Game Intro screen

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/FancyMenu#862]

**Comment by Keksuccino** [comment]
Not possible sadly.

**Comment by KaaayKaay** [comment]
> Not possible sadly.

How? And what do you mean by game intro, the loading screen?

**Comment by Keksuccino** [comment]
https://docs.fancymenu.net/en/game-intro

And there's a discussion in Discord for why this isn't possible.
