### ISSUE TITLE
When text is obstructed stop showing what is covered

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#865]
![image](https://github.com/Keksuccino/FancyMenu/assets/137423230/45586a0f-cd54-4b56-8b48-7767d6a60da0)

currently it just removes the text shadow

**Comment by Keksuccino** [comment]
I can't do anything about that probably. That's a visual bug caused by how Minecraft renders text. There's probably some way to fix that, but I haven't found it yet. They also like to change text rendering behaviour in like every update, so it's difficult to follow all changes.
