### ISSUE TITLE
Typo: Bigger than or equals instead of Smaller than or equals

### ISSUE THREAD

**Issue by Jab125** [Keksuccino/FancyMenu#866]
**Describe the bug**
A clear and detailed description of what the bug is.
Ditto
**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create a requirement for Is Number
2. Edit Requirement Value
3. Set mode
4. See Bigger Than or Equals twice

Additionally, it seems to reset to "Smaller than" when reopening the screen, like it can't find a value and is resetting to default.

**Expected behavior**
It should say Smaller Than or Equals
**Screenshots**
If screenshots would help to explain the issue, please include these.
![Screenshot 2024-06-06 at 10 36 28 am](https://github.com/Keksuccino/FancyMenu/assets/67534807/7788c898-8fe4-4120-bbad-fe9cb1894d23)
**Basic Informations (please complete the following information):**
 - OS: [e.g. macOS 14.2]
 - FancyMenu Version [e.g. 3.2.3]

 - Forge/Fabric Version [e.g. 0.15.11]
 - Minecraft Version [e.g. 1.20.6]
 - Active Mods [FancyMenu]

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
