### ISSUE TITLE
Incompatible with essential menu on 1.20.4+ fabric

### ISSUE THREAD

**Issue by sniffercraft34** [Keksuccino/FancyMenu#869]
**Describe the bug**
When I launch Minecraft with just the essential mod,  the menu from the mod starts fine. But when I load it with fancy menu and drippy loading screen, the essential menu disappears.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Launch Minecraft on 1.20.4 (may appear on other versions) fabric with drippy loading screen, fancy menu, and essential
2. Find the bug

**Expected behavior**
I expected the essential menu to appear as normal

**Screenshots**
With the essential mod (Not mine)
https://i.postimg.cc/h41XTsMf/download.jpg
With fancy menu, it removes it

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 3.2.3
 - Forge/Fabric Version 0.15.9
 - Minecraft Version 1.20.4
 - Active Mods Essential, Fabric API, Drippy Loading Screen, Fancy Menu

**Comment by Keksuccino** [comment]
I am 98% sure that's on Essential's side. (like always)
The way they add their stuff to the Title screen is very non-Vanilla and was always partially incompatible with FancyMenu.
If they would simply add it in a Vanilla-like way (with widgets they register to the screen's widget list), all problems would be gone.

**Comment by sniffercraft34** [comment]
Okay, thanks.
