### ISSUE TITLE
Game fails to launch when loaded with certain Instance Options inside ATLauncher.

### ISSUE THREAD

**Issue by priincipled** [Keksuccino/FancyMenu#870]
**Describe the bug**
When launching from ATLauncher with the following Instance Options: 
       Java Path: `/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home`
       Use Java Provided by Minecraft: No

Instance Options are used to get around a Java issue with Apple Silicon

Game fails to launch at all.

Bug resolves when FancyMenu and drippyloadingscreen are removed. 
**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Use the Instance settings listed above on ATLauncher
2. Play Instance

**Expected behavior**
Game loads normally

**Game Log**
https://gist.github.com/priincipled/c3db5c42d03c59b50fd6db57b4f8708e

**Screenshots**
If screenshots would help to explain the issue, please include these.

**Basic Informations (please complete the following information):**
 - OS: Mac OS Sonoma: 14.5
 - FancyMenu Version: 3.2.3
 - Forge/Fabric Version Fabric Version: Fabric 0.15.11 
 - Minecraft Version [e.g. 1.15.1]: 1.20.1
 - Active Mods: Better MC - v25 | Issue resolves with the removal of FancyMenu and also drippyloadingscreen

**Comment by Keksuccino** [comment]
This is most likely caused by ATLauncher, which likes to break my mods.
