### ISSUE TITLE
It's possible to anchor a parent element to one of its children if the parent has at least 2 children

### ISSUE THREAD

**Issue by SrRapero720** [Keksuccino/FancyMenu#872]
**Describe the bug**
You can do this:

https://github.com/Keksuccino/FancyMenu/assets/29090346/17f752fe-fa27-4eb0-bcae-f4eb960c0bfb

Label anchor is parented to the square, drag the square and moving it to the label causes auto-anchor tries to parent the square anchor to the label, it can and after was done it crashes due to a StackOverFlowError

![image](https://github.com/Keksuccino/FancyMenu/assets/29090346/fd3aeb4e-6ee0-444b-8481-3690d7538e82)

**Expected behavior**
Not be able to put a parent anchor to a child anchor

**Basic Informations (please complete the following information):**
 - OS: WIN 11
 - FancyMenu Version 3.2.3
 - Forge/Fabric Version 40.2.21
 - Minecraft Version 1.18.2
 - Active Mods: ---

**Comment by Keksuccino** [comment]
Related to #867

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
