### ISSUE TITLE
Add "open in editor" button to screens in the following format

### ISSUE THREAD

**Issue by KaaayKaay** [Keksuccino/FancyMenu#874]
# Idea

**Add the "Open in editor" button** to the following screen format **shown below** + allow **placeholders**

![Screenshot 2024-06-16 152853](https://github.com/Keksuccino/FancyMenu/assets/137423230/bf833670-b270-4d6f-a70d-8f5e9ca7e603)

# Use case

A **text input field linked to the variable "colour"** where the user can type in the HEX code of the colour theme they want for the modpack UI

That **same variable would be used in the "rectangle shape" element's colour property** as **show below**

![image](https://github.com/Keksuccino/FancyMenu/assets/137423230/1e378921-d79f-4142-970c-729041caf745)

# Extra info

Would work very well with the ability to change hue as shown in #873

**Comment by Keksuccino** [comment]
It's not as easy as "adding a button". Every element internally needs to support upating their values to update placeholders. I would need to constantly update colors to make placeholders work and I decided not to do that when coding v3.

**Comment by KaaayKaay** [comment]
> Every placeholder update eats performance. I optimized that process in v3, but it's still a heavy task.

Fair, I have noticed some performance issues with placeholders, tickers and variables so I can understand.

Maybe consider for advanced mode
