### ISSUE TITLE
FancyMenu Background not showing

### ISSUE THREAD

**Issue by Alexutul44** [Keksuccino/FancyMenu#877]
**Describe the bug**
So I want to create a minecraft modpack for my friends and I have 270+ mods and when I finish with the mods I started with an image for main menu with FacnyMenu and I put a background saved the Layout and when I exit the editors it still not showing my background but the changes I've done to the buttons (deleted and moved some of them) are showing like in editor.

**I don't think you can reproduce this but here it is** 
1. Current menu --> Customization: On --> Layouts --> New.
2. I deleted some buttons and move some like in this print screen : https://prnt.sc/piatpLpHaaPx
3. Right Click on gray background --> set Background.
4. Select Background Image --> Choose Image --> Choose file --> second.png (my desire image) : https://prnt.sc/RH_gbmarHFZs

**Screenshots**
Here I am in editor layout : https://prnt.sc/e7IKpI8RvLgr
Here I am in normal minecraft menu : https://prnt.sc/GB0XJoODEyg8

**Mod list kinda:**
If you really want to see what mods I put in this modpack I will paste a txt file taken from a crash-log with all the mods.
[TEST.txt](https://github.com/user-attachments/files/15904574/TEST.txt)

**Specs:**
 - OS: Windows 10
 - FancyMenu Version 2.14.9
 - Forge 36.2.34
 - Minecraft Version 1.16.5
 - Active Mods : 274 mods

**Comment by Keksuccino** [comment]
You have a mod installed that overrides the Vanilla menu background. You need to find this mod and disable its menu customizations or remove it. It's a mod conflict.
