### ISSUE TITLE
FMA texture doesn't get restarted on button hover after its very last frame got played (maybe some `isFinished` stuff I implemented??)

### ISSUE THREAD

**Issue by Rafii2198** [Keksuccino/FancyMenu#878]
**Describe the bug**
I have an FMA animation image set as a hover texture for a button. The animation doesn't loop, it just plays once. I have also enabled `Restart Animation Textures On Hover` so it starts playing from the beginning when hovering over, not in middle or something from previous hover.
The issue is that sometimes it gets stuck, and the animation won't play until the fancy menu is reloaded. It always happens when the animation finishes but also happens when it is in the middle, I found that the longer it plays, the higher chance of it breaking.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create FMA animation, set it to no loops
2. Create a new layout with a button
3. Set the hover texture to the FMA animation
4. Enable `Restart Animation Textures On Hover` option
5. Now save and when you hover over to see the whole animation
6. Then, next time you hover over, there will be no animation at all.

**Expected behavior**
It should start animating from the beginning

**Game Log**
https://mclo.gs/HoypUqE

**Video**

https://github.com/Keksuccino/FancyMenu/assets/26695327/ab8198f1-581c-4cbb-87f8-6463bf41e6ee

**Basic Information:**
 - OS: Windows 11
 - FancyMenu Version: 3.2.5
 - Fabric Version: 0.15.11
 - Minecraft Version: 1.21
 - Active Mods: 
     - Drippy Loading Screen 3.0.7
     - Fabric API 0.100.2+1.21
     - Konkrete 1.9.9
     - Melody 1.0.10
     - Mod Menu 11.0.0
     - Placeholder API 2.4.0-pre.2+1.21
     - Concentration 1.1.3 (It makes the fullscreen borderless, only used it for recording the video and thus appears in the logs, but the issue is not related to this mod)

**Fancy Menu config folder**
https://filetransfer.io/data-package/FlveAaFY#link
This is the complete config folder, like all of it, including the assets including the FMA file, configuration, customization, literally everything.

**Comment by Rafii2198** [comment]
I made some more test, and it seems that when it is in that stuck state, hovering over button will only show the first frame of the animation, and it gets stuck when it finishes the all loops, if loops are set to 2 it will only get stuck when it finishes playing for the second time, meaning it won't be a problem when it loops infinitely as it will never end

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
