### ISSUE TITLE
[MC 1.12.2] FM 1.5.1 When loading game, original menus load first.

### ISSUE THREAD

**Issue by desagas** [Keksuccino/FancyMenu#88]
Just updated from 1.4.6 to 1.5.1, in MC 1.12.2, and all my menus reverted to the original menus, but a after clicking through a couple of menus, they updated and changed to the updated menus. This happens every time the game loads, without exception.

I edited the singleplayer menu, and when first clicking into it, the menu is the original menu, but once I click on any button in the screen, via forwards or backwards, and then go back into the menu, the new menus show.

EDIT: Actually, when every single menu is loaded, regardless of what menu it is, the first time it is loaded, it shows the original menu, always, without exception, and then when reloading it or going back into it, it changes to the updated menu.

**Comment by Keksuccino** [comment]
Hi! What MC version do you use?
Do you have any other mods installed?

**Comment by desagas** [comment]
Actually, when every single menu is loaded, regardless of what menu it is, the first time it is loaded, it shows the original menu, always, without exception, and then when reloading it or going back into it, it changes to the updated menu.

**Comment by desagas** [comment]
Sorry, I am using 1.12.2

**Comment by desagas** [comment]
This only happens after the update, before it this did not happen.

**Comment by Keksuccino** [comment]
It works fine for me, I think one of your other mods is causing this. Could you send me a list with your installed mods please?

**Comment by desagas** [comment]
1.12.2
AE-Net-Vis-Tool-1.12.2-1.0.3.0-universal.jar
appliedenergistics2-rv6-stable-7.jar
AutoRegLib-1.3-32.jar
base-1.12.2-3.13.0.jar
Baubles-1.12-1.5.2.jar
Biome_Bundle-1.12.2-v6.1.jar
BiomeTweaker-1.12.2-3.2.368.jar
BiomeTweakerCore-1.12.2-1.0.39.jar
BNBGamingLib-1.12.2-2.17.6.jar
Bookshelf-1.12.2-2.3.590.jar
BrandonsCore-1.12.2-2.4.19.214-universal.jar
CEU-1.12.2-1.0.4.3.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
CompatSkills-1.12.2-1.17.0.jar
ContentTweaker-1.12.2-4.9.1.jar
CookingForBlockheads_1.12.2-6.5.0.jar
CraftTweaker2-1.12-4.1.20.592.jar
DimensionalControl-1.12.2-2.13.0.jar
DimensionStages-1.12.2-2.0.23.jar
fancymenu_1.5.1_MC_1.12-1.12.2.jar
FastWorkbench-1.12.2-1.7.3.jar
forestry_1.12.2-5.8.2.422.jar
FTBBackups-1.1.0.1.jar
FTBLib-5.4.7.2.jar
FTBQuests-1.9.0.12.jar
GameStages-1.12.2-2.0.123.jar
gregtech-1.12.2-1.10.1.557.jar
incontrol-1.12-3.9.17.jar
InventoryTweaks-1.63.jar
ItemFilters-1.0.4.2.jar
ItemStages-1.12.2-2.0.49.jar
jei_1.12.2-4.16.1.302.jar
jeiintegration_1.12.2-1.6.0.jar
konkrete_1.0.2_MC_1.12-1.12.2.jar
lazy-ae2-1.12.2-1.1.21.jar
levelup2-1.5.7.jar
libnine-1.12.2-1.1.9.jar
LootTweaker-0.2.0+MC1.12.2.jar
memory_repo
MobStages-1.12.2-2.0.8.jar
modnametooltip_1.12.2-1.10.1.jar
modtweaker-4.0.18.jar
moreoverlays-1.15.1-mc1.12.2.jar
MouseTweaks-2.10-mc1.12.2.jar
MTLib-3.0.6.jar
multiblocktweaker-1.12.2-stable-1.3.0.jar
NoWorldgen5You-1.12.2-1.0.6.jar
NuclearCraft-2o.4.5-1.12.2.jar
OpenTerrainGenerator
OpenTerrainGenerator-1.12.2 - v8.3.jar
OreStages-1.12.2-2.0.37.jar
PackagedAuto-1.12.2-1.0.3.14.jar
Placebo-1.12.2-1.6.0.jar
reauth-3.6.0.jar
RecipeStages-1.1.3.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
Reskillable-1.12.2-1.13.0.jar
ResourceLoader-MC1.12.1-1.5.3.jar
Scavenge V1.12-1.8.3.2.jar
Scavenge-Baubles V1.12-1.0.jar
Scavenge-GameStage V1.12-1.2.jar
Scavenge-ReSkillable V1.12-1.0.jar
Shadows_of_Greg-1.12.2-2.14.0.jar
theoneprobe-1.12-1.4.28.jar
Time Stages-1.3.jar
Toast Control-1.12.2-1.8.1.jar
topaddons-1.12.2-1.13.0.jar
volumetricflask-0.18.jar

**Comment by desagas** [comment]
I use the default config options that were created when i installed 1.4.6. I will try removing them and letting it load again.

**Comment by desagas** [comment]
I would focus on OTG and BiomeBundle, as they are the mods that add menu options

**Comment by desagas** [comment]
Just did a quick test, and it looks like the menus not altered or created by other mods load just fine, all edits show, first time, but all that were created or altered with mods load the original first, until clicked out of and back into, or reloaded.

**Comment by Keksuccino** [comment]
Thank you for the testing! Will try to figure out what’s causing this!

**Comment by Keksuccino** [comment]
Hi! I checked the customization system with mods installed that add it's own buttons to the main menu, but and I wasn't able to reproduce the bug :/ There was another bug I found (thanks to you :D), related to buttons added by mods, but this isn't blocking the customization system from injecting the custom menu.

Do you have updated other mods at the same time you updated FancyMenu?

**Comment by desagas** [comment]
All mods were up to date at the time I reported this issue. The only thing that changed was updating your mod. Tye custom menus from your mod worked as intended before I updated your mod, and afterwards, it started not working correctly. I will try it again today, and see what happens  I have video of it happening as well. I’ll try to post it, or at least post a screen shot of it.

**Comment by Keksuccino** [comment]
Yes, a video showing the issue would be great!

Oh and could you send me your latest.log file (located at '.minecraft/logs/latest.log') after the issue just happened, please? Maybe navigate through some menus too and then send the file to me? This could be very helpful too!

**Comment by desagas** [comment]
[Here is the video.](https://youtu.be/2pMB06kuxKQ) What happens in the video happens every single time without exception.

**Comment by Keksuccino** [comment]
Thank you for the video! Have send you a friend request in discord :p

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.5.3! Thank you for your report!
