### ISSUE TITLE
Add option to disable buttons (inactive)

### ISSUE THREAD

**Issue by InTheProcess** [Keksuccino/FancyMenu#883]
**Describe your idea**
My GUI looks weak because the buttons just disappear.  It looks like I did a terrible job on the GUI.  I would like to be able to disable the buttons instead along with a custom tooltip for this state.

**Comment by DadudeGaming** [comment]
would love to see this

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
