### ISSUE TITLE
Mark mod as client only in fabric.mod.json

### ISSUE THREAD

**Issue by JulianVennen** [Keksuccino/FancyMenu#884]
As marked on modrinth this mod is client only and does not support dedicated servers.
Fabric has a feature for one-sided mods like this that completely prevents loading them on the incorrect side.

To do this, just set the environment option in the fabric.mod.json to "client" instead of "*".
That also prevents dependency issues on servers (e.g. if fancy menu is installed, but melody isn't)

**Comment by Keksuccino** [comment]
THIS MOD IS NOT CLIENT-ONLY AND IT'S A BUG THAT I CAN'T SET IT TO SOMETHING ELSE ON MODRINTH.
It's faszinating how many times I have to tell people that. I mean it's in the frickin description that it's not client-only. You literally just need to read the description.
