### ISSUE TITLE
Unable to open CreateWorldScreen in MC 1.21 [Confirmed]

### ISSUE THREAD

**Issue by TheSexyYeti** [Keksuccino/FancyMenu#888]
Trying to make a small mod pack for fabric, minecraft 1.21. And I only really have fancy menu and Mr. Crayfish's Menulogue installed to start out. And I was getting frustrated trying to alter the existing elements for the default screen. So I just decided to delete them all and remake them. And I was able to use the "Copy identifier for current screen" to copy the location for each button. But for some reason it won't even let me bring down the dropdown menu to use that function when I go to the "Singleplayer" screen. I tried using the "Debug overlay" to see what the location is for the singleplayer screen is. But when I input that into the actions for the button. It doesn't accept it. all I get is this error screen as shown in the screenshot.
![Untitled](https://github.com/Keksuccino/FancyMenu/assets/50222286/5fc92cd5-781f-4edb-ad00-376d89804fbd)

**Comment by Keksuccino** [comment]
You should use the Vanilla Singleplayer button and customize it. You set an anchor point to it (right-click) and then you can customize it like every normal element.

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
