### ISSUE TITLE
can't dissable realms_notification

### ISSUE THREAD

**Issue by vitaluska123** [Keksuccino/FancyMenu#889]
![image](https://github.com/Keksuccino/FancyMenu/assets/87501597/14f15b93-a96b-4165-8210-5c01e050f766)

i can't dissable this 
![image](https://github.com/Keksuccino/FancyMenu/assets/87501597/992b2918-9b3f-4ca0-81e8-76fe2e1477f0)

But in editor nothing...
![image](https://github.com/Keksuccino/FancyMenu/assets/87501597/b54a1336-9b58-45f8-9661-4e2e1d2dfa0b)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - fancymenu_fabric_3.2.3_MC_1.20.1
 - Fabric Version 0.15.11
 - Minecraft Version 1.20.1

**Comment by Keksuccino** [comment]
That's the update notification od ModMenu. You can disable it in the ModMenu settings.
