### ISSUE TITLE
Patreon Link on README

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#89]
**Describe your idea**
Need your patreon link on the README.md

- [x] **Does it frustrates you to not already have this feature in the mod?** __this line frustrates me__ _because_ **frustrates** should be spelled ***frustrate***. :)
Is your feature something you can't live without or is it just something that would be cool to see in FancyMenu?
- [x] Yes, i can live without it, but it would probably get your more donators
- [ ] No

**Comment by Keksuccino** [comment]
Done :p
