### ISSUE TITLE
Progressbars doesn't support custom color transparency

### ISSUE THREAD

**Issue by SrRapero720** [Keksuccino/FancyMenu#890]
**Describe the bug**
Custom progress bars doesn't support transparency on custom coloring
I remember in some old days, beta has support for it. not sure on what point got removed

**To Reproduce**
- put a color with transparency e.j: ``#000000cc``

**Expected behavior**
Support transparency

**Game Log**
https://gist.github.com/SrRapero720/7dc7333a9457885228770b5ca4daa767

**Screenshots**
both uses  ``#000000cc`` as color
![image](https://github.com/Keksuccino/FancyMenu/assets/29090346/7c7589f5-f1ea-4104-a479-6b0fdee1099c)

**Basic Informations (please complete the following information):**
 - OS: Win 11
 - FancyMenu Version 3.2.3
 - Forge/Fabric Version 47.2.20
 - Minecraft Version 1.20.1
 - Active Mods [full modpack]

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
