### ISSUE TITLE
Once-per-session ticker can't set variable to result of Web Text placeholder

### ISSUE THREAD

**Issue by palette-dev** [Keksuccino/FancyMenu#891]
**Describe the bug**
When a ticker on the title screen is set to tick once per session, it can't set a variable to the result of a Web Text placeholder when ticking
If you set the ticker to tick once per load, it works if you enter another menu and exit back out to the title screen, but it still doesn't work on first load
All other parts of the tickers action script still can execute normally

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create a ticker on the title screen
2. Set the ticker to tick once per session
3. Add the action to set a variable value to the result of a Web Text placeholder to the ticker
4. Save the layout
5. Quit and re-launch Minecraft
6. The variable doesn't contain anything after loading the title screen (if the variable isn't empty before quitting and isn't set to clear on reload, it still doesn't contain anything afterwards)

**Expected behavior**
The variable is successfully set to the result of the Web Text placeholder

**Game Log**
[latest.log](https://mclo.gs/Na2pfw5)

**Basic Informations (please complete the following information):**
 - OS: Windows 11 Pro
 - FancyMenu Version: 3.2.3
 - Fabric Version: 0.15.11
 - Minecraft Version: 1.20.4
 - Active Mods:
   - FancyMenu
   - Konkrete
   - Melody
   - Fabric API

**Comment by Keksuccino** [comment]
that's not really a bug, but a limitation of the asynchronous nature of the Web Text placeholder, so I can't really fix that, sorry.
