### ISSUE TITLE
After installing both Fancy Meny and Drippy Loading Screen game broke completely

### ISSUE THREAD

**Issue by KrokusAstra** [Keksuccino/FancyMenu#894]
**Describe the bug**
After installing both mods (Fancy Meny and Drippy Loading Screen), Minecraft became like this (screenshot). I got used to this, trying to make pack for myself to play, often see some errors or problems, and i tried most logical desicion - roll back and just delete both mods.
But problem did not go away even after i deleted both mods.
More than this, i cannot access main menu or game itself at all, even after mods were deleted. Minecraft somehow just trying to load me straight up into my save file (i guess), ignoring main menu, but couldn't proceed, loading like eternity, and then dies, as if i never launch it.

I guess the only way to fix it - re-download entire modpack from zero, saving only mods/configs/resource/shaderpacks folders and save files (cuz some nasty devs like to imprint configs into save file, not just basic config folder).

I guess initially there was some incompability problem, but i don't understand why problem continue/became worse after mods were removed. It shouldn't work like than... unless mod changed original minecraft files.

**Expected behavior**
Rolling back after mods were deleted, as if they never were installed.

**Game Log**
[latest.log](https://github.com/user-attachments/files/16091386/latest.log)

**Screenshots**
![изображение_2024-07-04_013237762](https://github.com/Keksuccino/FancyMenu/assets/172990355/58adda4d-e936-47e7-8e14-f6ee517bae62)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 3.2.3
 - Drippy Loading Screen Version 3.0.1
 - Forge 47.2.17
 - Minecraft Version 1.20.1
 - List of mod could be seen inside log file

**Comment by Keksuccino** [comment]
This is not caused by Drippy or FancyMenu. It's probably a mod conflict, launcher issue or simply a broken graphics driver.
