### ISSUE TITLE
screens are not opening via action

### ISSUE THREAD

**Issue by ALEILGOD** [Keksuccino/FancyMenu#895]
When i try to open the fletching screen GUI from apotheosis via action it tells me that the screen is incompatible with FancyMenu

**Game Log**
[https://gist.github.com/ALEILGOD/7eaaa9c2b8420684967cf4292b8b7786](url)
i think this is the part that matters, the log is more than a 1000 lines

**Screenshots**
![Screenshot_2](https://github.com/Keksuccino/FancyMenu/assets/116183327/778ea1a9-414e-444b-9157-5105f2a9d7c8)

 - OS: Windows 11
 - FancyMenu Version: v3.2.3
 - Forge version: 47.3.0
 - Minecraft Version: 1.20.1
 - Active Mods (a lot): EMI and addons, inventorio, inventory profiles next and fabulous fletching that i think could cause the issue

**Comment by ALEILGOD** [comment]
the log is not working here is the new link
[https://gist.github.com/ALEILGOD/7eaaa9c2b8420684967cf4292b8b7786](url)

**Comment by ALEILGOD** [comment]
the link itself is not working

**Comment by ALEILGOD** [comment]
copy it into the search bar

**Comment by ALEILGOD** [comment]
https://gist.github.com/ALEILGOD/7eaaa9c2b8420684967cf4292b8b7786

**Comment by ALEILGOD** [comment]
all the screens are broken the buttons wont open any of the screens

**Comment by Keksuccino** [comment]
Duplicate of #942
