### ISSUE TITLE
i try to load my menu in other pc

### ISSUE THREAD

**Issue by vitaluska123** [Keksuccino/FancyMenu#898]
![image](https://github.com/Keksuccino/FancyMenu/assets/87501597/b10dce47-eee3-4427-ad12-5c33a9fc738b)

**To Reproduce**
save as mrpack without config folder
save fancymenu config as zip
download minecraft by minecraft_launcher_lib (python)
add fancymenu config in minecraft folder

**Expected behavior**
![image](https://github.com/Keksuccino/FancyMenu/assets/87501597/d9822cfa-86ae-4140-8bb9-b88ee174e384)

**Basic Informations (please complete the following information):**
OS: Windows 11
fancymenu_fabric_3.2.3_MC_1.20.1
Fabric Version 0.15.11
Minecraft Version 1.20.1

**Comment by Keksuccino** [comment]
Please join the Discord for support, thank you very much!
#569
