### ISSUE TITLE
gui scale option

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu#90]
**Describe your idea**
I tend to build my menus in GUI SCALE 2. As you know that is not the default gui scale as such on first launch if the player has a wxga (extreme widescreen) monitor the default scale ruins all of my layouts.

An option to force the gui scale initially to the one i designed my menus in would be most excellent.

**Does it frustrate you to not already have this feature in the mod?**
- [x] yes 
- [ ] no

**Is your feature something you can't live without?** 
- [ ] yes 
- [x] no

**is it just something that would be cool to see in FancyMenu?**
- [x] yes 
- [ ] no

**Comment by Keksuccino** [comment]
You can use the `setscale` customization action to do this :D

Or do you mean to force ALL menus to the same scale? This would cause issues with the `setscale` action, but I will add an option to set the GUI scale on start, like you mentioned in #61 :)

**Comment by Keksuccino** [comment]
Will close this for now, because I think I’ve added what you wanted me to add? :‘D FancyMenu v1.1.0 adds a config option to set the default GUI scale on first launch.

**Comment by Tminec** [comment]
We definetily need force gui scale cus my modpack elements get corrupted when u change gui scale (I think I am a bit late)

**Comment by Keksuccino** [comment]
> We definetily need force gui scale cus my modpack elements get corrupted when u change gui scale (I think I am a bit late)

Dude you already have forced GUI scales. Right-click the editor background -> GUI Scale.

Also check if you are using the correct anchors for your elements. There is a docs page called "Positioning Elements" about this.
