### ISSUE TITLE
Just read (I have no idea for title)

### ISSUE THREAD

**Issue by HalfStony** [Keksuccino/FancyMenu#904]
**Describe your idea**
I recently downloaded this mod, and found out that it's incompatible. And no, i will not write something like a 7 yr old kid would write. I want the mod to just... show the Essential buttons, and i dont need to change their position. I just want them to be useable and visible. Nothing more... because like... i did not want to change ANYTHING on the main menu and pause. Just create my own gui's etc.

**Comment by Keksuccino** [comment]
It's not my fault Essential isn't working with FancyMenu. Please report this to the Essential devs. They need to fix that. Thank you.
