### ISSUE TITLE
List background renders in front of Panorama background in scrollable screens

### ISSUE THREAD

**Issue by JustStorm** [Keksuccino/FancyMenu#908]
**To Reproduce**
1. Open multiplayer game screen (aka the tab with server list)
2. Open some custom layout for this screen in editor
3. set background (Layout > Properties > Set Background) to any **cubic panorama**
(In the editor it shows alright, but it's actually not)
4. Save the layout and exit editor
5. See the issue: most of the panorama is blocked by the dirt screen (panorama can be partly seen with disabled footer and header)

**Expected behavior**
A cubic to be set as a background for servers tab
! NOTE Bug occurs with FM v3.2.3 (forge 1.20.1), but doesn't occur with FM 3.2.2 (forge 1.20.1)

**Game Log**
https://gist.github.com/JustStorm/6715b537a32301d9ffc3747b4b2c50a8

**Screenshots**
![image](https://github.com/user-attachments/assets/aecd0606-36ff-4803-9c49-da0a69f5b459)

**Basic Informations**
 - OS: Windows 10
  - FancyMenu Version 3.2.3
 - Forge/Fabric Version 47.2.20
 - Minecraft Version 1.20.1
 - Active Mods FancyMeny, OpenLoader

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
