### ISSUE TITLE
[1.12.2] crash on world creation

### ISSUE THREAD

**Issue by Landsurfer2000** [Keksuccino/FancyMenu#91]
**Describe the bug**
game crashes when trying to create a new world, haven't tested loading an already made world however

**To Reproduce**
1. go to world creation screen
2. create world
3. world hits the 0% loading screen and crashes, can be escaped with esc but game closes after

**Expected behavior**
world is supposed to load

**Crash Log**
[crash report](https://pastebin.com/mVVN4zD1)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 1.5.3
 - Forge Version 14.23.5.2854 (latest)
 - Minecraft Version 1.12.2
 - Active Mods (in crash report)

thank you so much for everything you do!

**Comment by desagas** [comment]
https://pastebin.com/uKmNLY9B, here is my crash report. It is not so much that it crashes, that is the problem, it is that the mod does not allow minecraft to switch screens, which results in a error.

**Comment by Keksuccino** [comment]
It doesn’t block mods from switching screens.

Hotfix will be out today. Thank you for reporting this!

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.5.3.1!
Thank you very much again for reporting this to me so quickly.
It was NOT mod-related and also happened when no other mods were active.
