### ISSUE TITLE
Command to pause game

### ISSUE THREAD

**Issue by Jetpack-Cat** [Keksuccino/FancyMenu#910]
Add a command to pause and a command to unpause Minecraft.

Idea: when entering a world for the first time, pause the game and show a custom fancy menu ui to begin the mod pack story arc, or immediately play a video.

Commands to pause and un pause the game would allow me to add in story screens without worrying the player might die if it's at night. Obviously doesn't work on a server.

I have the player falling from the sky at the beginning of a new world. This would allow me to begin the story before the player falls and hit the ground.

I could put the player into spectate mode, but then all the sounds and music still play and it limits what's possible.

There's no mod I can find that allows me to pause and un pause the game with a command.

Obviously won't work on servers.

**Comment by Keksuccino** [comment]
Custom GUIs should pause the game by default when they are open.
That only works in SP.

**Comment by Keksuccino** [comment]
<img width="845" alt="Screenshot_1" src="https://github.com/user-attachments/assets/5783a2b7-cd16-45c3-aea5-3ac1de511ad6">
