### ISSUE TITLE
Layouts not showing up in list (probably not a bug, but user error)

### ISSUE THREAD

**Issue by PabloEmDesespero** [Keksuccino/FancyMenu#912]
**Describe the bug**
The bug make the layer don't work as expected

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Active current screen customization
2. Pass the mouse over layout
3. Click in new
4. Now making a layer that can't be seen

**Expected behavior**
A clear and detailed description of what you expected to happen.

I want to make a good menu for my personal modpack, but i can't see any layout that i made

**Game Log**
[latest.log](https://github.com/user-attachments/files/16391747/latest.log)

**Screenshots**
![image](https://github.com/user-attachments/assets/e9843991-bf5c-4cb1-8630-abbaf3cf8983)

Mods Folder:
![Mods](https://github.com/user-attachments/assets/8b445457-f2d8-4b03-99d1-6487ee97181c)

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Pro
 - FancyMenu Version: 3.2.3
 - Forge/Fabric Version: Forge 40.2.21
 - Minecraft Version: 1.18.2
 - Active Mods: 265 Mods

**Comment by Keksuccino** [comment]
Well, you can't see your layouts when not having the layout menu open.

<img width="468" alt="Screenshot_1" src="https://github.com/user-attachments/assets/a14caf94-730f-4076-af7a-9e53184ed319">

**Comment by PabloEmDesespero** [comment]
i fixed, i changed the ice and fire menu in config files to don't show them
