### ISSUE TITLE
Mod Elements Get Hidden Upon Customizing Screen.

### ISSUE THREAD

**Issue by eithli** [Keksuccino/FancyMenu#915]
Just something I’ve discovered while trying to get this to work. Fabric - 1.20.1

Bedrockify Ex:

![IMG_5488](https://github.com/user-attachments/assets/4889c0a0-34d4-4afe-ac65-d26360f314a6)
![image](https://github.com/user-attachments/assets/9788a007-3a5f-4e1d-87ac-da41c6d7d5d7)

Another Ex: 
![IMG_5495](https://github.com/user-attachments/assets/f7f08705-213a-487d-b6f3-2a86a22a2084)

**Comment by Keksuccino** [comment]
This is a mod conflict with Bedrockify and not a bug in FancyMenu.
I will not add support for Bedrockify, sorry.
