### ISSUE TITLE
Placeholder to get file/image name by their ID

### ISSUE THREAD

**Issue by scatman2934** [Keksuccino/FancyMenu#917]
A way to get file/image name by their ID would be really useful. The placeholder would return the name of the file/image.

Placeholder could look like this:
{"placeholder":"get_file_name","values":{"path_from_asset":"textures/","file":"4"}}

so lets say in the "textures" folder, these are the files:
pokemon.txt
pikachu.png
stats.txt
attacks.txt
types.txt

the placeholder above would return "attacks.txt"

**Comment by Keksuccino** [comment]
Files don't really have indexes or IDs, so that's not possible. They don't always have the same order.
