### ISSUE TITLE
Custom main menu music won't play

### ISSUE THREAD

**Issue by Bratorsortnal** [Keksuccino/FancyMenu#919]
**Describe the bug**
A clear and detailed description of what the bug is.
I followed the wiki, added the audio element, added a track there, disabled vanilla music, but the custom music still won't play (The volume is alright)

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Try to add main menu music via the wiki

**Expected behavior**
A clear and detailed description of what you expected to happen.
I expected the custom music to play

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!
[latest.log](https://github.com/user-attachments/files/16475682/latest.log)

**Screenshots**
If screenshots would help to explain the issue, please include these.
Screenshots won't help here

**Basic Informations (please complete the following information):**
 - OS: [e.g. Windows] Latest build of Windows 11
 - FancyMenu Version [e.g. 0.2] v3.2.3 for 1.20.4
 - Forge/Fabric Version [e.g. 31.2.24] 0.15.11
 - Minecraft Version [e.g. 1.15.1] 1.20.4
 - Active Mods [e.g. Optifine, 5zig, TooManyItems] Mod list in the following screenshot
 - 
![Eefe](https://github.com/user-attachments/assets/a4542ad4-cf24-4154-9c70-3174bb842337)

**Comment by Keksuccino** [comment]
https://docs.fancymenu.net/en/fix-audio
