### ISSUE TITLE
Certain buttons unclickable with customization

### ISSUE THREAD

**Issue by syelents** [Keksuccino/FancyMenu#92]
**Describe the bug**
In the Multiplayer Screen, when using custom textures, hover sounds,or click sounds, for the Join Server, Edit, and Delete buttons, they stay disabled and are unclickable until you either 
**A)** join(or attempt to join) a server and then you go back to the multiplayer screen
**B)** click reload from the customization buttons

This happens whether or not you have a custom Hover Button Texture or not. 
You are able to join by clicking the arrow next to the icon or double-clicking.

**EDIT:** I have now noticed that this also happens when you put a custom hoversound or clicksound on the Join Server, Edit, and Delete buttons.

**To Reproduce**
1. Have a custom button texture, set a custom hover sound or click sound for the Join Server, Edit, or Delete button in the Multiplayer Select screen.
2. Click on "Multiplayer"
3. Click on a server to join
4. The Join Server, Edit, and Delete buttons are unclickable.

**Expected behavior**
After clicking a server, the Join Server, Edit, and Delete buttons should display their "uncovered" texture and should be clickable.

**Screenshots**
![2020-10-12_00 52 20](https://user-images.githubusercontent.com/54427152/95708288-dca62300-0c29-11eb-85c6-4d8ca6cc0375.png)

![FancyMenuBug](https://user-images.githubusercontent.com/54427152/95708274-d152f780-0c29-11eb-8710-8c5c16880f09.gif)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version: 1.5.3.1
 - Forge Version: 34.1.19
 - Minecraft Version: 1.16.3
 - Active Mods: Konkrete & FancyMenu

**Comment by Keksuccino** [comment]
Hi! Thank you for reporting this bug! Will try to fix this with the next update! :)

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v1.5.4! Thank you for your report!
