### ISSUE TITLE
Architectury API causes tooltips to not render without background + Tooltips do not render on fancymenu custom screen

### ISSUE THREAD

**Issue by Pro752** [Keksuccino/FancyMenu#922]
**Describe the bug**
When the Architecture API is installed,  button tooltip's background is not rendered, the issue is fixed when you hover over a "working tooltip"  i.e. those in the accessibility tab.

Another issue is that the default tooltips are not rendering at all in custom screens (Portuguese (Brazil) language)

**To reproduce**

Bug #1
![javaw_WftzFalJHL-ezgif com-optimize](https://github.com/user-attachments/assets/55c42588-aa62-45a4-be97-29e8ace37163)
1. Install the Architecture API
2. Hover over any fancymenu button that has a tooltip

Bug #2
![javaw_97KOGCgEiU](https://github.com/user-attachments/assets/f1996bd4-2870-435e-bc94-528a96067058)
1. Enable screen customization in one that has tooltips
2. Hover over any default button that has a tooltip
> This problem happens even without Architecture API

**Basic Information**
- OS: Windows 11
- FancyMenu Version - 3.2.3-1.20.6-fabric
- Forge/Fabric Version - Fabric 1.20.6 - Fabric API - 0.100.8+1.20.6
- Minecraft Version - 1.20.6
- Active Mods:
Fabric API
FancyMenu
Konkrete
Melody
Architecture API

**Comment by Keksuccino** [comment]
Please don't put multiple bugs/conflicts in one issue. That's hella confusing. Thank you very much.
I split the issues into separate ones and will close this one.

Please also make sure to report the Architectury API issue to the Architectury devs.
