### ISSUE TITLE
Crash on custom launcher

### ISSUE THREAD

**Issue by Dragonir44** [Keksuccino/FancyMenu#927]
**Describe the bug**
I'm creating my own launcher for my modpacks and in the new version, I've started to separate minecraft and modpack resources (for those who know, the root variable for the minecraft base and overrides.gameDirectory for the modpacks on the mclc library) except that as soon as I launch the game this way, it crashes after the forge loading phase and tells me in the crash log that it's coming from FancyMenu and DrippyLoading screen.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Create a little nodeJS script with the minecraft-core-launcher library
2. Split the root dir and the game dir
3. Launch the game

**Expected behavior**
The game launch and crash after forge loading mods

**Game Log**
crash report : https://gist.github.com/Dragonir44/8c88d24394b1fd00b5cf4381977da15f
logs : no file was generated because technically, the game won't start

**Basic Informations (please complete the following information):**
 - OS: Windows and Linux
 - FancyMenu Version 3.2.3
 - Forge/Fabric Version forge 47.3.5
 - Minecraft Version 1.20.1
 - Active Mods see end of crash log

**Comment by Keksuccino** [comment]
Dude no offense, but I'm not gonna start adding support for custom launchers that do stuff in a different way than all other launchers. FancyMenu works great in other 3rd-party launchers, so it's on you to make it work in your launcher. Sorry, but that's how it is.
