### ISSUE TITLE
NullPointerException in FancyMenu Mod During Server Transfer with Minecraft Snapshot 24w03a

### ISSUE THREAD

**Issue by RyuguDev** [Keksuccino/FancyMenu#929]
**Description**
When attempting to transfer to another server using the new transfer packet introduced in Minecraft snapshot 24w03a, the FancyMenu mod throws a `NullPointerException`. This occurs because the mod tries to access a `TextWidget` (`statusTextFancyMenu`) that has not been initialized.

**To Reproduce**
1. Connect to a Minecraft server using a version that supports the new transfer packet (from snapshot 24w03a).
2. Attempt to transfer to another server using the new transfer functionality.
3. Observe the error related to `statusTextFancyMenu` being `null` in the game logs.

**Expected behavior**
The FancyMenu mod should handle the new transfer packet correctly without causing a `NullPointerException`. The mod should display the appropriate status or update without errors.

**Game Log**
https://mclo.gs/TfZ2cuA

**Comment by MiguVT** [comment]
Issue stills, any update?

**Comment by MiguVT** [comment]
I have this in log about packet handle fail, idk if it can help: https://mclo.gs/t7F9ths

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.3.0!
