### ISSUE TITLE
Mp4 animation support

### ISSUE THREAD

**Issue by BruhIndeed** [Keksuccino/FancyMenu#93]
Mp4 is literally less than 1/100 the size of a png sequence in my case of a 20 second 30 fps 3d render

**Comment by Keksuccino** [comment]
Hi! It's not possible to render video files in Minecraft (lwjgl) without using third party APIs and I don’t want to do that atm, sorry.
Maybe I will add it someday in a future update, but no promises.

**Comment by Keksuccino** [comment]
Support for videos will not get added, I'm sorry.
