### ISSUE TITLE
Fancymenu Slideshows didn't work !

### ISSUE THREAD

**Issue by kiraitoshi** [Keksuccino/FancyMenu#932]
slideshows / myslideshow / images +properties.txt
didn't work
![Screenshot_1105](https://github.com/user-attachments/assets/1f5a121c-3795-43aa-99da-c2fa6075aaeb)
![Screenshot_1106](https://github.com/user-attachments/assets/7a77ae32-e012-479c-a44f-45012445f093)

help !

**Comment by kiraitoshi** [comment]
i read all this things ! https://docs.fancymenu.net/en/slideshows

**Comment by Keksuccino** [comment]
Would be great to have _any_ information about your instance. You know, like it's described in the bug report template you ignored.

**Comment by Swyatosha** [comment]
bruh i have same problem, are there any solutions?

**Comment by Swyatosha** [comment]
and yeah here my properties 
![image](https://github.com/user-attachments/assets/2306b1e4-f00f-4ce6-946f-b9ce1b6254ac)

**Comment by Keksuccino** [comment]
Unable to reproduce. Slideshows work perfectly fine (tested in Fabric 1.20.4).
