### ISSUE TITLE
1.8.9 version

### ISSUE THREAD

**Issue by Twoti7758** [Keksuccino/FancyMenu#935]
Hello, I'm a huge fan of your Fancy Menu mod and I'm reaching out to ask if it would be possible for you to create an older version compatible with 1.8.9 . I understand that downgrading the mod might require significant effort, but I believe it would bring joy to many players, including myself, who are interested in playing with this amazing mod on an older Minecraft version. If you're willing to consider this, I'd be extremely grateful!

**Comment by Keksuccino** [comment]
No.
