### ISSUE TITLE
Audio in Game Intro Animations

### ISSUE THREAD

**Issue by Dzheremi2** [Keksuccino/FancyMenu#937]
**Describe your idea**
As I saw in YouTube videos of previous versions of this mod, in V2, game intro supported playing audio. But with new FMA files it isn't possible anymore.
My idea is returning the ability to play audio while Game Intro Animations.

**Comment by Keksuccino** [comment]
This will not come back the same way it was in v2. Video support is planned in the future, then you will be able to play sound in the intro again. No ETA for video support tho.

**Comment by Yr1t** [comment]
> This will not come back the same way it was in v2. Video support is planned in the future, then you will be able to play sound in the intro again. No ETA for video support tho.

I don't know how the inner workings of the mod works, so I'm not sure how difficult this would be, but would it be possible to just give the option to add an Audio Element to the Game Intro menu, like how you can add audio to any other UI? 

I [managed to get a Game Intro with audio working](https://youtu.be/lengvaiM65M) on the latest build by having the background animation of the main menu play once, having an audio that synced with it play once every session, and then having all of the menu elements fade in on a timer that synced with the end of the intro. The downside of this method is that I cannot use an animated looping background for the main menu, as it's already set to the "Game Intro" I hacked together.

I know you said you were planning on adding video support in the future, but why not add audio support to FMA files? Is there any specific reason for this restriction? I was able to put something together within the limitations of your mod, so I'm just a little confused on your stance when it's already somewhat possible.

**Comment by Keksuccino** [comment]
> This will not come back the same way it was in v2. Video support is planned in the future, then you will be able to play sound in the intro again. No ETA for video support tho.
