### ISSUE TITLE
Incompatibiliy with Chat Colors

### ISSUE THREAD

**Issue by LenKagamine** [Keksuccino/FancyMenu#939]
**Describe the issue**
The game crashes when loading if chat colors is installed

**Game Log**
(https://pastebin.com/P9D8W0GM)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version: 3.2.3
 - Forge/Fabric Version: Forge 37.3.10
 - Minecraft Version: 1.20.1
 - Active Mods: Fancy Menu 3.2.3; Chat Colors 3.1; Konkrete 1.8.0; Melody 1.0.3

**Comment by Keksuccino** [comment]
Already listed as incompatible: https://docs.fancymenu.net/en/incompatibility-list
