### ISSUE TITLE
Support for fabric?

### ISSUE THREAD

**Issue by Kichura** [Keksuccino/FancyMenu#94]
This mod is an very interesting mod but since i'm not an forge user; Is it possible to port this entire mod to fabric aswell instead of just forge itself or does it require rewriting the entire source code of it?

(This isn't considered to be an issue/feature request but is an question instead for this mod)

**Comment by Keksuccino** [comment]
Hi! I started working on a fabric port :) Still too many things to do for a full port, but I’m working on it!

**Comment by Keksuccino** [comment]
Fabric version is out: https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric#c14
