### ISSUE TITLE
Can't open any vanilla/modded/custom GUI with fancymenu V3

### ISSUE THREAD

**Issue by ALEILGOD** [Keksuccino/FancyMenu#942]
**Describe the bug**
I am trying to open the Fabulous Fletching screen from the Apotheosis fletching screen but the mod wont let me do so

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Install Fabulous Fletching and Apotheosis
2. Create a button on the apotheosis fletching GUI
3. in the identifier copy `net.mcreator.fabulousfletching.client.gui.FletchingGuiScreen`
4. Cant open the screen

**Expected behavior**
The screen should open

**Game Log**
https://gist.github.com/ALEILGOD/366cad663ef0d585623a5ae85bbde6de

**Screenshots**
![Screenshot 2024-09-21 170211](https://github.com/user-attachments/assets/ab18514f-21d4-4295-9aa4-002ffbad6579)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 3.2.3-1.20.1
 - Forge/Fabric Version 43.2.0 [FORGE]
 - Minecraft Version 1.20.1
 - Active Mods (too many, but i tried with only those two)

**Comment by ALEILGOD** [comment]
This is the second time i try to send this

**Comment by ALEILGOD** [comment]
**UPDATE**
I can open custom GUIs that I made

**Comment by Keksuccino** [comment]
Vanilla screens work fine. Just tested it on MC 1.20.1 Forge with the MP screen and Options screen.
Most modded screens can't get opened via FM, because they need stuff to work that FM doesn't know how to handle/create.
I don't fix mod screens anymore, because that would be way too much work, sorry.

**Comment by ALEILGOD** [comment]
ok thanks
