### ISSUE TITLE
My whole GUI moved but i dont know how to fix

### ISSUE THREAD

**Issue by ButterWaffle8282** [Keksuccino/FancyMenu#943]
![123](https://github.com/user-attachments/assets/145fe352-e54f-4fe0-a68b-aeaa143f257c)
![image](https://github.com/user-attachments/assets/70f9be84-b2b0-4db5-bd46-3a64d621300c)

As you can see in the picture, the GUI moved right away. Because of this, the mouse cursor is recognized to the right of the mouse that appears on the screen. I tried deleting all of the mod files of Fancymenu to solve it, but it didn't work. Is there no way?

**Comment by Keksuccino** [comment]
If it still happens when FancyMenu isn't even installed, it's not caused by FancyMenu.

**Comment by Keksuccino** [comment]
Closed because probably not related to FancyMenu and not reproducible.
Could be a mod conflict of some sort or not related to FM at all.
