### ISSUE TITLE
Fancy and Essentials

### ISSUE THREAD

**Issue by Kino022** [Keksuccino/FancyMenu#946]
The mod seems to be incompatible with Essential, it wont let me customize the Essential mod buttons. If it is possible to customize it, please tell me because I've been sitting here for an hour pressing all the buttons and trying different things and it doesn't work.

There are no logs, it has not crashed, its just an issue of not being able to customize the Essential mod menu buttons.

Screenshots:
![image_2024-09-27_154152521](https://github.com/user-attachments/assets/97613414-ce00-4ea0-aabb-0ec35e18c84c)
![image_2024-09-27_154338064](https://github.com/user-attachments/assets/8257da77-bec2-4974-88f3-af81b3e99b1b)

 -  Windows 11
 - FancyMenu 3.2.3
 - Fabric 0.92.2
 - Minecraft Version: 1.20.1
 - Active Mods: Essential_1-3-4-1_fabric_1-20-1.jar

**Comment by Keksuccino** [comment]
Essential being incompatible with FM is not FM's fault, but Essentials.
This incompatibility is well known, has been posted in issues multiple times and is part of the [incompatiblity list](https://docs.fancymenu.net/en/incompatibility-list).
