### ISSUE TITLE
"Options" Text in the options screen is not recognized by FancyMenu in 1.20.1

### ISSUE THREAD

**Issue by Arrowpuppet** [Keksuccino/FancyMenu#950]
**Describe the bug**
The "Options" text near the top of the options screen is not a recognized element by FancyMenu, and therefore cannot be customized. This does not show up in all versions; FancyMenu in 1.20.6 recognizes it just fine, while in 1.20.1 it does not.

**To Reproduce**
1. Open the game menu if in-game.
2. Select "Options..."
3. Edit the layout for current screen.

**Expected behavior**
The menu text should be recognized as a customizable element.

**Game Log**
[Log](https://pastebin.com/fH4dz8tm)

**Screenshots**
![Screenshot 2024-10-07 200407](https://github.com/user-attachments/assets/cdea91dd-e978-4e0c-98a9-7e27bc527012)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version: 3.2.3
 - Forge/Fabric Version: Fabric 0.16.5
 - Minecraft Version: 1.20.1
 - Active Mods: Fabric API, FancyMenu, Konkrete, Melody.

**Comment by Keksuccino** [comment]
Right-click the editor background. There is an option to edit the menu title.
