### ISSUE TITLE
[1.20.1] Crash on startup with 3.3.0

### ISSUE THREAD

**Issue by xg787** [Keksuccino/FancyMenu#951]
**Describe the bug**
crash

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. load fm 3.3.0
2. crash

**Expected behavior**
load

**Game Log**
[latest.log](https://github.com/user-attachments/files/17353208/latest.log)

**Basic Informations (please complete the following information):**
 - OS: [Windows]
 - FancyMenu Version [3.3.0]
 - Forge/Fabric Version [forge 47.3.11]
 - Minecraft Version [1.20.1]

**Comment by Keksuccino** [comment]
Fixed in FancyMenu v3.3.1!
