### ISSUE TITLE
Welcome Screen opens multiple times

### ISSUE THREAD

**Issue by VaporeonScripts** [Keksuccino/FancyMenu#952]
**Describe the bug**
![image](https://github.com/user-attachments/assets/5cd9e7bc-7846-4d05-8173-7707714c5032)

**To Reproduce**
use new fancy menu version, run mc, disable the welcome screen in config
**Expected behavior**
no welcome message for every launch

**Game Log**
no need?

**Screenshots**
![image](https://github.com/user-attachments/assets/045702e9-b890-473c-ac08-418ebe692f68)

**Basic Informations (please complete the following information):**
 - OS: CachyOS (Arch)
 - FancyMenu Version new one from neoforge
 - Forge/Fabric Version .68
 - Minecraft Version 1.21.1
 - Active Mods too many lmao (435)

**Comment by Keksuccino** [comment]
Works perfectly fine for me.
Please try it without other mods, even tho I don't think this is a mod conflict.

And please also **SEND YOUR LOG** after the screen appears when it shouldn't.

**Comment by VaporeonScripts** [comment]
Nvm it fixed itself ,sorry
