### ISSUE TITLE
[BUG] Welcome screen cannot be disabled 1.20.1 - 3.3.1

### ISSUE THREAD

**Issue by muggleorwizard** [Keksuccino/FancyMenu#953]
**Describe the bug**
Welcome screen cannot be disabled.

**To Reproduce**
Steps to reproduce the behavior :
1. In config options B:welcome_screen_shown = 'false';
2. Save
3. Start game
4. Welcome screen still shows up and config reverts to 'true'

**Expected behavior**
Welcome screen does not show up

Latest.log: https://pastebin.com/UdCbV0ww

Related to closed issue: https://github.com/Keksuccino/FancyMenu/issues/952 

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 3.3.1
 - Forge/Fabric Version 47.3.10
 - Minecraft Version 1.20.1
 - Active Mods: https://pastebin.com/3GeEJxvH

**Comment by Keksuccino** [comment]
`welcome_screen_SHOWN`. It has to be `true` to NOT show up again and the screen sets this value to `true` by itself when clicking on the Open Documentation button.
