### ISSUE TITLE
Add multiple request types for Web Images and More

### ISSUE THREAD

**Issue by anjanilearns** [Keksuccino/FancyMenu#955]
The feature is like that, when we use image source as web we get access to choose multiple types of requests we can send those includes POST, GET, PUT, DELETE and much more.

+ I wanna suggest that please add a way to get results from the web API and make the button disabled and enabled with the if else blocks. Also can change value with if else blocks and web API

**Comment by Keksuccino** [comment]
That will not happen, sorry. Web sources are good as they are.
