### ISSUE TITLE
Legacy4J Incompatibility 

### ISSUE THREAD

**Issue by BypassSysZombie** [Keksuccino/FancyMenu#958]
*Why I think?*
I Think Why Is Incompatible is because It says fancy menu and Legacy4J in the .txt 

*Log Files*
[Log.zip](https://github.com/user-attachments/files/17483559/Log.zip) or 
https://gist.github.com/BypassSysZombie/edb5fdfca0bebbbaec2765fae597c4ee

**Screenshots**
![image_2024-10-22_184636380](https://github.com/user-attachments/assets/d806bf02-a3d0-4086-a02f-e45be4ece550)

**Basic Informations**
 - OS: Windows
 - FancyMenu Version: 3.3.2 
 - Forge/Fabric Version Fabric 0.16.7
 - Minecraft Version 1.21.1
 - Active Mods JEI ,Legacy4J,CraftedCore,Walkers,wthit,xaero's Minimap, Xaero's World Map,SkinShifter,Forge Config api Port,inmersivemc,konkrete,legacy skins,sit

**Comment by Keksuccino** [comment]
Legacy4J changes lots of menus.  It will probably never be compatible with FancyMenu.
