### ISSUE TITLE
Incompatibility with Capes

### ISSUE THREAD

**Issue by seriousfreezing** [Keksuccino/FancyMenu#959]
Every time I try to modify the interface it stays for a while, but then it comes back with the vanilla buttons from the Capes mod. Which totally breaks the buttons I made.

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu Version 3.3.2
 - Forge/Fabric Version 0.16.7
 - Minecraft Version 1.21.1
 - Active Mods: https://modrinth.com/modpack/bedrock-reloaded/version/18.0.0

[More Info](https://github.com/CaelTheColher/Capes/issues/150)

**Comment by Keksuccino** [comment]
The Capes dev needs to fix that, I can't fix it on my end.
Except it's a Tab screen (like the Create World Screen with tabs at the top), but even then I can't do much about it, because Tab screens are pure pain and I didn't figure out yet how to add full support for them.
