### ISSUE TITLE
Support for system folders

### ISSUE THREAD

**Issue by BruhIndeed** [Keksuccino/FancyMenu#96]
System folders (Desktop, Downloads, Documents, etc) can be relocated by the user so they are hard to keep track of. It would be kinda useful to be able to use them as a file path in downloading and other actions that need a specified path.
![photo_2020-10-21_12-31-43](https://user-images.githubusercontent.com/65122295/96701552-6926b300-1399-11eb-8661-cc1fc5523b63.jpg)

**Comment by Keksuccino** [comment]
Making this work for all operating systems would be too hard, sorry. Will not add that.
