### ISSUE TITLE
Incompatble GUI Error But made using FancyMenu

### ISSUE THREAD

**Issue by FortnasPlayer** [Keksuccino/FancyMenu#969]
So apperently i am making a first official release of my VRCraft: classic Modpack and after i made the button that upon click sends the player to a GUI containing links and Information it says that the Cusom GUI is not existing or comes from a unsupported mod but after clicking on 'OK' it sends you to the Custom GUI and its weird

**Comment by Keksuccino** [comment]
Closed because bug report template ignored.
