### ISSUE TITLE
animation doesn't play correctly

### ISSUE THREAD

**Issue by GitEz-code** [Keksuccino/FancyMenu#97]
**Describe the bug**
the background video is playing correclty but the minecarft logo is still here and button donesn't not do their animation

**To Reproduce**
1. download the example animation from curseforge
2. extrate on /config/FancyMenu
3. launch the game

**Expected behavior**
the animation must play and after all the button appare from the side of the screen

**Screenshots**
https://www.youtube.com/watch?v=0ukv1ElTg58

**Basic Informations:**
 - OS: Lubuntu 20.04 (linux)
 - FancyMenu Version: 1.5.3.1
 - Forge Version: 14.23.5.28 54
 - Minecraft Version: 1.12.2
 - Active Mods: Fancy menu and Konkrete

**Comment by Keksuccino** [comment]
That's not a bug.

The example *animation*, as the name says, is just the animation, not the full menu shown in the GIF :D 

You can hide the Minecraft logo in the [mod config](https://github.com/Keksuccino/FancyMenu/wiki/Mod-Configuration#mainmenu).

The buttons can be edited in the [layout editor](https://github.com/Keksuccino/FancyMenu/wiki/Layout-Editor) :)

**Comment by GitEz-code** [comment]
ok ! thx for reply !
