### ISSUE TITLE
Custom Cursor by jflec

### ISSUE THREAD

**Issue by Taknax** [Keksuccino/FancyMenu#974]
**Describe the issue**
What exactly is telling you that the mod is incompatible?
When the player open the inventory the game chrashes.

**Game Log**
[latest.log](https://github.com/user-attachments/files/17692776/latest.log)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - FancyMenu 3.3.2
 - Forge Version 47.3.12
 - Minecraft Version 1.20.1
 - Active Mods Konkrete, Melody, FancyMenu, Custom Cursor

**Comment by Taknax** [comment]
i did not know fancy menu has it own. Is that written in the wiki so i can figure out how?

**Comment by Keksuccino** [comment]
Just add a new Cursor element. It’s pretty much self explaining :D
