### ISSUE TITLE
MCA Reborn character editor screen compat

### ISSUE THREAD

**Issue by Taknax** [Keksuccino/FancyMenu#975]
**Describe your idea**
In the earlier versions of FancyMenu, it was possible to modify the character editor screen of MCA. That was pretty nice.

https://i.imgur.com/NsjGhuX.png
https://i.imgur.com/fUjxW4i.png

**Comment by Keksuccino** [comment]
FancyMenu can still edit all Vanilla-like screens. Nothing changed. If you don’t see the screen's elements in the editor anymore, it’s most probably the other mod that changed something.
