### ISSUE TITLE
Bug with background (dark)

### ISSUE THREAD

**Issue by ohiodudeya** [Keksuccino/FancyMenu#98]
I'm having problems with the mod. Can you help me, please?

When I set background and save everything, the image in the main menu becomes dark (as if the brightness was turned down on the phone)

**To Reproduce**
1. Go to 'Customizations'
2. Click on empty place
3. Chose file with my background
4. Save all
5. See error

**Expected behavior**

**Crash Log**
file:///C:/Users/Green/Desktop/latest.log

**Screenshots**
https://imgur.com/a/e8OiW65

**Basic Informations**
 - OS: [Windows 10 Pro 64-bit Build 18363]
 - FancyMenu Version [fancymenu_1.5.3.1_MC_1.12-1.12.2]
 - Forge Version [14.23.5.2854]
 - Minecraft Version [1.12.2]
 - Active Mods [Optifine 1.12.2_HD_U_F4 , konkrete_1.0.3_MC_1.12-1.12.2 , fancymenu_1.5.3.1_MC_1.12-1.12.2]

**Comment by Keksuccino** [comment]
Hi! Thank you for your report! I think there was a little mistake with your log file ^^ Please upload it to https://pastebin.com/, thank you very much!

**Comment by ohiodudeya** [comment]
Log: https://pastebin.com/939fWMiu

Image of my background (Screenshot): 
imgur --> https://imgur.com/a/R8UTTBf
  or
yapx --> https://yapx.ru/u/JWGTV
![2020-10-27_23 15 09](https://user-images.githubusercontent.com/73557671/97460615-f9429a80-194d-11eb-8ae1-67716718bd83.png)

**Comment by Keksuccino** [comment]
Thank you! But I still need your background image file :) The normal (not dark) image (no screenshot; the real file you set as background in your menu) ^^

**Comment by Keksuccino** [comment]
@ohiodudeya

**Comment by ohiodudeya** [comment]
The bug works with all backgrounds, whatever they are. I tried to put a screenshot and just a downloaded photo from the Internet, changed the size of 1920x1080 and 800x600. This bug works with everything

**Comment by ohiodudeya** [comment]
> @ohiodudeya

![2020-10-26_22 21 28](https://user-images.githubusercontent.com/73557671/98418044-25b78e80-2093-11eb-8e94-5170251cfd7e.png)

**Comment by Keksuccino** [comment]
Could you please try to load only FancyMenu without any other mods? (optifine too)
I'm a bit clueless here.. This bug doesn't really makes sense, it shouldn't happen :/
Tried to reproduce it, but without luck.

Maybe you're using a special launcher or something that's messing up MC?

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
