### ISSUE TITLE
loading screen

### ISSUE THREAD

**Issue by Senkosan4** [Keksuccino/FancyMenu#980]
I use the fancy menu and dripping mod loading screen to customize my menu. When I launch Minecraft, my custom loading screen appears first, but instead of smoothly transitioning to the Minecraft main menu, a red screen appears for a second and only then the main menu.

 - OS: Windows
 - FancyMenu Version [3.2.3]
 - Forge Version [e.g. 31.2.24]
 - Minecraft Version [e.g. 1.20.1]
 - Active Mods 
 - embbedium
 -

**Comment by Keksuccino** [comment]
Report this in the Drippy repo please. This is the FancyMenu repo.
