### ISSUE TITLE
Menu elements become muddled when minimizing window/enabling fullscreen

### ISSUE THREAD

**Issue by TheMinecraftCatLover** [Keksuccino/FancyMenu#990]
I've made a custom menu for my modpack, but when I change the screen to fullscreen, or minimize it, all of the elements I have customized overlap and become muddled. (They don't seem to change size according to the window size?)

To reproduce- make a custom menu and minimize/go full screen

I'm not sure why this is happening (I do have other mods installed, but none that impact the main menu that much)- am I missing something? I have checked the FancyMenu docs, and tried enabling force GUI scaling, auto scaling etc, but the menu scaling is still wrong. Is there any way to just force it to be a smaller/larger version of the original? Do I need to do something with the anchor points?
Sorry if I am missing anything obvious, I am still a little new to using FancyMenu!

no game log.

screenshot of when I enable fullscreen:
![2024-12-12_18 55 10](https://github.com/user-attachments/assets/77e41ab1-d00c-4e56-96ce-3b8bebceb07b)

 - OS: Windows 11
 - FancyMenu 3.2.5
 - Fabric 0.16.9
 - Minecraft Version 1.21 Java

 - Active Mods (quite long, sorry) (this also happened with another custom modpack I made using fancymenu, and the same thing occurred, so I don't think it has something to do with other mods)
 
Skin Shuffle
YetAnotherConfigLib
Sodium
Subtle Effects
libIPN
Inventory Profiles Next
Fabric Language Kotlin
Effect Timer Plus
Continuity
Immediatelyfast
ETF
Lighty
When Dungeons Arise - Seven Seas
You're in Grave Danger
Configurable
KleeSlabs
Balm
FPS Reducer
Notes
Just Enough Breeding
Iris Shaders
Axolotl Bucket Fix
BetterF3
Satin Free Wakes
AmbientSounds6
CreativeCore
Experienced Worlds
ModernFix
Trinkets
IndyPets
Items Displayed
FTB Teams
FTB Library
FTB XMod Compat
FTB Quests
Forge Config API Port
Easy Magic
Easy Anvils
Better Tridents
Puzzles Lib
Easy Shulker Boxes
Fzzy Config
owo-lib
Iceberg
Advancement Plaques
Freecam
Sound Physics Remastered
Trade Cycling
Hopo Better Underwater Ruins
spark
Searchables
Controlling
Clumps
FancyMenu
Konkrete
Melody
playerAnimator
Tide
FerriteCore
Enhanced Cats
Just Enough Effect Descriptions
Just Enough Items
Attack Through Grass
Armor Trim Item Fix
Fabric API
Respawnable Pets
Visual Overhaul
Blur+
Just Enough Professions
Flower Patch
Nemo's Woodcutter
Artifacts
Text Placeholder API
Visuality
Mod Menu
Pufferfish's Attributes
Pufferfish's Skills
Pufferfish's Skill Trees
Elytra/Chestplate Swapper
Just Mob Heads
Collective
Inventory Totem
Vanilla Zoom
Invisible Frames
Architectury API
Cloth Config API
Jade
Better Third Person
No Resource Pack Warnings
AppleSkin
Yeetus Experimentus
Leaves Us In Peace
Panorama
Small Ships
Better Statistics Screen
TCDCommons API
Cherished Worlds
Comforts
Eating Animation
Skin Layers 3D
Not Enough Animations
Entity Culling
EMF
Carry ON
Sodium/Embeddium Dynamic Lights
Better Advancements
Just Enough Resources
Unwrecked Ships
Xaero's World Map
Xaero's Minimap
Mouse Tweaks
Blahaj
Fish of Theieves
Friends&Foes
Easy Shulker Boxes

**Comment by Keksuccino** [comment]
This is not a bug. Please read the docs: https://docs.fancymenu.net/en/positioning-elements
