### ISSUE TITLE
Crash on startup on 1.19.2

### ISSUE THREAD

**Issue by Laxider** [Keksuccino/FancyMenu#993]
**Describe the bug**
When trying to run the game, after a few seconds while it loads, the game crashes

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Go to 'launcher'
2. Click on 'clic on start'
3. Scroll down to '//'
4. See error //

**Game Log**
https://gist.github.com/Laxider/ce0e69de2d02d47df3d8b08587b78e5e

**Screenshots**
List of mods   https://imgur.com/a/P6iGe5N 

**Basic Informations:**
 - OS: [Windows 11]
 - FancyMenu Version [3.3.2]
 - Forge/Fabric Version [43.4.6]
 - Minecraft Version [1.19.2]
 - Active Mods [Oculus and others]

**Comment by Laxider** [comment]
I found the problem, 2 libraries were missing, konkrete and melody, which is not mentioned on the curseforge page or modright that are needed

**Comment by Keksuccino** [comment]
ok buddy

<img width="312" alt="Screenshot_1" src="https://github.com/user-attachments/assets/235a194d-bfe2-4b7d-9c88-ee95b86eed20" />

<br>

<img width="719" alt="Screenshot_2" src="https://github.com/user-attachments/assets/f6b6c3b3-040c-4698-bb63-8c94c262dea9" />
