### ISSUE TITLE
The Original Button in Minecraft Don't deleted automatically

### ISSUE THREAD

**Issue by qaz1qazlol2** [Keksuccino/FancyMenu#994]
**Describe the bug**
As the title says

**To Reproduce**
Just launch the game and do nothing(If you modify the size of the window the bug will be fixed)

**Expected behavior**
The Original button should be hidden
![image](https://github.com/user-attachments/assets/b01fdcba-965a-45ae-be4f-a23759343506)

**Game Log**
[latest.log](https://github.com/user-attachments/files/18217854/latest.log)

**Screenshots**
![image](https://github.com/user-attachments/assets/541a8ace-db82-4b86-9413-eb9c2a2d7733)

**Basic Informations (please complete the following information):**
 - OS: Windows 11 23H2
 - FancyMenu Version 3.3.2
 - Forge/Fabric Version 40.2.21
 - Minecraft Version 1.18.2
 - Active Mods : A Lot,But one mod using mixin tweaked the loading screen.

**Comment by Keksuccino** [comment]
This should not happen and is most probably caused by a mod conflict. Find and remove the mod that breaks it.
For future questions, please join the Discord: #569
