### ISSUE TITLE
[Skipped Version] 1.21.2-1.21.3 Support?

### ISSUE THREAD

**Issue by ItzLoonie** [Keksuccino/FancyMenu#998]
You kinda... skipped 1.21.2-1.21.3

You have FancyMenu for 1.21.1 and 1.21.4, but not in between.

The 1.21.1 and 1.21.4 versions do not load for 1.21.2-1.21.3.

Many people still use 1.21.3 due to various mods not being updated (myself included).

**Comment by Keksuccino** [comment]
I will not add support for 1.21.2 and 1.21.3, sorry.
