### ISSUE TITLE
Allow widget to move smoothly

### ISSUE THREAD

**Issue by heipiao233** [Keksuccino/FancyMenu#999]
I'm making a layout for world loading screen like another video game's loading screen:
![load](https://github.com/user-attachments/assets/d2b0ed78-d128-4a8e-9fa5-fd683c69870f)
However, if I only use world_load_progress placeholder for advanced , the progress label doesn't move smoothly. I'm finding a way to make it move smoothly or follow the progress bar.

This is how it looks like now:

https://github.com/user-attachments/assets/10fc46a7-3ec4-4576-a2a0-eee1ee21850c

**Comment by Keksuccino** [comment]
You can anchor elements to progress bars and set in the progress bar element that its progress should be the anchor origin. That's how you make elements follow the progress of progress bars.
